### ISSUE TITLE
serverless webpack error

### ISSUE THREAD

**Issue by splinermann** [brianmario/mysql2#1007]
when I include mysql2 in a serverless webpack project it does not compile i get this error
    ERROR in src/handler.js from UglifyJs
    undefined

My serverless.yml
`service: appsync-tester

plugins:

   - serverless-plugin-webpack

provider:
  name: aws
  runtime: nodejs8.10

functions:
  insert:
    handler: src/handler.handler

package:
 individually: true`

this is my handler
`
const mysql = require('mysql2')

exports.handler = async (event, context, callback) => {
  console.log('Received event {}', JSON.stringify(event, 3))

  return true
}
`
this is my webpack.config

`const path = require('path')
const slsw = require('serverless-webpack')

module.exports = {
  entry: slsw.lib.entries,
  target: 'node',
  devtool: 'source-map',
  module: {
    rules: [
      {
        test: /\.(js)$/,
        use: [
          // { loader: 'shebang-loader' }
        ]
      }
    ]
  },
  output: {
    libraryTarget: 'commonjs',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js'
  }`

**Comment by sodabrew** [comment]
Strongly advise rewriting in Ruby.
