### ISSUE TITLE
LoadError: cannot load such file -- mysql2/mysql2

### ISSUE THREAD

**Issue by awead** [brianmario/mysql2#1010]
I've seen all the issues regarding this error, and I've tried all the suggestions, and I'm still getting this error. This is a relatively new Mac OS install, and I've used mysql2 without any issues before, which is why this is truly baffling.

I'm seeing the error with multiple Rubies: 2.3.3, 2.3.7, 2.4.1.

Here's what I did:

    $ ruby --version
    ruby 2.3.7p456 (2018-03-28 revision 63024) [x86_64-darwin17]
    $ brew install mysql
    $ mysql --version
    mysql  Ver 8.0.12 for osx10.13 on x86_64 (Homebrew)
    $ gem install mysql2 -V -- --srcdir=/usr/local/include/mysql --platform=ruby
    [...]
    Successfully installed mysql2-0.5.2
    1 gem installed
    $ ruby -e "require 'mysql2'"
    [...]
    cannot load such file -- mysql2/mysql2 (LoadError)

That's the short version. I initially encountered this problem when trying to do a `bundle install` on an existing project, with an earlier version of mysql2, and that led me to the above. I've tried different options with the gem command such as:

* --srcdir=/usr/local/Cellar/mysql/8.0.12
* --with-ldflags=-L/usr/local/opt/openssl/lib --with-cppflags=-I/usr/local/opt/openssl/include
* as well as trying different Ruby versions

Homebrew is up-to-date, XCode is installed, etc. Other gems that require compiled extensions are working fine. Am I just missing something obvious here?

**Comment by awead** [comment]
Updates:
I was able to reproduce this on my other laptop (same MacOS version) but only after re-installing Mysql via Homebrew. I've also tried re-compiling the gem against different versions of Mysql downloaded from their community site:

* mysql-5.5.62, generic source only
* mysql-8.0.13-macos10.14-x86_64, compiled

**Comment by awead** [comment]
If I look at the locations of lookups that `Kernel.require` is using for mysql, I see:
```
pry(#<Bundler::Runtime>)> $:.select { |path| path =~ /mysql/ } 
=> ["$HOME/.asdf/installs/ruby/2.3.3/lib/ruby/gems/2.3.0/gems/mysql2-0.3.21/lib",
 "$HOME/.asdf/installs/ruby/2.3.3/lib/ruby/gems/2.3.0/extensions/x86_64-darwin-17/2.3.0-static/mysql2-0.3.21"]
```
However, the compiled extensions are located in: `$HOME/.asdf/installs/ruby/2.3.3/lib/ruby/gems/2.3.0/gems/mysql2-0.3.21/ext`

So the issue seems to be that `$:` does not include the ext directory, or that the extensions are in the wrong place. However, in looking at other gems with compiled extensions such as sqlite3, it has a directory like `extensions/x86_64-darwin-17/2.3.0-static/sqlite3-1.3.12` with the extensions in it.

**Comment by awead** [comment]
OK, I think I've figured this out. My current project specifies mysql2 version 0.3.21. When trying to install that version:
`gem install mysql2 -v '0.3.21' -V -- --srcdir=/usr/local/include/mysql --platform=ruby`
It compiles correctly, and the gem is installed, but I get the `cannot load such file -- mysql2/mysql2`
When I tried to install the latest gem:
`gem install mysql2 -V -- --srcdir=/usr/local/include/mysql --platform=ruby`
This also compiles correctly, and the gem is installed, but I still get the `cannot load such file -- mysql2/mysql2`.
The trick was, simply:
`gem install mysql2`
I assumed that I still needed the extra `srcdir` parameter, when in fact I didn't. You used to need this parameter in order for everything to work, but at some point that changed.

**Comment by tushaarl** [comment]
I am also getting same error. Also by using the command gem install mysql2 i get include error

**Comment by tiagogeraldi** [comment]
I've solved that adding mysql_config
```shell
gem install mysql2 -v 0.4.4 -- --with-mysql-config=/usr/local/Cellar/mysql@5.6/5.6.42/bin/mysql_config --with-ldflags=-L/usr/local/opt/openssl/lib --with-cppflags=-I/usr/local/opt/openssl/include
```

**Comment by kokorolee** [comment]
It work for me.
- sudo gem install mysql2
- gem uninstall mysql2
- bundle

**Comment by lauer** [comment]
I am facing the same problems. 

None of the above helped me. 

Tried with ruby 2.6.1, 2.5.3 - mysql2 gem 0.4.10, 0.5.1 and 0.5.2

E.g. with `gem install mysql2 -v '0.5.2' -- --with-mysql-config=/usr/local/bin/mysql_config  --srcdir=/usr/local/include/mysql/ --platform=ruby  --with-ldflags=-L/usr/local/opt/openssl/lib --with-cppflags=-I/usr/local/opt/openssl/include`

Using rbenv.

**Comment by ashwinvidiyala** [comment]
I'm facing the same issue as well. I'm using:

- Ruby 2.6.1
- mysql 8.0.15
- mysql2 gem 0.5.1
- rbenv

I've separately tried both of the following commands to download mysql2 (after just doing `gem install mysql2` to no avail), and while I'm able to download mysql2 0.5.1 (with either command), I can't get rid of the Rails Server issue:

1. `gem install mysql2 -v 0.5.1 -- --with-mysql-config=/usr/local/Cellar/mysql/8.0.15/bin/mysql_config --with-ldflags=-L/usr/local/opt/openssl/lib --with-cppflags=-I/usr/local/opt/openssl/include --platform=ruby`
2. `gem install mysql2 -v '0.5.1' -- --srcdir=/usr/local/include/mysql --platform=ruby`

Please help!

**Comment by dominicsayers** [comment]
I now have this issue with

* Ruby 2.6.2
* MySQL 5.7.25
* mysql2 gem 0.5.2
* rbenv

I have tried all the above remedies. After manually installing `mysql2` I can run `bin/rails console` and perform database operations but I cannot run `rspec`.

Installation:

```
gem uninstall mysql2
gem install mysql2 -v '0.5.2' -- --with-mysql-config=/usr/local/Cellar/mysql@5.7/5.7.25/bin/mysql_config --with-ldflags=-L/usr/local/opt/openssl/lib --with-cppflags=-I/usr/local/opt/openssl/include --platform=ruby
bundle install
```

RSpec:

```
$ bin/rspec
/Users/dominic/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:33:in `require': cannot load such file -- mysql2/mysql2 (LoadError)
	from /Users/dominic/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
	from /Users/dominic/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /Users/dominic/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
	from /Users/dominic/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.2/lib/mysql2.rb:33:in `<main>'
	from /Users/dominic/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	from /Users/dominic/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	from /Users/dominic/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/dominic/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	from /Users/dominic/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/dominic/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
	from /Users/dominic/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/runtime.rb:76:in `each'
	from /Users/dominic/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/runtime.rb:76:in `block in require'
	from /Users/dominic/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/runtime.rb:65:in `each'
	from /Users/dominic/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/runtime.rb:65:in `require'
	from /Users/dominic/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler.rb:114:in `require'
	from /Users/dominic/Development/openc/oc-core-snapshots-app/config/application.rb:12:in `<top (required)>'
	from /Users/dominic/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/spring-2.0.2/lib/spring/application.rb:92:in `require'
	from /Users/dominic/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/spring-2.0.2/lib/spring/application.rb:92:in `preload'
	from /Users/dominic/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/spring-2.0.2/lib/spring/application.rb:153:in `serve'
	from /Users/dominic/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
	from /Users/dominic/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
	from /Users/dominic/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
	from /Users/dominic/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/dominic/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/dominic/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```

As I said, `console` is OK:

```
$ bin/rails console
Running via Spring preloader in process 35672
Loading development environment (Rails 5.2.3)
irb(main):001:0> Snapshot.first
   (3.0ms)  SET NAMES utf8mb4 COLLATE utf8mb4_unicode_520_ci,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483
  Snapshot Load (0.9ms)  SELECT  `snapshots`.* FROM `snapshots` ORDER BY `snapshots`.`id` ASC LIMIT 1
=> nil
```

**Comment by dominicsayers** [comment]
For anyone having the same problems as me in https://github.com/brianmario/mysql2/issues/1010#issuecomment-480860283, in the end I deleted my project folder, did a `git clone` and rebundled from scratch. That fixed it for me.

**Comment by dukejones** [comment]
`sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /`

from 
`https://gorails.com/setup/osx/10.14-mojave`

**Comment by mindaslab** [comment]
I'm facing this same issue here :|

**Comment by mindaslab** [comment]
This https://github.com/brianmario/mysql2/issues/1010#issuecomment-460257986 solved it

**Comment by omarsotillo** [comment]
Command that solved it for me: 
- Uninstall all gems 
- `gem uninstall mysql2`
```
sudo gem install mysql2 -v '0.4.9' -- \
  --with-mysql-include=/usr/local/Cellar/mysql-client/5.7.23_1/include/mysql \
  --with-mysql-config=/usr/local/Cellar/mysql-client/5.7.23_1/bin/mysql_config \
  --with-ldflags=-L/usr/local/opt/openssl/lib```

**Comment by bpang** [comment]
I solved it similarly to comment #1010 using mysql2 0.5.2 without uninstalling gems on Mac OS 10.14 Mojave.

`gem install mysql2 -v 0.5.2 -- --with-mysql-config=/usr/local/Cellar/mysql@5.7/5.7.28/bin/mysql_config --with-ldflags=-L/usr/local/opt/openssl/lib --with-cppflags=-I/usr/local/opt/openssl/include`

**Comment by wdiechmann** [comment]
I believe my "decadence" started when I indulged myself with Calibre and ocrmypdf - which one of them installed a fresh openssl is unclear to me - but eventually I drilled my way to `ls -lad /usr/local/Cellar/opens*` which showed me:

```
drwxr-xr-x  3 walther  staff  96 23 Mar  2019 /usr/local/Cellar/openssl
drwxr-xr-x  3 walther  staff  96 29 Jun 22:50 /usr/local/Cellar/openssl@1.1
```

So - when I `brew switch openssl 1.0.2r` and later `gem uninstall mysql2` then `gem install mysql2 -v 0.5.2` and finally `bundle` in my Rails project folder all was good and well in *ruby land*

😌

**Comment by joallard** [comment]
Reading @awead's comment above, I ran into this and it was important not to include `--srcdir`.

What I ended up using:
```
bundle config build.mysql2 --with-mysql-config=/usr/local/opt/mysql-client/bin/mysql_config --platform=ruby --with-ldflags=-L/usr/local/opt/openssl/lib --with-cppflags=-I/usr/local/opt/openssl/include --with-opt-dir=/usr/local/opt/openssl@1.1
```

**Comment by joallard** [comment]
Months later on another computer, I'm able to run bundle and `rails environment`, but not `rspec`. Same error message.

**Comment by zahhar** [comment]
As of today Homebrew defaults to MySQL 8.0, OpenSSL 1.1 and mysql2 0.5 that work great all together out of the box. However to upgrade of my legacy applications from Rails 3.2 to more recent versions I had to setup local environment on my MacOS BigSur 11.1. 

My goal was to install mysql2 gem version 0.3.x (this is only one allowing smooth migration from Rails 3.2 to Rails 4.2 through versions 4.0 and 4.1) together with mySQL 5.x. Both of them in turn depend on OpenSSL 1.0

Here is what worked for me:

```
// Clean-up all your faulty attempts you did before
// Homebrew does not store openssl 1.0 anymore, so I had to find alternative — openssl1.0.2t 
wget https://github.com/tebelorg/Tump/releases/download/v1.0.0/openssl.rb
brew install openssl.rb

brew install mysql@5.7
brew link mysql@5.7 --force
brew install mysql-client@5.7
// NB! Pay close attention to path where you have mysql_config and openssl 1.0 installed
gem install mysql2 -v 0.3.21 -- --with-mysql-config=/usr/local/bin/mysql_config --with-ldflags=-L/usr/local/Cellar/openssl/1.0.2t/lib --with-cppflags=-I/usr/local/Cellar/openssl/1.0.2t/include

```

Voilá:
```
Building native extensions with: '--with-mysql-config=/usr/local/bin/mysql_config --with-ldflags=-L/usr/local/Cellar/openssl/1.0.2t/lib --with-cppflags=-I/usr/local/Cellar/openssl/1.0.2t/include'
This could take a while...
Successfully installed mysql2-0.3.21
Parsing documentation for mysql2-0.3.21
Installing ri documentation for mysql2-0.3.21
Done installing documentation for mysql2 after 0 seconds
1 gem installed
```

**Comment by tiagogeraldi** [comment]
On my new mac M1 CPU, the directories changed a bit:

```
gem install mysql2 -v 0.4.4 -- --with-mysql-config=/opt/homebrew/Cellar/mysql@5.7/5.7.34/bin/mysql_config --with-ldflags=-L/opt/homebrew/opt/openssl/lib --with-cppflags=-I/opt/homebrew/opt/openssl/include
```

**Comment by junaidehsan** [comment]
> Months later on another computer, I'm able to run bundle and `rails environment`, but not `rspec`. Same error message.
> 
> Edit: Thanks to @dominicsayers above, I deleted the contents of `tmp/` and could run Rspec. Bootsnap might have been involved.

@joallard answer helped me, if you are facing issues running rspec than delete the content of tmp folder and run the command and it wil fix.

**Comment by inarendran** [comment]
These steps worked for me:
I am using M1 macbook

1. Install mysql 5.7 in i386 architecture
2. before installing the gem export `LIBRARY_PATH` this variable with openssl lib path (export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/opt/openssl/lib/)
3. gem install mysql2 -v '0.4.8' -- --with-mysql-config=/opt/homebrew/Cellar/mysql@5.7/5.7.36/bin/mysql_config 

now try running rails s.

**Comment by HFT-turnet** [comment]
Works for me (M1, MariaDB via homebrew):
gem install mysql2 -- --with-mysql-config=/opt/homebrew/Cellar/mariadb/10.6.4/bin/mysql_config --with-ldflags=-L/opt/homebrew/opt/openssl@1.1/lib --with-cppflags=-I/opt/homebrew/opt/openssl@1.1/include

**Comment by okta2510** [comment]
> I've solved that adding mysql_config
> 
> ```shell
> gem install mysql2 -v 0.4.4 -- --with-mysql-config=/usr/local/Cellar/mysql@5.6/5.6.42/bin/mysql_config --with-ldflags=-L/usr/local/opt/openssl/lib --with-cppflags=-I/usr/local/opt/openssl/include
> ```

thank you

**Comment by sajjadmurtaza** [comment]
my rails server is working fine but when I run my spec then I got   `cannot load such file -- mysql2/mysql2`
 error 

can someone help me here?

`rspec spec/
`

```
An error occurred while loading rails_helper.
Failure/Error: require File.expand_path('../../config/environment', __FILE__)

LoadError:
  cannot load such file -- mysql2/mysql2
# ./config/application.rb:7:in `<top (required)>'
# ./config/environment.rb:2:in `require_relative'
# ./config/environment.rb:2:in `<top (required)>'
# ./spec/rails_helper.rb:4:in `<top (required)>'
No examples found.


Finished in 0.00003 seconds (files took 5.21 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

**Comment by vishaldeepak** [comment]
I have the same issue as mentioned above

**Comment by joallard** [comment]
@sajjadmurtaza @vishaldeepak Have you tried deleting `tmp/`?

**Comment by vishaldeepak** [comment]
That did it , thank you

**Comment by joshuapaubox** [comment]
For M1 this worked for me: 

gem install mysql2 -v 0.5.3 -- --with-mysql-config=/opt/homebrew/opt/mysql@5.7/bin/mysql_config --with-ldflags=-L/opt/homebrew/opt/openssl@1.1/lib --with-cppflags=-I/opt/homebrew/opt/openssl@1.1/include

**Comment by rhugo** [comment]
> Reading @awead's comment above, I ran into this and it was important not to include `--srcdir`.
> 
> What I ended up using:
> 
> ```
> bundle config build.mysql2 --with-mysql-config=/usr/local/opt/mysql-client/bin/mysql_config --platform=ruby --with-ldflags=-L/usr/local/opt/openssl/lib --with-cppflags=-I/usr/local/opt/openssl/include --with-opt-dir=/usr/local/opt/openssl@1.1
> ```

I have this issue now:

xxx@Mac-mini xxx % rails c                                                
<internal:/Users/xxx/.rvm/rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- /Users/rhugo/.rvm/gems/ruby-3.2.2/gems/mysql2-0.5.5/lib/mysql2/**mysql2.bundle** (LoadError)

**Comment by Faq** [comment]
@rhugo thats on M1?
for me always works this, when pointing to exact paths:
```
gem install mysql2 -v '0.5.5' -- \
--with-mysql-lib=/opt/homebrew/Cellar/mysql@5.7/5.7.38/lib \
--with-mysql-dir=/opt/homebrew/Cellar/mysql@5.7/5.7.38 \
--with-mysql-config=/opt/homebrew/Cellar/mysql@5.7/5.7.38/bin/mysql_config \
--with-mysql-include=/opt/homebrew/Cellar/mysql@5.7/5.7.38/include
```

**Comment by Anirudh2011** [comment]
> my rails server is working fine but when I run my spec then I got `cannot load such file -- mysql2/mysql2` error
> 
> can someone help me here?
> 
> `rspec spec/ `
> 
> ```
> An error occurred while loading rails_helper.
> Failure/Error: require File.expand_path('../../config/environment', __FILE__)
> 
> LoadError:
>   cannot load such file -- mysql2/mysql2
> # ./config/application.rb:7:in `<top (required)>'
> # ./config/environment.rb:2:in `require_relative'
> # ./config/environment.rb:2:in `<top (required)>'
> # ./spec/rails_helper.rb:4:in `<top (required)>'
> No examples found.
> 
> 
> Finished in 0.00003 seconds (files took 5.21 seconds to load)
> 0 examples, 0 failures, 1 error occurred outside of examples
> ```


This issue is still happening for Mac M1. tried everything, installed mysql-0.5.5.
Rails console and server are running but not in test environment. Can anyone please help out

**Comment by Faq** [comment]
@Anirudh2011, you did not provide command/parameters with what you install this gem.

**Comment by Anirudh2011** [comment]
> @Anirudh2011, you did not provide command/parameters with what you install this gem.

These are the following commands I tried.
`gem install mysql2 -v '0.5.5' -- --with-opt-dir=$(brew --prefix openssl)
gem install mysql2 -v 0.5.5 -- --with-mysql-config=/opt/homebrew/Cellar/mysql/8.0.33_3/bin/mysql_config
`

I am able to install the gem successfully.
But when I try to run 
`RAILS_ENV=test bundle exec rails c` or 
`rspec`

It throws the following error 
`'require': cannot load such file -- mysql2/mysql2 (LoadError)`

I am able to successfully run Rails console in development environment

**Comment by Faq** [comment]
Did you tried with https://github.com/brianmario/mysql2/issues/1010#issuecomment-1541421162 ?

**Comment by Marvelxy** [comment]
> For M1 this worked for me:
> 
> gem install mysql2 -v 0.5.3 -- --with-mysql-config=/opt/homebrew/opt/mysql@5.7/bin/mysql_config --with-ldflags=-L/opt/homebrew/opt/openssl@1.1/lib --with-cppflags=-I/opt/homebrew/opt/openssl@1.1/include

This worked for me, but I had to change to my specific version of mysql2 gem and mysql.

`gem install mysql2 -v 0.5.5 -- --with-mysql-config=/opt/homebrew/opt/mysql@8.1/bin/mysql_config --with-ldflags=-L/opt/homebrew/opt/openssl@1.1/lib --with-cppflags=-I/opt/homebrew/opt/openssl@1.1/include`
