### ISSUE TITLE
rake db:create not working 

### ISSUE THREAD

**Issue by harrychengly** [brianmario/mysql2#1017]
Hi, I'm new to ruby on rails here. 

I tried to change the database.yml to mysql  as such : 
```
default: &default
  adapter: mysql2
  username: root
  password: 
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: todo_dev

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.

test:
  <<: *default
  database: todo_dev

production:
  <<: *default
  database: todo_dev


```

Also performed the following: 
1. gem install mysql2 -- --srcdir=/usr/local/mysql/include
2. added "gem 'mysql2'" to Gemfile
3. bundle install 

However, when i try to run` rake db:create`, it would give me this error
```
rake aborted!
LoadError: cannot load such file -- mysql2/mysql2
/Users/harrycly/todo/config/application.rb:7:in `<top (required)>'
/Users/harrycly/todo/Rakefile:4:in `require_relative'
/Users/harrycly/todo/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
```

Any help is much appreciated.

**Comment by harrychengly** [comment]
I'm using:
mysql2 0.5.2
ruby 2.5.3
Rails 5.2.2

**Comment by sodabrew** [comment]
`gem install mysql2` put the gem into the system gem directory and this is not being used. The arguments to this build are not propagated into the local build.

`bundle install` creates a local gem directory.

Use the `bundle config` command to set arguments for the local mysql2 build: https://bundler.io/v1.16/bundle_config.html#BUILD-OPTIONS (example provided for original mysql gem)


You can `gem uninstall mysql2` at any time to avoid the confusion of two installations, the system one is not being used.

**Comment by sodabrew** [comment]
(Didn’t mean to close this, you close it once you’ve got the issue sorted out)

**Comment by harrychengly** [comment]
thank you! this worked!
