### ISSUE TITLE
compatibility problem with latest ruby 2.6

### ISSUE THREAD

**Issue by carrot555** [brianmario/mysql2#1021]
bundle install --force
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
mysql2-0.5.2-x64-mingw32 requires ruby version >= 2.0, < 2.6, which is
incompatible with the current version, ruby 2.6.0p0

**Comment by sodabrew** [comment]
Known issue. Will include Ruby 2.6 for Windows builds in the next release.

**Comment by carrot555** [comment]
Thanks. Is there any timeline for next release ?

**Comment by jsh562** [comment]
+1     any estimate? as I am in the middle of planning an upgrade

**Comment by metalmaze** [comment]
Is there any further updates to this?

**Comment by dsisnero** [comment]
any update on this?

**Comment by iris-liu0312** [comment]
Also having this problem.
>gem install mysql2 -v 0.5.2
ERROR:  Error installing mysql2:
        The last version of mysql2 (= 0.5.2) to support your Ruby & RubyGems was 0.5.2. Try installing it with `gem install mysql2 -v 0.5.2`
        mysql2 requires Ruby version >= 2.0, < 2.6. The current ruby version is 2.6.1.33.

**Comment by darkBuddha** [comment]
trying to use Rails on Windows sucks. First SQLite problems, i thought easy lets switch to good old MySQL, then this.

**Comment by andikarekatias** [comment]
> 
> 
> Known issue. Will include Ruby 2.6 for Windows builds in the next release.

when is the next release?

**Comment by rahadur** [comment]
`λ gem install mysql2 -v 0.5.2`
```console
ERROR:  Error installing mysql2:
        The last version of mysql2 (= 0.5.2) to support your Ruby & RubyGems was 0.5.2. Try installing it with `gem install mysql2 -v 0.5.2`
        mysql2 requires Ruby version >= 2.0, < 2.6. The current ruby version is 2.6.3.62.
```
When is the next release?

#### Environment
 
* Windows

**Comment by unknown-acolyte** [comment]
I'm also very interested in the timeline on this release.

**Comment by steffanllyn-ln** [comment]
I'm also keenly interested in the resolution of this incompatibility with Ruby 2.6; our test automation framework is effectively locked into a deprecated version of Ruby (2.3) until mysql2 is updated.

**Comment by Babilonczyk251017** [comment]
Doesn anyone know when is the next release?

**Comment by uuuyyttu** [comment]
Any furthur news about this?

**Comment by anicething** [comment]
> `λ gem install mysql2 -v 0.5.2`
> 
> ```
> ERROR:  Error installing mysql2:
>         The last version of mysql2 (= 0.5.2) to support your Ruby & RubyGems was 0.5.2.
>         Try installing it with `gem install mysql2 -v 0.5.2`
>         mysql2 requires Ruby version >= 2.0, < 2.6. The current ruby version is 2.6.3.62.
> ```
> 
> When is the next release come?
> 
> #### Environment
> * Windows 10
> * Ruby 2.6.3p62
> * MySQL 8.0.16

I met the same problem.

**Comment by Daniel1707** [comment]
Does anyone know when is the next release?

**Comment by sodabrew** [comment]
...when I cut the release. Sorry for the ambiguity and delay, gotta make time for this.

**Comment by Manask322** [comment]
Please try to do it earliest.

**Comment by sudhin-joseph** [comment]
> ...when I cut the release. Sorry for the ambiguity and delay, gotta make time for this.

Please create a fix or a suggest a workaround at the earliest.

**Comment by hyrious** [comment]
Workaround: manually [download the .gem file](https://rubygems.org/downloads/mysql2-0.5.2.gem) then install it:
```
gem i mysql2-0.5.2.gem
Temporarily enhancing PATH for MSYS/MINGW...
Installing required msys2 packages: mingw-w64-x86_64-libmariadbclient
Building native extensions. This could take a while...
Successfully installed mysql2-0.5.2
Parsing documentation for mysql2-0.5.2
Installing ri documentation for mysql2-0.5.2
Done installing documentation for mysql2 after 1 seconds
1 gem installed
```
This issue might be caused by releasing multiple `0.5.2` packages, but I don't know how to fix it either.

**Comment by breisig** [comment]
We also can't get our rails project working without the proper fix released.

**Comment by carrot555** [comment]
Hi @sodabrew, If you have no time for the new release maybe Rails developers team should pick this up? The plug-in actually important for Rails 6 and mysql compatibility. Many people are using mysql. It is actually baffling why such plugins are actually not part of Rails. Rails require databases to run, strange approach to be honest.

**Comment by MacLove13** [comment]
Awaiting a solution

**Comment by piperino29** [comment]
Awaiting a solution...

**Comment by titibudala** [comment]
Anything?

**Comment by philCryoport** [comment]
> 
> 
> Workaround: manually [download the .gem file](https://rubygems.org/downloads/mysql2-0.5.2.gem) then install it:
> 
> ```
> gem i mysql2-0.5.2.gem
> Temporarily enhancing PATH for MSYS/MINGW...
> Installing required msys2 packages: mingw-w64-x86_64-libmariadbclient
> Building native extensions. This could take a while...
> Successfully installed mysql2-0.5.2
> Parsing documentation for mysql2-0.5.2
> Installing ri documentation for mysql2-0.5.2
> Done installing documentation for mysql2 after 1 seconds
> 1 gem installed
> ```
> 
> This issue might be caused by releasing multiple `0.5.2` packages, but I don't know how to fix it either.

So I downloaded the gem manually and installed it...and then when I ran `bundle install`, it complained once again that mysql2 v0.5.2 was not compatible with Ruby 2.6.x

```
C:\Users\Foo\GitHub\Bar>gem i c:\users\Foo\Downloads\mysql2-0.5.2.gem
Temporarily enhancing PATH for MSYS/MINGW...
Installing required msys2 packages: mingw-w64-x86_64-libmariadbclient
Building native extensions. This could take a while...
Successfully installed mysql2-0.5.2
Parsing documentation for mysql2-0.5.2
Installing ri documentation for mysql2-0.5.2
Done installing documentation for mysql2 after 1 seconds
1 gem installed

C:\Users\Foo\GitHub\Bar>bundle install
Fetching gem metadata from https://rubygems.org/...
mysql2-0.5.2-x64-mingw32 requires ruby version < 2.6, which is incompatible with
the current version, ruby 2.6.5p114
```

I looked through the bundle documentation and I didn't see a way to request that `bundle install` ignore the `mysql2` gem as it's already installed.  Ideas?

**Comment by sodabrew** [comment]
https://rubygems.org/gems/mysql2 0.5.3 is now posted with updated Windows pre-built binaries for Ruby 2.2 - 2.6.

**Comment by lydiap01** [comment]
> 
> 
> https://rubygems.org/gems/mysql2 0.5.3 is now posted with updated Windows pre-built binaries for Ruby 2.2 - 2.6.

sodabrew - newbie here- what exactly do I do to access https://rubygems.org/gems/mysql2 0.5.3?

**Comment by lydiap01** [comment]
> 
> 
> > https://rubygems.org/gems/mysql2 0.5.3 is now posted with updated Windows pre-built binaries for Ruby 2.2 - 2.6.
> 
> sodabrew - newbie here- what exactly do I do to access https://rubygems.org/gems/mysql2 0.5.3?

Please disregard. I had a "d'uh" moment! I fixed it.

**Comment by podor** [comment]
Hello,
I'm newbie in ruby, I tried to install Redmine on W10 but I have this:

`C:\redmine-4.1.1>gem install mysql2 -v 0.5.3`
`ERROR:  Error installing mysql2:`
        `The last version of mysql2 (= 0.5.3) to support your Ruby & RubyGems was 0.5.3. Try installing it with  gem install mysql2 -v 0.5.3  mysql2 requires Ruby version >= 2.2, < 2.7.dev. The current ruby version is 2.7.2.137.`

It seems that the new version of mysql2 (0.5.3) donc really work with ruby v2.7


RubyGems Environment:
  - RUBYGEMS VERSION: 3.1.4
  - RUBY VERSION: 2.7.2 (2020-10-01 patchlevel 137) [x64-mingw32]
  - INSTALLATION DIRECTORY: C:/Ruby27-x64/lib/ruby/gems/2.7.0
  - USER INSTALLATION DIRECTORY: C:/Users/podor/.gem/ruby/2.7.0
  - RUBY EXECUTABLE: C:/Ruby27-x64/bin/ruby.exe
  - GIT EXECUTABLE:
  - EXECUTABLE DIRECTORY: C:/Ruby27-x64/bin
  - SPEC CACHE DIRECTORY: C:/Users/podor/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: C:/ProgramData
  - RUBYGEMS PLATFORMS:
    - ruby
    - x64-mingw32
  - GEM PATHS:
     - C:/Ruby27-x64/lib/ruby/gems/2.7.0
     - C:/Users/podor/.gem/ruby/2.7.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - C:\Windows\system32
     - C:\Windows
     - C:\Windows\System32\Wbem
     - C:\Windows\System32\WindowsPowerShell\v1.0\
     - C:\Windows\System32\OpenSSH\
     - C:\Ruby27-x64\bin
     - C:\Users\podor\AppData\Local\Microsoft\WindowsApps
