### ISSUE TITLE
Mysql2::Result nested iterations buggy

### ISSUE THREAD

**Issue by felix-d** [brianmario/mysql2#1028]
When nesting iterations, I believe `Mysql2::Result` does not behave as expected.

```ruby  
@result.each_with_index do |_, i|
  p "outer: #{i}"
  @result.each_with_index do |_, j|
    p "inner: #{j}"
  end
end
```

Outputs

```
"outer: 0"
"inner: 0"
"inner: 1"
```

I would expect the output to be

```
"outer: 0"
"inner: 0"
"inner: 1"
"outer: 1"
"inner: 0"
"inner: 1"
```

Maybe there's an intention behind this? Since arrays and other enumerables do not behave this way, it is a bit surprising.

**Comment by sodabrew** [comment]
This is expected behavior. Those are the same result objects, not copies, so you're mutating them in place as you iterate.

**Comment by felix-d** [comment]
This is what I expected looking at the source code and what you suggested is the solution I ended up adopting. 

Thanks for your response, I’ll close this for now and hopefully this issue can be a reference for anyone scratching their head at this.
