### ISSUE TITLE
egg 框架私有云部署mysql2模块报错

### ISSUE THREAD

**Issue by 13349253469** [brianmario/mysql2#1030]
npm stop
egg-catalogbuy@1.0.0 stop /app/project/egg-catalogbuy
egg-scripts stop --title=egg-catalogbuy

[egg-scripts] stopping egg application with --title=egg-catalogbuy
[egg-scripts] can't detect any running egg process
[egg-scripts] stopped

npm start
egg-catalogbuy@1.0.0 start /app/project/egg-catalogbuy
egg-scripts start --daemon --title=egg-catalogbuy

[egg-scripts] Starting egg application at /app/project/egg-catalogbuy
[egg-scripts] Run node /app/project/egg-catalogbuy/node_modules/egg-scripts/lib/start-cluster {"title":"egg-catalogbuy","baseDir":"/app/project/egg-catalogbuy","framework":"/app/project/egg-catalogbuy/node_modules/egg"} --title=egg-catalogbuy
[egg-scripts] Save log file to /home/appuser/logs
[egg-scripts] Wait Start: 1...
[egg-scripts] Wait Start: 2...
[egg-scripts] Wait Start: 3...
[egg-scripts] tail -n 100 /home/appuser/logs/master-stderr.log
[egg-scripts] Got error when startup:
[egg-scripts] Trace
[egg-scripts] at Packet.readLengthCodedNumberExt (/app/project/egg-catalogbuy/node_modules/mysql2/lib/packets/packet.js:226:13)
[egg-scripts] at Packet.readLengthCodedNumber (/app/project/egg-catalogbuy/node_modules/mysql2/lib/packets/packet.js:188:17)
[egg-scripts] at Packet.readLengthCodedString (/app/project/egg-catalogbuy/node_modules/mysql2/lib/packets/packet.js:355:22)
[egg-scripts] at new ResultSetHeader (/app/project/egg-catalogbuy/node_modules/mysql2/lib/packets/resultset_header.js:71:52)
[egg-scripts] at Query.resultsetHeader (/app/project/egg-catalogbuy/node_modules/mysql2/lib/commands/query.js:104:16)
[egg-scripts] at Query.execute (/app/project/egg-catalogbuy/node_modules/mysql2/lib/commands/command.js:39:22)
[egg-scripts] at Connection.handlePacket (/app/project/egg-catalogbuy/node_modules/mysql2/lib/connection.js:449:32)
[egg-scripts] at PacketParser.Connection.packetParser.p [as onPacket] (/app/project/egg-catalogbuy/node_modules/mysql2/lib/connection.js:72:12)
[egg-scripts] at PacketParser.executeStart (/app/project/egg-catalogbuy/node_modules/mysql2/lib/packet_parser.js:75:16)
[egg-scripts] at Socket.Connection.stream.on.data (/app/project/egg-catalogbuy/node_modules/mysql2/lib/connection.js:79:25)
[egg-scripts] at emitOne (events.js:116:13)
[egg-scripts] at Socket.emit (events.js:211:7)
[egg-scripts] at addChunk (_stream_readable.js:263:12)
[egg-scripts] at readableAddChunk (_stream_readable.js:250:11)
[egg-scripts] at Socket.Readable.push (_stream_readable.js:208:10)
[egg-scripts] at TCP.onread (net.js:594:20)
[egg-scripts] 2019-03-19 23:38:45,527 ERROR 23733 nodejs.unhandledExceptionError: Should not reach here: undefined
[egg-scripts] at Packet.readLengthCodedNumberExt (/app/project/egg-catalogbuy/node_modules/mysql2/lib/packets/packet.js:227:11)
[egg-scripts] at Packet.readLengthCodedNumber (/app/project/egg-catalogbuy/node_modules/mysql2/lib/packets/packet.js:188:17)
[egg-scripts] at Packet.readLengthCodedString (/app/project/egg-catalogbuy/node_modules/mysql2/lib/packets/packet.js:355:22)
[egg-scripts] at new ResultSetHeader (/app/project/egg-catalogbuy/node_modules/mysql2/lib/packets/resultset_header.js:71:52)
[egg-scripts] at Query.resultsetHeader (/app/project/egg-catalogbuy/node_modules/mysql2/lib/commands/query.js:104:16)
[egg-scripts] at Query.execute (/app/project/egg-catalogbuy/node_modules/mysql2/lib/commands/command.js:39:22)
[egg-scripts] at Connection.handlePacket (/app/project/egg-catalogbuy/node_modules/mysql2/lib/connection.js:449:32)
[egg-scripts] at PacketParser.Connection.packetParser.p [as onPacket] (/app/project/egg-catalogbuy/node_modules/mysql2/lib/connection.js:72:12)
[egg-scripts] at PacketParser.executeStart (/app/project/egg-catalogbuy/node_modules/mysql2/lib/packet_parser.js:75:16)
[egg-scripts] at Socket.Connection.stream.on.data (/app/project/egg-catalogbuy/node_modules/mysql2/lib/connection.js:79:25)
[egg-scripts] at emitOne (events.js:116:13)
[egg-scripts] at Socket.emit (events.js:211:7)
[egg-scripts] at addChunk (_stream_readable.js:263:12)
[egg-scripts] at readableAddChunk (_stream_readable.js:250:11)
[egg-scripts] at Socket.Readable.push (_stream_readable.js:208:10)
[egg-scripts] at TCP.onread (net.js:594:20)
[egg-scripts] name: "unhandledExceptionError"
[egg-scripts] pid: 23733
[egg-scripts] hostname: lhqcdz-uaes-ecom-nodejs0-ebaeef1e.novalocal

**Comment by sodabrew** [comment]
You're looking for the npm package. This is the Ruby gem. Completely unrelated projects. Good luck!
