### ISSUE TITLE
mysql2 0.5.2 crashes with Rails 5.2.2.1 and Ruby 2.4.x/2.5.x

### ISSUE THREAD

**Issue by odanylevskyi** [brianmario/mysql2#1031]
Please help. Stuck with the solution and can't find it anywhere.

/Users/xxxxxxx/.rvm/gems/ruby-2.4.5/gems/mysql2-0.5.2/lib/mysql2/client.rb:90: [BUG] Segmentation fault at 0x0000000000000000
ruby 2.4.5p335 (2018-10-18 revision 65137) [x86_64-darwin18]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:                    
     * ~/Library/Logs/DiagnosticReports                                     
     * /Library/Logs/DiagnosticReports                                      
   for more details.                                                        
Don't forget to include the above Crash Report log file in bug reports.     

-- Control frame information -----------------------------------------------
c:0046 p:---- s:0339 e:000338 CFUNC  :connect
c:0045 p:0688 s:0327 e:000326 METHOD /Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/mysql2-0.5.2/lib/mysql2/client.rb:90 [FINISH]
c:0044 p:---- s:0313 e:000312 CFUNC  :new
c:0043 p:0118 s:0308 e:000307 METHOD /Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/mysql2_adapter.rb:22
c:0042 p:0028 s:0301 e:000300 METHOD /Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_po
c:0041 p:0027 s:0297 e:000296 METHOD /Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_po
c:0040 p:0025 s:0293 e:000292 METHOD /Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_po
c:0039 p:0018 s:0287 e:000286 METHOD /Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_po
c:0038 p:0016 s:0281 e:000279 METHOD /Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_po
c:0037 p:0042 s:0275 e:000271 METHOD /Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_po
c:0036 p:0048 s:0268 e:000267 METHOD /Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_po
c:0035 p:0015 s:0262 e:000261 METHOD /Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2.1/lib/active_record/connection_handling.rb:118
c:0034 p:0008 s:0258 e:000257 METHOD /Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2.1/lib/active_record/connection_handling.rb:90
c:0033 p:0016 s:0254 e:000253 METHOD /Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:554
c:0032 p:0014 s:0248 e:000247 BLOCK  /Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/callbacks.rb:28
c:0031 p:0037 s:0245 e:000244 METHOD /Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:98
c:0030 p:0016 s:0236 e:000235 METHOD /Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/callbacks.rb:26
c:0029 p:0024 s:0229 e:000228 METHOD /Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/executor.rb:14
c:0028 p:0030 s:0221 e:000220 METHOD /Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/debug_exceptions.rb:61
c:0027 p:0012 s:0210 e:000209 METHOD /Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/web-console-3.7.0/lib/web_console/middleware.rb:135
c:0026 p:0092 s:0204 e:000203 BLOCK  /Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/web-console-3.7.0/lib/web_console/middleware.rb:30 [FINISH]
c:0025 p:---- s:0194 e:000193 CFUNC  :catch
c:0024 p:0011 s:0189 e:000188 METHOD /Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/web-console-3.7.0/lib/web_console/middleware.rb:20
c:0023 p:0030 s:0182 e:000181 METHOD /Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/show_exceptions.rb:33
c:0022 p:0051 s:0175 E:002510 METHOD /Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/railties-5.2.2.1/lib/rails/rack/logger.rb:38
c:0021 p:0012 s:0165 e:000164 BLOCK  /Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/railties-5.2.2.1/lib/rails/rack/logger.rb:26
c:0020 p:0007 s:0162 e:000161 BLOCK  /Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/activesupport-5.2.2.1/lib/active_support/tagged_logging.rb:71
c:0019 p:0019 s:0159 e:000158 METHOD /Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/activesupport-5.2.2.1/lib/active_support/tagged_logging.rb:28
c:0018 p:0016 s:0153 e:000152 METHOD /Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/activesupport-5.2.2.1/lib/active_support/tagged_logging.rb:71
c:0017 p:0049 s:0148 e:000147 METHOD /Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/railties-5.2.2.1/lib/rails/rack/logger.rb:26
c:0016 p:0049 s:0142 e:000141 METHOD /Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/sprockets-rails-3.2.1/lib/sprockets/rails/quiet_assets.rb:13
c:0015 p:0061 s:0137 e:000136 METHOD /Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/remote_ip.rb:81
c:0014 p:0047 s:0131 e:000130 METHOD /Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/request_id.rb:27
c:0013 p:0105 s:0125 e:000124 METHOD /Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/rack-2.0.6/lib/rack/method_override.rb:22
c:0012 p:0026 s:0119 e:000118 METHOD /Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/rack-2.0.6/lib/rack/runtime.rb:22
c:0011 p:0039 s:0109 e:000108 METHOD /Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/activesupport-5.2.2.1/lib/active_support/cache/strategy/local_cache_middleware.rb
c:0010 p:0024 s:0102 E:0014f0 METHOD /Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/executor.rb:14
c:0009 p:0103 s:0094 E:001560 METHOD /Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/static.rb:127
c:0008 p:0012 s:0086 E:0015f0 METHOD /Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/rack-2.0.6/lib/rack/sendfile.rb:111
c:0007 p:0026 s:0074 E:001650 METHOD /Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/railties-5.2.2.1/lib/rails/engine.rb:524
c:0006 p:0032 s:0068 E:0016a8 METHOD /Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/puma-3.12.1/lib/puma/configuration.rb:227
c:0005 p:0302 s:0063 E:0017a8 METHOD /Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/puma-3.12.1/lib/puma/server.rb:660
c:0004 p:0040 s:0038 E:001840 METHOD /Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/puma-3.12.1/lib/puma/server.rb:474
c:0003 p:0084 s:0026 E:0018c8 BLOCK  /Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/puma-3.12.1/lib/puma/server.rb:334 [FINISH]
c:0002 p:0160 s:0016 E:001970 BLOCK  /Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/puma-3.12.1/lib/puma/thread_pool.rb:135 [FINISH]
c:0001 p:---- s:0003 e:000002 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/puma-3.12.1/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/puma-3.12.1/lib/puma/server.rb:334:in `block in run'
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/puma-3.12.1/lib/puma/server.rb:474:in `process_client'
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/puma-3.12.1/lib/puma/server.rb:660:in `handle_request'
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/puma-3.12.1/lib/puma/configuration.rb:227:in `call'
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/railties-5.2.2.1/lib/rails/engine.rb:524:in `call'
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/rack-2.0.6/lib/rack/sendfile.rb:111:in `call'
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/static.rb:127:in `call'
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/activesupport-5.2.2.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/rack-2.0.6/lib/rack/runtime.rb:22:in `call'
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/rack-2.0.6/lib/rack/method_override.rb:22:in `call'
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/sprockets-rails-3.2.1/lib/sprockets/rails/quiet_assets.rb:13:in `call'
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/railties-5.2.2.1/lib/rails/rack/logger.rb:26:in `call'
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/activesupport-5.2.2.1/lib/active_support/tagged_logging.rb:71:in `tagged'
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/activesupport-5.2.2.1/lib/active_support/tagged_logging.rb:28:in `tagged'
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/activesupport-5.2.2.1/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/railties-5.2.2.1/lib/rails/rack/logger.rb:26:in `block in call'
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/railties-5.2.2.1/lib/rails/rack/logger.rb:38:in `call_app'
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/web-console-3.7.0/lib/web_console/middleware.rb:20:in `call'
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/web-console-3.7.0/lib/web_console/middleware.rb:20:in `catch'
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/web-console-3.7.0/lib/web_console/middleware.rb:30:in `block in call'
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/web-console-3.7.0/lib/web_console/middleware.rb:135:in `call_app'
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:98:in `run_callbacks'
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:554:in `call'
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2.1/lib/active_record/connection_handling.rb:90:in `connection'
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2.1/lib/active_record/connection_handling.rb:118:in `retrieve_connection'
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:1010:in `retrieve_connection'
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:382:in `connection'
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:523:in `checkout'
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:795:in `acquire_connection'
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:834:in `try_to_checkout_new_connection'
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:855:in `checkout_new_connection'
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:811:in `new_connection'
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/mysql2_adapter.rb:22:in `mysql2_connection'
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/mysql2_adapter.rb:22:in `new'
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/mysql2-0.5.2/lib/mysql2/client.rb:90:in `initialize'
/Users/odanylevskyi/.rvm/gems/ruby-2.4.5/gems/mysql2-0.5.2/lib/mysql2/client.rb:90:in `connect'

-- Machine register context ------------------------------------------------
 rax: 0x0000000107e19d97 rbx: 0x0000000000000001 rcx: 0x0000000107e1a3ac
 rdx: 0x0000000000000000 rdi: 0x00007ff68a102600 rsi: 0x0000000000000020
 rbp: 0x000070000a77feb0 rsp: 0x000070000a77fc70  r8: 0x0000000000000008
  r9: 0x00007ff68c944b90 r10: 0x00007ff68d4991b0 r11: 0x0000000106f2ca60
 r12: 0x0000000000000008 r13: 0x00007ff68a2de9b0 r14: 0x00007ff68a102600
 r15: 0x0000000000000000 rip: 0x0000000107e19d97 rfl: 0x0000000000010213

-- C level backtrace information -------------------------------------------
0   libruby.2.4.5.dylib                 0x0000000106f9fc17 rb_vm_bugreport + 135
1   libruby.2.4.5.dylib                 0x0000000106e28823 rb_bug_context + 467
2   libruby.2.4.5.dylib                 0x0000000106f14f28 sigsegv + 72
3   libsystem_platform.dylib            0x00007fff5a994b3d _sigtramp + 29
4   libmysqlclient.21.dylib             0x0000000107e19d97 mysql_options + 848
5   mysql2.bundle                       0x0000000107dfc32b rb_mysql_connect + 395
6   libruby.2.4.5.dylib                 0x0000000106f9928a call_cfunc_8 + 58
7   libruby.2.4.5.dylib                 0x0000000106f9319b vm_call_cfunc + 283
8   libruby.2.4.5.dylib                 0x0000000106f7c3f1 vm_exec_core + 12257
9   libruby.2.4.5.dylib                 0x0000000106f8d9f6 vm_exec + 118
10  libruby.2.4.5.dylib                 0x0000000106f9aaba rb_call0 + 202
11  libruby.2.4.5.dylib                 0x0000000106e96069 rb_class_new_instance + 41
12  libruby.2.4.5.dylib                 0x0000000106f9319b vm_call_cfunc + 283
13  libruby.2.4.5.dylib                 0x0000000106f7c3f1 vm_exec_core + 12257
14  libruby.2.4.5.dylib                 0x0000000106f8d9f6 vm_exec + 118
15  libruby.2.4.5.dylib                 0x0000000106f9ae05 invoke_block_from_c_splattable + 501
16  libruby.2.4.5.dylib                 0x0000000106f9be8e catch_i + 78
17  libruby.2.4.5.dylib                 0x0000000106f8a64a vm_catch_protect + 154
18  libruby.2.4.5.dylib                 0x0000000106f8ad64 rb_f_catch + 68
19  libruby.2.4.5.dylib                 0x0000000106f9319b vm_call_cfunc + 283
20  libruby.2.4.5.dylib                 0x0000000106f7bbb0 vm_exec_core + 10144
21  libruby.2.4.5.dylib                 0x0000000106f8d9f6 vm_exec + 118
22  libruby.2.4.5.dylib                 0x0000000106f8c356 vm_invoke_proc + 262
23  libruby.2.4.5.dylib                 0x0000000106f9474f vm_call_opt_call + 159
24  libruby.2.4.5.dylib                 0x0000000106f7c3f1 vm_exec_core + 12257
25  libruby.2.4.5.dylib                 0x0000000106f8d9f6 vm_exec + 118
26  libruby.2.4.5.dylib                 0x0000000106f8c356 vm_invoke_proc + 262
27  libruby.2.4.5.dylib                 0x0000000106f543d2 thread_start_func_2 + 1682
28  libruby.2.4.5.dylib                 0x0000000106f53d18 thread_start_func_1 + 184
29  libsystem_pthread.dylib             0x00007fff5a99d305 _pthread_body + 126
30  libsystem_pthread.dylib             0x00007fff5a9a026f _pthread_start + 70

-- Other runtime information -----------------------------------------------

* Loaded script: bin/rails

* Loaded features:

    0 enumerator.so
    1 thread.rb
    2 rational.so
    3 complex.so
    4 /Users/odanylevskyi/.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/x86_64-darwin18/enc/encdb.bundle
    5 /Users/odanylevskyi/.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/x86_64-darwin18/enc/trans/transdb.bundle
    6 /Users/odanylevskyi/.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/unicode_normalize.rb
    7 /Users/odanylevskyi/.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/x86_64-darwin18/rbconfig.rb
    8 /Users/odanylevskyi/.rvm/rubies/ruby-2.4.5/lib/ruby/site_ruby/2.4.0/rubygems/compatibility.rb
    9 /Users/odanylevskyi/.rvm/rubies/ruby-2.4.5/lib/ruby/site_ruby/2.4.0/rubygems/defaults.rb
   10 /Users/odanylevskyi/.rvm/rubies/ruby-2.4.5/lib/ruby/site_ruby/2.4.0/rubygems/deprecate.rb5.2.2.1/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/Users/xxxxxxxx/.rvm/gems/ruby-2.4.5/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:98:in `run_callbacks'
/Users/xxxxxxxx/.rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  /Users/xxxxxxxx/.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:554:in `call'
/Users/xxxxxxxx/.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2.1/lib/active_record/connection_handling.rb:90:in `connection'
/Users/xxxxxxxx/.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2.1/lib/active_record/connection_handling.rb:118:in `retrieve_connection'
  /Users/xxxxxxxx/.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:1010:in `retrieve_connection'
/Users/xxxxxxxx/.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:382:in `connection'
/Users/xxxxxxxx/.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:523:in `checkout'
  /Users/xxxxxxxx/.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:795:in `acquire_connection'
/Users/xxxxxxxx/.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:834:in `try_to_checkout_new_connection'
/Users/xxxxxxxx/.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:855:in `checkout_new_connection'
  /Users/xxxxxxxx/.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:811:in `new_connection'
/Users/xxxxxxxx/.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/mysql2_adapter.rb:22:in `mysql2_connection'
/Users/xxxxxxxx/.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/mysql2_adapter.rb:22:in `new'
  /Users/xxxxxxxx/.rvm/gems/ruby-2.4.5/gems/mysql2-0.5.2/lib/mysql2/client.rb:90:in `initialize'
/Users/xxxxxxxx/.rvm/gems/ruby-2.4.5/gems/mysql2-0.5.2/lib/mysql2/client.rb:90:in `connect'

-- Machine register context ------------------------------------------------
 rax: 0x0000000107e19d97 rbx: 0x0000000000000001 rcx: 0x0000000107e1a3ac
 rdx: 0x0000000000000000 rdi: 0x00007ff68a102600 rsi: 0x0000000000000020
 rbp: 0x000070000a77feb0 rsp: 0x000070000a77fc70  r8: 0x0000000000000008
  r9: 0x00007ff68c944b90 r10: 0x00007ff68d4991b0 r11: 0x0000000106f2ca60
 r12: 0x0000000000000008 r13: 0x00007ff68a2de9b0 r14: 0x00007ff68a102600
 r15: 0x0000000000000000 rip: 0x0000000107e19d97 rfl: 0x0000000000010213

-- C level backtrace information -------------------------------------------
0   libruby.2.4.5.dylib                 0x0000000106f9fc17 rb_vm_bugreport + 135
1   libruby.2.4.5.dylib                 0x0000000106e28823 rb_bug_context + 467
2   libruby.2.4.5.dylib                 0x0000000106f14f28 sigsegv + 72
3   libsystem_platform.dylib            0x00007fff5a994b3d _sigtramp + 29
4   libmysqlclient.21.dylib             0x0000000107e19d97 mysql_options + 848
5   mysql2.bundle                       0x0000000107dfc32b rb_mysql_connect + 395
6   libruby.2.4.5.dylib                 0x0000000106f9928a call_cfunc_8 + 58
7   libruby.2.4.5.dylib                 0x0000000106f9319b vm_call_cfunc + 283
8   libruby.2.4.5.dylib                 0x0000000106f7c3f1 vm_exec_core + 12257
9   libruby.2.4.5.dylib                 0x0000000106f8d9f6 vm_exec + 118
10  libruby.2.4.5.dylib                 0x0000000106f9aaba rb_call0 + 202
11  libruby.2.4.5.dylib                 0x0000000106e96069 rb_class_new_instance + 41
12  libruby.2.4.5.dylib                 0x0000000106f9319b vm_call_cfunc + 283
13  libruby.2.4.5.dylib                 0x0000000106f7c3f1 vm_exec_core + 12257
14  libruby.2.4.5.dylib                 0x0000000106f8d9f6 vm_exec + 118
15  libruby.2.4.5.dylib                 0x0000000106f9ae05 invoke_block_from_c_splattable + 501
16  libruby.2.4.5.dylib                 0x0000000106f9be8e catch_i + 78
17  libruby.2.4.5.dylib                 0x0000000106f8a64a vm_catch_protect + 154
18  libruby.2.4.5.dylib                 0x0000000106f8ad64 rb_f_catch + 68
19  libruby.2.4.5.dylib                 0x0000000106f9319b vm_call_cfunc + 283
20  libruby.2.4.5.dylib                 0x0000000106f7bbb0 vm_exec_core + 10144
21  libruby.2.4.5.dylib                 0x0000000106f8d9f6 vm_exec + 118
22  libruby.2.4.5.dylib                 0x0000000106f8c356 vm_invoke_proc + 262
23  libruby.2.4.5.dylib                 0x0000000106f9474f vm_call_opt_call + 159
24  libruby.2.4.5.dylib                 0x0000000106f7c3f1 vm_exec_core + 12257
25  libruby.2.4.5.dylib                 0x0000000106f8d9f6 vm_exec + 118
26  libruby.2.4.5.dylib                 0x0000000106f8c356 vm_invoke_proc + 262
27  libruby.2.4.5.dylib                 0x0000000106f543d2 thread_start_func_2 + 1682
28  libruby.2.4.5.dylib                 0x0000000106f53d18 thread_start_func_1 + 184
29  libsystem_pthread.dylib             0x00007fff5a99d305 _pthread_body + 126
30  libsystem_pthread.dylib             0x00007fff5a9a026f _pthread_start + 70

-- Other runtime information -----------------------------------------------

* Loaded script: bin/rails

* Loaded features:

    0 enumerator.so
    1 thread.rb
    2 rational.so
    3 complex.so
    4 /Users/xxxxxxxx/.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/x86_64-darwin18/enc/encdb.bundle
    5 /Users/xxxxxxxx/.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/x86_64-darwin18/enc/trans/transdb.bundle
    6 /Users/xxxxxxxx/.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/unicode_normalize.rb
    7 /Users/xxxxxxxx/.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/x86_64-darwin18/rbconfig.rb
    8 /Users/xxxxxxxx/.rvm/rubies/ruby-2.4.5/lib/ruby/site_ruby/2.4.0/rubygems/compatibility.rb
    9 /Users/xxxxxxxx/.rvm/rubies/ruby-2.4.5/lib/ruby/site_ruby/2.4.0/rubygems/defaults.rb
   10 /Users/xxxxxxxx/.rvm/rubies/ruby-2.4.5/lib/ruby/site_ruby/2.4.0/rubygems/deprecate.rb
   11 /Users/xxxxxxxx/.rvm/rubies/ruby-2.4.5/lib/ruby/site_ruby/2.4.0/rubygems/errors.rb
   12 /Users/xxxxxxxx/.rvm/rubies/ruby-2.4.5/lib/ruby/site_ruby/2.4.0/rubygems/version.rb
   13 /Users/xxxxxxxx/.rvm/rubies/ruby-2.4.5/lib/ruby/site_ruby/2.4.0/rubygems/requirement.rb
   14 /Users/xxxxxxxx/.rvm/rubies/ruby-2.4.5/lib/ruby/site_ruby/2.4.0/rubygems/platform.rb
   15 .........
[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

[IMPORTANT]
Don't forget to include the Crash Report log file under
DiagnosticReports directory in bug reports.

Abort trap: 6

**Comment by myhyper** [comment]
same here

**Comment by odanylevskyi** [comment]
I have downgraded mysql to 0.4.10 and it works. But none of higher versions works with Rails 5.2.2.1 and Ruby 2.4.x/2.5.x.

**Comment by chagel** [comment]
+1

**Comment by jagrament** [comment]
+1

**Comment by denisdenes** [comment]
+1

**Comment by jstoks** [comment]
@ odanylevskyi Thanks for the tip. I'm having the same issue and had to downgrade as well. Similar stack trace Ruby 2.5.5, Rails 5.2.3.

**Comment by chagel** [comment]
Finally fixed this long-time issue by reinstall mysql2 and specify openssl dependency libs. There has been changes in recent macOS for OpenSSL, such as deprecation support of SSL v2. 

> gem install mysql2 -v '0.5.2' -- --with-ldflags=-L/usr/local/opt/openssl/lib --with-cppflags=-I/usr/local/opt/openssl/include

**Comment by odanylevskyi** [comment]
@chagel Thanks it helps. Closing that issue now.

**Comment by paboalim-cw** [comment]
Thanks for your answer @chagel . It saved my time!
