### ISSUE TITLE
Using UDF for value on prepared statement insert

### ISSUE THREAD

**Issue by daveroberts** [brianmario/mysql2#1037]
I have a table with an ID that is BINARY(16).  I have a function, uuid_to_bin, that takes a VARCHAR(36) and returns a BINARY(16).  This code though:

```ruby
DB.use do |db|
      stmt = db.prepare("INSERT INTO some_table (id, name) VALUES (?, ?)
      stmt.execute("uuid_to_bin('9ec8dd7b-b28e-4a0e-bd1e-65b364cfeac5')", "test")
      return db.affected_rows
    end
```

Doesn't execute the UDF and instead tries to insert the function as a string.  Is there a way I can tell the mysql2 gem this is a user defined function?

**Comment by sodabrew** [comment]
Right, if that were allowed it would be a SQL injection!

Try it this way:

```
DB.use do |db|
      stmt = db.prepare("INSERT INTO some_table (id, name) VALUES (uuid_to_bin(?), ?)
      stmt.execute("9ec8dd7b-b28e-4a0e-bd1e-65b364cfeac5", "test")
      return db.affected_rows
end
```

**Comment by daveroberts** [comment]
Thanks
