### ISSUE TITLE
Did anyway can to port Mysql 8.0 on 0.3.x

### ISSUE THREAD

**Issue by imiskolee** [brianmario/mysql2#1039]
Hi,Team:

I am working on a old ruby project(Ruby 1.9.3), and want to use MySQL 8.0,  did we have anyway to solve Mysql2 0.3.x bugs on MySQL 8.0, or list all changes for 8.0 ?

**Comment by sodabrew** [comment]
No, I'm not going to do this work to support ancient Ruby with modern MySQL. It doesn't make sense for any sensible use case. It isn't a good use of my time as a maintainer. Strongly advise that you update your Ruby version to a supported version at this time.
