### ISSUE TITLE
mysql2 gem doesn't support Openssl FIPS mode

### ISSUE THREAD

**Issue by pkazi** [brianmario/mysql2#1059]
When running any query over mysql client, getting fips error as 
```OpenSSL internal error, assertion failed: Low level API call to digest SHA1 forbidden in FIPS mode!```

Platform - `CentOS Linux release 7.6.1810 (Core) `
openssl version - `OpenSSL 1.0.2k-fips  26 Jan 2017`
Kernel in FIPS mode

**Comment by sodabrew** [comment]
But what would this gem to do change this?

**Comment by sodabrew** [comment]
Closing since there was no reply.
