### ISSUE TITLE
Can you update secure connection to version 0.2.19?

### ISSUE THREAD

**Issue by hungbuijr** [brianmario/mysql2#1061]
My project is using mysql2 version 0.2.19 and i stuck when bundle install your gem.
Can you update it like this?

https://github.com/brianmario/mysql2/blob/267a53887cb52f799d6a84f08cd1664bf6288f86/ext/mysql2/client.c#L1384

I will be honest if can be your contributor. Thank from my bottom of heart!

**Comment by sodabrew** [comment]
I’m sorry, please update your project. I’m not going  to make any new 0.2.x releases.

**Comment by hungbuijr** [comment]
> I’m sorry, please update your project. I’m not going to make any new 0.2.x releases.

So sad when read your message, Because this project is own by my company and i cannot recommend or suggest them to upgrade version. They are scare of conflicting when upgrade.

However, so many thankful to you @sodabrew . I 'll be grateful if can contribute for you something!
