### ISSUE TITLE
Segmentation fault with ruby 2.4.1, mysql2 0.5.1 and rails 0.5.7

### ISSUE THREAD

**Issue by priyamwad-pathak** [brianmario/mysql2#1069]
When I tried to run following migration to change schema's collation (to include emoticons), I got the segmentation fault.

`
class ChangeDatabaseCharsetAndCollation < ActiveRecord::Migration[5.0]
  def db
    ActiveRecord::Base.connection
  end

  def up
    execute "ALTER DATABASE `#{db.current_database}` CHARACTER SET utf8mb4;"
      db.tables.each do |table|
        execute "ALTER TABLE `#{table}` CONVERT TO CHARACTER SET utf8mb4 COLLATION utf8mb4_unicode_ci;"
        db.columns(table).each do |column|
          case column.sql_type
            when "text"
              execute "ALTER TABLE `#{table}` MODIFY body TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
            when /varchar\(([0-9]+)\)/i
              # InnoDB has a maximum index length of 767 bytes, so for utf8 or utf8mb4
              # columns, you can index a maximum of 255 or 191 characters, respectively.
              # If you currently have utf8 columns with indexes longer than 191 characters,
              # you will need to index a smaller number of characters.
              indexed_column = db.indexes(table).any? { |index| index.columns.include?(column.name) }
              sql_type = (indexed_column && $1.to_i > 191) ? "VARCHAR(191)" : column.sql_type.upcase
              execute "ALTER TABLE `#{table}` CHANGE `#{column.name}` `#{column.name}` #{sql_type} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
          end
        end
    end
  end
end
`

I'm getting segmentation fault while running this. Ruby level backtrace information is given below:

-- Ruby level backtrace information ----------------------------------------
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/bin/bundle:22:in `<main>'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/bin/bundle:22:in `load'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/exe/bundle:22:in `<top (required)>'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/exe/bundle:30:in `block in <top (required)>'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/cli.rb:18:in `start'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/cli.rb:27:in `dispatch'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/cli.rb:463:in `exec'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:28:in `run'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:74:in `load'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/bin/rake:22:in `<top (required)>'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/bin/rake:22:in `load'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:83:in `block in run'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:110:in `top_level'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:125:in `run_with_threads'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block in top_level'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `each'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:160:in `invoke_task'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/task.rb:182:in `invoke'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `execute'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `each'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `block in execute'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.0.7/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.0.7/lib/active_record/tasks/database_tasks.rb:163:in `migrate'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.0.7/lib/active_record/migration.rb:984:in `migrate'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.0.7/lib/active_record/migration.rb:1006:in `up'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.0.7/lib/active_record/migration.rb:1006:in `new'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.0.7/lib/active_record/migration.rb:1127:in `initialize'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.0.7/lib/active_record/connection_adapters/abstract/schema_statements.rb:1008:in `initialize_schema_migrations_table'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.0.7/lib/active_record/schema_migration.rb:24:in `create_table'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.0.7/lib/active_record/schema_migration.rb:20:in `table_exists?'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.0.7/lib/active_support/deprecation/instance_delegator.rb:20:in `silence'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.0.7/lib/active_support/deprecation/reporting.rb:36:in `silence'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.0.7/lib/active_record/schema_migration.rb:20:in `block in table_exists?'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.0.7/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:344:in `table_exists?'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.0.7/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:355:in `data_source_exists?'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.0.7/lib/active_record/connection_adapters/abstract/database_statements.rb:63:in `select_values'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.0.7/lib/active_record/connection_adapters/mysql/database_statements.rb:19:in `select_rows'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.0.7/lib/active_record/connection_adapters/mysql/database_statements.rb:65:in `select_result'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.0.7/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:225:in `execute_and_free'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.0.7/lib/active_record/connection_adapters/mysql/database_statements.rb:65:in `block in select_result'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.0.7/lib/active_record/connection_adapters/mysql/database_statements.rb:21:in `block in select_rows'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.0.7/lib/active_record/connection_adapters/mysql/database_statements.rb:21:in `to_a'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-mini-profiler-1.0.0/lib/patches/db/mysql2.rb:8:in `each'
/Users/priyamwad.pathak/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-mini-profiler-1.0.0/lib/patches/db/mysql2.rb:8:in `each'

**Comment by sodabrew** [comment]
Please try again with mysql2 0.5.2 because that is the most recent version and I believe your bug is fixed per the release notes: https://github.com/brianmario/mysql2/releases/tag/0.5.2

**Comment by priyamwad-pathak** [comment]
It worked with latest version (0.5.2). Thanks!
