### ISSUE TITLE
Can't connect to MySQL 8.0 with SSL

### ISSUE THREAD

**Issue by vitobotta** [brianmario/mysql2#1077]
Hi! I am trying to connect to a managed MySQL database by DigitalOcean, which uses MySQL 8.0.

In my Docker image I am installing mysql-client and libmysqlclient-dev for MySQL 8.0 and the mysql2 gem is installed without errors. But when the Rails (6) app starts I get this error:

```
libmysqlclient.so.20: cannot open shared object file: No such file or directory - /home/rails/bundle/gems/mysql2-0.5.2/lib/mysql2/mysql2.so (LoadError)
```

Any idea on how to fix? Unfortunately DigitalOcean only offers MySQL 8.0. Thanks in advance.

**Comment by vitobotta** [comment]
I am reopening and have changed the title as I am getting another error now:

```
Mysql2::Error::ConnectionError (SSL connection error: unknown error number)
```

That unknown error doesn't say much. I am using a connection string that enables SSL and am specifying the path of the certificate with the `sslca` option. What can I do?

**Comment by Marinofull** [comment]
@vitobotta were you able to find a solution?
I'm with the same issue, I used mysql 5.7 with my rails application, and when tried to upgrade for mysql 8.0 got the same message on the first migration to build the database:
`#<Mysql2::Error: SSL connection error: unknown error number>
Couldn't create database for {"adapter"=>"mysql2", "pool"=>5, "timeout"=>5000, "host"=>"db", "username"=>foo, "password"=>"bar", "database"=>"foobar"}, {:charset=>"utf8", :collation=>"utf8_unicode_ci"}`

**Comment by Victorcorcos** [comment]
vito botta pra lenhar

**Comment by sodabrew** [comment]
@vitobotta Someone just commented on this issue, so now I'm seeing it for the first time in a year. Please, please always create a new issue for a new issue.

Since it's been a year, are you still stuck? If you solved the problem, what was your solution?

Off the cuff, my own guess would be that you may have upgraded your server without upgrading your client library. The recent changes in MySQL 8's SSL support very likely require a MySQL 8.x client library as well.

**Comment by vitobotta** [comment]
Hi @sodabrew , sorry I had forgotten about this. I switched to Postgres months ago.

**Comment by jjy05** [comment]
> Oh looks like I had to run `apt-get install libmysqlclient20`.

Thanks a lot!!!!! I use Sinatra and try to connect  to a mysql8 database in docker but I got error "SSL connection error: unknown error number", I didn't find any solution.Your comment saved me!

**Comment by buithehien1991** [comment]
How about windows with RubyInstaller ? Please help me
