### ISSUE TITLE
db:schema:dump generates different code between development and test environments

### ISSUE THREAD

**Issue by vitobotta** [brianmario/mysql2#1078]
Hi, I am currently using the revision 46369c0e6773c2ae91aac9f01bfbf71482f1cbeb of the gem because I am using MySQL 8 managed by DigitalOcean and I had problems with the 0.5.2 release. 

If I run `db:schema:dump` in the test environment it generates `create_table` blocks having the `options` config set to `"ENGINE=InnoDB DEFAULT CHARSET=utf8"`. However if I run `db:schema:dump` in the development environment, `options` is set to the full create table sql command `"CREATE TABLE ...."`. Of course this dump is not valid, in fact if I try `db:schema:load` with this schema I get an error saying that the syntax is invalid.

What could be causing this different behaviour between development and test environments?

Thanks!

**Comment by vitobotta** [comment]
It looks like it may be something related to the version of MySQL 8 managed by DigitalOcean (not sure yet). If I connect the development environment to the test database running on my Mac, or run the schema dump from the test container but with RAILS_ENV set to `development`, the schema.rb generated is valid. So the only difference seems to be DO's MySQL....

**Comment by sodabrew** [comment]
mysql2 gem does not get involved in the schema dump contents. This is an ActiveRecord feature.

**Comment by vitobotta** [comment]
Thanks @sodabrew. I have done other tests and I believe it's a problem with DigitalOcean, not with mysql2 or rails.
