### ISSUE TITLE
Mysql2 don't support Ruby 2.6.5

### ISSUE THREAD

**Issue by rodolfoholy** [brianmario/mysql2#1082]
Dear Mysql2 owner,

I tried to gem install mysql2, but the gem don't support the new stable version of Ruby 2.6.5.114. Any news when this update can come?

λ gem install mysql2 -v 0.5.2
ERROR:  Error installing mysql2:
        The last version of mysql2 (= 0.5.2) to support your Ruby & RubyGems was 0.5.2. Try installing it with `gem install mysql2 -v 0.5.2`
        mysql2 requires Ruby version >= 2.0, < 2.6. The current ruby version is 2.6.5.114.

Thanks for your attention and your great support!

**Comment by sodabrew** [comment]
You're on Windows?

**Comment by rodolfoholy** [comment]
@sodabrew Yes.

**Comment by sodabrew** [comment]
https://rubygems.org/gems/mysql2 0.5.3 is now posted with updated Windows pre-built binaries for Ruby 2.2 - 2.6.
