### ISSUE TITLE
Querying for `.not(attribute: [nil, ""])` always brings back no results in Rails 6

### ISSUE THREAD

**Issue by jsilasbailey** [brianmario/mysql2#1108]
I wasn't exactly sure where to bring this up, but seems to be an issue at the level of the mysql adapter as it doesn't occur with a postgres db. Let me know if this needs to be brought up in [rails](https://github.com/rails/rails) instead.

## Context
When querying for records that have a *non-empty* AND *non-null* attribute on a column that is of type `VARCHAR` and `NULL`-able, no records are ever returned despite records existing that should be returned. Also, even if you just want to query for records with an empty attribute, `where(attribute: "")`, incorrect SQL is generated.

Is this a choice in behavior or unexpected?
Rails before version 6 generates expected SQL below.

## Expected
```ruby
Model.where.not(attribute: [nil, ""]).to_sql
#=> SELECT ... WHERE NOT (attribute IS NULL OR attribute = "")
```
```ruby
Model.where(attribute: "").to_sql
#=> SELECT ... WHERE attribute = ""
```

## Actual
```ruby
Model.where.not(attribute: [nil, ""]).to_sql
#=> SELECT ... WHERE NOT (attribute IS NULL OR attribute = NULL)
```
```ruby
Model.where(attribute: "").to_sql
#=> SELECT ... WHERE attribute = NULL
```

## Versions
Ruby: 2.5.7
Rails: 6.0.2.1
DB: MariaDB 10.1

**Comment by sodabrew** [comment]
This is a Rails / ActiveRecord issue. The mysql2 driver does not provide SQL generation, it only executes the SQL as generated from the layer above.

**Comment by jsilasbailey** [comment]
> This is a Rails / ActiveRecord issue. The mysql2 driver does not provide SQL generation, it only executes the SQL as generated from the layer above.

Thanks I'll move this there
