### ISSUE TITLE
Mysql lost parameters during saving

### ISSUE THREAD

**Issue by se0ga** [brianmario/mysql2#1110]
Sorry we just desperate and need help.
We are trying to migrate from rails 4 to rails 5 and
have an error, where it says we have a null violation for one of our fields: created_at
in this code:

    version_set.each_with_index do |version_from_set, index|
      ...
      version_name = version_from_set['version_name']
      new_version = Version.new
      new_version.name = version_name
      new_version.save
      ...
    end
Error:
> ActiveRecord::NotNullViolation (Mysql2::Error: Field 'created_at' doesn't have a default value: INSERT INTO versions (updated_at) VALUES ('2020-02-25 10:55:50')) We are thinking about upgrading mysql - but not convinced that this is the issue. And it's not easy to upgrade it in AWS Elastic Beanstalk Schema.db

Its working fine with RACK_ENV=development but error appear in RACK_ENV=production.

Error with stack of requests:
[![enter image description here][1]][1]

1. Error
2. Requests should be the same but every request was cut of of one parameter
and in the last request there are only one parameter.

This is how it looks in development mode. All parameters was provided:

[![enter image description here][2]][2]

We desperate. We spend couple weeks trying to track this error. Any suggestions?
Rails 5.0.7.2 (5.2.4.1 the same)
mysql2 0.4.10(0.5.2 the same)
Ruby 2.6.5

  [1]: https://i.stack.imgur.com/3FqYV.png
  [2]: https://i.stack.imgur.com/Z91GA.png

**Comment by sodabrew** [comment]
Based on the error:

> ActiveRecord::NotNullViolation (Mysql2::Error: Field 'created_at' doesn't have a default value: INSERT INTO versions (updated_at) VALUES ('2020-02-25 10:55:50')) We are thinking about upgrading mysql - but not convinced that this is the issue. And it's not easy to upgrade it in AWS Elastic Beanstalk Schema.db

Have you tried adjusting the schema to set a default value for the `updated_at` field? Here's a blog post about some MySQL options: https://optimize-this.blogspot.com/2012/04/datetime-default-now-finally-available.html

Based on the difference between staging and production, have you compared the schemas and the MySQL server versions to see if something is different?

I see you also posted at https://github.com/rails/rails/issues/38622 as well, but this is not a Rails bug, this is also not a mysql2 gem bug, so really you need to look at your code and your database schema and correctly configure your application.

**Comment by se0ga** [comment]
Thanks!
