### ISSUE TITLE
Can't import "mysql2/promise" into ES module (MJS) on Node.js 13.12/14.00

### ISSUE THREAD

**Issue by pubmikeb** [brianmario/mysql2#1114]
I'm trying to convert my project from CommonJS (CJS) to ES Module (MJS), to do that I use:
```js
import mysqlPromise from "mysql2/promise";
```

But then I get an error:
> Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\Users\User\IdeaProjects\…\node_modules\mysql2\promise' imported from…

Then I found a recently closed [thread](https://github.com/nodejs/node/issues/27408) on the Node.js Github, where it's written «Closing as this is by design.»

Is it possible to provide `mysql2/promise` in MJS-friendly mode to be able to easily import `mysql2/promise`?

**Comment by simi** [comment]
Seems you have reported issue to wrong repo. This is `mysql2` rubygem repo. You're looking probably for `mysql2` node package repo, which is hosted at https://github.com/sidorares/node-mysql2.

**Comment by pubmikeb** [comment]
@simi, you're right! Sorry. Could you, please, close this issue?
