### ISSUE TITLE
Generated query for prepared statements

### ISSUE THREAD

**Issue by psulightning** [brianmario/mysql2#1129]
Maybe I'm dense, but I cannot seem to find a way to see what the query generated through the prepared statements resulted in.  I would like to be able to see for debugging purposes.  Is this possible current on 0.5.3, or should this be a feature request?

Thanks.

**Comment by sodabrew** [comment]
This isn't a thing that exists. The query isn't generated at run time at all - you write the query and put `?` question marks where the variables will go. When you execute the query, there isn't like string interpolation that substitutes the question marks on the client-side, it actually happens on the server-side API not the SQL parsing layer.

**Comment by psulightning** [comment]
I always forget how they work (been a long time since i did a DBMS course).  Thanks for the response.
