### ISSUE TITLE
Question: Set Password Support?

### ISSUE THREAD

**Issue by bstopp** [brianmario/mysql2#1133]
This is more of a question. I'm trying to execute a _SET PASSWORD_ command, and while I'm not getting any errors back, it also does not update the password.

So mostly my q is: is this command supported? (is that a dumb q to ask? )

**Comment by sodabrew** [comment]
User management statements are just like any other SQL statement. There is no specific driver support required.

**Comment by bstopp** [comment]
That's what i thought - and yet, the password is not being updated.
