### ISSUE TITLE
Rethinking CI?

### ISSUE THREAD

**Issue by junaruga** [brianmario/mysql2#1149]
Do you know Travis's following announcements about their changes?

https://blog.travis-ci.com/oss-announcement
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing
> The upcoming pricing change will affect those of you who are:
> Building on the macOS environment
> Building with more than 10 concurrent builds
> Building on a public repositories only

And I feel Travis on my forked repository is very slow now.

It seems that the Ruby project recently migrated the most cases to GitHub Actions remaining a few non-x86_64 jobs in Travis.
https://github.com/ruby/ruby/blob/f3c19ddfbcfde63505a34b7a5b3a640f23b22dc0/.travis.yml#L199-L204

So, how do you think of migrating Travis to GitHub Actions or an alternative CI?

**Comment by sodabrew** [comment]
Yes, Travis is done. I want to migrate several projects to GitHub Actions. I would gladly take a PR before I have time to do it myself!

**Comment by gautamkrishnar** [comment]
I Will give it a try during my free time

**Comment by simi** [comment]
@gautamkrishnar I think it could be done in iterative way. It could be possible to get up quickly simple pipeline using linux + default mariadb in there and we can add the rest in following PRs. Feel free to ping me if any help is needed.

**Comment by junaruga** [comment]
OK. Thanks for your help, guys!

**Comment by junaruga** [comment]
@gautamkrishnar I sent the PR #1154 now, but I think you can also sent your PR.

**Comment by gautamkrishnar** [comment]
@junaruga please feel free to work on it, I was busy with my work didn't get a chance to look into it.

**Comment by junaruga** [comment]
I am waiting someone's review for my PR https://github.com/brianmario/mysql2/pull/1154 to migrate majority of cases in Travis to GitHub Actions. Anyone, could you review to merge it? Thanks.

**Comment by sodabrew** [comment]
Thank you @junaruga !!

**Comment by junaruga** [comment]
I opened a new PR https://github.com/brianmario/mysql2/pull/1168 to migrate centos case from Travis to GitHub Actions, and add fedora cases here.

**Comment by junaruga** [comment]
Now I am working on migrating Mac OSX case in Travis to GitHub Actions.

**Comment by junaruga** [comment]
I opened a new PR #1170 to migrate macOS case from Travis to GitHub Actions.

**Comment by junaruga** [comment]
Note Travis-ci.org shut down will occur on May 31, 2021.
https://blog.travis-ci.com/2021-05-07-orgshutdown

I know this repository does not use non-x86_64 (amd64) CPU CI cases. But just in case, here is a useful info. The `arch: arm64`, `arch: ppc64le`, `arch: s390x` free unlimited builds for all the open source repositories yesterday. If you migrate this repository to travis-ci.com, we can use these CPU architectures for free even after the May 31, 2021.
https://docs.travis-ci.com/user/billing-overview/#partner-queue-solution

Here is my repository to test the CPU architectures on travis-ci.com. I confirmed it is free.
https://github.com/junaruga/ci-multi-arch-native-test
