### ISSUE TITLE
Homebrew 3.0.0 issue?

### ISSUE THREAD

**Issue by naoyanickf** [brianmario/mysql2#1166]
I  started to use homebrew 3.0.0, so my mysql install folder is now under "opt/homebrew".
After this change, I couldn't connect mysql with mysql2. Now When I type "rails server", I'm getting 

```
dyld: lazy symbol binding failed: Symbol not found: _mysql_server_init
  Referenced from: /Users/naoyafujita/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/mysql2-0.5.2/lib/mysql2/mysql2.bundle
  Expected in: flat namespace

dyld: Symbol not found: _mysql_server_init
  Referenced from: /Users/naoyafujita/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/mysql2-0.5.2/lib/mysql2/mysql2.bundle
  Expected in: flat namespace
```

I think this is because of my new brew path. But how can I deal with this?

**Comment by pquimo** [comment]
Are you by chance on an M1 mac?  I was getting that same error, and decided it was probably because mysql was compiled for x86 and ruby & mysql2 gem were compiled for arm.  My solution was to build mysql myself.  That fixed it for me.

**Comment by naoyanickf** [comment]
@pquimo yes, I'm using M1 mac. 

>My solution was to build mysql myself.

thanks! I will try it!

**Comment by naoyanickf** [comment]
@pquimo 

actually... how to do it?

**Comment by pquimo** [comment]
Here's a gist of what I did.

https://gist.github.com/pquimo/7623184dd229dfbb50f3c0fcd1d6923c

**Comment by naoyanickf** [comment]
@pquimo ooooooo!!!!

thank you!!! 

this would help so many people in the future...
