### ISSUE TITLE
Could we have a new release? (0.5.4)

### ISSUE THREAD

**Issue by casperisfine** [brianmario/mysql2#1179]
Sorry for asking this, I know it's a bit annoying for maintainers. But there's a bunch of important fixes on master and there wasn't any release in over a year. 

We've been using `mysql2` as a git gem for a long time, and I'd love if we could finally go back to a published version.

**Comment by casperisfine** [comment]
@sodabrew sorry to insist, but it's really annoying to have to use the git gem on all new projects.

**Comment by TomA-R** [comment]
This would be really useful, maybe @brianmario or @tenderlove could help? Thanks a lot in advance

**Comment by tenderlove** [comment]
I have access to do a release, but I haven't committed to this project in quite a while.  @sodabrew do you have time to ship a release?  If not, I can take care of it (but I don't want to step on your toes 🙇🏻‍♂️)

**Comment by sodabrew** [comment]
Thanks for the nudge, I really do need to do this!

**Comment by listerino** [comment]
hey @sodabrew is this something we can help with?

**Comment by listerino** [comment]
Happy 2 year anniversary to the last release! 🎉  57 commits and 1300 lines of change later, it seems like cutting a new release is simply too much effort. Can we get another maintainer @sodabrew? Otherwise maybe @tenderlove can take this task over?

**Comment by simi** [comment]
I think we should fix master CI first. @listerino I think you're more than welcomed to help on that. I can try to spend some time in that during the weekend as well.

**Comment by listerino** [comment]
That's a fair point, @simi! I'll have a look into it, thank you for also volunteering, it's appreciated

**Comment by casperisfine** [comment]
> I think we should fix master CI first.

There are currently 3 issues on CI:

  - One client session tracking test fail against mysql 8: https://github.com/brianmario/mysql2/issues/1220 I pinged the original author and he's a college so I'll make sure to followup on that one.
  - There's a small Ruby 3.1 change, I submitted a PR for it: https://github.com/brianmario/mysql2/pull/1219
  - Then there's two date casting test that need to be updated for mysql 8 https://github.com/brianmario/mysql2/issues/1208, I'll submit a PR too.

**Comment by casperisfine** [comment]
For the datetime one: https://github.com/brianmario/mysql2/pull/1221

So only the session tracking one has no fix yet.

**Comment by listerino** [comment]
You're a machine, thank you, Jean. I was planning to set my weekend aside to investigate what took you ~2 hours - fingers crossed your fixes get reviewed&merged!

**Comment by casperisfine** [comment]
The original problem remains though, I'll see with @tenderlove for the merges on next week, but it would be best if @sodabrew was around for the actual release.

**Comment by TomA-R** [comment]
Seems like we owe a _thank you_ to our friends at Shopify for looking into the CI issues - thanks guys!

**Comment by casperisfine** [comment]
Looks like there's two more issues on CI:

```
wrong number of arguments (given 5, expected 1)
ruby/3.1.0/psych.rb:323:in `safe_load'
~/gems/rubocop-0.50.0/lib/rubocop/config_loader.rb:216:in `yaml_safe_load'
ruby/gems/3.1.0/gems/rubocop-0.50.0/lib/rubocop/config_loader.rb:199:in `load_yaml_configuration'
```

That's because the rubocop version is way too old to work with the YAML that ships with ruby-head. I'll submit a PR to upgrade rubocop.

Then the macos builds are failing with:

```
linking shared-object mysql2/mysql2.bundle
ld: warning: directory not found for option '-L/usr/local/opt/openssl@3/lib'
ld: library not found for -lssl
```

This one rings a bell, but these makefiles aren't exactly my forte.

**Comment by casperisfine** [comment]
Oh and thanks @tenderlove for the merges.

**Comment by casperisfine** [comment]
Two more CI fixes:

  - Fix ruby-head & rubocop incompatibility https://github.com/brianmario/mysql2/pull/1225
  - Fix macOS SSL link issue: https://github.com/brianmario/mysql2/pull/1225

After these two, there are two failures left on `macOS / mysql` specifically:

```

  1) Mysql2::Client#query evented async queries should be supported
     Failure/Error: expect(loops >= 1).to be true

       expected true
            got false
     # ./spec/mysql2/client_spec.rb:756:in `block (3 levels) in <top (required)>'

  2) Mysql2::EM::Client should not raise error when closing client with no query running
     Failure/Error: expect(callbacks_run).to eq([:callback])

       expected: [:callback]
            got: []

       (compared using ==)

       Diff:
       @@ -1 +1 @@
       -[:callback]
       +[]
     # ./spec/em/em_spec.rb:124:in `block (4 levels) in <top (required)>'
     # ./spec/em/em_spec.rb:114:in `block (2 levels) in <top (required)>'
```

But so far I wasn't able to reproduce them so not sure what to do at this point.

**Comment by sodabrew** [comment]
Million thanks for the energy this week getting the test failures cleaned up and reviewing recent PRs!

**Comment by BrianHawley** [comment]
Don't forget Ruby 2.7 to 3.1 support (Windows binaries) and #1232 (deprecation warning on Ruby 3.1).

**Comment by casperisfine** [comment]
Any opinions on what to do about the osx failures?

**Comment by fuegas** [comment]
It looks related to https://bugs.ruby-lang.org/issues/17865 , however, those are fixed for Ruby 2.6 and 2.7. I'm not sure if this is something you can patch before compiling the gem. The [code change of the PR](https://github.com/ruby/ruby/pull/4504/files) seems small. Is this something that can be applied before building the gem on OS-X? As Ruby 2.4 went EOL on 2020-03-31, the chance of a conflict during the apply should be minimal.

**Comment by casperisfine** [comment]
> It looks related to https://bugs.ruby-lang.org/issues/17865

No that's just a red herring, it's all just warnings. The actual issue is the spec failure: https://github.com/brianmario/mysql2/issues/1179#issuecomment-983479297

**Comment by ottok** [comment]
A new 0.5.4 release that includes commit cca57b97ad6d1b1b985376be110b89d2b487dea6 would enable Debian to release a new version of [ruby-mysql2](https://tracker.debian.org/pkg/ruby-mysql2) to fix [Debian bug #1002087](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1002087), which in turn would unblock [MariaDB 10.6](https://tracker.debian.org/pkg/mariadb-10.6) from entering Debian testing, which in turn would unblock [mariadb-10.5 10.5.13-0+deb11u1](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1000342) from entering Debian Bullseye, which in turn would fix [Debian#1003839](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1003839) and a bunch of other issues.

Thanks everybody who are maintaining this library! Your work is important :)

**Comment by cllns** [comment]
I'd also appreciate a release, since I ran into the same issue as #1096, which has been fixed in https://github.com/brianmario/mysql2/commit/f62edc0d17b3c31fdf2d5581a82feec8393239d2 but not released yet.

If others are also trying to install mysql2 on Ruby 2.7 after running Homebrew's `brew install mysql`, I got it working by:
1. Changing `Gemfile` to use `github: "brianmario/mysql2"` instead of default Rubygems.org source
2. Running [this command to configure bundler for Homebrew's mysql](https://github.com/brianmario/mysql2/issues/1229#issuecomment-1016037330):
```shell
bundle config build.mysql2 \
  --with-mysql-lib=/opt/homebrew/opt/mysql/lib \
  --with-mysql-dir=/opt/homebrew/opt/mysql\
  --with-mysql-config=/opt/homebrew/opt/mysql/bin/mysql_config \
  --with-mysql-include=/opt/homebrew/opt/mysql/include\
  --with-ldflags=-L/opt/homebrew/opt/openssl@3/lib\
  --with-cppflags=-I/opt/homebrew/opt/openssl@3/include
```
3. Running `bundle install`

**Comment by zenspider** [comment]
Nudge

**Comment by tenderlove** [comment]
Do we have any blockers left for release?

**Comment by casperisfine** [comment]
@tenderlove there are two tests failing on OSX CI https://github.com/brianmario/mysql2/issues/1179#issuecomment-983479297. I tried to reproduce them but couldn't, so I have no idea what's up.

I'd be of the opinion to skip them for now, but that's not my call.

**Comment by bquorning** [comment]
#1115 (merged) added some support for Ruby 2.7’s `GC.compact`, but #1192 (open) claims to _also_ add support for `GC.compact`. I was hoping that v0.5.4 would have full support for compacting GC, so maybe someone could take a look at #1192 and see if it’s still relevant?

I noticed that the [0.5.4 milestone](https://github.com/brianmario/mysql2/milestone/29) has 7 open issues but whether they are truly blockers before the next release, I cannot say.

**Comment by casperisfine** [comment]
> so maybe someone could take a look at https://github.com/brianmario/mysql2/pull/1192 and see if it’s still relevant?

#1115 registered the gobal variables so that they won't move, that prevent mysql2 from hard crashing.

https://github.com/brianmario/mysql2/pull/1192 refactor mysql2 to use new APIs, so that's the objects it creates can be moved, it's nice but not absolutely necessary.

**Comment by tomfull123** [comment]
It looks like the outstanding issues on the [0.5.4 milestone](https://github.com/brianmario/mysql2/milestone/29) have all come over from previous milestones, so they aren't new issues, I don't think they should block the release.

One of the issues does have an approve PR though.

**Comment by zenspider** [comment]
Should I *not* keep nudging on this?

**Comment by breisig** [comment]
Keep nudging. We are all waiting.

**Comment by tenderlove** [comment]
@sodabrew I'd like to get this thing shipped.  LMK if you want to do it, or if you see anything blocking.  Otherwise I'll ship this next week.

Thanks!

**Comment by tenderlove** [comment]
Alright.  I shipped 0.5.4.  Please file any issues if you have problems upgrading and I'll try to get any issues shipped ASAP.  Thanks for your patience everyone! ❤️

**Comment by BrianHawley** [comment]
@tenderlove could you add a new release to the Releases section here? That's where we see the changelogs.

**Comment by tenderlove** [comment]
@BrianHawley done
