### ISSUE TITLE
dockerコンテナをappとdbで分ける

### ISSUE THREAD

**Issue by it-walker** [brianmario/mysql2#1189]
## 概要

現在、一緒になっているので、そのうち別々に分けたい。

**Comment by junaruga** [comment]
@it-walker Did you point the issue on the wrong repository? I think this repository encourages English. チケットを書き込むページを間違えていませんか？閉じてもらえませんか？

**Comment by sodabrew** [comment]
@it-walker Your question is about separation an application from its database? yes, you should definitely use separate containers for applications and databases! This is a general best practice, though, and not related to the mysql2 gem itself which will work in either configuration with a database on localhost or another hostname.

**Comment by junaruga** [comment]
Aaron, you are so kind. :-)
I can read Japanese, and I think he did not ask a question to someone here. It seems that the text is his memo for the task.
