### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found: _mysql_init

### ISSUE THREAD

**Issue by olimart** [brianmario/mysql2#121]
What does that issue means when running rake db:create (apply to setup, migrate...) and how to resolve it?

dyld: lazy symbol binding failed: Symbol not found: _mysql_init
  Referenced from: /Library/Ruby/Gems/1.8/gems/mysql2-0.2.6/lib/mysql2/mysql2.bundle
  Expected in: flat namespace

dyld: Symbol not found: _mysql_init
  Referenced from: /Library/Ruby/Gems/1.8/gems/mysql2-0.2.6/lib/mysql2/mysql2.bundle
  Expected in: flat namespace

**Comment by bradical** [comment]
I ran into this recently and @ain's command did the trick, but interestingly this:
```
$ gem uninstall
$ bundle config build.mysql --with-mysql-config=/path/to/mysql_config
$ bundle install
``` 
did not even though I verified I was installing the same gem version in both cases.

**Comment by ain** [comment]
Glad it worked out for you @bradical!

**Comment by bradical** [comment]
I also figured out my other issue which was that I was using `build.mysql` as the param for bundler instead of `build.mysql2`. Be careful with this if you've used both gems in the past. `bundle config` will list properties you have set and `bundle config --delete <name>` will let you remove old ones.

**Comment by RabeyaMuna** [comment]
Hello, 
I am still finding the issue:

 bundle exec rake db:drop db:create db:migrate
```

2024-02-15
[BLZ] The data provided may not be accurate.
dyld[94091]: missing symbol called
zsh: abort      bundle exec rake db:drop db:create db:migrate
rabeyakhatunmuna@Rabeyas-MBP expertiger-app % 
```

How to solve the issue?

I am using postgresql

**Comment by abdulhanan001** [comment]
@RabeyaMuna were you able to resolve this issue?

**Comment by sodabrew** [comment]
This issue is more than a decade old, I'm locking it to new posts about different problems (even if they look superficially similar). Please open a new ticket, you can link to this ticket if you think it's relevant prior discussion. Thank you!
