### ISSUE TITLE
CI Failure: Session tracking test failing against mysql 8

### ISSUE THREAD

**Issue by casperisfine** [brianmario/mysql2#1220]
Ref: https://github.com/brianmario/mysql2/pull/1092

This test currently fail on CI when ran against mysql 8.0:

```
  1) Mysql2::Client session_track returns multiple session track type values when available
     Failure/Error: expect(res).to eq(["________"])

       expected: ["________"]
            got: nil

       (compared using ==)
     # ./spec/mysql2/client_spec.rb:1084:in `block (3 levels) in <top (required)>'
```

I dug a bit and `mysql_session_track_get_first(wrapper->client, NUM2INT(type), &data, &length)` returns `1`, but I have no idea why.

@insom any idea what might be wrong?

**Comment by junaruga** [comment]
You can see https://github.com/brianmario/mysql2/issues/1165 too.

**Comment by junaruga** [comment]
Perhaps the test needs to enable `performance_schema`: `ON`, but the option is actually `OFF`? The value is printed by `SHOW VARIABLES LIKE 'performance_schema'`. If this is the reason, maybe this past PR: https://github.com/brianmario/mysql2/pull/1193 might help you to fix it.

**Comment by junaruga** [comment]
Ah I see some progresses for the issue: https://github.com/brianmario/mysql2/pull/1222#issuecomment-982368118 . Thanks, forks!

**Comment by junaruga** [comment]
Wow, thank you Shopify team!
https://github.com/brianmario/mysql2/commit/366bd0de190f44f2e1c1da7048921dd33b64f187

**Comment by junaruga** [comment]
@tenderlove Can you remove the `allow-failure: true` for the passed CI cases you confirmed in https://github.com/brianmario/mysql2/blob/master/.github/workflows/build.yml ? Thanks.
