### ISSUE TITLE
Ruby 1.9.3 mysql2 0.3.21

### ISSUE THREAD

**Issue by lynnq** [brianmario/mysql2#1234]
I have MySql 5.6.51. When it loaded the app, I got 

/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/values/time_zone.rb:270: warning: circular argument reference - now
Error: The application encountered the following error: incompatible library version - /usr/local/rvm/gems/ruby-1.9.3-p551/gems/mysql2-0.3.21/lib/mysql2/mysql2.so (LoadError)

Any ideas?

**Comment by sodabrew** [comment]
These are versions so far behind current community support windows! If you have luck finding others who may have seen and solved this problem years ago and posted about it, please do link back here as it may help someone in the future who also maintains a very old application.

**Comment by lynnq** [comment]
No solution found
