### ISSUE TITLE
Temporary Credentials

### ISSUE THREAD

**Issue by lloydpick** [brianmario/mysql2#1237]
I'm using AWS [IAM Database Authentication](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.html) to talk to my databases. The way this works is that before connecting, I use some [AWS APIs](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/RDS/AuthTokenGenerator.html) to get a temporary token which is used as the password to connect to the database, and this token lasts for 15 minutes. 

However, if for whatever reason reconnection has to occur after 15 minutes, you'll get an access denied. I'm also doing this from within Lambda, so there's no way to say "well, I hit an access denied, shut the entire lambda down, let it boot back up again and get new credentials", I need to handle it.

I'm just wondering what the best approach for that is.

**Comment by sodabrew** [comment]
Turn off auto reconnect. If the connection fails then on the next query or ping you get an exception and you can terminate the lambda instance.
