### ISSUE TITLE
Error installing mysql2: no rb_enc_interned_str in ruby.h

### ISSUE THREAD

**Issue by atsalolikhin-spokeo** [brianmario/mysql2#1266]
See also:  https://github.com/brianmario/mysql2/issues/1265

I am opening this issue because I don't think this is just a ruby 3 on Windows 10 problem, I ran into it with ruby-2.7.4 on [Amazon Linux 2022](https://github.com/amazonlinux/amazon-linux-2022).

```
$ gem install mysql2
Building native extensions. This could take a while...
ERROR:  Error installing mysql2:
        ERROR: Failed to build gem native extension.

    current directory: /home/jenkins/.rvm/gems/ruby-2.7.4/gems/mysql2-0.5.4/ext/mysql2
/home/jenkins/.rvm/rubies/ruby-2.7.4/bin/ruby -I /home/jenkins/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0 -r ./siteconf20220526-91281-1eeqm3v.rb extconf.rb
checking for rb_absint_size()... yes
checking for rb_absint_singlebit_p()... yes
checking for rb_wait_for_single_fd()... yes
checking for rb_enc_interned_str() in ruby.h... no
```

The logfile for the gem install ends with:

```
"gcc -o conftest -I/home/jenkins/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/x86_64-linux -I/home/jenkins/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0/ruby/backward -I/home/jenkins/.rvm/rubies/ruby-2.7.4/include/ruby-2.7.0 -I.    -g -O2 -fPIC conftest.c  -L. -L/home/jenkins/.rvm/rubies/ruby-2.7.4/lib -Wl,-rpath,/home/jenkins/.rvm/rubies/ruby-2.7.4/lib -L. -fstack-protector-strong -rdynamic -Wl,-export-dynamic     -Wl,-rpath,/home/jenkins/.rvm/rubies/ruby-2.7.4/lib -L/home/jenkins/.rvm/rubies/ruby-2.7.4/lib -lruby  -lm   -lc"
/usr/bin/ld: /tmp/ccOwhd6u.o: in function `t':
/home/jenkins/.rvm/gems/ruby-2.7.4/gems/mysql2-0.5.4/ext/mysql2/conftest.c:17: undefined reference to `rb_enc_interned_str'
collect2: error: ld returned 1 exit status
```

I checked the ruby.h files on my system and sure enough there is no `rb_enc_interned_str` there.

Nor do I see it in Ruby's [ruby.h](https://raw.githubusercontent.com/ruby/ruby/master/include/ruby/ruby.h)

**Comment by atsalolikhin-spokeo** [comment]
I have the same issue with ruby-3.0.2 (package from AWS).  I have all these ruby packages:

```
ruby-libs-3.0.2-149.amzn2022.x86_64
rubygem-psych-3.3.0-149.amzn2022.x86_64
rubypick-1.1.1-14.amzn2022.noarch
rubygems-3.2.22-149.amzn2022.noarch
ruby-3.0.2-149.amzn2022.x86_64
ruby-devel-3.0.2-149.amzn2022.x86_64
```

**Comment by atsalolikhin-spokeo** [comment]
I resolved my issue by installing the MySQL dev package, `mysql-community-devel`.

**Comment by atsalolikhin-spokeo** [comment]
@JayeLovee Well, you are on Windows, so I'm not sure how that would work.  I am on Linux so I get it from: https://dev.mysql.com/downloads/repo/yum/

I install the RPM (package) that provides the definition for the package repository, and then I install the "devel" package from that repository:
 
```
rpm --import https://repo.mysql.com/RPM-GPG-KEY-mysql-2022
dnf install -y https://repo.mysql.com/mysql80-community-release-el8-1.noarch.rpm
dnf install -y mysql-community-devel
```

I would imagine you go here:  https://dev.mysql.com/downloads/installer/

and run the installer and make sure you check the box for installing libraries and headers (or all development files) if there is such an option.  (I don't have a Windows computer to try it on.)   Good luck!

**Comment by JayeLovee** [comment]
it worked, thank you. unfortunately the mysql2 gem is still throwing the same error after downloading and installing mysql. i ran a test server and database to confirm mysql was working, tried the gem again, got the same error.

**Comment by atsalolikhin-spokeo** [comment]
Okay, good luck with that!

**Comment by random-pixels** [comment]
On Linux Ubuntu/Mint (and probably Debian) I had to do the following to fix it.
`sudo apt-get install libmysqlclient-dev`

**Comment by chmich** [comment]
On debian:
`apt install libmariadb-dev-compat libmariadb-dev`
solved it.

**Comment by macanudo527** [comment]
On Amazon Linux 2023:
`sudo yum install mariadb105 mariadb105-devel`
fixed it.
