### ISSUE TITLE
LoadError: cannot load such file -- mysql

### ISSUE THREAD

**Issue by rustamata** [brianmario/mysql2#1277]
Hey guys,
mysql2 doesn't work for me by some reason. I build Docker image `FROM ruby:2.7.4-slim` and then install libmysqlclient by using `apt-get install -y default-libmysqlclient-dev`. When I try to use the gem i get the following error: `LoadError: cannot load such file -- mysql`.
Looks like mysql2 cannot find libmysqlclient. Could you please help to resolve this problem?

**Comment by sodabrew** [comment]
The error suggests you're missing the "2" in "mysql2" in the file you're importing the gem.

**Comment by rustamata** [comment]
Sorry my bad. The connection string was actually wrong. Thanks for your help!
