### ISSUE TITLE
Segmentation fault with Rails 6.1.3.2, MySQL 8.0.30 and CentOS 9

### ISSUE THREAD

**Issue by nconsulting** [brianmario/mysql2#1285]
I'm getting a segmentation fault with mysql2 

CentOS 9 Stream - Linux 5.14.0-197.el9.x86_64
Rails 6.1.3.2
ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux]
mysql2 0.5.4
MySQL 8.0.30
mysql-devel 8.0.30-3.e19
OpenSSL 3.0.1

It is a new installation. I can connect just fine to the MySQL database with a Wordpress site and SQLYog.

I attached the error log. How can I fix this?

[log1.txt](https://github.com/brianmario/mysql2/files/10076399/log1.txt)

**Comment by Faq** [comment]
Just wondering why rvm and not rbenv?

When this segmentation fault happens, any reproduction steps?

**Comment by nconsulting** [comment]
I'm migrating a CentOS 8 server to a CentOS 9 server. I used rvm on the CentOS 8 server. I have switched to rbenv and I'm now using Ruby 3.1.x, which seems to be compatible with OpenSSL 3. I don't have any more segmentation faults.
