### ISSUE TITLE
Suppressing warnings in MariaDB Connector C (Fedora) case

### ISSUE THREAD

**Issue by junaruga** [brianmario/mysql2#1305]
Seeing the Fedora cases CI log on the latest master branch (6528137e2f3a743c0afb38abb4fbe1de1cbc9695), there are some warnings printed in the process of running the test. I would like to suppress the warnings.

https://github.com/brianmario/mysql2/actions/runs/3972990412/jobs/6811349042#step:4:283
```
+ bundle exec rake spec
...
 /build/lib/mysql2/client.rb:58: warning: Your mysql client library does not support setting ssl_mode; full support comes with 5.6.36+, 5.7.11+, 8.0+
    should set ssl_mode option verify_identity
/build/lib/mysql2/client.rb:58: warning: Your mysql client library does not support setting ssl_mode; full support comes with 5.6.36+, 5.7.11+, 8.0+
    should set ssl_mode option required
/build/lib/mysql2/client.rb:58: warning: Your mysql client library does not support setting ssl_mode; full support comes with 5.6.36+, 5.7.11+, 8.0+
    should set ssl_mode option verify_ca
    should be able to connect via SSL options
/build/lib/mysql2/client.rb:58: warning: Your mysql client library does not support setting ssl_mode; full support comes with 5.6.36+, 5.7.11+, 8.0+
    should set ssl_mode option disabled
/build/lib/mysql2/client.rb:58: warning: Your mysql client library does not support setting ssl_mode; full support comes with 5.6.36+, 5.7.11+, 8.0+
...
   #each
/build/spec/mysql2/statement_spec.rb:311: warning: :cache_rows is ignored if :stream is true
/build/spec/mysql2/statement_spec.rb:311: warning: :cache_rows is ignored if :stream is true
     should yield different value for #first if streaming
...
```

The issue was discussed at https://github.com/brianmario/mysql2/pull/1294, however I want to open the issue ticket to manage the status.

**Comment by sodabrew** [comment]
Thank you, commented on the other issue just now. I think this could be the last thing to solve before a next release, btw

**Comment by junaruga** [comment]
Thank you for considering this issue, and I also would like to see the next release.

**Comment by sodabrew** [comment]
Ok, the version numbers are in the 3.x range (`30207`) -- that must be the MariaDB Connector/C family: https://mariadb.com/kb/en/about-mariadb-connector-c/

Looking at the docs for the ssl-enforce option, it looks like version 3.1.1 should be the minimum for full support https://mariadb.com/kb/en/configuring-mariadb-connectorc-with-option-files/#ssl-enforce 

The code now more clearly shows a problem: it won't let 3xxxx through the code path that sets `SSL_VERIFY_SERVER_CERT` or `SSL_MODE_ENFORCED`.

https://github.com/brianmario/mysql2/blob/6528137e2f3a743c0afb38abb4fbe1de1cbc9695/ext/mysql2/client.c#L128-L153

**Comment by junaruga** [comment]
Yes, Fedora cases use the MariaDB Connector/C RPM package to run the mysql2 gem. And thanks for checking it.

**Comment by junaruga** [comment]
The warnings in the SSL tests are suppressed by #1306. Thanks!

The remaining warning is below. I assume this is the expected result. And we can suppress it by capturing the warning by RSpec `output`. And I don't think we have to fix it before the next release.

https://github.com/brianmario/mysql2/actions/runs/3981580490/jobs/6825405070#step:4:547

```
/build/spec/mysql2/statement_spec.rb:311: warning: :cache_rows is ignored if :stream is true
/build/spec/mysql2/statement_spec.rb:311: warning: :cache_rows is ignored if :stream is true
```
