### ISSUE TITLE
Why can't find mysql2.so ??

### ISSUE THREAD

**Issue by hopewise** [brianmario/mysql2#1307]
I am getting this error in a dockerized rails app:

```
"errorMessage": "libmysqlclient.so.18: cannot open shared object file: No such file or directory - /home/app/vendor/bundle/ruby/2.7.0/gems/mysql2-0.5.3/lib/mysql2/mysql2.so"
```

although while building the Dockerfile, I have checked the content for `/home/app/vendor/bundle/ruby/2.7.0/gems/mysql2-0.5.3/lib/mysql2`

```
Step 31/32 : RUN echo "$(ls -la /home/app/vendor/bundle/ruby/2.7.0/gems/mysql2-0.5.3/lib/mysql2)"
--
461 | ---> Running in 457420558b8f
462 | total 196
463 | drwxrwxrwx 1 app app    158 Jan 30 09:35 .
464 | drwxrwxrwx 1 app app     37 Jan 30 09:35 ..
465 | -rwxrwxrwx 1 app app   6216 Jan 30 09:35 client.rb
466 | -rwxrwxrwx 1 app app    121 Jan 30 09:35 console.rb
467 | -rwxrwxrwx 1 app app   1124 Jan 30 09:35 em.rb
468 | -rwxrwxrwx 1 app app   3790 Jan 30 09:35 error.rb
469 | -rwxrwxrwx 1 app app     53 Jan 30 09:35 field.rb


#THE MISSING mysql2.so FILE ALREADY IN THE EXPECTED LOCATION:
470 | -rwxrwxrwx 1 app app 161368 Jan 30 09:35 mysql2.so
471 | -rwxrwxrwx 1 app app     93 Jan 30 09:35 result.rb
472 | -rwxrwxrwx 1 app app    231 Jan 30 09:35 statement.rb
473 | -rwxrwxrwx 1 app app     45 Jan 30 09:35 version.rb
```

for env:

```
Step 22/32 : RUN gem environment
--
118 | ---> Running in eff1641e46c1
119 | RubyGems Environment:
120 | - RUBYGEMS VERSION: 3.1.6
121 | - RUBY VERSION: 2.7.7 (2022-11-24 patchlevel 221) [x86_64-linux]
122 | - INSTALLATION DIRECTORY: /usr/local/bundle
123 | - USER INSTALLATION DIRECTORY: /home/app/.gem/ruby/2.7.0
124 | - RUBY EXECUTABLE: /usr/local/bin/ruby
125 | - GIT EXECUTABLE: /usr/bin/git
126 | - EXECUTABLE DIRECTORY: /usr/local/bundle/bin
127 | - SPEC CACHE DIRECTORY: /home/app/.gem/specs
128 | - SYSTEM CONFIGURATION DIRECTORY: /usr/local/etc
129 | - RUBYGEMS PLATFORMS:
130 | - ruby
131 | - x86_64-linux
132 | - GEM PATHS:
133 | - /usr/local/bundle
134 | - /home/app/.gem/ruby/2.7.0
135 | - /usr/local/lib/ruby/gems/2.7.0
136 | - GEM CONFIGURATION:
137 | - :update_sources => true
138 | - :verbose => true
139 | - :backtrace => false
140 | - :bulk_threshold => 1000
141 | - "install" => "--no-document"
142 | - "update" => "--no-document"
143 | - REMOTE SOURCES:
144 | - https://rubygems.org/
145 | - SHELL PATH:
146 | - /usr/local/bundle/bin
147 | - /usr/local/sbin
148 | - /usr/local/bin
149 | - /usr/sbin
150 | - /usr/bin
151 | - /sbin
152 | - /bin
```

So, it says cannot open shared object file: No such file or directory - `/home/app/vendor/bundle/ruby/2.7.0/gems/mysql2-0.5.3/lib/mysql2/mysql2.so` ?!

**Comment by hopewise** [comment]
I just update it to use 0.5.5, but I am still getting the same error:

```
"errorMessage": "libmysqlclient.so.18: cannot open shared object file: No such file or directory - /home/app/vendor/bundle/ruby/2.7.0/gems/mysql2-0.5.5/lib/mysql2/mysql2.so",
```

**Comment by junaruga** [comment]
Have you searched the [past issues by your error message](https://github.com/brianmario/mysql2/issues?q=is%3Aissue+cannot+%22open+shared+object+file%3A+No+such+file+or+directory%22+is%3Aclosed+)? Perhaps, this one? https://github.com/brianmario/mysql2/issues/1113

**Comment by hopewise** [comment]
I read that some people have solved a similar issue by clearing the cache of the gem, still checking out..

**Comment by junaruga** [comment]
OK. Which OS are you using in the container? Did you install MySQL or MariaDB dev (devel) package? Perhaps, this one? https://github.com/brianmario/mysql2/issues/756

**Comment by hopewise** [comment]
Its debian 10, I even changed the base image to `FROM mysql:5.7.37-debian` but I am getting the same error:

```
"errorMessage": "libmysqlclient.so.18: cannot open shared object file: No such file or directory - /home/app/vendor/bundle/ruby/2.7.0/gems/mysql2-0.5.5/lib/mysql2/mysql2.so"
```

although the file is already there

**Comment by sodabrew** [comment]
The mysql2.so file is there. It is trying to load `libmysqlclient.so.18`. Please make sure you have installed the mysql client libraries in your output image. For example, this is a common pattern:

```
FROM ruby:3 AS build
COPY . .
RUN bundle install

FROM ruby:3-slim
COPY --from build . .
EXEC bundle exec rails s
```

The issue is that the build image has libmysqlclient-dev installed by default:
https://hub.docker.com/layers/library/buildpack-deps/bullseye/images/sha256-d444ea68c293f59bb366988d1bc4896ded5dea5352fdb9ec6879416a58aca1ee?context=explore%5B%2Furl
<img width="1244" alt="image" src="https://user-images.githubusercontent.com/39406/215854550-f9eb284c-d43c-4da7-a5a5-8cc8ce94327c.png">

Therefore on the output image, you see to add a line like this:
```
RUN apt-get install -y --no-install-recommends default-libmysqlclient
```

Nb. you can see the image that there's some migration from libmysqlclient to default-libmysqlclient in Debian -- this is because they are migrating to MariaDB. It works fine to use a MariaDB client library to talk to a MySQL server; YMMV: confirm that the specific versions work correctly for your installation.

**Comment by hopewise** [comment]
Thanks @sodabrew for the details, yes having a multi stage docker file would be very efficient to reduce image size and optimal performance, but I am having issue with the full image already, my docker file:
```
FROM ruby:2.7.7
RUN apt-get update
RUN apt-get install -y --no-install-recommends default-mysql-client
# Create a secure user for prod and app directory.
RUN mkdir /home/app \
    && groupadd -g 10001 app \
    && useradd -u 10000 -g app app \
    && chown -R app:app /home/app

USER app

WORKDIR "/home/app"

# Copy prod application files and set handler.
ENV BUNDLE_IGNORE_CONFIG=1
ENV BUNDLE_PATH=/home/app/vendor/bundle
ENV BUNDLE_CACHE_PATH=/home/app/vendor/cache
ENV RAILS_SERVE_STATIC_FILES=1

# Install the AWS Lambda Runtime Interface Client & Crypteia for secure SSM-backed envs.
RUN gem install 'aws_lambda_ric'
ENTRYPOINT [ "/usr/local/bundle/bin/aws_lambda_ric" ]

RUN gem install bundler -v 2.1.4

COPY . .
USER root
#RUN chmod -R 0777 /usr/local/bundle
RUN chown -R app: /home/app
RUN chmod -R u+w /home/app
USER app
RUN gem environment

RUN gem install racc -v '1.5.2' --source 'https://rubygems.org/'
RUN bundle config set path '/app/home/vendor/bundle'
RUN bundle install


USER root

RUN chmod -R 0777 ./config
RUN chmod -R 0777 ./log
RUN chmod -R 0777 /home/app/vendor
RUN chown -R app: /home/app

USER app

CMD ["config/environment.Lamby.cmd"]

```

it seems that it tries to find `libmysqlclient.so.18` but its not found.. I tried to solve it when I used `FROM mysql:5.7.37-debian` as:

```
RUN ln -s /usr/lib/x86_64-linux-gnu/libmariadb.so.3 /usr/lib/x86_64-linux-gnu/libmysqlclient.so.18
RUN ln -s /usr/lib/x86_64-linux-gnu/libssl.so.1.1 /usr/lib/x86_64-linux-gnu/libssl.so.10
```

but now, I am using ruby official image, shouldn't the following have the issue solved?

```
FROM ruby:2.7.7
RUN apt-get update
RUN apt-get install -y --no-install-recommends default-mysql-client
```

Can you provide an example Dockerfile that has the required libraries as the same name expected by `mysql2.so` ?

**Comment by sodabrew** [comment]
Linking the library names like that lacks binary ABI guarantees but is useful as a test. It suggests that your mysql2.so binary was compiled against MySQL but your container has MariaDB libraries. Is it possible that you're doing a `bundle install` outside of the Dockerfile and slurping the host-compiled binary gems into your dockerfile image (at the `COPY . .` layer)

**Comment by hopewise** [comment]
I've put my Dockerfile [above](https://github.com/brianmario/mysql2/issues/1307#issuecomment-1411922447), it has `RUN bundle install` as I am not installing them inside the host..

**Comment by sodabrew** [comment]
Yes, that's precisely what I'm saying to double-check for this reason: `bundle install` will reuse an already installed gem if it is present on the filesystem. Therefore if you have run `bundle install` on the host fs, then run `docker build .` and the line for `COPY . .` pulls your `vendor/` directory into the image layer, then `bundle install` will just confirm that yep, it's got all the fine, nothing to do here, but in fact the files were compiled by the host OS and not the Docker base image OS, thus causing runtime linker problems.

**Comment by hopewise** [comment]
it turned out that I was building the gems on a different OS ( the host ) , once built the gems inside the docker its self, it got worked.

**Comment by sodabrew** [comment]
Glad to hear that you were able to resolve the problem! Thanks for reporting back and closing the thread, it's always super helpful for the next person who runs into the same problem to be able to google it and find a solution 💁
