### ISSUE TITLE
gem install mysql2 -v 0.4.2 failed with ./result.h:24:3: error: unknown type name ‘my_bool’

### ISSUE THREAD

**Issue by prasadnh** [brianmario/mysql2#1309]
Hello
couldn't find any solution... (painful to resolve too many package fixes. but mysql never ending fix)
Using mysql_config at /usr/bin/mysql_config
-----
checking for mysql.h... yes
checking for errmsg.h... yes
checking for mysqld_error.h... yes
-----
Setting libpath to /usr/lib/x86_64-linux-gnu
-----
creating Makefile

current directory: /usr/local/rvm/gems/ruby-2.2.5/gems/mysql2-0.4.2/ext/mysql2
make "DESTDIR=" clean

current directory: /usr/local/rvm/gems/ruby-2.2.5/gems/mysql2-0.4.2/ext/mysql2
make "DESTDIR="
compiling client.c
In file included from ./mysql2_ext.h:41,
                 from client.c:1:
./result.h:24:3: error: unknown type name ‘my_bool’
   24 |   my_bool *is_null;
      |   ^~~~~~~
./result.h:25:3: error: unknown type name ‘my_bool’
   25 |   my_bool *error;
      |   ^~~~~~~
client.c: In function ‘nogvl_read_query_result’:
client.c:434:3: error: unknown type name ‘my_bool’; did you mean ‘bool’?
  434 |   my_bool res = mysql_read_query_result(client);
      |   ^~~~~~~
      |   bool
client.c: In function ‘_mysql_client_options’:
client.c:755:3: error: unknown type name ‘my_bool’; did you mean ‘bool’?
  755 |   my_bool boolval;
      |   ^~~~~~~
      |   bool
client.c:790:10: error: ‘MYSQL_SECURE_AUTH’ undeclared (first use in this function); did you mean ‘MYSQL_DEFAULT_AUTH’?
  790 |     case MYSQL_SECURE_AUTH:
      |          ^~~~~~~~~~~~~~~~~
      |          MYSQL_DEFAULT_AUTH
client.c:790:10: note: each undeclared identifier is reported only once for each function it appears in
client.c: In function ‘set_secure_auth’:
client.c:1178:38: error: ‘MYSQL_SECURE_AUTH’ undeclared (first use in this function); did you mean ‘MYSQL_DEFAULT_AUTH’?
 1178 |   return _mysql_client_options(self, MYSQL_SECURE_AUTH, value);
      |                                      ^~~~~~~~~~~~~~~~~
      |                                      MYSQL_DEFAULT_AUTH
client.c:1179:1: warning: control reaches end of non-void function [-Wreturn-type]
 1179 | }
      | ^
client.c: At top level:
cc1: warning: unrecognized command line option ‘-Wno-used-but-marked-unused’
cc1: warning: unrecognized command line option ‘-Wno-static-in-inline’
cc1: warning: unrecognized command line option ‘-Wno-reserved-id-macro’
cc1: warning: unrecognized command line option ‘-Wno-missing-variable-declarations’
cc1: warning: unrecognized command line option ‘-Wno-documentation-unknown-command’
cc1: warning: unrecognized command line option ‘-Wno-disabled-macro-expansion’
cc1: warning: unrecognized command line option ‘-Wno-covered-switch-default’
cc1: warning: unrecognized command line option ‘-Wno-conditional-uninitialized’
make: *** [Makefile:238: client.o] Error 1

make failed, exit code 2

Gem files will remain installed in /usr/local/rvm/gems/ruby-2.2.5/gems/mysql2-0.4.2 for inspection.
Results logged to /usr/local/rvm/gems/ruby-2.2.5/extensions/x86_64-linux/2.2.0/mysql2-0.4.2/gem_make.out

**Comment by sodabrew** [comment]
Please try mysql2 0.5.4.

**Comment by prasadnh** [comment]
Thanks it worked

**Comment by sodabrew** [comment]
It seems like you are picking up on an older codebase -- Ruby 2.2 is long out of service, and mysql2 0.4.x are years-old releases as well. There's been a lot of movement in Ruby since those versions were current, good luck!!

**Comment by prasadnh** [comment]
agree..but client wants to stay around these. I don't have much options other than find help from developers :)

**Comment by prasadnh** [comment]
I was able to install successfully but when I run my app, it still complaining with this error
Gem::LoadError: Specified 'mysql2' for database adapter, but the gem is not loaded. Add `gem 'mysql2'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord).

**Comment by sodabrew** [comment]
You'll need to be on ActiveRecord 4.2.11 or higher to use mysql2 0.5.x: https://github.com/brianmario/mysql2#ruby-on-rails--active-record

Since you're currently on mysql2 0.4.x, you're probably on Rails / Active Record 4.2.x less than 4.2.11. Staying within the same major.minor of Rails and getting to the latest micro release should be low risk and have a minimum of gem headaches.

**Comment by sodabrew** [comment]
The version of the rails gems should be in the Gemfile / Gemfile.lock. Sometimes the Gemfile only names the green and not the version, in which case Gemfile.lock will show what was installed when the code was written. It is a best practice to specify gem versions with some amount of flexibility, e.g. `gem "mysql2", "~> 0.5.3"` would indicate that bundler can install the highest available 0.5.3, or 0.5.4, or 0.5.5, or some future 0.5.342, but not 0.6.1, etc.

**Comment by prasadnh** [comment]
Yes my Gemfile.lock has all the versions.
