### ISSUE TITLE
Ruby 2.7.0 Mysql2 query doesn't sum decimal(8,2) values correctly

### ISSUE THREAD

**Issue by yutveg** [brianmario/mysql2#1312]
I've got an extremely simple query:

```
sum_row =
  db_client.query(
    '
  SELECT SUM(30_day_profit) AS sum FROM product_listings
  '
  )
```

Instead of returning 82796.18 as it does in DBeaver, the query is returning 0.8279618e5.

I have no idea why

**Comment by sodabrew** [comment]
Could you share what you learned debugging this? Always helpful for the next person with a similar problem!

**Comment by carlivar** [comment]
82796.18 and 0.8279618e5 are the same values, just a different format.
