### ISSUE TITLE
ld: library not found for -lzlib

### ISSUE THREAD

**Issue by dcblanton78** [brianmario/mysql2#1316]
Getting the following error when trying to install mysql2 even though I have lzlib installed:

This could take a while...
ERROR:  Error installing mysql2:
	ERROR: Failed to build gem native extension.

    current directory: /Users/dcblanton78/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/mysql2-0.5.3/ext/mysql2
/Users/dcblanton78/.rbenv/versions/3.0.6/bin/ruby -I /Users/dcblanton78/.rbenv/versions/3.0.6/lib/ruby/3.0.0 -r ./siteconf20230512-27102-zmyqxf.rb extconf.rb --with-mysql-config\=/opt/homebrew/opt/mysql/bin/mysql_config --with-ldflags\=-L/opt/homebrew/opt/zstd/lib\ -L/opt/homebrew/opt/openssl@3/lib --with-cppflags\=-I/opt/homebrew/opt/openssl@3/include
checking for rb_absint_size()... yes
checking for rb_absint_singlebit_p()... yes
checking for rb_wait_for_single_fd()... yes
-----
Using mysql_config at /opt/homebrew/opt/mysql/bin/mysql_config
-----
checking for mysql.h... yes
checking for errmsg.h... yes
checking for SSL_MODE_DISABLED in mysql.h... yes
checking for SSL_MODE_PREFERRED in mysql.h... yes
checking for SSL_MODE_REQUIRED in mysql.h... yes
checking for SSL_MODE_VERIFY_CA in mysql.h... yes
checking for SSL_MODE_VERIFY_IDENTITY in mysql.h... yes
checking for MYSQL.net.vio in mysql.h... yes
checking for MYSQL.net.pvio in mysql.h... no
checking for MYSQL_ENABLE_CLEARTEXT_PLUGIN in mysql.h... yes
checking for SERVER_QUERY_NO_GOOD_INDEX_USED in mysql.h... yes
checking for SERVER_QUERY_NO_INDEX_USED in mysql.h... yes
checking for SERVER_QUERY_WAS_SLOW in mysql.h... yes
checking for MYSQL_OPTION_MULTI_STATEMENTS_ON in mysql.h... yes
checking for MYSQL_OPTION_MULTI_STATEMENTS_OFF in mysql.h... yes
checking for my_bool in mysql.h... no
-----
Don't know how to set rpath on your system, if MySQL libraries are not in path mysql2 may not load
-----
-----
Setting libpath to /opt/homebrew/opt/mysql/lib
-----
creating Makefile

current directory: /Users/dcblanton78/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/mysql2-0.5.3/ext/mysql2
make DESTDIR\= clean

current directory: /Users/dcblanton78/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/mysql2-0.5.3/ext/mysql2
make DESTDIR\=
compiling client.c
In file included from client.c:15:
./mysql_enc_name_to_ruby.h:43:1: warning: a function declaration without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
mysql2_mysql_enc_name_to_rb_hash (str, len)
^
./mysql_enc_name_to_ruby.h:86:1: warning: a function declaration without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
mysql2_mysql_enc_name_to_rb (str, len)
^
client.c:787:14: warning: incompatible function pointer types passing 'VALUE (void *)' (aka 'unsigned long (void *)') to parameter of type 'VALUE (*)(VALUE)' (aka 'unsigned long (*)(unsigned long)') [-Wincompatible-function-pointer-types]
  rb_rescue2(do_send_query, (VALUE)&args, disconnect_and_raise, self, rb_eException, (VALUE)0);
             ^~~~~~~~~~~~~
/Users/dcblanton78/.rbenv/versions/3.0.6/include/ruby-3.0.0/ruby/internal/iterator.h:51:25: note: passing argument to parameter here
VALUE rb_rescue2(VALUE(*)(VALUE),VALUE,VALUE(*)(VALUE,VALUE),VALUE,...);
                        ^
client.c:795:16: warning: incompatible function pointer types passing 'VALUE (void *)' (aka 'unsigned long (void *)') to parameter of type 'VALUE (*)(VALUE)' (aka 'unsigned long (*)(unsigned long)') [-Wincompatible-function-pointer-types]
    rb_rescue2(do_query, (VALUE)&async_args, disconnect_and_raise, self, rb_eException, (VALUE)0);
               ^~~~~~~~
/Users/dcblanton78/.rbenv/versions/3.0.6/include/ruby-3.0.0/ruby/internal/iterator.h:51:25: note: passing argument to parameter here
VALUE rb_rescue2(VALUE(*)(VALUE),VALUE,VALUE(*)(VALUE,VALUE),VALUE,...);
                        ^
4 warnings generated.
compiling infile.c
compiling mysql2_ext.c
compiling result.c
compiling statement.c
linking shared-object mysql2/mysql2.bundle
ld: library not found for -lzlib
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [mysql2.bundle] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/dcblanton78/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/mysql2-0.5.3 for inspection.
Results logged to /Users/dcblanton78/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/extensions/arm64-darwin-22/3.0.0/mysql2-0.5.3/gem_make.out

**Comment by sodabrew** [comment]
Looks like you're passing custom arguments to point to zlib. Usually this isn't needed. What prompted you to add the arguments? Does it just work without adding the explicit zlib link dir?

**Comment by aliibsin** [comment]
I'm getting the same error and it persists whether I use custom arguments to point to zlib or not. I've tried many iterations of custom arguments of getting the installer to recognize the path. Stuff like `--with-zlib-lib=/usr/local/Cellar/zlib/1.2.13/lib` or adding something similar to a .bundle/.config for mysql. 

The only work around I found was not using homebrew and directly installing mysql and using that installation's directory. However, this isn't really ideal since the new installation doesn't retain any data from homebrew's installation.

**Comment by elfotografo007** [comment]
I am having the same issue on a Mac with M1, doing just `gem install mysql2 -v '0.5.5'` I get the same error:

```
ld: library not found for -lzlib
```

If I try something like `gem install mysql2 -v '0.5.5' -- --with-zlib-lib=$(brew --prefix zlib)/lib`, it doesn't work either. 

It looks like it is detecting the mysql and openssl dirs correctly on my end. I am using ruby 2.7.6.

**Comment by petergoldstein** [comment]
On my Intel Mac I was having similar problems.  Using a modification of @elfotografo007 's answer (because I have a different homebrew install directory) worked for me.  For reference:

```
gem install mysql2 -v '0.5.5' -- --with-mysql-lib=/usr/local/opt/mysql/lib --with-mysql-dir=/usr/local/opt/mysql --with-mysql-config=/usr/local/opt/mysql/bin/mysql_config --with-mysql-include=/usr/local/opt/mysql/include --with-ldflags=-L/usr/local/opt/zlib/lib
```

Thanks for the solution.

**Comment by dcblanton78** [comment]
It didn't work when I tried it without custom arguments either....


Building native extensions. This could take a while...

ERROR:  Error installing mysql2:

ERROR: Failed to build gem native extension.


    current directory:
/Users/dcblanton78/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/mysql2-0.5.5/ext/mysql2

/Users/dcblanton78/.rbenv/versions/3.0.6/bin/ruby -I
/Users/dcblanton78/.rbenv/versions/3.0.6/lib/ruby/3.0.0 -r
./siteconf20230514-57099-zz1qpb.rb extconf.rb

checking for rb_absint_size()... yes

checking for rb_absint_singlebit_p()... yes

checking for rb_gc_mark_movable()... yes

checking for rb_wait_for_single_fd()... yes

checking for rb_enc_interned_str() in ruby.h... yes

-----

Using --with-openssl-dir=/Users/dcblanton78/.rbenv/versions/3.0.6/openssl

-----

-----

Using mysql_config at /opt/homebrew/bin/mysql_config

-----

checking for mysql.h... yes

checking for errmsg.h... yes

checking for SSL_MODE_DISABLED in mysql.h... yes

checking for SSL_MODE_PREFERRED in mysql.h... yes

checking for SSL_MODE_REQUIRED in mysql.h... yes

checking for SSL_MODE_VERIFY_CA in mysql.h... yes

checking for SSL_MODE_VERIFY_IDENTITY in mysql.h... yes

checking for MYSQL.net.vio in mysql.h... yes

checking for MYSQL.net.pvio in mysql.h... no

checking for MYSQL_DEFAULT_AUTH in mysql.h... yes

checking for MYSQL_ENABLE_CLEARTEXT_PLUGIN in mysql.h... yes

checking for SERVER_QUERY_NO_GOOD_INDEX_USED in mysql.h... yes

checking for SERVER_QUERY_NO_INDEX_USED in mysql.h... yes

checking for SERVER_QUERY_WAS_SLOW in mysql.h... yes

checking for MYSQL_OPTION_MULTI_STATEMENTS_ON in mysql.h... yes

checking for MYSQL_OPTION_MULTI_STATEMENTS_OFF in mysql.h... yes

checking for my_bool in mysql.h... no

-----

Don't know how to set rpath on your system, if MySQL libraries are not in
path mysql2 may not load

-----

-----

Setting libpath to /opt/homebrew/Cellar/mysql/8.0.33/lib

-----

creating Makefile


current directory:
/Users/dcblanton78/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/mysql2-0.5.5/ext/mysql2

make DESTDIR\= clean


current directory:
/Users/dcblanton78/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/mysql2-0.5.5/ext/mysql2

make DESTDIR\=

compiling client.c

In file included from client.c:15:

./mysql_enc_name_to_ruby.h:43:1: warning: a function declaration without a
prototype is deprecated in all versions of C and is not supported in C2x
[-Wdeprecated-non-prototype]

mysql2_mysql_enc_name_to_rb_hash (str, len)

^

./mysql_enc_name_to_ruby.h:86:1: warning: a function declaration without a
prototype is deprecated in all versions of C and is not supported in C2x
[-Wdeprecated-non-prototype]

mysql2_mysql_enc_name_to_rb (str, len)

^

2 warnings generated.

compiling infile.c

compiling mysql2_ext.c

compiling result.c

result.c:304:35: warning: implicit conversion loses integer precision:
'unsigned long' to 'int' [-Wshorten-64-to-32]

        precision = field->length - (field->decimals > 0 ? 2 : 1);

                  ~ ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

1 warning generated.

compiling statement.c

linking shared-object mysql2/mysql2.bundle

ld: library not found for -lzlib

clang: error: linker command failed with exit code 1 (use -v to see
invocation)

make: *** [mysql2.bundle] Error 1


make failed, exit code 2


Gem files will remain installed in
/Users/dcblanton78/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/mysql2-0.5.5
for inspection.

Results logged to
/Users/dcblanton78/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/extensions/arm64-darwin-22/3.0.0/mysql2-0.5.5/gem_make.out

**Comment by steveh** [comment]
Command that worked for me (same as above but using `brew prefix` instead):

```bash
gem install mysql2 -- \
  --with-openssl-dir=$(brew --prefix openssl@1.1) \
  --with-ldflags=-L$(brew --prefix zlib)/lib \
  --with-mysql-lib=$(brew --prefix mysql)/lib \
  --with-mysql-dir=$(brew --prefix mysql) \
  --with-mysql-config=$(brew --prefix mysql)/bin/mysql_config \
  --with-mysql-include=$(brew --prefix mysql)/include
```

**Comment by dcblanton78** [comment]
That worked for me as well. Thanks Steve!
