### ISSUE TITLE
Unable to install 0.5.5 on Macbook M2

### ISSUE THREAD

**Issue by aagg-cw** [brianmario/mysql2#1328]
Machine: Macbook Air M2, 2022
OS: macOS 13.2.1
Package management: homebrew, rvm
Ruby version: 3.0.6

Running `gem install mysql2 -v 0.5.5` fails (see attached mkmf.log below).

I've tried `brew install gcc mysql@5.7 mysql-client@5.7 zstd openssl` and setting `LIBRARY_PATH=$(brew --prefix zstd)/lib/:$(brew --prefix openssl)/lib/` which did not change anything. Unfortunately none of the invocations found from searching for this error are helping.

Note that this issue seems specific to 0.5.5. Installing 0.5.4 works just fine.

Could you please point me to the right direction here? Thank you!

<details>
<summary>mkmf.log</summary>
<code>

have_func: checking for rb_enc_interned_str() in ruby.h... -------------------- yes

"gcc -fdeclspec -o conftest -I/Users/xxx/.rvm/rubies/ruby-3.0.6/include/ruby-3.0.0/arm64-darwin22 -I/Users/xxx/.rvm/rubies/ruby-3.0.6/include/ruby-3.0.0/ruby/backward -I/Users/xxx/.rvm/rubies/ruby-3.0.6/include/ruby-3.0.0 -I. -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -O3 -I/opt/homebrew/opt/libyaml/include -I/opt/homebrew/opt/libksba/include -I/opt/homebrew/opt/readline/include -I/opt/homebrew/opt/zlib/include -I/opt/homebrew/opt/openssl@1.1/include -fno-common -pipe conftest.c  -L. -L/Users/xxx/.rvm/rubies/ruby-3.0.6/lib -L. -L/opt/homebrew/opt/libyaml/lib -L/opt/homebrew/opt/libksba/lib -L/opt/homebrew/opt/readline/lib -L/opt/homebrew/opt/zlib/lib -L/opt/homebrew/opt/openssl@1.1/lib -fstack-protector-strong  -m64   -lruby.3.0   "
conftest.c:16:57: error: use of undeclared identifier 'rb_enc_interned_str'
int t(void) { void ((*volatile p)()); p = (void ((*)()))rb_enc_interned_str; return !p; }
                                                        ^
1 error generated.
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: #include <ruby.h>
 4: 
 5: /*top*/
 6: extern int t(void);
 7: int main(int argc, char **argv)
 8: {
 9:   if (argc > 1000000) {
10:     int (* volatile tp)(void)=(int (*)(void))&t;
11:     printf("%d", (*tp)());
12:   }
13: 
14:   return !!argv[argc];
15: }
16: int t(void) { void ((*volatile p)()); p = (void ((*)()))rb_enc_interned_str; return !p; }
/* end */

"gcc -fdeclspec -o conftest -I/Users/xxx/.rvm/rubies/ruby-3.0.6/include/ruby-3.0.0/arm64-darwin22 -I/Users/xxx/.rvm/rubies/ruby-3.0.6/include/ruby-3.0.0/ruby/backward -I/Users/xxx/.rvm/rubies/ruby-3.0.6/include/ruby-3.0.0 -I. -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -O3 -I/opt/homebrew/opt/libyaml/include -I/opt/homebrew/opt/libksba/include -I/opt/homebrew/opt/readline/include -I/opt/homebrew/opt/zlib/include -I/opt/homebrew/opt/openssl@1.1/include -fno-common -pipe conftest.c  -L. -L/Users/xxx/.rvm/rubies/ruby-3.0.6/lib -L. -L/opt/homebrew/opt/libyaml/lib -L/opt/homebrew/opt/libksba/lib -L/opt/homebrew/opt/readline/lib -L/opt/homebrew/opt/zlib/lib -L/opt/homebrew/opt/openssl@1.1/lib -fstack-protector-strong  -m64   -lruby.3.0   "
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: #include <ruby.h>
 4: 
 5: /*top*/
 6: extern int t(void);
 7: int main(int argc, char **argv)
 8: {
 9:   if (argc > 1000000) {
10:     int (* volatile tp)(void)=(int (*)(void))&t;
11:     printf("%d", (*tp)());
12:   }
13: 
14:   return !!argv[argc];
15: }
16: extern void rb_enc_interned_str();
17: int t(void) { rb_enc_interned_str(); return 0; }
/* end */

</code>
</details>

**Comment by hknaksu** [comment]
+1
Ruby 3.2.2
Mysql 8.0.33
MacOS 13.5

**Comment by aagg-cw** [comment]
On debugging this it seems rvm places the ruby headers incorrectly. Using the headers from rbenv instead fixes the issue.
