### ISSUE TITLE
Does a mysql2 to MySQL version compatibility list exist?

### ISSUE THREAD

**Issue by dylanz** [brianmario/mysql2#1330]
Is there a compatibility list of what versions of the mysql2 gem work with what versions of MySQL?
For example, will mysql2 0.3.21 work with MySQL 8.0.33?

**Comment by dylanz** [comment]
@sodabrew gotcha!  I've been dealing with getting a Ruby 2.5 / Rails 3 application working with MySQL 8 and wasn't sure if this was a possibility or not... however:  `{os: ubuntu-20.04, ruby: '2.5', db: mysql80}`.  It's possible!  Compilation issues on an M1 seems to be the culprit.  Thanks for the heads up here!

**Comment by sodabrew** [comment]
In this case, I recommend creating a local/private fork and backport as needed for your environment. Gemfile has a nice syntax for referencing a git repository https://bundler.io/guides/git.html
