### ISSUE TITLE
Compatibility Inquiry: mysql2 0.5.5 with Ruby 3.3.0

### ISSUE THREAD

**Issue by sydverisk** [brianmario/mysql2#1351]
Hi,

I'm seeking confirmation regarding the compatibility of the gem mysql2 0.5.5 with the recently released Ruby 3.3.0 (December 25, 2023).

While I reviewed the gem's documentation on RubyGems https://rubygems.org/gems/mysql2, it only specifies a minimum required Ruby version of 2.0, and tested against Ruby MRI 2.0 through 2.7 (all versions to date) Ruby MRI 3.0, 3.1, 3.2 (all versions to date)

Unfortunately, I haven't found any explicit confirmation on compatibility with newer versions like 3.3.0.

Given your expertise in this area, could you offer any insights or leads on this matter? Any information you can provide would be greatly appreciated.

Thank you for your time and assistance!

**Comment by sodabrew** [comment]
Yes, the mysql2 gem works with Ruby 3.3.0. Just added to CI today in #1340 (albeit belatedly).
