### ISSUE TITLE
Release v0.5.6 is missing

### ISSUE THREAD

**Issue by VitaliySerov** [brianmario/mysql2#1355]
I see that v0.5.6 is released, but I don't see it under

https://github.com/brianmario/mysql2/releases

**Comment by flavorjones** [comment]
@tenderlove could you please create a release? here's a description if it's helpful:

```
# 0.5.6

## What's changed

* Support utf8mb3 charset naming for MySQL 8 and MariaDB 10.6. (#1323) @jeremy
* Support for libmysqlclient 8.3 (#1346, #1352, #1353) @xjunior @flavorjones
```

**Comment by tenderlove** [comment]
Done https://github.com/brianmario/mysql2/releases/tag/0.5.6

**Comment by VitaliySerov** [comment]
@tenderlove Thanks
