### ISSUE TITLE
error require in "mysql2 / lib / mysql2.rb " file

### ISSUE THREAD

**Issue by sjbwylbs** [brianmario/mysql2#192]
in "mysql2 / lib / mysql2.rb " file
link this:https://github.com/brianmario/mysql2/blob/master/lib/mysql2.rb

have require "mysql2/mysql2"

but  didn't have mysql2.rb file in "mysql2 / lib / mysql2/directory".

is't a bug?

**Comment by gowtham-sai** [comment]
@svalleru , 

That lead me to 
```bash
./client.h:23:3: error: use of undeclared identifier 'TRAP_BEG'
  TRAP_BEG;
  ^
./client.h:25:3: error: use of undeclared identifier 'TRAP_END'
  TRAP_END;
```

Using mysql2 - 0.3.12b6. Any suggestion?

**Comment by sodabrew** [comment]
Please don't ask for new help on very-old-and-unrelated issues. mysql2 0.3.12b6 is out of date, and the `b6` part indicates that it was a beta version to begin with, please update to a current revision, either 0.3.x or 0.4.x.

**Comment by gowtham-sai** [comment]
@sodabrew, I accept that it is outdated and very old. But.., old project and huge code base. So.. :)
