### ISSUE TITLE
Mysql2::Error: closed MySQL connection

### ISSUE THREAD

**Issue by ntalbott** [brianmario/mysql2#209]
We have a long-running, fairly active daemon that dies intermittently with this error (max once a day, min every few weeks). We're on Rails 3.0.10 and mysql2 0.2.11. Here's the full error:

```
Mysql2::Error: closed MySQL connection: DELETE FROM `atable` WHERE (id IN (976613))

#<ActiveRecord::StatementInvalid: Mysql2::Error: closed MySQL connection: DELETE FROM `atable` WHERE (id IN (976613))>
```

Any ideas on what could be going on? Anything I can do to help debug?

**Comment by kjaleshire** [comment]
Today is someday. Thank you for posting a summary!

**Comment by ericboehs** [comment]
This helped me today as well. Future internetians: this solution is still relevant.

**Comment by alan-12gigs** [comment]
More insight on how to debug this. I did the following after setting `reconnect: true` on `database.yml`, and this solution not working.

```
cd /your_rails_deploy_code/log
cat production.log

# check the pids from delayed job:
E, [2017-02-01T19:45:21.614579 #2592] ERROR -- : 2017-02-01T19:45:21+0000: [Worker(delayed_job.3 host:demeter pid:2592)] Job ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper (id=193675) FAILED (0 prior attempts) with Mysql2::Error: closed MySQL connection
```

On my specific case, `pid:2592` is the only one constantly failing. Why? Let's find out:

```
[deploy@demeter] ps -ef | grep 2592
deploy   23318     1  0 Jan31 ?        00:00:40 production/delayed_job.3
deploy   23318     1  0 Feb01 ?        00:00:40 production/delayed_job.1
deploy   23318     1  0 Feb01 ?        00:00:40 production/delayed_job.0
```

I noticed that specific process started days before my latest deploy. As soon as I killed it, the errors were gone. What I assume happened on my specific case was that my latest deploy did not delete all delayed_job instances correctly.

**Comment by ngocson2vn** [comment]
On your MySQL server, please check the following parameters:
`wait_timeout`
`net_read_timeout`
`net_write_timeout`
