### ISSUE TITLE
Mysql2::Error: MySQL server has gone away under Rails 3.1.1

### ISSUE THREAD

**Issue by thoughtafter** [brianmario/mysql2#213]
I upgraded an app to Rails 3.1.1 and pushed it to a staging server.  I'm seeing lots of "Mysql2::Error: MySQL server has gone away" including in the console.  This could easily be a bug in Rails 3.1.1 but I thought I would report it here to see if anyone else encounters it.

**Comment by joshuapinter** [comment]
For anyone running into this while forking in Rails, try clearing the existing connections before forking and then establish a new connection for each fork, like this: 

```ruby
# Clear existing connections before forking to ensure they do not get inherited.
::ActiveRecord::Base.clear_all_connections! 

fork do
  # Establish a new connection for each fork.
  ::ActiveRecord::Base.establish_connection 
  
  # The rest of the code for each fork...
end
```

See this StackOverflow answer here: https://stackoverflow.com/a/8915353/293280
