### ISSUE TITLE
no ipv6 support

### ISSUE THREAD

**Issue by naox** [brianmario/mysql2#279]
I've compiled mysql2 gem against newest mysql version
# ldd mysql2.so

```
    libmysqlclient.so.18 => /usr/lib64/libmysqlclient.so.18 (0x00007fba0eeb8000)
```

and still there is no ipv6 support. I've compiled php against same mysql version and there are no problems.
My mysql server is at ipv6 adress. I connect to it by hostname that is translated by /etc/hosts

Gem mysql2 only gives error

Can't connect to MySQL server on 'mysql5' (111) (Mysql::Error)
# cat /etc/hosts|grep mysql5

2a01:4f8:561:5165::c12          mysql5

Like I said there is zero problems with this configuration and php+mysql

**Comment by naox** [comment]
Its 3 years later and I still can't connect to ipv6 mysql server. There are no problems (on same server) with php, no problems with python but gem mysql2 in ruby still don't support ipv6 connections to server.
All you get when using domain that has AAAA record only as mysql host is:
Unknown MySQL server host 'mysql-ipv6.domain.com' (1) (Mysql2::Error)

**Comment by brianmario** [comment]
@naox interesting... We're just [handing the host string](https://github.com/brianmario/mysql2/blob/master/ext/mysql2/client.c#L340) passed in [directly to libmysqlclient](https://github.com/brianmario/mysql2/blob/master/ext/mysql2/client.c#L162-L165) to do with it what it will. And as @sodabrew and I have both tested, ipv6 connectivity has definitely been verified and working. Maybe there are some other connection options being passed that are somehow conflicting? Is there also an A record for that domain that libmysqlclient is maybe attempting to use first? Have you tried passing the ip address directly instead of a hostname?

**Comment by naox** [comment]
```
Unknown MySQL server host '2a01:4f8:162:12e7::c1' (1) (Mysql2::Error)
  /home/naox/.gems/2.1/gems/mysql2-0.3.18/lib/mysql2/client.rb:70:in `connect'
  /home/naox/.gems/2.1/gems/mysql2-0.3.18/lib/mysql2/client.rb:70:in `initialize'
```

```
root@sv1 [/home/naox/.gems/2.1/gems/mysql2-0.3.18/lib/mysql2]# ldd mysql2.so
        linux-vdso.so.1 =>  (0x00007fff8f3d6000)
        libmysqlclient.so.18 => /var/mysql-5.5.29/lib/libmysqlclient.so.18 (0x00007f54f4592000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f54f4362000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f54f40df000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f54f3ed6000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f54f3cd1000)
        libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007f54f3a99000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f54f3740000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f54f343f000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f54f3231000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f54f4cfd000)
``

I have both php libs and python libs compiled against var/mysql-5.5.29/lib/libmysqlclient.so.18 and ipv6 works. Does ipv6 really work for you? :/

**Comment by brianmario** [comment]
fwiw that ipv6 host is globally accessible:

```
irb(main):001:0> Mysql2::Client.new :host => "2a01:4f8:162:12e7::c1"
Mysql2::Error: Access denied for user 'brianmario'@'2601:9:7b80:68f:c4ac:9229:4955:ec1a' (using password: NO)
	from /Users/brianmario/github/github/vendor/gems/2.1.5/ruby/2.1.0/gems/mysql2-0.3.17/lib/mysql2/client.rb:70:in `connect'
	from /Users/brianmario/github/github/vendor/gems/2.1.5/ruby/2.1.0/gems/mysql2-0.3.17/lib/mysql2/client.rb:70:in `initialize'
	from (irb):1:in `new'
	from (irb):1
	from script/console:68:in `<main>'
```

Connecting appears to be working, but I got an auth error which I expected.

**Comment by brianmario** [comment]
And using the latest from master:

```
brianmario:mysql2.git brianmario$ bundle exec irb
irb(main):001:0> require 'mysql2'
=> true
irb(main):002:0> Mysql2::VERSION
=> "0.3.18"
irb(main):003:0> `git rev-list -1 HEAD`.rstrip
=> "5e21bf2f788d3eacac81f59c01d15f4c48e99bfc"
irb(main):004:0> Mysql2::Client.new :host => "2a01:4f8:162:12e7::c1"
Mysql2::Error: Access denied for user 'brianmario'@'2601:9:7b80:68f:c4ac:9229:4955:ec1a' (using password: NO)
	from /Users/brianmario/<snip>/mysql2.git/lib/mysql2/client.rb:70:in `connect'
	from /Users/brianmario/<snip>/mysql2.git/lib/mysql2/client.rb:70:in `initialize'
	from (irb):2:in `new'
	from (irb):2
	from /<snip>/rbenv/versions/2.1.5-github/bin/irb:11:in `<main>'
```

**Comment by naox** [comment]
Thanks. To bad there seem to be no way to check compiled in mysql lib version - other then by ldd which I did i showed proper version.
In mysql, mysqli in php you can display such info using for example phpinfo(). Without such debuging options i'm stuck in my problems for probably next 3 years or more.

example from php:
```
mysqli

MysqlI Support	 enabled
Client API library version	5.5.29
Client API header version	5.5.29
```

**Comment by brianmario** [comment]
The `Mysql2::Client#info` instance method will give you the return values of `mysql_get_client_version` and `mysql_get_client_info` from the libmysqlclient C api. That should give you the correct version of the library that's been loaded. Is it different than what PHP is loading?

**Comment by naox** [comment]
Unfortunetly I have no idea how to display this return value of "Mysql2::Client#info" because I don't program in ruby :) I'm only a guy that set ups mysql and ensures it always accessible 

```
# irb
irb(main):001:0> require 'mysql2'
=> true
irb(main):002:0> Mysql2::Client#info
=> Mysql2::Client
```

**Comment by brianmario** [comment]
Oh sorry haha ;)

The hash character syntax in ruby is a documentation pattern for showing a method is an instance method. The hash character itself in Ruby syntax is the start of a comment, so in your example code above Ruby interpreted `Mysql2::Client#info` as just `Mysql2::Client`, which is a constant.

I'm not realizing that you have to have a successfully connected client in order to call this `info` method because we use the connection's encoding to transcode the string value we get back from the libmysqlclient C api into whatever the caller has defined with `Encoding.default_internal`, if it's set (it defaults to nil). But, I'm _pretty sure_ the values we get back from that method will always be ASCII unless the caller is running some very custom version of libmysqlclient that has a version string with non-ascii characters in it...

Let me get a patch ready for that so you can get this info without needing to connect to a server first. I'll also add the libmysqlclient version that was linked against (what PHP is reporting as "header version" above). I'll cc you on the pull request once I have it open.

**Comment by naox** [comment]
```
irb(main):017:0> a = Mysql2::Client.new :host => "mysql5", :username => "naox_a", :password => "xxxxxxxx"
irb(main):020:0> a.info
=> {:id=>50077, :version=>"5.0.77"}
```

It seems that gem linked against old mysql version (which is linux distro defaut and I don't want to replace it)

It should have been linked against new version because /usr/bin/mysql_config is a symlink to this versions mysql_config

```
# /usr/bin/mysql_config
Usage: /usr/bin/mysql_config [OPTIONS]
Options:
        --cflags         [-I/var/mysql-5.5.29/include -g]
        --include        [-I/var/mysql-5.5.29/include]
        --libs           [-L/var/mysql-5.5.29/lib -lmysqlclient -lpthread -lm -lrt -ldl]
        --libs_r         [-L/var/mysql-5.5.29/lib -lmysqlclient_r -lpthread -lm -lrt -ldl]
        --plugindir      [/var/mysql-5.5.29/lib/plugin]
        --socket         [/tmp/mysql.sock]
        --port           [0]
        --version        [5.5.29]
        --libmysqld-libs [-L/var/mysql-5.5.29/lib -lmysqld]
        --variable=VAR   VAR is one of:
                pkgincludedir [/var/mysql-5.5.29/include]
                pkglibdir     [/var/mysql-5.5.29/lib]
                plugindir     [/var/mysql-5.5.29/lib/plugin]
```

even though during instalation output says good path to new mysql it seems not to link agains it:
```
# gem install mysql2 --verbos
...
Building native extensions.  This could take a while...
/usr/share/ruby-2.1.1/bin/ruby extconf.rb
checking for ruby/thread.h... yes
checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
checking for rb_thread_blocking_region()... yes
checking for rb_wait_for_single_fd()... yes
checking for rb_hash_dup()... yes
checking for rb_intern3()... yes
-----
Using mysql_config at /usr/bin/mysql_config
-----
checking for mysql.h... yes
checking for errmsg.h... yes
checking for mysqld_error.h... yes
-----
Setting libpath to /var/mysql-5.5.29/lib
-----
creating Makefile
make "DESTDIR=" clean
make "DESTDIR="
compiling client.c
compiling result.c
compiling mysql2_ext.c
compiling infile.c
linking shared-object mysql2/mysql2.so
make "DESTDIR=" install
/usr/bin/install -c -m 0755 mysql2.so ./.gem.20150311-22439-17qkpd3/mysql2
installing default mysql2 libraries

Successfully installed mysql2-0.3.18
1 gem installed

```

there is something wrong with "./configure" for mysql2 gem but I'm unclear how actualy makefile is created for gems
Here is contents of resulting makefile (/home/naox/.gems/2.1/gems/mysql2-0.3.18/ext/mysql2/Makefile) http://pastebin.com/eVhs1LWG



I've also tried installing gem with

```
# gem install mysql2 --verbose -- --with-mysql-dir=/var/mysql-5.5.29/
...
Building native extensions with: '--with-mysql-dir=/var/mysql-5.5.29/'
This could take a while...
/usr/share/ruby-2.1.1/bin/ruby extconf.rb --with-mysql-dir=/var/mysql-5.5.29/
checking for ruby/thread.h... yes
checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
checking for rb_thread_blocking_region()... yes
checking for rb_wait_for_single_fd()... yes
checking for rb_hash_dup()... yes
checking for rb_intern3()... yes
-----
Using --with-mysql-dir=/var/mysql-5.5.29
-----
checking for mysql.h... yes
checking for errmsg.h... yes
checking for mysqld_error.h... yes
-----
Setting libpath to /var/mysql-5.5.29//lib
-----
creating Makefile
make "DESTDIR=" clean
make "DESTDIR="
compiling client.c
compiling result.c
compiling mysql2_ext.c
compiling infile.c
linking shared-object mysql2/mysql2.so
make "DESTDIR=" install
/usr/bin/install -c -m 0755 mysql2.so ./.gem.20150311-2609-bcpau7/mysql2
installing default mysql2 libraries

Successfully installed mysql2-0.3.18
1 gem installed
```

but it still is linked agains old mysql version in the system
```
irb(main):017:0> a = Mysql2::Client.new :host => "mysql5", :username => "naox_a", :password => "xxxxxxxx"
irb(main):020:0> a.info
=> {:id=>50077, :version=>"5.0.77"}
```

I can provide user privlidge shell account (with possibility of compiling gems) for debuging this issue

**Comment by naox** [comment]
Problem was some old version in /home/naox/.gems/2.1/extensions/x86_64-linux/2.1.0-static/mysql2-0.3.18/mysql2 which was not replaced after running "gem install mysql2". Deleting it solved this problem. However why was it there and why it was not replaced by "gem install mysql2" efectively blocking any updates to a gem?

```
naox@sv1 [/home/naox/.gems/2.1/extensions/x86_64-linux/2.1.0-static/mysql2-0.3.18/mysql2]# ldd mysql2.so
ldd: warning: you do not have execution permission for `./mysql2.so'
        linux-vdso.so.1 =>  (0x00007fff05fff000)
        libmysqlclient_r.so.15 => /usr/lib64/libmysqlclient_r.so.15 (0x00007fe86f3b9000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fe86f19c000)
        libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007fe86ef64000)
        libnsl.so.1 => /lib64/libnsl.so.1 (0x00007fe86ed4c000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fe86eac8000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fe86e8bf000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fe86e6bb000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fe86e361000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fe86f945000)
```

also i can confirm that https://github.com/brianmario/mysql2/pull/594 is now working for me after removing this old mysql2.so

**Comment by brianmario** [comment]
> However why was it there and why it was not replaced by "gem install mysql2" efectively blocking any updates to a gem?

That's really strange. Maybe rubygems saw the existing version on disk, and since the gem you were trying to install had the same version number it just reused the cached copy? Nothing about the mysql2 gem build process should have been an issue there.

**Comment by naox** [comment]
I've submited detailed issue on this to rubygems on github: https://github.com/rubygems/rubygems/issues/1192

"gem install mysql2" does re-make file /home/user/.gems/2.1/gems/mysql2-0.3.18/ext/mysql2/mysql2.so while it does not (if file already exist)
/home/user/.gems/2.1/extensions/x86_64-linux/2.1.0-static/mysql2-0.3.18/mysql2/mysql2.so and the second one is actualy used by "requre xxxx". This issue is not specific to mysql2 gem as I observed it on other gems.
