### ISSUE TITLE
uninitialized constant Mysql2::Client::REMEMBER_OPTIONS (NameError)

### ISSUE THREAD

**Issue by llb0536** [brianmario/mysql2#294]
I have worked on it for one day .Any idea?

/usr/local/lib/ruby/gems/1.9.1/gems/mysql2-0.3.11/lib/mysql2/client.rb:12:in `<class:Client>': uninitialized constant Mysql2::Client::REMEMBER_OPTIONS (NameError)
    from /usr/local/lib/ruby/gems/1.9.1/gems/mysql2-0.3.11/lib/mysql2/client.rb:2:in`module:Mysql2'
    from /usr/local/lib/ruby/gems/1.9.1/gems/mysql2-0.3.11/lib/mysql2/client.rb:1:in `<top (required)>'
    from /usr/local/lib/ruby/gems/1.9.1/gems/mysql2-0.3.11/lib/mysql2.rb:10:in`require'
    from /usr/local/lib/ruby/gems/1.9.1/gems/mysql2-0.3.11/lib/mysql2.rb:10:in `<top (required)>'
    from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.0.18/lib/bundler/runtime.rb:68:in`require'
    from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.0.18/lib/bundler/runtime.rb:68:in `block (2 levels) in require'
    from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.0.18/lib/bundler/runtime.rb:66:in`each'
    from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.0.18/lib/bundler/runtime.rb:66:in `block in require'
    from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.0.18/lib/bundler/runtime.rb:55:in`each'
    from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.0.18/lib/bundler/runtime.rb:55:in `require'
    from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.0.18/lib/bundler.rb:120:in`require'
    from /Users/Liber/ktv/trunk/config/application.rb:11:in `<top (required)>'
    from /usr/local/lib/ruby/gems/1.9.1/gems/railties-3.2.8/lib/rails/commands.rb:53:in`require'
    from /usr/local/lib/ruby/gems/1.9.1/gems/railties-3.2.8/lib/rails/commands.rb:53:in `block in <top (required)>'
    from /usr/local/lib/ruby/gems/1.9.1/gems/railties-3.2.8/lib/rails/commands.rb:50:in`tap'
    from /usr/local/lib/ruby/gems/1.9.1/gems/railties-3.2.8/lib/rails/commands.rb:50:in `<top (required)>'
    from script/rails:6:in`require'
    from script/rails:6:in `<main>'
# 

---

System:OSX10.8.1

/usr/local/mysql $ mysql --version
/usr/local/mysql/bin/mysql  Ver 14.14 Distrib 5.5.27, for osx10.6 (i386) using readline 5.1

$ gem list mysql2

**\* LOCAL GEMS ***

mysql2 (0.3.11)

**Comment by Mohan-Rathour** [comment]
Hey I am still getting this issue .
/.rvm/gems/ruby-2.2.1@tasks-api/gems/mysql2-0.3.15/lib/mysql2/client.rb:12:in `<class:Client>': uninitialized constant Mysql2::Client::SECURE_CONNECTION (NameError)
	from /Users/mohanrathour/.rvm/gems/ruby-2.2.1@tasks-api/gems/mysql2-0.3.15/lib/mysql2/client.rb:2:in `<module:Mysql2>'
	from /Users/mohanrathour/.rvm/gems/ruby-2.2.1@tasks-api/gems/mysql2-0.3.15/lib/mysql2/client.rb:1:in `<top (required)>'
	from /Users/mohanrathour/.rvm/gems/ruby-2.2.1@tasks-api/gems/mysql2-0.3.15/lib/mysql2.rb:10:in `require'
	from /Users/mohanrathour/.rvm/gems/ruby-2.2.1@tasks-api/gems/mysql2-0.3.15/lib/mysql2.rb:10:in `<top (required)>'
	from /Users/mohanrathour/.rvm/gems/ruby-2.2.1@tasks-api/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require'
	from /Users/mohanrathour/.rvm/gems/ruby-2.2.1@tasks-api/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /Users/mohanrathour/.rvm/gems/ruby-2.2.1@tasks-api/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `each'
	from /Users/mohanrathour/.rvm/gems/ruby-2.2.1@tasks-api/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `block in require'
	from /Users/mohanrathour/.rvm/gems/ruby-2.2.1@tasks-api/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
	from /Users/mohanrathour/.rvm/gems/ruby-2.2.1@tasks-api/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `require'
	from /Users/mohanrathour/.rvm/gems/ruby-2.2.1@tasks-api/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'
	from /Users/mohanrathour/Desktop/work-space/tasks/config/application.rb:7:in `<top (required)>'
	from /Users/mohanrathour/.rvm/gems/ruby-2.2.1@tasks-api/gems/railties-4.1.4/lib/rails/commands/commands_tasks.rb:79:in `require'
	from /Users/mohanrathour/.rvm/gems/ruby-2.2.1@tasks-api/gems/railties-4.1.4/lib/rails/commands/commands_tasks.rb:79:in `block in server'
	from /Users/mohanrathour/.rvm/gems/ruby-2.2.1@tasks-api/gems/railties-4.1.4/lib/rails/commands/commands_tasks.rb:76:in `tap'
	from /Users/mohanrathour/.rvm/gems/ruby-2.2.1@tasks-api/gems/railties-4.1.4/lib/rails/commands/commands_tasks.rb:76:in `server'
	from /Users/mohanrathour/.rvm/gems/ruby-2.2.1@tasks-api/gems/railties-4.1.4/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /Users/mohanrathour/.rvm/gems/ruby-2.2.1@tasks-api/gems/railties-4.1.4/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/mohanrathour/Desktop/work-space/tasks/bin/rails:8:in `require'
	from /Users/mohanrathour/Desktop/work-space/tasks/bin/rails:8:in `<top (required)>'
	from /Users/mohanrathour/.rvm/gems/ruby-2.2.1@tasks-api/gems/spring-1.1.3/lib/spring/client/rails.rb:27:in `load'
	from /Users/mohanrathour/.rvm/gems/ruby-2.2.1@tasks-api/gems/spring-1.1.3/lib/spring/client/rails.rb:27:in `call'
	from /Users/mohanrathour/.rvm/gems/ruby-2.2.1@tasks-api/gems/spring-1.1.3/lib/spring/client/command.rb:7:in `call'
	from /Users/mohanrathour/.rvm/gems/ruby-2.2.1@tasks-api/gems/spring-1.1.3/lib/spring/client.rb:26:in `run'
	from /Users/mohanrathour/.rvm/gems/ruby-2.2.1@tasks-api/gems/spring-1.1.3/bin/spring:48:in `<top (required)>'
	from /Users/mohanrathour/.rvm/gems/ruby-2.2.1@tasks-api/gems/spring-1.1.3/lib/spring/binstub.rb:11:in `load'
	from /Users/mohanrathour/.rvm/gems/ruby-2.2.1@tasks-api/gems/spring-1.1.3/lib/spring/binstub.rb:11:in `<top (required)>'
	from /Users/mohanrathour/Desktop/work-space/tasks/bin/spring:16:in `require'
	from /Users/mohanrathour/Desktop/work-space/tasks/bin/spring:16:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'

**Comment by sodabrew** [comment]
@Mohan-Rathour There is a discussion in #603 that may be helpful with `SECURE_CONNECTION`.
