### ISSUE TITLE
stored procedure issues

### ISSUE THREAD

**Issue by krukid** [brianmario/mysql2#307]
Firstly, the stored procedure example on the main page doesn't seem to work, failing with:
`undefined method `next_result' for #<Mysql2::Client:0xb6f48538> (NoMethodError)`

Secondly, even if my stored proc returns a single result set, `mysql2` doesn't seem to handle the associated resources properly, because subsequent queries throw:
`Commands out of sync; you can't run this command now (Mysql2::Error)`

**Comment by iRonin** [comment]
Is calling `client.abandon_results!` still needed when working with stored procedures?

**Comment by sodabrew** [comment]
@iRonin Not necessarily, see the code for this test as an example: https://github.com/brianmario/mysql2/commit/2a7d09d288ccb6720e4ffb3608e708c33b56ae44
