### ISSUE TITLE
Expecting an Exception from Mysql2::Client#initialize if connect fails

### ISSUE THREAD

**Issue by fredngo** [brianmario/mysql2#319]
I am working on some failure modes in my application and would like to do something smart if the database is unavailable (This happened, for example, in the Amazon outage of 10/23/2012).

So I try something like this:

``` ruby
begin
  ActiveRecord::Base.connection.active?
rescue
  warn "********** The DB connection is dead!"
end
```

And I put the above in a rake task, shut down the mysql daemon locally and tried it out. Instead of getting my expected error message, I get this:

```
% rake test_db_connection
rake aborted!
Can't connect to MySQL server on '127.0.0.1' (61)
/Users/fred/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/mysql2-0.3.11/lib/mysql2/client.rb:44:in `connect'
/Users/fred/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/mysql2-0.3.11/lib/mysql2/client.rb:44:in `initialize'
/Users/fred/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/activerecord-3.2.8/lib/active_record/connection_adapters/mysql2_adapter.rb:16:in `new'
...

```

Looking into the mysql2 source, I find the following in Mysql2::Client#initialize:

``` ruby
def initialize(opts = {})
  ...
  connect user, pass, host, port, database, socket, flags
end
```

It seems that connect is a native C function that is being called, and if it fails to connect will abort the entire process.

So, my question is, is this expected behaviour? If so, is there a reason why a Mysql2::Error is not being thrown? And is there some other way to rescue from this so I can do something smart when the database is not available?

Thanks!

**Comment by thomasbiddle** [comment]
@fredngo I know this is super old and slightly off topic! But did you find anywhere to add this into Rails application by chance? I can't seem to find anywhere where I can throw my rescue statement where it will be caught!

**Comment by fredngo** [comment]
I'm afraid I never pursued this anymore... Good luck and do report back if you figure something out!
