### ISSUE TITLE
Error installing mysql2, Failed to build gem native extension. On Win XP with Ruby 2.0.0.

### ISSUE THREAD

**Issue by wzup** [brianmario/mysql2#364]
I cannot install the gem.

I have pre-installed MySQL here, no any spaces in the path:
`C:\mysql-5.6.10\mysql-5.6.10-win32`

I have **Ruby 2.0.0** from RubyInstaller.

The command I type:
`C:\>gem install mysql2 --platform=ruby -- --with-mysql-dir="C:\mysql-5.6.10\mysql-5.6.10-win32"`

**Readme.md** says:

> If you have installed MySQL to a non-standard location, add 
> `gem install mysql2 --with-mysql-config=/some/random/path/bin/mysql_config`

What is `/some/random/path/bin/mysql_config`? I don't have any `mysql_config` file in `bin/` directory of my MySQL installation. Could you explain what config is meant?

A copy/paste part from the error message:

```
ERROR:  Error installing mysql2:
        ERROR: Failed to build gem native extension.

    C:/Ruby200/bin/ruby.exe extconf.rb --with-mysql-dir=C:\mysql-5.6.10\mysql-5.6.10-win32
checking for rb_thread_blocking_region()... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby200/bin/ruby
```

What do all those **configuration options** mean? Do I have to pass any values with them for successful installation? **Readme.md** file doesn't provide info about them. Where may I find explanation?
1. How to solve the issue?
2. Is it even possible to install the gem on Win XP?

**Comment by vhosakot** [comment]
`yum install gcc gcc-c++ ruby-devel` resolved the `rb_thread_blocking_region()... *** extconf.rb failed ` error in CentOS for me.
