### ISSUE TITLE
Bundle windows binaries for ruby2

### ISSUE THREAD

**Issue by GhostGambler** [brianmario/mysql2#414]
This gem seems to lack binaries for ruby2 on Windows. That requires Windows users to download adapter files or install a whole mysql server, pass configuration options to `gem install`, etc.
It results in complex problems for beginners while installing the gem on a windows machine, which are not solvable for those and are not necessary since it's possible to ship precompiled files.

This problem arose in other gems as well and have mostly been sorted out, e.g. for sqlite3 with usage of cross compilers in a VM (see https://github.com/luislavena/sqlite3-ruby/pull/103).

Might it be possible that you sort issues out too and provide precompiled files for Windows users?

**Comment by sodabrew** [comment]
Now that #473 is merged, I will publish Windows binaries for the next release.

**Comment by simi** [comment]
@sodabrew ping me if you will need help.

**Comment by sodabrew** [comment]
I released mysql2 version 0.3.18 **with windows binaries** today!
