### ISSUE TITLE
segementation fault fix (worked for me)

### ISSUE THREAD

**Issue by ghost** [brianmario/mysql2#486]
this seems to fix the segmentation fault problem

The libmysql.lib included in the MySQL Connector/C 64 bit is not compatible with the mingw64-gcc compiler.

You need to generate mingw64 compatible libmysql.lib file.

To generate libmysql.lib file, you need gendef.exe, which can obtain from mingw-w64 distribution

In the lib folder of the mysql connector, produce libmysql.lib with the following steps.

gendef.exe libmysql.dll

dlltool -v --dllname libmysql.dll --def libmysql.def --output-lib libmysql.lib

after gendef.exe run gem command: gem install mysql2 --no-rdoc --no-ri -- '--with-mysql-lib="C:\Program Files\MySQL\MySQL Server 5.6\lib" --with-mysql-include="C:\Program Files\MySQL\MySQL Server 5.6\include" '

it won't work with the command [--with-opt-dir] on windows (I did this on windows 7 and it didn't work for me)

worked for me with the latest MySQL version ( I didn't try it on the standalone connectors)

this worked for me on windows 7

Source: https://bugs.ruby-lang.org/issues/8591

**Comment by david-de-malaga** [comment]
I've had the same problem and I solved with small changes. This is the track:

1. Download mysql-connector-c-noinstall-6.0.2-winx64 from https://copy.com/CHZ4eT4us6f1?download=1 (extract in C:\mysql-connector).
2.I got gendef, dlltool from minGW (look at this link https://github.com/kivy/kivy/wiki/Creating-a-64-bit-development-environment-with-MinGW-on-Windows), put C:\mingw32\bin in Environment variables and reboot windows.
3.Go to C:\mysql-connector\lib and to this:
    a)gendef.exe libmysql.dll
    b)dlltool -v --dllname libmysql.dll --def libmysql.def --output-lib libmysql.lib
3. Copy this file from C:\mysql-connector\lib\libmysql.dll to C:\Ruby21-x64\bin
4.Run this command in cmd.exe=> gem install mysql2 --no-rdoc --no-ri -- '--with-mysql-lib="C:\mysql-connector\lib" --with-mysql-include="C:\mysql-connector\include"'

It works for me !

**Comment by sodabrew** [comment]
I released mysql2 version 0.3.18 **with windows binaries** today!

Future visitors: use the binary build, or build yourself with 0.3.18. Do no use the workarounds posted above.

If you find a problem with the 0.3.18 version, please open a new ticket.

I am locking this issue now.
