### ISSUE TITLE
Lost connection to MySQL server during query on 'simple' queries

### ISSUE THREAD

**Issue by kakubei** [brianmario/mysql2#495]
Opening up a new issue for this since all the other similar ones are closed. We started seeing lots of these errors after upgrading to Padrino 0.12 and Mysql2 0.3.15. We don't have access to mysql.cnf (hosted on ClearDB) so can't tweak any of the settings there. Reconnect is set to true in our `database.rb` file. 

This is on Heroku and happens (unsurprisingly) during heavy usage. 

By "simple" queries, I mean it's nothing crazy, just a number of joins with properly formatted foreign keys which execute pretty quickly in the console.

Any ideas are welcome. 

   Lost connection to MySQL server during query

Padrino 0.12
Active Record 4.0.2
mysql2 (0.3.15)
puma (2.7.1)

Following is the backtrace:

gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:287query
    gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:287block in execute
    gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:435block in log
    gems/activesupport-4.0.2/lib/active_support/notifications/instrumenter.rb:20instrument
    gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:430log
    gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:287execute
    gems/activerecord-4.0.2/lib/active_record/connection_adapters/mysql2_adapter.rb:222execute
    gems/activerecord-4.0.2/lib/active_record/connection_adapters/mysql2_adapter.rb:226exec_query
    gems/activerecord-4.0.2/lib/active_record/connection_adapters/mysql2_adapter.rb:235select
    gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:24select_all
    gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract/query_cache.rb:63select_all
    gems/activerecord-4.0.2/lib/active_record/querying.rb:36find_by_sql
    gems/activerecord-4.0.2/lib/active_record/relation.rb:585exec_queries
    gems/activerecord-4.0.2/lib/active_record/relation.rb:471load
    gems/activerecord-4.0.2/lib/active_record/relation.rb:220to_a
    gems/activerecord-4.0.2/lib/active_record/relation/finder_methods.rb:315find_take
    gems/activerecord-4.0.2/lib/active_record/relation/finder_methods.rb:65take
    gems/activerecord-4.0.2/lib/active_record/relation/finder_methods.rb:48find_by
    gems/activerecord-4.0.2/lib/active_record/querying.rb:6find_by
    /app/app/controllers/books_controller.rb:57block (2 levels) in <top (required)>
    gems/padrino-core-0.12.0/lib/padrino-core/application/routing.rb:699call
    gems/padrino-core-0.12.0/lib/padrino-core/application/routing.rb:699block in route
    gems/padrino-core-0.12.0/lib/padrino-core/application/routing.rb:62[]
    gems/padrino-core-0.12.0/lib/padrino-core/application/routing.rb:62block (3 levels) in process_destination_path
    gems/sinatra-1.4.4/lib/sinatra/base.rb:976route_eval
    gems/newrelic_rpm-3.7.2.192/lib/new_relic/agent/instrumentation/sinatra.rb:133route_eval_with_newrelic
    gems/padrino-core-0.12.0/lib/padrino-core/application/routing.rb:62block (2 levels) in process_destination_path
    gems/padrino-core-0.12.0/lib/padrino-core/application/routing.rb:62catch
    gems/padrino-core-0.12.0/lib/padrino-core/application/routing.rb:62block in process_destination_path
    gems/padrino-core-0.12.0/lib/padrino-core/application/routing.rb:37instance_eval
    gems/padrino-core-0.12.0/lib/padrino-core/application/routing.rb:37process_destination_path
    (eval):613block in call
    (eval):602catch
    (eval):602call
    gems/http_router-0.11.0/lib/http_router.rb:307raw_call
    gems/padrino-core-0.12.0/lib/padrino-core/application/routing.rb:1101route!
    gems/padrino-core-0.12.0/lib/padrino-core/application/routing.rb:1086block in dispatch!
    gems/sinatra-1.4.4/lib/sinatra/base.rb:1049block in invoke
    gems/sinatra-1.4.4/lib/sinatra/base.rb:1049catch
    gems/sinatra-1.4.4/lib/sinatra/base.rb:1049invoke
    gems/padrino-core-0.12.0/lib/padrino-core/application/routing.rb:1084dispatch!
    gems/newrelic_rpm-3.7.2.192/lib/new_relic/agent/instrumentation/sinatra.rb:151dispatch_and_notice_errors_with_newrelic
    gems/newrelic_rpm-3.7.2.192/lib/new_relic/agent/instrumentation/sinatra.rb:146block in dispatch_with_newrelic
    gems/newrelic_rpm-3.7.2.192/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:339perform_action_with_newrelic_trace
    gems/newrelic_rpm-3.7.2.192/lib/new_relic/agent/instrumentation/sinatra.rb:143dispatch_with_newrelic
    gems/sinatra-1.4.4/lib/sinatra/base.rb:889block in call!
    gems/sinatra-1.4.4/lib/sinatra/base.rb:1049block in invoke
    gems/sinatra-1.4.4/lib/sinatra/base.rb:1049catch
    gems/sinatra-1.4.4/lib/sinatra/base.rb:1049invoke
    gems/sinatra-1.4.4/lib/sinatra/base.rb:889call!
    gems/sinatra-1.4.4/lib/sinatra/base.rb:877call
    gems/newrelic_rpm-3.7.2.192/lib/new_relic/rack/error_collector.rb:55call
    gems/newrelic_rpm-3.7.2.192/lib/new_relic/rack/browser_monitoring.rb:27call
    gems/newrelic_rpm-3.7.2.192/lib/new_relic/rack/agent_hooks.rb:32call
    gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:626call
    gems/rack-protection-1.5.2/lib/rack/protection/xss_header.rb:18call
    gems/rack-protection-1.5.2/lib/rack/protection/base.rb:50call
    gems/rack-protection-1.5.2/lib/rack/protection/base.rb:50call
    gems/rack-protection-1.5.2/lib/rack/protection/json_csrf.rb:18call
    gems/rack-protection-1.5.2/lib/rack/protection/base.rb:50call
    gems/rack-protection-1.5.2/lib/rack/protection/base.rb:50call
    gems/rack-protection-1.5.2/lib/rack/protection/frame_options.rb:31call
    gems/rack-1.5.2/lib/rack/head.rb:11call
    gems/rack-1.5.2/lib/rack/methodoverride.rb:21call
    gems/padrino-core-0.12.0/lib/padrino-core/reloader/rack.rb:22call
    gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225context
    gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220call
    gems/sinatra-1.4.4/lib/sinatra/base.rb:2004call
    gems/sinatra-1.4.4/lib/sinatra/base.rb:1469block in call
    gems/sinatra-1.4.4/lib/sinatra/base.rb:1778synchronize
    gems/sinatra-1.4.4/lib/sinatra/base.rb:1469call
    gems/padrino-core-0.12.0/lib/padrino-core/router.rb:82block in call
    gems/padrino-core-0.12.0/lib/padrino-core/router.rb:75each
    gems/padrino-core-0.12.0/lib/padrino-core/router.rb:75call
    gems/rack-1.5.2/lib/rack/urlmap.rb:65block in call
    gems/rack-1.5.2/lib/rack/urlmap.rb:50each
    gems/rack-1.5.2/lib/rack/urlmap.rb:50call
    gems/puma-2.7.1/lib/puma/configuration.rb:68call
    gems/puma-2.7.1/lib/puma/server.rb:486handle_request
    gems/puma-2.7.1/lib/puma/server.rb:357process_client
    gems/puma-2.7.1/lib/puma/server.rb:250block in run
    gems/puma-2.7.1/lib/puma/thread_pool.rb:92call
    gems/puma-2.7.1/lib/puma/thread_pool.rb:92block in spawn_thread

**Comment by drobune** [comment]
Same thing has occured on ClearDB.
```
Activ​eReco​rd::S​tatem​entIn​valid​: Mys​ql2::​Error​: Los​t con​necti​on to​ MySQ​L ser​ver d​uring​ quer​y: SE​LECT ​ `hoge`.* F​ROM `​hoge` ​ WHER​E `hoge`.`fuga_i​d` = ​xxx LIMI​T 1
```

**Comment by asurancetturix** [comment]
We are having the same problem, anyone could find a fix?

**Comment by ahmadhasankhan** [comment]
```
Mysql2::Error: Lost connection to MySQL server during query: SELECT id, locality_id, name FROM `sublocalities`  ORDER BY name
/Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in `query': Mysql2::Error: Lost connection to MySQL server during query: SELECT id, locality_id, name FROM `sublocalities`  ORDER BY name (ActiveRecord::StatementInvalid)
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in `block in execute'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/activesupport-3.2.22/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/ar-octopus-0.8.5/lib/octopus/abstract_adapter.rb:15:in `instrument'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/active_record.rb:59:in `block in log_with_newrelic_instrumentation'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/method_tracer.rb:73:in `block in trace_execution_scoped'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/method_tracer_helpers.rb:82:in `trace_execution_scoped'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/method_tracer.rb:71:in `trace_execution_scoped'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/active_record.rb:56:in `log_with_newrelic_instrumentation'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in `execute'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-3.2.22/lib/active_record/connection_adapters/mysql2_adapter.rb:213:in `execute'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-3.2.22/lib/active_record/connection_adapters/mysql2_adapter.rb:217:in `exec_query'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-3.2.22/lib/active_record/connection_adapters/mysql2_adapter.rb:226:in `select'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/database_statements.rb:18:in `select_all'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/query_cache.rb:63:in `select_all'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/ar-octopus-0.8.5/lib/octopus/proxy.rb:265:in `method_missing'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-3.2.22/lib/active_record/querying.rb:38:in `block in find_by_sql'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-3.2.22/lib/active_record/explain.rb:41:in `logging_query_plan'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-3.2.22/lib/active_record/querying.rb:37:in `find_by_sql'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-3.2.22/lib/active_record/relation.rb:171:in `exec_queries'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-3.2.22/lib/active_record/relation.rb:160:in `block in to_a'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-3.2.22/lib/active_record/explain.rb:41:in `logging_query_plan'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-3.2.22/lib/active_record/relation.rb:159:in `to_a'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-3.2.22/lib/active_record/relation/finder_methods.rb:159:in `all'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-3.2.22/lib/active_record/querying.rb:5:in `all'
        from /Users/ahmadhassan/ola/call_center/app/app.rb:16:in `<class:CallCenter>'
        from /Users/ahmadhassan/ola/call_center/app/app.rb:3:in `<top (required)>'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `block in require'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:236:in `load_dependency'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/padrino-core-0.10.7/lib/padrino-core/reloader.rb:148:in `safe_load'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/padrino-core-0.10.7/lib/padrino-core/loader.rb:163:in `block in require_dependencies'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/padrino-core-0.10.7/lib/padrino-core/loader.rb:161:in `each'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/padrino-core-0.10.7/lib/padrino-core/loader.rb:161:in `require_dependencies'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/padrino-core-0.10.7/lib/padrino-core/mounter.rb:148:in `locate_app_object'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/padrino-core-0.10.7/lib/padrino-core/mounter.rb:30:in `initialize'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/padrino-core-0.10.7/lib/padrino-core/mounter.rb:221:in `new'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/padrino-core-0.10.7/lib/padrino-core/mounter.rb:221:in `mount'
        from /Users/ahmadhassan/ola/call_center/config/apps.rb:34:in `<top (required)>'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `block in require'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:236:in `load_dependency'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/padrino-core-0.10.7/lib/padrino-core/reloader.rb:148:in `safe_load'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/padrino-core-0.10.7/lib/padrino-core/loader.rb:163:in `block in require_dependencies'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/padrino-core-0.10.7/lib/padrino-core/loader.rb:161:in `each'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/padrino-core-0.10.7/lib/padrino-core/loader.rb:161:in `require_dependencies'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/padrino-core-0.10.7/lib/padrino-core/loader.rb:70:in `block in load!'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/padrino-core-0.10.7/lib/padrino-core/loader.rb:70:in `each'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/padrino-core-0.10.7/lib/padrino-core/loader.rb:70:in `load!'
        from /Users/ahmadhassan/ola/call_center/config/boot.rb:73:in `<top (required)>'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/padrino-core-0.10.7/lib/padrino-core/cli/base.rb:23:in `require'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/padrino-core-0.10.7/lib/padrino-core/cli/base.rb:23:in `start'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/thor-0.15.4/lib/thor/task.rb:27:in `run'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/thor-0.15.4/lib/thor/invocation.rb:120:in `invoke_task'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/thor-0.15.4/lib/thor.rb:275:in `dispatch'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/thor-0.15.4/lib/thor/invocation.rb:109:in `invoke'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/padrino-core-0.10.7/lib/padrino-core/cli/base.rb:29:in `s'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/thor-0.15.4/lib/thor/task.rb:27:in `run'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/thor-0.15.4/lib/thor/invocation.rb:120:in `invoke_task'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/thor-0.15.4/lib/thor.rb:275:in `dispatch'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/thor-0.15.4/lib/thor/base.rb:425:in `start'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/gems/padrino-core-0.10.7/bin/padrino:9:in `<top (required)>'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/bin/padrino:23:in `load'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/bin/padrino:23:in `<main>'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/bin/ruby_executable_hooks:15:in `eval'
        from /Users/ahmadhassan/.rvm/gems/ruby-2.0.0-p598/bin/ruby_executable_hooks:15:in `<main>'

```

**Comment by Bodacious** [comment]
+1 for this issue.

- Rails 4.0.0
- MySQL2 0.3.20
- ClearDB is the provider

`(ActiveRecord::StatementInvalid) "Mysql2::Error: Lost connection to MySQL server during query: SHOW FULL FIELDS FROM `sessions`"`

**Comment by oranges13** [comment]
I am also having this issue on several web apps with Padrino, not Rails. We're using Sequel as the Database adapter not Active Record.

**Comment by CyberFerret** [comment]
Just came across this same thing using Padrino 13.1, and Sequel  as the adapter.  It seems if I leave the web app idle for a while and come back to try and do something, it falls over with this error.

**Comment by pchaganti** [comment]
Seeing the same thing when using Sequel as adapter with latest version of Padrino.

**Comment by sodabrew** [comment]
I read up on the Sequel adapter - it simply passed through constructor arguments to `Mysql2::Client#new` -- do you all have reconnect enabled? Are you all on mysql2 0.3.x or 0.4.x now?

**Comment by oranges13** [comment]
How can we confirm reconnect enabled or not?

**Comment by sodabrew** [comment]
Reconnect is disabled by default, so if you don't see it, then it's turned off.

**Comment by oranges13** [comment]
So how can we enable it?

**Comment by sodabrew** [comment]
Here are the options for Mysql2::Client#new which you can pass to Sequel#new: https://github.com/brianmario/mysql2#connection-options

**Comment by CyberFerret** [comment]
I added :reconnect => true to my connection string (Padrino 0.13.1 and Sequel) but still getting the "MySQL has gone away" messages.  In testing I assumed it was happening when the app had been idle for many minutes, but in production now, under heavy use, it happens once every 3 or 4 minutes right in the middle of a bunch of constant queries being run (i.e. within seconds of the last successful query).

I've checked the logs for things like memory and CPU usage on my server, as well as connection limits to the database server but they are always well under 10% of max capacity.

**Comment by born4new** [comment]
Any news on this? We're still having these errors with mysql2 0.3.21

**Comment by vnazarenko** [comment]
the same for me

**Comment by kln** [comment]
I created an initializer file and I try to reconnect when this error occurs. Its works for me.
Some problem with this approach?

```
# config/initializers/connection_fix.rb

Rails.application.config.after_initialize do
  config  = ActiveRecord::Base.configurations[Rails.env] ||
              Rails.application.config.database_configuration[Rails.env]

  adapter = config['adapter']

  if adapter == "mysql2"
   module ActiveRecord::ConnectionAdapters
     class Mysql2Adapter
       alias_method :execute_without_retry, :execute

       def execute(*args)
         execute_without_retry(*args)
       rescue ActiveRecord::StatementInvalid => e
         if e.message =~ /server has gone away/i ||
            e.message =~ /Lost connection to MySQL server during query/i
           reconnect!
           retry
         else
           raise e
         end
       end
     end
   end
  end
```

**Comment by camertron** [comment]
@kln your solution is the only one that worked for me. Thanks, and cheers!
