### ISSUE TITLE
Error while connecting MariaDB v10.0.10

### ISSUE THREAD

**Issue by cbajohr** [brianmario/mysql2#506]
The mysql2 gem is currently not working with the newest MariaDB Version 10.0.10

Exception:

/usr/local/rvm/gems/ruby-2.1.0/gems/mysql2-0.3.15/lib/mysql2.rb:8:in `require': Incorrect MySQL client library version! This gem was compiled for 5.5.34-MariaDB but the client library is 10.0.10-MariaDB. (RuntimeError)
from /usr/local/rvm/gems/ruby-2.1.0/gems/mysql2-0.3.15/lib/mysql2.rb:8:in`<top (required)>'
from /usr/local/rvm/gems/ruby-2.1.0@global/gems/bundler-1.5.1/lib/bundler/runtime.rb:76:in `require'
from /usr/local/rvm/gems/ruby-2.1.0@global/gems/bundler-1.5.1/lib/bundler/runtime.rb:76:in`block (2 levels) in require'
from /usr/local/rvm/gems/ruby-2.1.0@global/gems/bundler-1.5.1/lib/bundler/runtime.rb:72:in `each'
from /usr/local/rvm/gems/ruby-2.1.0@global/gems/bundler-1.5.1/lib/bundler/runtime.rb:72:in`block in require'
from /usr/local/rvm/gems/ruby-2.1.0@global/gems/bundler-1.5.1/lib/bundler/runtime.rb:61:in `each'
from /usr/local/rvm/gems/ruby-2.1.0@global/gems/bundler-1.5.1/lib/bundler/runtime.rb:61:in`require'
from /usr/local/rvm/gems/ruby-2.1.0@global/gems/bundler-1.5.1/lib/bundler.rb:131:in `require'
from /Users/christophbajohr/Work/www/kita-rabennest/config/application.rb:7:in`<top (required)>'
from /usr/local/rvm/gems/ruby-2.1.0/gems/railties-4.0.3/lib/rails/commands.rb:74:in `require'
from /usr/local/rvm/gems/ruby-2.1.0/gems/railties-4.0.3/lib/rails/commands.rb:74:in`block in <top (required)>'
from /usr/local/rvm/gems/ruby-2.1.0/gems/railties-4.0.3/lib/rails/commands.rb:71:in `tap'
from /usr/local/rvm/gems/ruby-2.1.0/gems/railties-4.0.3/lib/rails/commands.rb:71:in`<top (required)>'
from bin/rails:4:in `require'
from bin/rails:4:in`<main>'

**Comment by rahul286** [comment]
I had same problem.

Following worked for me:

```
gem uninstall mysql2
bundle config build.mysql2 --with-mysql-config=/usr/bin/mysql_config
bundle install
```

**Comment by blevonius-mdsol** [comment]
@rahul286 that fixed it for me, except mysql-config path for me was /usr/local/bin/mysql_config Thanks!

**Comment by HectorOrdonez** [comment]
The following worked for me:

```
sudo apt-get install libmariadbd-dev -y
bundle install
```
