### ISSUE TITLE
Could not load 'active_record/connection_adapters/mysql2_adapter'. Make sure that the adapter in config/database.yml is valid. If you use an adapter other than 'mysql', 'mysql2', 'postgresql' or 'sqlite3' add the necessary adapter gem to the Gemfile. (LoadError)

### ISSUE THREAD

**Issue by bianavarga** [brianmario/mysql2#534]
I am trying to use mysql2 to run cucumber tests.

I am getting the following error:

`Could not load 'active_record/connection_adapters/mysql2_adapter'. Make sure that the adapter in config/database.yml is valid. If you use an adapter other than 'mysql', 'mysql2', 'postgresql' or 'sqlite3' add the necessary adapter gem to the Gemfile. (LoadError)
/Users/bfay/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
/Users/bfay/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
/Users/bfay/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `block in require'
/Users/bfay/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:232:in `load_dependency'
/Users/bfay/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `require'
/Users/bfay/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/mysql2-0.3.16/lib/mysql2.rb:8:in `<top (required)>'
/Users/bfay/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
/Users/bfay/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
/Users/bfay/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `block in require'
/Users/bfay/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:232:in `load_dependency'
/Users/bfay/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `require'
/Users/bfay/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/mysql2_adapter.rb:4:in `<top (required)>'
/Users/bfay/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
/Users/bfay/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
/Users/bfay/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `block in require'
/Users/bfay/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:232:in `load_dependency'
/Users/bfay/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `require'
/Users/bfay/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/connection_specification.rb:188:in `spec'
/Users/bfay/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_handling.rb:50:in `establish_connection'
/Users/bfay/dev/conductor/cucumber/features/support/databases.rb:27:in `<class:ReportingDb>'
/Users/bfay/dev/conductor/cucumber/features/support/databases.rb:11:in `<top (required)>'
/Users/bfay/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/cucumber-1.3.16/lib/cucumber/rb_support/rb_language.rb:95:in `load'
/Users/bfay/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/cucumber-1.3.16/lib/cucumber/rb_support/rb_language.rb:95:in `load_code_file'
/Users/bfay/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/cucumber-1.3.16/lib/cucumber/runtime/support_code.rb:180:in `load_file'
/Users/bfay/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/cucumber-1.3.16/lib/cucumber/runtime/support_code.rb:83:in `block in load_files!'
/Users/bfay/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/cucumber-1.3.16/lib/cucumber/runtime/support_code.rb:82:in `each'
/Users/bfay/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/cucumber-1.3.16/lib/cucumber/runtime/support_code.rb:82:in `load_files!'
/Users/bfay/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/cucumber-1.3.16/lib/cucumber/runtime.rb:184:in `load_step_definitions'
/Users/bfay/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/cucumber-1.3.16/lib/cucumber/runtime.rb:42:in `run!'
/Users/bfay/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/cucumber-1.3.16/lib/cucumber/cli/main.rb:47:in `execute!'
/Users/bfay/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/cucumber-1.3.16/bin/cucumber:13:in `<top (required)>'
/usr/bin/cucumber:19:in `load'
/usr/bin/cucumber:19:in `<top (required)>'
-e:1:in `load'
-e:1:in `<main>'`

I can see that the error is that it is having trouble resolving `require 'mysql2/mysql2'` in mysql2.rb, which makes sense, since there is no mysql2.rb file inside the mysql2 directory. In the same file, there are no issues resolving the `'mysql2/version'` and `'mysql2/error'` requirements.

I can see that my file structure mirrors the structure I see at https://github.com/brianmario/mysql2/tree/master/lib. How is this dependency ever supposed to be resolved if there is no mysql2.rb file at https://github.com/brianmario/mysql2/tree/master/lib/mysql2?

Thanks!

--Biana

**Comment by Sultan91** [comment]
Same problem
