### ISSUE TITLE
connection fails to clean up in-use state after interrupt

### ISSUE THREAD

**Issue by tamird** [brianmario/mysql2#542]
repro case: https://gist.github.com/tamird/a2ead907a70a70d54236
this code reliably produces `Mysql2::Error: This connection is still waiting for a result, try again once you have the result` on my machine (and we see it in production, too).

I don't know enough about the MRI C API, so I haven't had much luck fixing this issue myself. /cc @eam

**Comment by tamird** [comment]
@sodabrew ping, this is probably the same issue we "fixed" in https://github.com/mperham/connection_pool/pull/67

Shall I attempt a similar fix?

**Comment by sodabrew** [comment]
I read through that issue, and I don't think I get it :8ball: What would you change in mysql2?

**Comment by tamird** [comment]
@sodabrew #592
