### ISSUE TITLE
SQL Injection Prevention

### ISSUE THREAD

**Issue by lavamunky** [brianmario/mysql2#543]
I have read from a previous comment that the Mysql2::Client.escape() functionality uses mysql_real_escape_string() (which I verified in the source), but I don't think this should be used since it does not prevent SQL Injection. 
For a statically typed language such as C, this isn't such a problem with dynamically created strings since it escapes both single and double quotes, so SQL Injection possibilities are very limited. With a non-statically typed language such as Ruby, however this means it is still vulnerable to SQL Injection vulnerabilities. Consider the Ruby code snippet: 

```
accountNum=params[:id] #params here is a generic hash containing the POST parameters from a request
password=params[:password]
query = "SELECT * FROM accounts WHERE accountNum=#{accountNum} AND password='#{password}'"
```

In this case using mysql_real_escape_string() will stop a user inserting a single quote into password and breaking the query, but it won't prevent somebody inserting a string into accountNum as there is no verification of the type. This also affects other languages and is prevalent in PHP for example due to the same reason. 
Without parameterized queries, it's probably best to create a function that properly sanitizes input. OWASP have a good example of a whitelisting technique for MySQL SQL Injection prevention: 
https://www.owasp.org/index.php/SQL_Injection_Prevention_Cheat_Sheet#MySQL_Escaping
Either this or you should make it clear that the escape function won't protect against SQL Injection completely.

**Comment by yippibrian** [comment]
I assume it is the case this would only be a concern for types that are not string since something like '#{accountNum}' would default to a string.  Is this correct?
