### ISSUE TITLE
Sidekiq - (ActiveRecord::StatementInvalid) "Errno::EBADF: Bad file descriptor 

### ISSUE THREAD

**Issue by ghost** [brianmario/mysql2#547]
Hi,

We got very weird exception while our sidekiq workers doing the job.
Details in here: https://github.com/mperham/sidekiq/issues/1945

Is this related to mysql2 gem?

**Comment by mperham** [comment]
I'd guess this might be something lower-level than gems.  Could people please post their operating system name and version, glibc version (`ldd --version`), libmysqlclient version (`repoquery --whatprovides *libmysqlclient*`), etc?

**Comment by iRonin** [comment]
Updating to the most recent version of the gem fixed this and other `Errno::EBADF: Bad file descriptor` errors.
