### ISSUE TITLE
Mysql 5.7 support

### ISSUE THREAD

**Issue by ghost** [brianmario/mysql2#548]
5.7 has some nice improvements, it would be great to see support in mysql2.

**Comment by tomfuertes** [comment]
Quick bash rundown for those coming from SEO channel for ctrl+v `NameError: uninitialized constant Mysql2::Client::SECURE_CONNECTION`:

```bash
$ brew tap homebrew/versions
$ brew update
$ brew uninstall mysql mysql2
$ brew install mysql56 # 5.6 locked version
# copy in the launchctrl output
$ gem uninstall mysql mysql2 # uninstall legacy gems
$ bundle install # to install / rebuild new refs
```

**Comment by sodabrew** [comment]
@tomfuertes Your post is invalid. MySQL 5.7 is supported. Directing people to downgrade to MySQL 5.6 is not necessary.

**Comment by xwaynec** [comment]
MySQL 5.7.9 update the libmysqlclient from libmysqlclient.18.dylib to libmysqlclient.20.dylib

**Comment by sodabrew** [comment]
@xwaynec If the library version changed, then you simply need to rebuild your mysql2 gem.
