### ISSUE TITLE
order by issue

### ISSUE THREAD

**Issue by John222** [brianmario/mysql2#555]
Hi guys i have a issue that the order by is not working correctly. Her is the output of the rails error log:

<code>ActionView::Template::Error (Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'leave DESC' at line 1: SELECT `user_schools`.\* FROM `user_schools`  WHERE `user_schools`.`user_id` = 8  ORDER BY joined, leave DESC):</code>

The controller request is: <code>@user_schools = UserSchool.where(:user_id => current_user.id).order("joined, leave DESC")</code>

I think the problem is that the gem is not putting any quotes around "joined,  leave DESC". I'm using MaraDB as MySQL server.

**Comment by swobspace** [comment]
I'm running in the same issue. order("name DESC, position DESC") works for sqlite and postgresql, but not for mysql with mysql2 (0.3.17, rails 3.2.21, mysql-server 5.5.41-0ubuntu0.
