### ISSUE TITLE
Got wrong value while processing another query result

### ISSUE THREAD

**Issue by tape88** [brianmario/mysql2#560]
Using:
````
centos 6.5 x86_x64
ruby 1.8.7
sinatra 1.4.5
mysql2 0.3.16
unicorn 4.8.2
mysql 5.5
````

Description:
I have books and books categories:
1) 30 books per page eg. with 20 pages and query like: 

```` 
@query = "select * from books where category_id ='#{@category_id}' shelf_id = '#{@shelf_id}' limit #{@limit} offset #{@offset}"
@books = $client.query(@query)
````

2) 30 books categories with books counter and query looks like:
````
@query = "select * from categories"
@categories = $client.query(@query)

````
then do each method on categories and get counter like:
````
@categories_with_counter = @categories.each do |item|
  @query = "select count(*) as obj_cnt from books where category_id = #{item['id']} and is_active = 1"
  @count = $client.query(@query)
  item['books_count'] = @count.map { |c| c['obj_cnt'] }.first
  @count = nil
  item
end
````

In result, if I open eg. 20tabs from pager as fast as I can, periodically I can get category count value instead book record while processing books result.
(I dont use multi statements and async queries ).

Also with the same action I also periodically have all mysql errors ))

Most repeated errors:
````
Mysql2::Error - Lost connection to MySQL server during query
Mysql2::Error - MySQL server has gone away
````

Rarely repeated errors:
````
Mysql2::Error - Table 'project.books' doesn't exist
Mysql2::Error - closed MySQL connection
Mysql2::Error - Malformed packet
Mysql2::Error - Lost connection to MySQL server at 'waiting for initial communication packet
````

Tried to:
1) reinstall mysql
2) reinstall mysql2
3) old versions of mysql
4) configure mysql settings with params like
read_timeout, connect_timeout, max_allowed_packet, interactive_timeout
5) set read_timeout, connect_timeout, reconnect as true, to use socket instead ip connection in mysql2 config
6) use ruby 1.9.3 instead 1.8.7
7) update all gems to latest version

At now:
1) connection applied in sinatra app "configure" block and looks like:
````
$client = Mysql2::Client.new(:host => @host, :database => @db, :username => @username, :password => @password, :reconnect => true)
````

2) Mysql config looks like empty, log path and pid path are set.

3) I can connect to the MySQL server manually from the same machine, using the same credentials as in config. Connection is stable db is on local machine.

**Comment by ioquatix** [comment]
I am having this problem too, mostly when connecting over SSH:

e.g.

    Unexpected error while processing request: Mysql2::Error: Malformed packet: SELECT  `poi`.* FROM `poi`  WHERE (name LIKE '%Top 1%') LIMIT 50

Repeating the query over and over again, eventually it works.

**Comment by ioquatix** [comment]
Has this been fixed? Or not reproducible anymore?

**Comment by sodabrew** [comment]
I haven't been able to reproduce, and do think it was a threading issue - but happy to reopen if it persists in current versions of mysql2.
