### ISSUE TITLE
Mysql2::Error: This connection is still waiting for a result, try again once you have the result.

### ISSUE THREAD

**Issue by anhuiliujun** [brianmario/mysql2#566]
We run a damemon which is a cosumer of RabbitMQ。And we use a gem called sneakers，which is a multi-process, mulit-thread framework。
And our code is running in microsoft azure environment。
After some time， we got lots of these errors。
Excuse me, My English is not good。

**Comment by sodabrew** [comment]
I see Timeout.timeout in the backtrace. Turns out that is really bad practice. Resolved by #592.
