### ISSUE TITLE
Windows, 64 bit 2.1.5 ruby, segfault :(

### ISSUE THREAD

**Issue by betam4x** [brianmario/mysql2#567]
rails s
C:/Ruby21-x64/lib/ruby/gems/2.1.0/extensions/x64-mingw32/2.1.0/mysql2-0.3.17/mysql2/mysql2.so: [BUG] Segmentation fault

(using mysql connector 6.1.5)

ruby 2.1.5p273 (2014-11-13 revision 48405) [x64-mingw32]

-- Control frame information -----------------------------------------------
c:0020 p:-11705814 s:0067 e:000066 TOP    [FINISH]
c:0019 p:---- s:0065 e:000064 CFUNC  :require
c:0018 p:0083 s:0061 e:000060 TOP    C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/mysql2-0.3.17/lib/mysql2.rb:8 [FINISH]
...
(long stack trace)

Any idea how to resolve this?

**Comment by sodabrew** [comment]
I've updated the PR at #473, please give it a spin.

**Comment by wpp** [comment]
I get a similar stacktrace on OS X (10.10.1).

>/Users/pw/.gem/ruby/2.2.0/bundler/gems/mysql2-068b4697c841/lib/mysql2/mysql2.bundle: [BUG] Segmentation fault at 0x00000000000418
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]

>-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/CrashReporter
     * /Library/Logs/CrashReporter
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   for more details.

>-- Control frame information -----------------------------------------------
c:0027 p:-17551710769610 s:0093 e:000092 TOP    [FINISH]
c:0026 p:---- s:0091 e:000090 CFUNC  :require
c:0025 p:0248 s:0087 e:000086 TOP    /Users/pw/.gem/ruby/2.2.0/bundler/gems/mysql2-068b4697c841/lib/mysql2.rb:28 [FINISH]
c:0024 p:---- s:0084 e:000083 CFUNC  :require
c:0023 p:0037 s:0080 e:000079 BLOCK  /Users/pw/.gem/ruby/2.2.0/gems/bundler-1.7.11/lib/bundler/runtime.rb:76 [FINISH]
c:0022 p:---- s:0077 e:000076 CFUNC  :each

**Comment by sodabrew** [comment]
#473 is merged! Closing as resolved.
