### ISSUE TITLE
SOCKS proxy incompatibility introduced in 0.3.16

### ISSUE THREAD

**Issue by timrwilliams** [brianmario/mysql2#571]
I'm using a SOCKS5 proxy to connect to a MySQL database from Rails via mysql2. Rails apps (and any other Ruby application) can automatically route all their outbound TCP traffic through the SOCKS proxy using a script based on the Dante client (https://www.inet.no/dante/doc/1.4.x/config/client.html) 

e.g. socksify rails c  

Version 0.3.16 has broken this with MySQL. The behaviour we see now is mysql2 rapidly trying to open connections with the MySQL server but failing, after a short period of time the MySQL host blocks the IP address and no further connections are possible. 

I have verified this functionality is still broken in 0.3.17. I'm happy to look in to this further but a lot of varied commits went in to 0.3.16 so would appreciate any pointers as to what change might have affected this.

I have a test MySQL database, rails app and proxy connection available to reproduce if anybody is able to look at this.

**Comment by simi** [comment]
`0.3.15` works?

**Comment by timrwilliams** [comment]
Yes. 0.3.15 and earlier work.

**Comment by sodabrew** [comment]
Interesting. If you can write a minimum reproduction case (i.e. not requiring all of rails loaded, just mysql2 directly) a `git bisect` can help narrow down the commit(s) that introduced this change.

**Comment by timrwilliams** [comment]
Created a reproduceable test here: https://github.com/timrwilliams/socks-mysql2-debug

You can use the hardcoded connection parameters, I've spun up a test MySQL instance and SOCKS server for this debugging only.

This test is only reproduceable on Linux as the socksify wrapper script does not support Windows or OSX.  

When it fails it fails quite aggressively, hammering the MySQL server with 5-10 connection attempts per second. I've set the max_connect_errors to max so you should be able to test without issue but let me know if you get blocked.

Let me know how I can assist.

**Comment by sodabrew** [comment]
Awesome! I may have some time this weekend to run a bisect and dig into it.

**Comment by timrwilliams** [comment]
Hi Aaron, have you had a chance to look at this? No pressure I just have a dedicated server and database running for debugging this issue which I don't want to be around indefinitely.

Cheers.

**Comment by sodabrew** [comment]
I bisected, and found the last good revision was 58f3f3ac5a6ca8ef09b3092a996f4d1e2c257cb8
and the first bad revision is 53591ca9ccaf1ad344016862f0d88d4753f6dc32
which both came from PR #505.

**Comment by timrwilliams** [comment]
Great find, that explanation makes sense. I don't think its realistic to drill down to either underlying library so the workaround is a good solution.

For others future reference you can nil this out in rails with the following database.yml config
    
    common: &common
      adapter: mysql2
      connect_timeout:

I'll close the issue and shut down the test servers (micro to the rescue!).

Thanks again.
