### ISSUE TITLE
ActiveRecord::StatementInvalid: Mysql2::Error: No database selected: SHOW TABLES LIKE 'schema_migrations'

### ISSUE THREAD

**Issue by solars** [brianmario/mysql2#575]
Hi,

If I do rake db:migrate in rails, I get:
ActiveRecord::StatementInvalid: Mysql2::Error: No database selected: SHOW TABLES LIKE 'schema_migrations'

I cannot really find anything useful about this error, can anyone tell me what this means?

**Comment by zsandin** [comment]
How did you resolve this?
