### ISSUE TITLE
Mysql2::EM::Client.new is blocking

### ISSUE THREAD

**Issue by troelskn** [brianmario/mysql2#582]
When using Mysql2 in an EM based app, the actual connection (e.g. creating a new instance of `Mysql2::EM::Client`) happens to block. This in turn blocks the entire application. I'm not sure if it's in any way feasible to do anything about, but it's a serious problem for these kind of apps.

**Comment by sodabrew** [comment]
What I learned from #571 and #505 is that if you pass a value for `:connect_timeout`, then it will make a non-blocking connect. This became the default since 0.3.16. Please try this, see if it helps?

**Comment by sodabrew** [comment]
Closing for lack of updates.
