### ISSUE TITLE
undefined method chars for ["P"]:Array - mysql2 0.3.18, Win7 x64, x64_mingw32

### ISSUE THREAD

**Issue by ABaumgaertner** [brianmario/mysql2#584]
simple test fails: mysql.rb 
gem install mysql2 --> mysql2-0.3.18-x64-mingw32

    more mysql.rb
    require 'mysql2'

    ruby mysql.rb
    C:/apps/redmine_dev/ruby/lib/ruby/2.2.0/Win32API.rb:18:in `initialize': undefined method `chars' for ["P"]:Array (NoMethodError)
        from C:/apps/redmine_dev/ruby/lib/ruby/gems/2.2.0/gems/mysql2-0.3.18-x64-mingw32/lib/mysql2.rb:23:in `new'
        from C:/apps/redmine_dev/ruby/lib/ruby/gems/2.2.0/gems/mysql2-0.3.18-x64-mingw32/lib/mysql2.rb:23:in `<top (required)>'
        from C:/apps/redmine_dev/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from C:/apps/redmine_dev/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from C:/apps/redmine_dev/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from mysql.rb:1:in `<main>'

    RubyGems Environment:
      - RUBYGEMS VERSION: 2.4.5
      - RUBY VERSION: 2.2.0 (2015-02-20 patchlevel 69) [x64-mingw32]
      - INSTALLATION DIRECTORY: C:/apps/redmine_dev/ruby/lib/ruby/gems/2.2.0
      - RUBY EXECUTABLE: C:/apps/redmine_dev/ruby/bin/ruby.exe
      - EXECUTABLE DIRECTORY: C:/apps/redmine_dev/ruby/bin
      - SPEC CACHE DIRECTORY: C:/Users/abaumgaertner/.gem/specs
      - SYSTEM CONFIGURATION DIRECTORY: C:/ProgramData
      - RUBYGEMS PLATFORMS:
        - ruby
        - x64-mingw32
      - GEM PATHS:
         - C:/apps/redmine_dev/ruby/lib/ruby/gems/2.2.0
         - C:/Users/abaumgaertner/.gem/ruby/2.2.0
      - GEM CONFIGURATION:
         - :update_sources => true
         - :verbose => true
         - :backtrace => false
         - :bulk_threshold => 1000
      - REMOTE SOURCES:
         - https://rubygems.org/
      - SHELL PATH:
         - C:\apps\redmine_dev\ruby\bin
         - C:\apps\redmine_dev\libs
         - C:\apps\redmine_dev\ImageMagick
         - D:\apps\mercurial_dev
         - d:\msys64\mingw64\bin
         - d:\msys64\mingw64\lib
         - d:\msys64\usr\bin
         - C:\Windows\system32
         - C:\Windows
         - C:\Windows\System32\Wbem
         - C:\Windows\System32\WindowsPowerShell\v1.0\

**Comment by sodabrew** [comment]
This is not tested with ruby 2.2 on windows as of yet. PR welcomed to address the issue.

**Comment by sodabrew** [comment]
Please let me know if the patch in #585 fixes this for you. I wasn't planning on a 0.3.19 release – I would recommend you to use Ruby 2.1.5 for now. Among other things, I do not have CI for Ruby 2.2 on Windows until RubyInstaller posts a Ruby 2.2 build, and then AppVeyor should pick it up a few weeks after that.

**Comment by sodabrew** [comment]
Found the smoking gun:
https://github.com/ruby/ruby/commit/2e5610353fd3c0067e2528763a53c2a635067f02

I will send a patch for Ruby 2.2.1. I can work around the problem in #585, but if you look at that method you'll see it is now self-inconsistent. The first line works with Array or String then four lines later assumes String.

**Comment by ABaumgaertner** [comment]
great - I'll keep an eye on https://bugs.ruby-lang.org/issues/10876 and retest once the patch is in.

**Comment by ABaumgaertner** [comment]
just recompiled todays ruby_2_2 branch and applied your patch to ext/win32/lib/Win32API.rb

    ruby mysql.rb
    C:/apps/redmine_dev/ruby/lib/ruby/2.2.0/Win32API.rb:16:in `initialize': no implicit conversion of String into Integer (TypeError)
        from C:/apps/redmine_dev/ruby/lib/ruby/2.2.0/Win32API.rb:16:in `new'
        from C:/apps/redmine_dev/ruby/lib/ruby/2.2.0/Win32API.rb:16:in `initialize'
        from C:/apps/redmine_dev/ruby/lib/ruby/gems/2.2.0/gems/mysql2-0.3.18-x64-mingw32/lib/mysql2.rb:23:in `new'
        from C:/apps/redmine_dev/ruby/lib/ruby/gems/2.2.0/gems/mysql2-0.3.18-x64-mingw32/lib/mysql2.rb:23:in `<top (required)>'
        from C:/apps/redmine_dev/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from C:/apps/redmine_dev/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from C:/apps/redmine_dev/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from mysql.rb:1:in `<main>'

**Comment by sodabrew** [comment]
I don't think that's my bug anymore. I'll compile up a Ruby 2.2.0 and see what's going on hands-on.

**Comment by sodabrew** [comment]
The upstream fix has landed on ruby-trunk, waiting for a backport to ruby_2_2 branch. It's a different patch than I offered, and unit tests were added :) I hope it will make it in for Ruby 2.2.1.

Please try the one-line change to your Win32API.rb in https://github.com/ruby/ruby/commit/dad59fcd12229edc05d8655f7895b8957c5dd114

**Comment by ABaumgaertner** [comment]
I compiled the latest ruby 2.2.1 version - fix is included. 
gem install mysql2
require 
a new error pops up ...
the directory c:\apps\redmine_dev\ruby2.2.1p85rev49672-2015-02-26\lib\ruby\gems\2.2.0\gems\mysql2-0.3.18-x64-mingw32\lib\mysql2\2.2 is in fact missing
2.0 and 2.1 exists.

    C:/apps/redmine_dev/ruby2.2.1p85rev49672-2015-02-26/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- mysql2/2.2/mysql2 (LoadError)
        from C:/apps/redmine_dev/ruby2.2.1p85rev49672-2015-02-26/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/apps/redmine_dev/ruby2.2.1p85rev49672-2015-02-26/lib/ruby/gems/2.2.0/gems/mysql2-0.3.18-x64-mingw32/lib/mysql2/mysql2.rb:2:in `<top (required)>'
        from C:/apps/redmine_dev/ruby2.2.1p85rev49672-2015-02-26/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/apps/redmine_dev/ruby2.2.1p85rev49672-2015-02-26/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/apps/redmine_dev/ruby2.2.1p85rev49672-2015-02-26/lib/ruby/gems/2.2.0/gems/mysql2-0.3.18-x64-mingw32/lib/mysql2.rb:31:in `<top (required)>'
        from C:/apps/redmine_dev/ruby2.2.1p85rev49672-2015-02-26/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from C:/apps/redmine_dev/ruby2.2.1p85rev49672-2015-02-26/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from C:/apps/redmine_dev/ruby2.2.1p85rev49672-2015-02-26/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'

Then I recompiled the mysql2 with my devkit - this works fine.
require tests succeeds

**Comment by sodabrew** [comment]
No problem, thank you! Correcting an upstream bug is always worth the effort.

I'll begin publishing a Ruby 2.2 binary in the next mysql2 gem version after Ruby 2.2.1 is out.

**Comment by sodabrew** [comment]
Followup - Today Ruby 2.2.1 was released and the Win32API fix made it into the release!
https://www.ruby-lang.org/en/news/2015/03/03/ruby-2-2-1-released/
