### ISSUE TITLE
Mysql2::Error: This connection is in use by: #<Thread:0x00000006907620 sleep>

### ISSUE THREAD

**Issue by onebree** [brianmario/mysql2#587]
**[UPDATE]** I downgraded back to RSpec 2.13.0, database_cleaner 1.2.0, AND removed Spring, and the issue is still happening. Like @sodabrew, I think it is related to `database_cleaner` gem.

------
**Rails 4.2.0, RSpec 3.1, Ruby 1.9.3**
**mysql2 0.3.17, database_cleaner 1.4.0**

The following is a snippet of our `spec_helper.rb` file _before_ the issue began.
```ruby
# Rails 4.2.0
# RSpec 2.13

Spork.each_run do
  class ActiveRecord::Base
    mattr_accessor :shared_connection
    @@shared_connection = nil 
    def self.connection
      @@shared_connection || ConnectionPool::Wrapper.new(:size => 1) { retrieve_connection }
    end 
end 
ActiveRecord::Base.shared_connection = ActiveRecord::Base.connection 	
User.acts_as_authentic { | c | c.maintain_sessions = false }
```

**THIS WEEK** we dropped Spork and are now going with the Spring gem. I omitted the `Spork.each_run` block from the helper files.
```
Failures:
  1) Exercise Ast Queues Page SAD PATHS add non-unique member
     Failure/Error: @ast_queue = create(:ast_queue, tenant: @tenant)
     ActiveRecord::StatementInvalid:
       Mysql2::Error: This connection is in use by: #<Thread:0x00000006907620 sleep>: SHOW FULL FIELDS FROM `sips`
     # ./spec/factories.rb:55:in `block (3 levels) in <top (required)>'
     # ./spec/factories.rb:264:in `block (3 levels) in <top (required)>'
     # ./spec/features/admin/ast_queues_spec.rb:9:in `block (2 levels) in <top (required)>'
     # -e:1:in `<main>'
```

I have tried to research this error message, but am only finding questions about Sidekiq. I did see a similar issue (#379), but I did not see any clear solution, especially to the monkey patch.

**Comment by sodabrew** [comment]
I'm not sure where the concurrent connections would be coming from (Rspec 3.1 doesn't do mult-threaded tests AFAIK), but it is important that the database connection pooling / sharing strategy does not re-use the same connection in multiple threads.

Maybe database_cleaner is doing something wonky? I'm not familiar with it. The README doesn't show anything obviously problematic though: https://github.com/DatabaseCleaner/database_cleaner

**Comment by onebree** [comment]
I have not read up much on `database_cleaner`. I tried a solution someone online came up with (DatabaseCleaner method calls) but it cleared my entire test database. That's an issue because we have a `test_seed.rb` file which fills the database with a test admin, tenant, etc -- so that these do not need to be created in every spec. Using those calls removed these values.

After each scenario runs, the database clears all data except for that seeded. Is that due to `database_cleaner`, or some other mechanism?

**Comment by sodabrew** [comment]
Yes I think `database_cleaner` is removing the records that were added by each test. If it's doing that in a separate thread, it would explain the error. I don't know if that is actually what it is doing, but that is my hunch of where to investigate.

**Comment by onebree** [comment]
Thank you for the help! I will read more about `database_cleaner` and try to contact a contributor for help, before submitting an issue. I would prefer to set the gem up as explained in the README, but, as I mentioned, doing such cleans out the test seed generated from a rake task.

**Comment by onebree** [comment]
@sodabrew I updated my original post. I downgraded back to RSpec 2.13.0, and I am having the same issue with threading.

**Comment by onebree** [comment]
@sodabrew Hi there. I removed the database_cleaner gem completely, and have had much fewer instances of the above error happening. When it does happen, I am writing a `4.times` statement in Ruby, followed by reloading the page (in the spec). The error appears in my log again.

It seems like if I place a lot of `Rails.logger.info` statements, I can "buffer" the time between threads, which delays the test itself. I found the exact line in the gem's code which triggers the error, and I would like to know how to all multiple threads to run (if possible) -- OR to somehow increase the time one thread is allowed to be open for, before switching to a new one.

**Comment by onebree** [comment]
@sodabrew Hi there. I removed the database_cleaner gem completely, and have had much fewer instances of the above error happening.

**Comment by onebree** [comment]
@sodabrew When it does happen, I am writing a `4.times` statement in Ruby, followed by reloading the page (in the spec). The error appears in my log again.

It seems like if I place a lot of `Rails.logger.info` statements, I can "buffer" the time between threads, which delays the test itself. I found the exact line in the gem's code which triggers the error, and I would like to know how to all multiple threads to run (if possible) -- OR to somehow increase the time one thread is allowed to be open for, before switching to a new one.

**Comment by sodabrew** [comment]
|  I found the exact line in the gem's code which triggers the error
Where is it occurring?

**Comment by onebree** [comment]
Sorry for not putting that! I am that familiar with C code, so I am putting (what I see as) the most relevant code block.

```c
/* /usr/local/lib/ruby/gems/1.9.1/gems/mysql2-0.3.18/ext/mysql2/client.c */
/* Line 676 */

  if (NIL_P(wrapper->active_thread)) {
    /* mark this connection active */
    wrapper->active_thread = thread_current;
  } else if (wrapper->active_thread == thread_current) {
    rb_raise(cMysql2Error, "This connection is still waiting for a result, try again once you have the result");
  } else {
    VALUE inspect = rb_inspect(wrapper->active_thread);
    const char *thr = StringValueCStr(inspect);

    rb_raise(cMysql2Error, "This connection is in use by: %s", thr);
    RB_GC_GUARD(inspect);
  }
```

**Comment by sodabrew** [comment]
Oh, yes that's the part where it warns about two threads trying to use the same connection. Now that I think about it, if you can post a backtrace from that exception it may point to the caller who crossed threads:

ruby
```
begin
  top level database action
rescue => e
  puts e.backtrace
  raise e # re-raise to avoid losing the error
end
```

**Comment by onebree** [comment]
I am not sure how much of it you want... Here is the starting chunk of it. Let me know if you need the rest.

```log
Mysql2::Error: This connection is in use by: #<Thread:0x000000026a2ff0 sleep>: SELECT  `users`.* FROM `users` WHERE `users`.`id` = 1 LIMIT 1
HUNTER DEBUG: Mysql2::Error
This connection is in use by: #<Thread:0x000000026a2ff0 sleep>
/usr/local/lib/ruby/gems/1.9.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `query'
/usr/local/lib/ruby/gems/1.9.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `block in execute'
/usr/local/lib/ruby/gems/1.9.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `block in log'
/usr/local/lib/ruby/gems/1.9.1/gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/lib/ruby/gems/1.9.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:460:in `log'
/usr/local/lib/ruby/gems/1.9.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `execute'
/usr/local/lib/ruby/gems/1.9.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/mysql2_adapter.rb:231:in `execute'
/usr/local/lib/ruby/gems/1.9.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/mysql2_adapter.rb:235:in `exec_query'
/usr/local/lib/ruby/gems/1.9.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:336:in `select'
/usr/local/lib/ruby/gems/1.9.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
/usr/local/lib/ruby/gems/1.9.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/query_cache.rb:68:in `block in select_all'
/usr/local/lib/ruby/gems/1.9.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/query_cache.rb:83:in `cache_sql'
/usr/local/lib/ruby/gems/1.9.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/query_cache.rb:68:in `select_all'
```

**Comment by sodabrew** [comment]
Further back, somewhere near the beginning is where the choice of connection id is being made.

**Comment by onebree** [comment]
Here is a gist of the rest of the backtrace... If you need the mysql table lookups, let me know:
https://gist.github.com/onebree/6b1356ee8b85efe7fa14

**Comment by onebree** [comment]
Hello. Since opening this issue, we found that modifying ActiveRecord's source code helped. In place of [L298-300](https://github.com/rails/rails/blob/v4.2.0/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb#L298-L300)

```ruby
# Original
def execute(sql, name = nil)
  log(sql, name) { @connection.query(sql) }
end

# Monkey-patch
SEMAPHORE = Mutex.new
def execute(sql, name = nil)
  begin
    raise 'Debugging'
  rescue => e
    SEMAPHORE.synchronize { log(sql, name) { @connection.query(sql) } }
  end
end
```

I know it's been many months later, but I just remembered I opened this issue. At least the issue is not with mysql2, but rather just ActiveRecord (somehow)

**Comment by sodabrew** [comment]
Thanks for the follow-up! Are you still using AR 4.2.0, or a newer AR? Have you filed a bug with AR to link back this one?

**Comment by onebree** [comment]
Yes, we are still using 4.2.0, and I have not filed a bug. I am not sure if it is a bug, or just our environment. I will submit one today though, and link to this issue for reference

**Comment by onebree** [comment]
Referenced in https://github.com/rails/rails/issues/21734
