### ISSUE TITLE
Inserting "nil" to a INT column produces 0 instead of NULL

### ISSUE THREAD

**Issue by peteygao** [brianmario/mysql2#588]
My code is as simple as can be:
```ruby
value = mysql_db.escape(params[:value])

if params[:counter].nil?
  counter = nil
else
  counter = mysql_db.escape(params[:counter])
end

mysql_db.query("INSERT INTO my_table (value, counter) VALUES (#{value}, #{counter})")
```

Then if I go into mysql and query:
```sql
SELECT * FROM my_table ORDER BY id DESC LIMIT 1;
```
I'll see something like:
```
+----+-----------+----------+
| id |   value   |  counter |
+----+-----------+----------+
|  3 |   hello   |        0 |
+----+-----------+----------+
```

My intention here is for `counter` to be `NULL` and not `0`. Is this not how I should be using `.escape` or `nil` when using mysql2?

**Comment by sodabrew** [comment]
Try this instead:
```
mysql_db.query("INSERT INTO my_table (value, counter) VALUES (#{value.nil? : 'NULL" : value}, #{counter})")
```

**Comment by peteygao** [comment]
Thanks, that does work... Interesting behaviour, but it makes sense. Is there any reason why Mysql2::Client#escape will only handle Strings? It makes for very clunky escaping logic...

**Comment by sodabrew** [comment]
`Mysql2::Client#escape` is a wrapper around `mysql_real_escape_string` http://dev.mysql.com/doc/refman/5.0/en/mysql-real-escape-string.html which only consumes a string. We'd have to write a bunch more logic to handle the Ruby type conversions to MySQL equivalents for things that cannot be coerced to strings. It's a reasonable request.

**Comment by peteygao** [comment]
Hi @sodabrew, does closing this ticket mean this won't be addressed in the near future? Thanks!
