### ISSUE TITLE
Compiling native mysql2 gem

### ISSUE THREAD

**Issue by aboutte** [brianmario/mysql2#590]
I would really like to use the mysql2 gem for a project I am working on but do not have the tools needed in my production environment to compile the native extensions.  I found this article:

http://stackoverflow.com/questions/3667918/how-do-you-precompile-the-native-extensions-for-a-ruby-gem-for-linux

and was hoping to use that procedure to build the gem in my non production environment and then I could take care of installing that gem in production.  

When going through that procedure I do end up with a gem but it does not seem to have all the required pieces.  

The specific steps I am taking are:

* yum install ruby-devel mysql-devel
* yum groupinstall "Development Tools"
* I download the source for the 0.3.18 tag: https://github.com/brianmario/mysql2/archive/0.3.18.zip
* unzip -d mysql2 mysql2-0.3.18.zip
* cd mysql2/mysql2-0.3.18
* rake native gem

I end up with a pkg directory with the following:

```
pkg
├── mysql2-0.3.18-x86_64-linux
│   ├── ext
│   │   └── mysql2
│   │       └── extconf.rb
│   └── lib
│       └── mysql2
│           └── mysql2.so
└── mysql2-0.3.18-x86_64-linux.gem

5 directories, 3 files
```

I can then install the local gem but when I try and use it I get an error:

```
[root@dvp-us-west-2a-10-129-128-60 pkg]# ll
total 72
drwxr-xr-x 4 root root  4096 Mar  6 06:12 mysql2-0.3.18-x86_64-linux
-rw-r--r-- 1 root root 68608 Mar  6 06:12 mysql2-0.3.18-x86_64-linux.gem
[root@dvp-us-west-2a-10-129-128-60 pkg]# gem install mysql2
Successfully installed mysql2-0.3.18-x86_64-linux
Parsing documentation for mysql2-0.3.18-x86_64-linux
Installing ri documentation for mysql2-0.3.18-x86_64-linux
Done installing documentation for mysql2 after 0 seconds
1 gem installed
[root@dvp-us-west-2a-10-129-128-60 pkg]# gem list

*** LOCAL GEMS ***

bigdecimal (1.2.0)
json (1.8.1)
mysql2 (0.3.18 x86_64-linux)
psych (2.0.0)
rake (10.4.2)
rake-compiler (0.9.5)
rdoc (4.1.0)
[root@dvp-us-west-2a-10-129-128-60 pkg]# irb
irb(main):001:0> require 'mysql2'
LoadError: cannot load such file -- mysql2
	from /usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from (irb):1
	from /usr/bin/irb:12:in `<main>'
irb(main):002:0>
```

I know this is really out side the scope of mysql2 but I am hoping somebody already has a solution to this issue for mysql2.  I am using EC2 for production and non production servers using the latest Amazon Linux AMI.

**Comment by sodabrew** [comment]
Do you have `libmysqlclient.so` on your production machine?

**Comment by aboutte** [comment]
Yes I do.  Not sure how I can determine if that is within Rubys path.

```
[root@fraudcartcyber-dev-us-west-2a-10-131-14-5 pkg]# find / -iname libmysqlclient.so*
/usr/lib64/mysql/libmysqlclient.so.18
/usr/lib64/mysql/libmysqlclient.so
/usr/lib64/mysql/libmysqlclient.so.18.0.0
```

**Comment by sodabrew** [comment]
There are two ways that mysql2.so may find its libmysqlclient.so - by rpath (in the mysql2.so binary) or by ld.so.conf (system paths). If you run `ldd mysql2.so` it will print out the paths for each library dependency.

**Comment by sodabrew** [comment]
If you do find that the output from `ldd mysql2.so` points to a path in your build system, there are options to change or disable the compile-time rpath: https://github.com/brianmario/mysql2#configuration-options

**Comment by aboutte** [comment]
Thanks for all your help sodabrew!  I ended up getting this to work.  The only things I can see that I changed is that I installed the rspec gem and I stopped downloading the latest tag zip and started doing a git clone and checking out the latest tag.  

For anyone that stumbles across this the steps I took were:

* yum groupinstall "Development tools"
* yum install ruby-devel
* yum install mysql
* /opt/chef/embedded/bin/gem install rake-compiler
* /opt/chef/embedded/bin/gem install rspec
* cd ~/
* git clone git@github.com:brianmario/mysql2.git
* cd mysql2
* git tag
* git checkout 0.3.18
* /opt/chef/embedded/bin/rake native gem

Is there anyway I can submit this compiled gem to rubygems.org so I and others can install it without compiling?

**Comment by sodabrew** [comment]
There's quite a bit more to it - each Ruby major needs its own build because the APIs have changed, and there are a lot of variations on the compiler and compiler options that may impact binary compatibility. Further, the MySQL client libraries can vary, too, and where those libraries are located on the system can vary widely. Take a look at the rpath code in ext/mysql2/extconf.rb, and at tasks/compile.rake for the Windows build for a sense of scope on the variety of builds that would be needed.

If a user has separate build and deploy environments, I would certainly not expect them to also pull directly from an external binary source into the deploy environment. So the build step is where this site-specific compile would occur. A site may choose to build binary gems to distribute or to build the gem and package it as a .deb or .rpm or other packaging tool. At my site, we generally build an entire Rails application and all of its gems with Bundler and distribute the entire thing as a tarball to our production servers.

If there are any README updates you think will help the next person, suggestions are welcome!

**Comment by chendrix** [comment]
Does the mysql2 gem always require a versioned libmysqlclient.so?

**Comment by sodabrew** [comment]
Having libmysqlclient.so available to the linker is sufficient. The OP never posted the output from `ldd mysql2.so`, so I don't know if the problem I suspected–that his mysql2.so was pointed at a missing or invalid path to libmysqlclient.so–was actually the problem.
