### ISSUE TITLE
Specify Engine in database.yml

### ISSUE THREAD

**Issue by skillachie** [brianmario/mysql2#602]
Hi mysql2 team,

Thank you for the great work. Is it possible currently to override the default engine being used by specifying the engine to be used in the database.yml file ?

The default is currently ENGINE=InnoDB  however myself and others might want to have the flexibility to specify the engine to be used example ENGINE=ndbcluster

**Comment by brianmario** [comment]
You should be able to specify an initial command in `database.yml` which will configure the default storage engine used for those connections.

Something like this:

``` yml
production:
  init_command: "SET default_storage_engine=MYISAM"
```

**Comment by skillachie** [comment]
Hi Brian,

Thanks for the prompt reply.  This does not appear to override the engine being used for me when the tables are being created. However I will take a further look at your suggestion

**Comment by brianmario** [comment]
I was found that in their [documentation](http://dev.mysql.com/doc/refman/5.5/en/storage-engine-setting.html) for setting the storage engine. Maybe take a look at that and see if there's another way that could work?

**Comment by skillachie** [comment]
Brian,

Thanks again. Was not able to get it resolved  without overriding the create_table(method) similar to what another user suggested.

```
ActiveRecord::ConnectionAdapters::Mysql2Adapter
class ActiveRecord::ConnectionAdapters::Mysql2Adapter
  def create_table(table_name, options = {})
    super(table_name, options.reverse_merge(:options => "ENGINE=NDB"))
  end
end
```

**Comment by brianmario** [comment]
Oooh this is an ActiveRecord "bug" then. Maybe try opening an issue over at
https://github.com/rails/rails?
