### ISSUE TITLE
 Mysql2::Error: Timeout waiting for a response from the last query. (waited 1 seconds):

### ISSUE THREAD

**Issue by jamesfebin** [brianmario/mysql2#609]
I am using the mysql2 0.3.18. My app runs on rails 4.  I get the following error .  Mysql2::Error: Timeout waiting for a response from the last query. (waited 1 seconds).
Occasionally for simple select queries.

**Comment by fjyaniez** [comment]
Hi @jamesfebin, we are having similar problems in our app also with mysql 0.3.18 and Rails 4 when the queries seemed to stuck for too long and we added the `read_timeout` param to our `database.yml` file. Did you find anything new?

**Comment by asurancetturix** [comment]
Hello @jamesfebin and @fjyaniez, we are having also this issue. Our application is deployed on heroku server and using clearDB. We will be moving to a new DB server with more control to try to fix this issue.

**Comment by sodabrew** [comment]
Unfortunately I don't have any further insight than you all do; your help debugging and reporting your findings back to this thread will be extremely helpful.

**Comment by fjyaniez** [comment]
Well, in our case it seems MySQL or firewall are closing the connections for being idle, so when one of this connections is picked from the connection pool to being used by a thread, we get this error.

**Comment by salimane** [comment]
> Well, in our case it seems MySQL or firewall are closing the connections for being idle, so when one of this connections is picked from the connection pool to being used by a thread, we get this error.

@fjyaniez do you remember how you fixed the problem ultimately ?

**Comment by fjyaniez** [comment]
Hi @salimane, I didn't...

**Comment by salimane** [comment]
oh, i was hoping for a solution to this problem :(
