### ISSUE TITLE
Calling count on a newly initalized result object causes segfault

### ISSUE THREAD

**Issue by davidgibbons** [brianmario/mysql2#610]
Tested on ruby 1.8.7 and 2.2.0
With mysql2 gem version 0.3.18

Stumbled across this when trying to build up some unit tests.

irb(main):001:0> require 'rubygems'
=> true
irb(main):002:0> require 'mysql2'
=> true
irb(main):003:0> a = Mysql2::Result.new
=> #<Mysql2::Result:0x7f96e31e63c0>
irb(main):004:0> a.count
(irb):4: [BUG] Segmentation fault

**Comment by sodabrew** [comment]
Neat! This wouldn't happen during normal usage, but it's not nice behavior anyhow.

**Comment by sodabrew** [comment]
Resolved by #630
