### ISSUE TITLE
UPDATE queries

### ISSUE THREAD

**Issue by Oreolek** [brianmario/mysql2#613]
How to do UPDATE and DELETE queries using Mysql2? Or do I need Mysql for that? The ″documentation" completely misses this.

**Comment by simi** [comment]
just like any query mentioned in https://github.com/brianmario/mysql2#usage

```ruby
results = client.query("SELECT * FROM users WHERE group='githubbers'")
results = client.query("DELETE FROM users")
results = client.query("UPDATE users SET ...")
```
