### ISSUE TITLE
Duplicated Fractional Seconds on timestamp updates

### ISSUE THREAD

**Issue by tjchambers** [brianmario/mysql2#615]
I am seeing duplicated fractional seconds in the SQL time values posted to the MYSQL database running MySQL 5.6.17. I am running Rails 4.2.1, Ruby 2.2.0 with mysql2 gem (0.3.17 or 0.3.18 - same behavior). Here is an example of what I see on an update:

```
x = Person.last
x.title = 'a title2'
x.save!
```

Results in Rails console:

```
Loading test environment (Rails 4.2.1)
irb: warn: can't alias context from irb_context.
2.2.0 :001 > x = Person.last
  Person Load (12.2ms)  SELECT  `persons`.* FROM `persons` WHERE `persons`.`active` = 1 AND (
      exists(select 1 from collectives c, tenants t
      where c.active
        and t.active
        and persons.tenant_id = t.org_id
        and c.id = persons.tenant_id))  ORDER BY `persons`.`name` DESC, `persons`.`id` DESC LIMIT 1
    1 row, 293 Bytes

 => #<Person id: 96019, name: "yy yy", source: "spbackground@schellingpoint.com", email: nil, username: nil, notes: nil, updated_at: "2015-04-30 15:04:13.671129", title: "a title", keyword: nil, master: false, tenant_id: 3608, active: true, phone: nil, eusage: "", ehash: nil, pref_lang: "en", dnc: false, hard_bounces: 0, soft_bounces: 0, spapikey: nil, permalink: "96019-102b99fd-a415b0", created_at: "2015-01-10 19:14:15.962732", community_id: nil, profile: nil>
2.2.0 :002 > x.title = 'a title2'
 => "a title2"
2.2.0 :003 > x.save!
   (0.2ms)  BEGIN
  User Load (0.5ms)  SELECT  `users`.* FROM `users` WHERE `users`.`email` = 'spbackground@schellingpoint.com' LIMIT 1
    1 row, 386 Bytes

  SQL (0.8ms)  UPDATE `persons` SET `title` = 'a title2', `updated_at` = '2015-04-30 15:32:27.363016.363016' WHERE `persons`.`id` = 96019
```

Note the timestamp in the last line has the fractional seconds TWICE. **2015-04-30 15:32:27.363016.363016**

I really do not know whether this is a rails issue or a mysql2 gem issue, but I infer it is the gem formatting the timestamp SQL. 

My database column definition for timestamp field updated_at is:

```
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
```

While this does not appear to harm anything (I believe the correct timestamp is recorded), the SQL generated is incorrect IMHO.

**Comment by tjchambers** [comment]
BTW - I did not see any specs in this gem for testing fractional seconds in time fields. I may have missed them, but a quick search did not show any.

**Comment by sodabrew** [comment]
The gem is not formatting the timestamp SQL. What version of Rails are you using?

**Comment by tjchambers** [comment]
I am using Rails 4.2.1. I looked at Rails on Github, but was unable to locate the formatting. I will look again. Thanks.
