### ISSUE TITLE
Table name with .

### ISSUE THREAD

**Issue by manoelneto** [brianmario/mysql2#616]
Fbmpost.table_name = "post_gtvdrumshotmail_baby.com"
=> "post_gtvdrumshotmail_baby.com"
irb(main):035:0> Fbmpost.count
Mysql2::Error: Table 'post_gtvdrumshotmail_baby.com' doesn't exist: SHOW FULL FIELDS FROM \`post_gtvdrumshotmail_baby\`.\`com\`
ActiveRecord::StatementInvalid: Mysql2::Error: Table 'post_gtvdrumshotmail_baby.com' doesn't exist: SHOW FULL FIELDS FROM \`post_gtvdrumshotmail_baby\`.\`com\`
  from /app/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in \`query'
  from /app/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in \`block in execute'
  from /app/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract_adapter.rb:280:in \`block in log'
  from /app/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.14/lib/active_support/notifications/instrumenter.rb:20:in \`instrument'
  from /app/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract_adapter.rb:275:in \`log'
  from /app/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in \`execute'
  from /app/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.14/lib/active_record/connection_adapters/mysql2_adapter.rb:213:in \`execute'
  from /app/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:259:in \`execute_and_free'
  from /app/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.14/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:426:in \`columns'
  from /app/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.14/lib/active_record/connection_adapters/schema_cache.rb:12:in \`block in initialize'
  from /app/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.14/lib/active_record/model_schema.rb:229:in \`yield'
  from /app/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.14/lib/active_record/model_schema.rb:229:in \`columns'
  from /app/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.14/lib/active_record/model_schema.rb:249:in \`column_names'
  from /app/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.14/lib/active_record/relation/calculations.rb:220:in \`aggregate_column'
  from /app/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.14/lib/active_record/relation/calculations.rb:241:in \`execute_simple_calculation'
  from /app/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.14/lib/active_record/relation/calculations.rb:215:in \`perform_calculation'
  from /app/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.14/lib/active_record/relation/calculations.rb:159:in \`calculate'
  from /app/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.14/lib/active_record/relation/calculations.rb:58:in \`count'
  from /app/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.14/lib/active_record/querying.rb:12:in \`count'
  from (irb):35
  from /app/vendor/bundle/ruby/2.0.0/gems/railties-3.2.14/lib/rails/commands/console.rb:47:in \`start'
  from /app/vendor/bundle/ruby/2.0.0/gems/railties-3.2.14/lib/rails/commands/console.rb:8:in \`start'
  from /app/vendor/bundle/ruby/2.0.0/gems/railties-3.2.14/lib/rails/commands.rb:41:in \`<top (required)>'
  from script/rails:6:in \`require'
  from script/rails:6:in \`<main>'irb(main):036:0>

**Comment by sodabrew** [comment]
You must escape the table name if it contains characters with special meaning. A period is used as the separator, e.g. in `SELECT * FROM database_name.table_name`.
