### ISSUE TITLE
No support for geometry data type

### ISSUE THREAD

**Issue by jdart** [brianmario/mysql2#619]
There's probably a good reason this isn't already the case, but is there any chance of adding basic support for the geometry data type?

There are adapters that extend this one to provide the functionality but they're struggling to keep up.

**Comment by sodabrew** [comment]
I don't think there is a standard Ruby object to convert into, so we would have a hard time providing this conversion in C.

**Comment by jdart** [comment]
Is it too hacky to represent it as a string?

**Comment by sodabrew** [comment]
I assumed that string is how the datatype is currently returned... could you put together a code snippet showing how things aren't working now, and a not-working code snippet of how you would like it to work?

**Comment by jdart** [comment]
I think I have conflated this gem with the AR adapter. Sorry for the waste
of time.
