### ISSUE TITLE
Incorrect MySQL client library version! 

### ISSUE THREAD

**Issue by beslow** [brianmario/mysql2#620]
mysql2.rb:31:in `require': Incorrect MySQL client library version! This gem was compiled for 5.5.41-MariaDB but the client library is 5.6.24. (RuntimeError)

**Comment by sodabrew** [comment]
This happens if you compile against one set of MySQL (or MariaDB) libraries but have a different set in your runtime library paths. You'll need to resolve this discrepancy on your build/deploy server environments.

**Comment by cdelrosario** [comment]
Hi sorry to ask here but I cannot find a solution to this similar issue. 

I am on OSX and uninstalled MySQL and installed Mariadb.

I am getting this error when I start rails server:
`Gem Load Error is: Incorrect MySQL client library version! This gem was compiled for 10.5.19-MariaDB but the client library is 3.1.20`

Any help on how can I make them the same version?
Thank you.
