### ISSUE TITLE
Different timestamp precisions with activerecord 4.2.1 based on query method

### ISSUE THREAD

**Issue by jorihardman** [brianmario/mysql2#621]
I've reported this issue over at rails/rails#19711, but I figured I would post it here as well since it seems to be specific to the mysql2 adapter.

Basically, the issue is that timestamp precision is different when doing a where query with a hash as argument vs a where query with a string argument. Here's how I was able to reproduce:

1. Create a new rails 4.2.1 app.
2. Add mysql2 to gemfile and set up a new database with Mysql version 5.6.23.
3. Create a single model with just timestamps.
4. Open Rails console and do the following:

  ```
  2.2.2 :005 > time_now = Time.now
   => 2015-05-18 11:30:49 -0500
  2.2.2 :006 > Test.where(created_at: time_now)
    Test Load (0.4ms)  SELECT `tests`.* FROM `tests` WHERE `tests`.`created_at` = '2015-05-18 16:30:49'
   => #<ActiveRecord::Relation []>
  2.2.2 :007 > Test.where('created_at = ?', time_now)
    Test Load (0.4ms)  SELECT `tests`.* FROM `tests` WHERE (created_at = '2015-05-18 16:30:49.674136')
   => #<ActiveRecord::Relation []>
  ```

As you can see, the executed query is different, even though I would expect it to be the same. The second one has millisecond precision.

**Comment by sodabrew** [comment]
Thank you for the link to the AR ticket, I'll keep an eye on it. This is an active record issue exclusively, code wise.

**Comment by sodabrew** [comment]
Wait why was https://github.com/rails/rails/issues/19711 closed? This is an AR issue. The mysql2 gem takes fully baked query strings as input, so if the query is different it ain't us making it different and we cannot fix it here, we don't parse the query string.

**Comment by sodabrew** [comment]
Resolved by https://github.com/rails/rails/pull/20732 which will appear in an upcoming version of Rails. Thank you @jorihardman for running this to ground!
