### ISSUE TITLE
Performance problems

### ISSUE THREAD

**Issue by pmontrasio** [brianmario/mysql2#623]
I had to move an application from PostgreSQL 9.4 to MariaDB 10 (customer choice). I'm using ActiveRecord but it's not a Rails app. I have a seeding script for the database. It creates 1.000 customers and some associated records using FactoryGirl. It runs in 1 minute 3" with PostgreSQL and 21 minutes 47" with MariaDB. It can't be the database (a 20x difference is impossible, I expect them to be reasonably matched). The database is running on Ubuntu 12.04 and the distribution's MySQL 5.5 is almost equally slow (16 minutes 23"). Connecting through the UNIX domain socket or the network port doesn't change the times much. The distribution MySQL is probably fairly well configured so I'm looking at the adapter now.

I installed the gem with the correct libraries 

    bundle config build.mysql2 --with-mysql-config=/path/to/mariadb/bin/mysql_config
    bundle

and I checked that mysql_config returns the path to the MariaDB libraries.

This is not the first time I've been using mysql2 and in the other projects I didn't notice anything strange. Even if I never matched MySQL against PostgreSQL (pg gem) I think I would have noticed such a slow database access.

Did anybody had similar problems?

**Comment by sodabrew** [comment]
If you have a ruby profiler, look to see if there is a hot spot in code.

Look for queries that may be locking the tables. This can cause slow behavior without obvious high cpu load. Because the query optimizers are very different between Pg and MySQL, these situations can occur on one db not the other.

As for database tuning, that's largely out of scope for this issue tracker, but here a a few ideas to kick start: for temp objects with unit tests, try using an in memory table type. For bulk inserts, do them all inside a single transaction. Make sure there is enough innodb log space, otherwise the transaction journal has to be flushed too often. Make sure there is enough innodb buffer pool - I've seen distribution defaults as low as 8MB when a good value might be 2GB.

**Comment by pmontrasio** [comment]
Thank you for the quick reply.
I increased the innodb limits in MariaDB with no much luck. I added ruby-prof to the Gemfile and got this (profiling really slows down everything, even the script with pg)

```
time seed.rb

real  34m11.670s
user  13m39.276s
sys 0m2.250s

 %self      total      self      wait     child     calls  name
 60.38   1232.813  1232.813     0.000     0.000    32185   Mysql2::Client#query
  1.15     23.575    23.575     0.000     0.000  5010169   Symbol#to_s
  0.76     56.351    15.574     0.000    40.777  2626436   ActiveRecord::Attribute#value
  0.73     85.412    14.983     0.000    70.428  2273409  *Class#new
 ```

As you can see the script spends most of its time in the query method of the adapter. The time spent in any of the other methods is negligible (by method). The number of records added to the database is 32152, so nearly one call to ```query``` per record.

```real - user``` is consistent with the 20/21 minutes I observed.

The script runs inside a single  transaction. Removing it didn't make any difference.
However the pg adapter has a notable difference of behavior:

```
time seed.rb

real	12m14.176s
user	11m58.355s
sys	0m1.816s

 %self      total      self      wait     child     calls  name
  2.80     20.263    20.263     0.000     0.000  5228923   Symbol#to_s
  1.78     74.409    12.920     0.000    61.489  2350642  *Class#new
  1.76     42.606    12.753     0.000    29.853  2641396   ActiveRecord::Attribute#value
  1.75     12.675    12.675     0.000     0.000  2731769   Regexp#match
  1.62     11.713    11.713     0.000     0.000  2523283   String#to_s
  1.50     10.886    10.886     0.000     0.000  1597864   String#sub
  1.41     10.242    10.242     0.000     0.000  2131464   Kernel#class
  1.26      9.516     9.133     0.000     0.383    32328   PG::Connection#exec_prepared
  1.07      7.774     7.774     0.000     0.000  1634528   ActiveRecord::AttributeMethods::Dirty#original_raw_attributes
  1.05      7.636     7.636     0.000     0.000  1494388   Array#compact
  1.04      8.064     7.568     0.000     0.496  1546550   ActiveSupport::HashWithIndifferentAccess#convert_key
  1.04      7.498     7.498     0.000     0.000       39   PG::Connection#async_exec
```

There are 32328 ```exec_prepared``` and only 39 ```async_exec``` vs the 32185 ```exec``` of mysql2. Could that account for the difference of performance? I wonder what pg does, maybe it bundles some statements together before sending them to the database.

I confirm that without profiling the script with pg ends with

```
real	1m0.436s
user	0m46.730s
sys	0m0.858s
```

about the same ```real - user``` of the script with the profiling.

**Comment by pmontrasio** [comment]
I run the pg script to generate 100x less times records.
The interesting thing is that the number of the ```async_exec``` calls is still 39 even if the ```exec_prepared``` are down by a 100 factor. The running time of those 39 calls is about what it was in the original test. Maybe I'll ask to the pg maintainers what those calls are for.  
 
```
 %self      total      self      wait     child     calls  name
 71.00      7.740     7.740     0.000     0.000       39   PG::Connection#async_exec
  1.06      0.413     0.116     0.000     0.297    63407  *Class#new
  0.97      0.106     0.106     0.000     0.000    51815   Symbol#to_s
  0.93      0.101     0.101     0.000     0.000    60549   Kernel#class
  0.55      0.060     0.060     0.000     0.000    27041   Regexp#match
  0.53      0.059     0.058     0.000     0.002      322   PG::Connection#exec_prepared
```

**Comment by sodabrew** [comment]
Are these INSERTs? Are you running this through ActiveRecord? If so, take a look at https://github.com/zdennis/activerecord-import which will help batch the data into larger INSERT statements.

**Comment by pmontrasio** [comment]
They are mostly INSERTS. The script is made of loops that create records, get their ids and use them to create other associated records. I got a significant speed improvement by separating the creation of the records between different loops:  I use activerecord-import to create the records,  ```select("id")``` to get their ids and pass them to the next loop.

The mysql2 script went down to 93 seconds from 20 minutes. The pg one got a little faster too, from 63 seconds to 47. Here are the profiling

mysql2

```
 %self      total      self      wait     child     calls  name
  6.37     49.813    49.813     0.000     0.000     1045   Mysql2::Client#query
  3.11     24.316    24.316     0.000     0.000  4058968   Regexp#match
  2.93     22.910    22.910     0.000     0.000  4942224   Symbol#to_s
  2.15     16.848    16.848     0.000     0.000  2926195   String#to_s
```

We are down to 1045 calls to the database from more than 32k.

pg

```
 %self      total      self      wait     child     calls  name
  3.19     22.543    22.543     0.000     0.000  5109512   Symbol#to_s
  2.75     85.513    19.417     0.000    66.096  1954102   ActiveRecord::Attribute#value
  2.60     18.412    18.412     0.000     0.000  2711909   Regexp#match
  2.57     18.200    18.200     0.000     0.000  2944522   String#to_s
...
  1.33      9.418     9.418     0.000     0.000     1054   PG::Connection#async_exec
....
  0.00      0.001     0.001     0.000     0.000        2   PG::Connection#exec_prepared
```

All the statements are executed with ```async_exec``` now because there is nothing worth to be prepared. The two ```exec_prepared``` are probably the only two records I still create without activerecord-import.

Prepared statements seemed to make a large difference before I used activerecord-import. I read that mysql2 doesn't support them but there is a pull request for that https://github.com/brianmario/mysql2/pull/289 It seems to be due for 0.4.0. Am I wrong if I suspect that it will bridge the gap in performance between the two drivers, but not in this seeding use case? Those 9.4 seconds spent inside pg's ```async_exec``` are still significantly less than the 49.8 of mysql2's ```query```. I wonder what's causing this difference. Anyway, I'm closing this issue because I don't think there are other optimizations to be done in the script and it's fast enough now.

@sodabrew Thank you for your help!
