### ISSUE TITLE
Connect to old legacy DB - SESSION variables causing error

### ISSUE THREAD

**Issue by tonydm** [brianmario/mysql2#626]
I'm wondering if possible to disable the sending of the init variables when initiating a connection.  My issue is this.  I have a Rails app, an Intranet Portal, which needs to connect to Mysql, Postgres, MSSQL.    I've run into a mysql version 3.23.58 that is incompatible with the NAME and SESSION variables attempting to be set.  My nasty work around is to create a model without ActiveRecord using dbi and dbd-mysql which interact with the db server without issue.  But then, of course, I loose all the benefits of ActiveRecord. 

```
Mysql::Error: You have an error in your SQL syntax near 'NAMES latin1,  @@SESSION.sql_mode = '', @@SESSION.strict = 0, @@SESSION.sql_auto' at line 1
```

**Comment by sodabrew** [comment]
You're using the Mysql gem and not the Mysql2 gem, so this isn't the right gem to report this. I think this may be coming from Active Record - what version of Rails are you using have?

**Comment by tonydm** [comment]
I actually get the same error using the Mysql2 gem.  I happened to post the error after going from Mysql2 to Mysql.  I am using 4.2.1

**Comment by sodabrew** [comment]
This is a Rails issue. Neither MySQL adapter gem is generating that query, it's coming from Active Record. I think the error is specifically from the NAMES bit, which you can disable by setting `encoding: ` in your database.yml. The code is here:
https://github.com/rails/rails/blob/v4.2.1/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb#L847-851

Coincidentally, a big chunk of that code is from my commit back in 2012, here:
 https://github.com/rails/rails/commit/97d06e8c4bd44154abda41a3f7e4bc49929a919f

**Comment by tonydm** [comment]
You are correct sir, I see that now.  I will look at overriding the method and perhaps check the ```version:``` option of the specific connection.  Appreciate your response

**Comment by sodabrew** [comment]
Good luck! Please close the issue if this is resolved for you.
