### ISSUE TITLE
 MySQL server has gone away

### ISSUE THREAD

**Issue by chebyte** [brianmario/mysql2#644]
Hello guys I have a problem, my app get this error

````
ActiveRecord::StatementInvalid: Mysql2::Error: MySQL server has gone away: SHOW FULL FIELDS FROM `experiment_trials`
````
I tried many things and nothing works, I tried the flag reconnect: true and wait_timeout: 2147483 and not works

I have rails 3, ruby 2.0, mysql2 0.3.18 and mysql-server 5.5

anyone knows how can I fix it ?

thanks for advance!

**Comment by APohio** [comment]
Hey, this is probably to do with the space on your server, or the memory available.
