### ISSUE TITLE
Relative path not allowed in OS X: "unsafe use of relative rpath libmysqlclient.18.dylib"

### ISSUE THREAD

**Issue by KhedronWilk** [brianmario/mysql2#646]
Hi!

Seems like the gem uses a relative path to access libmysqlclient.18dylib on OS X and latest version of OS X classifies the usage of relative paths to libs as unsafe. (?)

```
LoadError: dlopen(/Library/Ruby/Gems/2.0.0/gems/mysql2-0.3.18/lib/mysql2/mysql2.bundle, 9): Library not loaded: libmysqlclient.18.dylib
  Referenced from: /Library/Ruby/Gems/2.0.0/gems/mysql2-0.3.18/lib/mysql2/mysql2.bundle
  Reason: unsafe use of relative rpath libmysqlclient.18.dylib in /Library/Ruby/Gems/2.0.0/gems/mysql2-0.3.18/lib/mysql2/mysql2.bundle with restricted binary - /Library/Ruby/Gems/2.0.0/gems/mysql2-0.3.18/lib/mysql2/mysql2.bundle
/Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
/Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/Library/Ruby/Gems/2.0.0/gems/mysql2-0.3.18/lib/mysql2.rb:31:in `<top (required)>'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `each'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `block in require'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `require'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'
/Library/WebServer/Documents/redmine-3.0.3/config/application.rb:5:in `<top (required)>'
/Library/WebServer/Documents/redmine-3.0.3/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)
```

**$** otool -L /Library/Ruby/Gems/2.0.0/gems/mysql2-0.3.18/lib/mysql2/mysql2.bundle
```
/Library/Ruby/Gems/2.0.0/gems/mysql2-0.3.18/lib/mysql2/mysql2.bundle:
	/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/libruby.2.0.0.dylib (compatibility version 2.0.0, current version 2.0.0)
	libmysqlclient.18.dylib (compatibility version 18.0.0, current version 18.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```

**$** bundle show mysql2
```
/Library/Ruby/Gems/2.0.0/gems/mysql2-0.3.18
```

**$** ruby -v
```
ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
```

**$** mysql -V
```
mysql  Ver 14.14 Distrib 5.6.26, for osx10.8 (x86_64) using  EditLine wrapper
```

**$** hostinfo
```
Mach kernel version:
	 Darwin Kernel Version 15.0.0: Tue Jul 21 21:47:25 PDT 2015; root:xnu-3247.1.68~32/RELEASE_X86_64
```

That is OS X 10.11 "El Capitan" beta 5 and I realize that is unproven ground but someone needs to be first... :-) If I can do anything to close this issue I am more than willing to mess upp my configuration, it feels like it is already halfway lost anyway. I guess maybe something can be changed in the Makefile for the gem but I don't have enough knowledge to read that one properly.

(Tried to search for if this is a known issue but could not find matching issue. My apology if there is.)

**Comment by sodabrew** [comment]
We've seen the symptom before e.g. in #205 and #257 and #589. It's an issue in the libmysqlclient.18.dylib build/link upstream. The underlying bug is http://bugs.mysql.com/bug.php?id=61699 -- there's a recent note that it may have been fixed in MySQL 5.7.4, which would be progress, but not yet helpful to anybody running on a GA release.

**Comment by sodabrew** [comment]
You may be able to fix your libmysqlclient in-place with:

```
$ sudo install_name_tool -id <path to libmysqlclient.18.dylib> <repeat path to libmysqlclient.18.dylib>
```

**Comment by KhedronWilk** [comment]
Hmprh, I have to improve my search skills.... 

Thanks sodabrew for quick reply! The install_name_tool trick did not help but I am grateful anyway. 

To link between /usr/local/lib and /usr/lib used to help but I think part of the problem is the "root less" mode Apple has put OS X 10.11 in (you're not allowed to touch most files in /usr even as root).

I close this issue since the bug is upstream. Let's hope the future mysql version is better.

**Comment by softwhisper** [comment]
Just to avoid the SIP of OSX 10.11 you can reboot with Cmd+R and under the Utilities menu, go yo Security and disable the SIP option. After that I could make the ln to the /usr/lib folder.

Hope that this could gave a few time while Mysql don't release a new version for OSX 10.11

**Comment by jonathansimmons** [comment]
So I was using the utilities fix mentioned above by @softwhisper. My computer upgraded to the GM release of 10.11 this morning though and that fix has been removed. 

Is there a known work-around for this in GM 10.11?

**Comment by chrisidefix** [comment]
The most simple workaround should be to use the OS X build-in tool `install_name_tool` as @sodabrew recommended. I am using it heavily on some other libraries that have the same issue now, but to be honest it's a pain. You really have to rename ALL references in your executables and dependent libraries.

You can script it, though - something like this should work:
```
lib_path=/PATH/TO/LIBS

lib_names[0]=LIB_NAME_1
lib_names[1]=LIB_NAME_2
lib_names[2]=LIB_NAME_3

for lib_name in ${lib_names[*]}
do
    for lib_name1 in ${lib_names[*]}
    do
         install_name_tool -change ${lib_name1}.dylib ${lib_path}${lib_name1}.dylib ${lib_path}${lib_name}.dylib
    done
done
```

**Comment by jonathansimmons** [comment]
Turns out just a simple symlink in `usr/local/lib` worked fine:

`sudo ln -s /usr/local/mysql/lib/libmysqlclient.18.dylib /usr/local/lib/libmysqlclient.18.dylib`

**Comment by chrisidefix** [comment]
Does this mean OS X 10.11 considers the location `/usr/local/lib` (and probably `/usr/lib`) as secure and allows to dynamically link to libraries in there, but not to other directories?
@jonathansimmons could you please let me know the output of `otool -L /Library/Ruby/Gems/2.0.0/gems/mysql2-0.3.18/lib/mysql2/mysql2.bundle` (or similar library/executable that fails to find dynamically linked libraries without the symbolic link?

**Comment by jonathansimmons** [comment]
@chrisidefix This is what I got with or without the symlink in place. 

```
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: can't open file: /Library/Ruby/Gems/2.0.0/gems/mysql2-0.3.18/lib/mysql2/mysql2.bundle (No such file or directory)
```

**Comment by chrisidefix** [comment]
Ok, that file doesn't exist on your system, but could you try to figure out where on your machine `mysql2` is located and then call: `otool -L /MY/PATH/TO/MY/mysql2` (replace the /MY/PATH/.. stuff with your actual path). Would also be interesting to see what `otool -L /usr/local/mysql/lib/libmysqlclient.18.dylib` brings up.

**Comment by jonathansimmons** [comment]
Sorry about that. Here you go:
```
jonathan@Jonathan ~ $ otool -L /usr/local/mysql/lib/libmysqlclient.18.dylib
/usr/local/mysql/lib/libmysqlclient.18.dylib:
	/usr/local/mysql/lib/libmysqlclient.18.dylib (compatibility version 18.0.0, current version 18.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 65.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 169.3.0)
```


```
jonathan@Jonathan ~ $ otool -L /Users/jonathan/.rvm/gems/ruby-2.1.2/gems/mysql2-0.3.20/lib/mysql2/mysql2.bundle 
/Users/jonathan/.rvm/gems/ruby-2.1.2/gems/mysql2-0.3.20/lib/mysql2/mysql2.bundle:
	/Users/jonathan/.rvm/rubies/ruby-2.1.2/lib/libruby.2.1.0.dylib (compatibility version 2.1.0, current version 2.1.0)
	libmysqlclient.18.dylib (compatibility version 18.0.0, current version 18.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```

**Comment by georges** [comment]
Seems that the menu to disable SIP in OS X 10.11 is not available in final release, therefore can't use the symlink trick. Anyone found a workaround for this?

**Comment by jonathansimmons** [comment]
@georges 

See my comment above just symlinking to `user/local/lib` Seems to work fine.

**Comment by georges** [comment]
Indeed! Thanks a bunch. I was missing the 'lib' directory in '/usr/local/' so the symlink failed to be created and I just was too quick to associate that with being caused by SIP. I was 15 min away from giving up and switch to Postgres...

**Comment by blakeperdue** [comment]
@jonathansimmons solution of symlinking to `/usr/local/lib` worked for me on GM 10.11:

`sudo ln -s /usr/local/mysql/lib/libmysqlclient.18.dylib /usr/local/lib/libmysqlclient.18.dylib`

**Comment by chelexey** [comment]
OSX 10.11 final: symlinking to `/usr/local/lib` works like a charm, thanks!

**Comment by sodabrew** [comment]
Thanks everyone for your steps to resolve this issue! Would someone volunteer some concise text to add to the README?

**Comment by chrisidefix** [comment]
In a related note: OS X El Capitan (10.11) may remove the `/usr/local` directory and makes it *very* difficult to create it as described here (you can't even do it as root): https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/El_Capitan_and_Homebrew.md#if-usrlocal-does-not-exist

**Comment by thiagok** [comment]
@blakeperdue Thanks man! Saved my life today!

**Comment by Enri1991** [comment]
Hello! I've tried the solutions above without any success.

Before and after the simlink solution i get the same error:

```
$ rake db:create
rake aborted!
LoadError: dlopen(/Library/Ruby/Gems/2.0.0/gems/mysql2-0.4.2/lib/mysql2/mysql2.bundle, 9): Library not loaded: libmysqlclient.18.dylib
  Referenced from: /Library/Ruby/Gems/2.0.0/gems/mysql2-0.4.2/lib/mysql2/mysql2.bundle
  Reason: unsafe use of relative rpath libmysqlclient.18.dylib in /Library/Ruby/Gems/2.0.0/gems/mysql2-0.4.2/lib/mysql2/mysql2.bundle with restricted binary - /Library/Ruby/Gems/2.0.0/gems/mysql2-0.4.2/lib/mysql2/mysql2.bundle
/Library/Ruby/Gems/2.0.0/gems/mysql2-0.4.2/lib/mysql2.rb:31:in `require'
/Library/Ruby/Gems/2.0.0/gems/mysql2-0.4.2/lib/mysql2.rb:31:in `<top (required)>'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `require'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `block (2 levels) in require'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
/Users/enrico/Documents/Schedario/lavori_in_corso_enrico/jump/config/application.rb:7:in `<top (required)>'
/Users/enrico/Documents/Schedario/lavori_in_corso_enrico/jump/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
```


$ otool -L /Library/Ruby/Gems/2.0.0/gems/mysql2-0.4.2/lib/mysql2/mysql2.bundle 
```
/Library/Ruby/Gems/2.0.0/gems/mysql2-0.4.2/lib/mysql2/mysql2.bundle:
	/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/libruby.2.0.0.dylib (compatibility version 2.0.0, current version 2.0.0)
	libmysqlclient.18.dylib (compatibility version 18.0.0, current version 18.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```


otool -L /usr/local/mysql/lib/libmysqlclient.18.dylib
```
/usr/local/mysql/lib/libmysqlclient.18.dylib:
	libmysqlclient.18.dylib (compatibility version 18.0.0, current version 18.0.0)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 56.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 169.3.0)
```

Can somebody help?
Thank You

**Comment by Enri1991** [comment]
Reinstalling ruby, rails and creating a new app using RVM instead of mac's ruby, solved the problem for me.

**Comment by ignacio-chiazzo** [comment]
I have the same problem, any solution for this Issue?

**Comment by buckeyekt** [comment]
I'm still having this issue even though I'm using postgres.

Kathryns-MBP:studentdata kathrynknotts$ rake db:create
rake aborted!
LoadError: dlopen(/Library/Ruby/Gems/2.0.0/gems/pg-0.18.1/lib/pg_ext.bundle, 9): Library not loaded: libpq.5.dylib
  Referenced from: /Library/Ruby/Gems/2.0.0/gems/pg-0.18.1/lib/pg_ext.bundle
  Reason: unsafe use of relative rpath libpq.5.dylib in /Library/Ruby/Gems/2.0.0/gems/pg-0.18.1/lib/pg_ext.bundle with restricted binary - /Library/Ruby/Gems/2.0.0/gems/pg-0.18.1/lib/pg_ext.bundle
/Library/Ruby/Gems/2.0.0/gems/pg-0.18.1/lib/pg.rb:4:in `require'
/Library/Ruby/Gems/2.0.0/gems/pg-0.18.1/lib/pg.rb:4:in `<top (required)>'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `require'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `block (2 levels) in require'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
/Users/kathrynknotts/studentdata/config/application.rb:7:in `<top (required)>'
/Users/kathrynknotts/studentdata/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
Kathryns-MBP:studentdata kathrynknotts$ 

I attempted to do the symlink.

Kathryns-MBP:~ kathrynknotts$ sudo ln -s /usr/local/postgres/lib/libpq.5.dylib /usr/local/lib/libpq.5.dylib
Password:
ln: /usr/local/lib/libpq.5.dylib: File exists

Anyone have any suggestions? Thanks

**Comment by workanator** [comment]
Well I had the same issue with DBD::Pg installation on El Captain. That is Perl right but maybe my experience will be helpful.

I did
1. sudo ln -s /usr/local/postgres/lib/libpq.5.dylib /usr/local/lib/libpq.5.dylib
2. export POSTGRES_LIB="/usr/local/lib/"
3. Other stuff

**Comment by tgalery** [comment]
Any updates on this issue. I'm trying to use mysql2 as part of a plugin for chef DK (using its embedded ruby 2.1), but the lib simply can't be loaded. I Installed mysql 5.6 from a .dmg file for el captain and installed the mysql2 lib with the --with-mysql-dir option. The symlink solution did not work for me.
