### ISSUE TITLE
Cannot build mysql2 on Centos 6.6 with gcc 4.5.x

### ISSUE THREAD

**Issue by david-xie** [brianmario/mysql2#651]
Here's the output:

	Building native extensions.  This could take a while...
	ERROR:  While executing gem ... (Gem::Ext::BuildError)
		ERROR: Failed to build gem native extension.

		/usr/local/bin/ruby -r ./siteconf20150813-8428-du59mx.rb extconf.rb
	checking for ruby/thread.h... yes
	checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
	checking for rb_thread_blocking_region()... no
	checking for rb_wait_for_single_fd()... yes
	checking for rb_hash_dup()... yes
	checking for rb_intern3()... yes
	-----
	Using mysql_config at /usr/local/bin/mysql_config
	-----
	checking for mysql.h... yes
	checking for errmsg.h... yes
	checking for mysqld_error.h... yes
	-----
	Setting libpath to /usr/local/lib/mysql
	-----
	creating Makefile

	make "DESTDIR=" clean

	make "DESTDIR="
	compiling client.c
	client.c: In function ‘invalidate_fd’:
	client.c:187:43: error: ‘O_CLOEXEC’ undeclared (first use in this function)
	client.c:187:43: note: each undeclared identifier is reported only once for each function it appears in
	make: *** [client.o] Error 1

	make failed, exit code 2

	Gem files will remain installed in /usr/local/lib/ruby/gems/2.2.0/gems/mysql2-0.3.19 for inspection.
	Results logged to /usr/local/lib/ruby/gems/2.2.0/extensions/x86_64-linux/2.2.0/mysql2-0.3.19/gem_make.out

BTW, I tried both gcc 4.5.2 and 4.5.4. Also, this is mysql version if it helps:
mysql  Ver 14.14 Distrib 5.1.56, for unknown-linux-gnu (x86_64) using readline 5.1

**Comment by sodabrew** [comment]
This is interested - you have SOCK_CLOEXEC defined by system headers, but O_CLOEXEC is not defined. The code in question assumes *_CLOEXEC all appeared at the same time in headers, which on reflection might be false, and given your evidence, is false. I'll tag this for a 0.3.20 item and clean up the #ifdefs to catch this situation.

**Comment by david-xie** [comment]
@sodabrew It worked!

	[c_dxie@merchant-wallet-app1-staging mysql2]$ sudo gem install mysql2-0.3.19.gem
	Building native extensions.  This could take a while...
	Successfully installed mysql2-0.3.19
	Parsing documentation for mysql2-0.3.19
	Installing ri documentation for mysql2-0.3.19
	Done installing documentation for mysql2 after 1 seconds
	1 gem installed

**Comment by david-xie** [comment]
One more thing, I am not a pro in C, but I am wondering what's impact of changing SOCK_CLOEXEC to O_CLOEXEC, and is it proper to change it.

**Comment by sodabrew** [comment]
`SOCK_CLOEXEC` is used with `socket()` and `O_CLOEXEC` is used with `open()`.

**Comment by sodabrew** [comment]
Fix by commits cb3e98d on branch 0.3.x and 3907e94 on master.

**Comment by sodabrew** [comment]
Please try 0.3.20 and let me know if it compiles correctly.

**Comment by david-xie** [comment]
@sodabrew It worked! Cheers!
