### ISSUE TITLE
Improving install/compile time

### ISSUE THREAD

**Issue by gravyboat** [brianmario/mysql2#655]
Hey guys, I'm currently working on improving some system build times and for reasons I don't want to get into I can't use gem caching correctly for the development we are doing. I've noticed on the build that the mysql2 gem takes quite a long time even with specifying where the mysql config lives. Past pre-compiling the gem, increasing system resources, or caching it is there any way to improve install times that aren't obvious from the base options?

**Comment by sodabrew** [comment]
I can't think of anything else besides those.

**Comment by brianmario** [comment]
Taking a quick glance through `extconf.rb`, I think there are some checks we could drop if we were to only support say - Ruby 2.0+.

Having the external dependency on libmysqlclient has been a huge source of pain in the lifetime of this project. All of the different checks we do there have only been to help make it easier for people to install this library. Without it, we'd have to require them set where libmysqlclient is (unless it's in a default library path already).

For reference - on my laptop (Core i7, SSD, OSX 10.10.5), running a `bin/rake clean compile` takes just under 3 seconds pretty consistently.

**Comment by sodabrew** [comment]
Yep, me too. 3 seconds.

**Comment by gravyboat** [comment]
Hmm, compile time for me takes a lot longer than that (we're talking about minutes). I will review our bundle config/process to confirm the time it takes for each gem to install then go from there to make sure mysql is the culprit again, maybe I missed something in the strace that was leading me in the wrong direction. Thanks for the quick response, I'm going to close this.

**Comment by sodabrew** [comment]
What versions of Ruby / GCC / MySQL do you have? What platform are you on?

**Comment by gravyboat** [comment]
This is on a CentOS 6.6 box with Ruby 1.8.6, the latest GCC, and the latest mysql available from the repo at build time. I'm honestly surprised it even works with that Ruby release, so good job there.
