### ISSUE TITLE
Is it possible to figure out the table name from a query?

### ISSUE THREAD

**Issue by onebree** [brianmario/mysql2#660]
The reason why I need this is long-winded, so here is a quick example. I am going to reference the following query by the assigned object:

```ruby
scripts = client.query('SELECT * FROM scripts WHERE name LIKE "test%"')
```

When referencing `scripts`, I would like to later find out which table the query belongs to. Is there an easy way to do this with mysql2? I found that `rows` hash only includes the table _fields_ and not the table name itself. And if the method is not easy, what else could I do? Thank you.

**Comment by sodabrew** [comment]
Negative, this information is not provided by the MySQL API. Even if you do a `SHOW FULL PROCESSLIST` in another connection, it will only tell you the database that the query is running in, not the tables it is querying.

**Comment by onebree** [comment]
Okay, thank you. I have made a work around for my code, where I have `scripts = ['scripts', <result>]`. I am going to close this issue as my question is answered.
