### ISSUE TITLE
Remove a result after the query is made?

### ISSUE THREAD

**Issue by onebree** [brianmario/mysql2#661]
I tried doing the following:

```ruby
query.delete_if { |row| row[:type] == 'Script' && row[:id] == 100 }
# => undefined method `delete_if' for #<Mysql2::Result:0x0000000340bfe8> (NoMethodError)
```

`delete_if` works for both hashes and arrays. I am not sure how the `Mysql2::Result` object is stored, but it is enumerable, with each element a hash. I would like to do something like the above code, rather than creating a long query including more than one table.

**Comment by sodabrew** [comment]
Mysql2::Result is an Enumerable, which does not have delete_if. You can use select or reject instead.

**Comment by onebree** [comment]
Okay. If it is not in the README already, I think it would be good to note the object type of the Result.
