### ISSUE TITLE
Catch Mysql2::Error: Got a packet bigger than 'max_allowed_packet' bytes in rails

### ISSUE THREAD

**Issue by nimashariatian** [brianmario/mysql2#662]
Hi guys,
I am not sure if this is the right location to post this but I am on Rails 4.2 and having serious issues trying to catch the exception: Mysql2::Error: Got a packet bigger than 'max_allowed_packet' bytes 

I have tried:

    begin
    rescue Exception => e
    end 

as well as 

    begin
    rescue Mysql2::Error => e
    end 

any suggestions?

**Comment by sodabrew** [comment]
Please post your backtrace? I suspect ActiveRecord is catching and re-raising the exception under another name.

**Comment by nimashariatian** [comment]
this is inside a sidekiq worker. what basically happens is something like:

    class UserWorker
        include Sidekiq::Worker
        sidekiq_options retry: 2

        def perform
            Process.fork do
                 begin
                     @user = User.first
                     @user.name = "john"
                     @user.save
                     @user.data = get_very_large_json(..)
                     @user.name = "foo"
                     @user.save! 
                 rescue Exception => e 
                     Rails.logger.info "Exception occured: #{e.inspect}"
                 end 
            end
            Process.wait
            Rails.logger.info "==> Reached here.."
        end
    end

After running the code, the rails log displays something crazy like: 

    Mysql2::Error: Got a packet bigger than 'max_allowed_packet' bytes: UPDATE `users` SET       `users`.`data` = x'7b226e616d65223a224441455f696e74657276616c.....

    ==> Reached here..

and inspect '@use'r after the code execution:

    @user.name => "john"

**Comment by sodabrew** [comment]
It's not a crazy error, and rescuing it won't fix the problem. Please research that error message and determine whether you want to a) allow larger packets, or b) make sure your rows values are smaller.

**Comment by nimashariatian** [comment]
thanks @sodabrew , i know why the error occurs, not really trying to fix the problem, my question is: is it possible to catch this?

**Comment by nimashariatian** [comment]
also appreciate the prompt response :)

**Comment by sodabrew** [comment]
Oh, no sweat. So yeah you should be able to catch the Mysql2::Error, I'm not sure why that's not working, I still suspect AR is rescuing and re-raising it under a different exception class, but I don't really see enough context to advise on what's missing.

**Comment by nimashariatian** [comment]
thanks.. 
thats what i initially thought as well.. i was really surprised when 
rescue Exception => e 
didn't work 
is there a way to measure the large data size against the max_packet_allowed from Rails?

**Comment by sodabrew** [comment]
Hi, sorry I missed your follow-up question. You can query MySQL to find the current value of `max_allowed_packet` like this (showing the output on my system, it's the default of 1MB):

```
mysql> SHOW GLOBAL VARIABLES LIKE 'max_allowed_packet';
+--------------------+---------+
| Variable_name      | Value   |
+--------------------+---------+
| max_allowed_packet | 1048576 |
+--------------------+---------+
1 row in set (0.00 sec)
```

You can execute this in Rails with `ActiveRecord::Base.connection.execute(sql query above)`.
