### ISSUE TITLE
Tag and release mysql2 0.4.0

### ISSUE THREAD

**Issue by sodabrew** [brianmario/mysql2#668]
This is a big release for Prepared Statements. TODO list:

- [x] Tag the release
- [x] Post the Release info
- [x] Push source gem
- [x] Build & Push Windows gems
- [x] Close the milestone: https://github.com/brianmario/mysql2/milestones/0.4.0

**Comment by jeremy** [comment]
:clap:

**Comment by sodabrew** [comment]
* [ ] Blog post or something
