### ISSUE TITLE
mysql2 0.4.0 Gem::LoadError - fix

### ISSUE THREAD

**Issue by faramund** [brianmario/mysql2#675]
I updated mysql2 to 0.4.0. Unfortunately I got an error :
Specified 'mysql2' for database adapter, but the gem is not loaded. Add `gem 'mysql2'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord). (Gem::LoadError)
I downgraded the gem to 0.3.20. and everything is fine now. So you have a bug somewhere.

**Comment by sodabrew** [comment]
This is not enough information. Please check and see if the mysql2 gem built, or you need to update your Gemfile in some way. If you have an error message, posting it will help me know what the error is.

**Comment by philipgiuliani** [comment]
I have the same problem. I ran `bundle update mysql2` (had 0.3.20 before) and now when i want to run `rails c` i get the following message:
```
/gems/activerecord-4.2.4/lib/active_record/connection_adapters/connection_specification.rb:177:in `rescue in spec':
Specified 'mysql2' for database adapter, but the gem is not loaded. Add `gem 'mysql2'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord). (Gem::LoadError)
```

gem "mysql2" is of course in my Gemfile and its also installed. Downgrading fixes the problem again.

**Comment by philipgiuliani** [comment]
## Update
Rails has limited the gem to `~> 0.3.18`

https://github.com/rails/rails/commit/5da5e3772c32593ecf2f27b8865e81dcbe3af692

in master it's now supported.

**Comment by sodabrew** [comment]
@philipgiuliani Thanks for finding that - because the adapter is calling for `~> 0.3.x` (where x has been updated at times for different bug fixes), it will fail to load 0.4.0. This is sure to cause some confusion because Bundler isn't aware of this restriction and will update mysql2 beyond the range supported by AR.

Reported at Rails as well: https://github.com/rails/rails/issues/21544

**Comment by kaleemullah360** [comment]
do 
`gem 'mysql2', '~> 0.3.18'` this gem works with `rails version 4.x.x` 
if install `gem 'mysql2', '~> 0.4.0'` it produces gem load error

**Comment by nimashariatian** [comment]
any updates regarding this issue?

**Comment by sodabrew** [comment]
Rails 4.2.5 and above will allow mysql2 versions 0.3.x and 0.4.x at your option.

For older versions of Rails, you'll need to pin mysql2 in your Gemfile, for example:
```
gem 'rails', '~> 4.1.0'
gem 'mysql2', '~> 0.3.13'

**Comment by jd159** [comment]
How exactly do you pin gem 'mysql2', '~> 0.3.13'??

**Comment by sodabrew** [comment]
If the project you are working on has a Gemfile, then you'll edit the Gemfile. For more information: http://bundler.io/
