### ISSUE TITLE
[Peformance]ActiveRecord raw sql very slower than MySql

### ISSUE THREAD

**Issue by AugustoPedraza** [brianmario/mysql2#682]
I'm running a simple raw MySql query with ActiveRecord(#select_all method) and the time used to return result is slower that running the same query directly in MySql Workbench.

The query is the following:

```sql
SELECT 
      CASE 
        WHEN
        WeekDay(c.collect_date) >=0 AND WeekDay(c.collect_date) <5 THEN 1
      ELSE 0 
      END AS is_business_day, 
      HOUR(c.collect_date) consumption_hour, 
        SUM(c.energy), 
        AVG(c.power) 
    FROM consumptions c
    INNER JOIN devices d ON c.device_id=d.device_id AND d.ftp_id=1    
    GROUP BY CASE WHEN
        WeekDay(c.collect_date) >=0 AND WeekDay(c.collect_date) <5 THEN 1
      ELSE 0 
      END, HOUR(c.collect_date)
```
I run some profiling with [ruby-prof](https://github.com/ruby-prof/ruby-prof) and I got the following results:

Method | Consumed time for ftp_id= 1 | Consumed time for ftp_id= 2
-----------|---------------------------------------|-----------------------------------------
*Rails mysql console*| 470 ms|28_900 ms
*Mysql Workbench* |8_728 ms| 12_974 ms
*ActiveRecord(__execute__)*|  430 ms | 29_121 ms
*ActiveRecord(__select_all__)*|  474 ms | 29_889 ms

Below, also you can see some db's data:

  - Total records Consumptions: 3_873_814
      - For ftp_id 1: 226_047
      - For ftp_id 2: 3_647_767
  - Total records Devices:      170
      - For ftp_id 1: 73
      - For ftp_id 2: 97

NOTE: [ in this Google Drive link](https://drive.google.com/file/d/0B8MdWulMFj-oSjVJOU1FZG1oUFU/view?usp=sharing) are the profiling results.

NOTE: the project is using the **0.3.18** gem version.

**Comment by sodabrew** [comment]
Please try this again with two variations:
* `client.query(sql, :streaming => true, cache_rows => false)` - maybe the cost is transferring the results?
* `client.query(sql, :cast => false)` - maybe the cost is casting the results into Ruby types?

**Comment by carsonreinke** [comment]
Are you flushing MySQL's query cache and such?  What about running each bench mark multiple times?

**Comment by AugustoPedraza** [comment]
@sodabrew Thanks for you answer. I already did that you recommended me, but the result times are similar.
**The result set are just ~50 rows.**

Something that catches my attention is that **Mysql Workbench** is faster that **Mysql Console**.

Now, I'm trying running the queries without cache(just as @carsonreinke suggest), that I suppose is enable by default for Mysql Workbench.

**Comment by sodabrew** [comment]
The query cache is on the server side: https://dev.mysql.com/doc/refman/5.1/en/query-cache.html

**Comment by JoshMcKin** [comment]
I use workbench quite a bit and if you are using the "Duration / Fetch Time", its been my observation that is only the network time, meaning round trip from the server and does not include the time it took workbench to connect/reconnect if idle, build the outbound call, or process the results.

**Comment by AugustoPedraza** [comment]
@sodabrew I was researching a little about it, and I got the following query:

```sql
flush tables;SELECT SQL_NO_CACHE
      CASE 
        WHEN
        WeekDay(c.collect_date) >=0 AND WeekDay(c.collect_date) <5 THEN 1
      ELSE 0 
      END AS is_business_day, 
      HOUR(c.collect_date) consumption_hour, 
        SUM(c.energy), 
        AVG(c.power) 
    FROM consumptions c
    INNER JOIN devices d ON c.device_id=d.device_id AND d.ftp_id=2
    GROUP BY CASE WHEN
        WeekDay(c.collect_date) >=0 AND WeekDay(c.collect_date) <5 THEN 2
      ELSE 0 
      END, HOUR(c.collect_date);
```

But, the results are the same: **Mysql Workbench** still is much faster than **Mysql command line**.

**Comment by AugustoPedraza** [comment]
@JoshMcKin thanks for share your thoughts. However, I think that the time should not be too different because when I run the same query into the Mysql command line, there is an live connection, and also IMHO I consider that the time consumed for process the result is not significant because the result set are ~50 rows.

**Comment by AugustoPedraza** [comment]
I closed this issue because I consider that it is more related to Mysql Workbench instead of this gem, because the time used by the gem is **very similar to the used by the Mysql command line**.

Thanks to all for your help!
