### ISSUE TITLE
Connection fails for localhost when host is the FQDN.

### ISSUE THREAD

**Issue by ypid** [brianmario/mysql2#686]
ping jessie.testing
    PING jessie.testing (127.0.1.1) 56(84) bytes of data.
    64 bytes from jessie.testing (127.0.1.1): icmp_seq=1 ttl=64 time=0.026 ms

    irb(main):001:0> require 'mysql2'
    => true
    irb(main):002:0> client = Mysql2::Client.new(:host => "jessie.testing", :username => "db_user", :password => "db_password")
    Mysql2::Error: Can't connect to MySQL server on 'jessie.testing' (111)
            from /var/lib/gems/2.1.0/gems/mysql2-0.4.1/lib/mysql2/client.rb:79:in `connect'
            from /var/lib/gems/2.1.0/gems/mysql2-0.4.1/lib/mysql2/client.rb:79:in `initialize'
            from (irb):2:in `new'
            from (irb):2
            from /usr/bin/irb:11:in `<main>'
    irb(main):003:0> client = Mysql2::Client.new(:host => "localhost", :username => "db_user", :password => "db_password")
    => #<Mysql2::Client:0x00000001578860 @read_timeout=nil, @query_options={:as=>:hash, :async=>false, :cast_booleans=>false, :symbolize_keys=>false, :database_timezone=>:local, :application_timezone=>nil, :cache_rows=>true, :connect_flags=>2147525125, :cast=>true, :default_file=>nil, :default_group=>nil, :host=>"localhost", :username=>"db_user", :password=>"db_password"}>
    irb(main):004:0> client = Mysql2::Client.new(:host => "::1", :username => "db_user", :password => "db_password")
    => #<Mysql2::Client:0x0000000137fae0 @read_timeout=nil, @query_options={:as=>:hash, :async=>false, :cast_booleans=>false, :symbolize_keys=>false, :database_timezone=>:local, :application_timezone=>nil, :cache_rows=>true, :connect_flags=>2147525125, :cast=>true, :default_file=>nil, :default_group=>nil, :host=>"::1", :username=>"db_user", :password=>"db_password"}>

**Comment by sodabrew** [comment]
It looks like your local host name is resolving to ::1 which is the ipv6 equivalent of 127.0.0.1. If your MySQL server is not listening on ipv6 it would result in this error.

**Comment by ypid** [comment]
Right on :+1: Thanks. My MariaDB server only listens on ::1 which is [the default configuration](http://docs.debops.org/en/latest/ansible/roles/ansible-mariadb_server/docs/defaults.html#envvar-mariadb_server_bind_address) of the DebOps project.

    netstat -tulpen |grep mysql
    tcp6       0      0 ::1:3306                :::*                    LISTEN      108        12409       871/mysqld

    irb(main):004:0> client = Mysql2::Client.new(:host => "localhost", :username => "db_user", :password => "db_password")
    => #<Mysql2::Client:0x000000015a8718 @read_timeout=nil, @query_options={:as=>:hash, :async=>false, :cast_booleans=>false, :symbolize_keys=>false, :database_timezone=>:local, :application_timezone=>nil, :cache_rows=>true, :connect_flags=>2147525125, :cast=>true, :default_file=>nil, :default_group=>nil, :host=>"localhost", :username=>"db_user", :password=>"db_password"}>

**Comment by ypid** [comment]
ping6 jessie.testing
    PING jessie.testing(localhost) 56 data bytes
    64 bytes from localhost: icmp_seq=1 ttl=64 time=0.077 ms
    64 bytes from localhost: icmp_seq=2 ttl=64 time=0.059 ms

Would it make sense to fallback to v6 if v4 does not work?

**Comment by ypid** [comment]
Never mind. This is already done. I just need to configure resolution also for v6 jessie.testing in `/etc/hosts`.

**Comment by sodabrew** [comment]
The mysql2 gem doesn't make any interpretation of the hostname. The MySQL / MariaDB client library simply calls gethostbyname to convert it into an ipaddress. There is one special case that "localhost" means to try using a unix domain socket first.

**Comment by ypid** [comment]
Thanks again. So it is beneficial to mysql2 in terms of performance when the host is "localhost". Good to know. Then I will let my Workaround for this in the Ansible foodsoft role in place.
