### ISSUE TITLE
Error installing - failed to build native extension.

### ISSUE THREAD

**Issue by boykoc** [brianmario/mysql2#687]
Cannot seem to locate the issue with this and wanted to flag.

I've checked stackoverflow and other issues and found very similar errors but the main issues others report seem to be in place (e.g. I have development libraries, proper headers).

This is a cloned aws instance from an existing app and mysql2 gem exists and runs fine until I try to upgrade or install or fresh install I get the below error.

Output

Fetching: mysql2-0.3.11.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing mysql2:
        ERROR: Failed to build gem native extension.

        /home/user/.rvm/rubies/ruby-1.9.3-p392/bin/ruby extconf.rb
checking for rb_thread_blocking_region()... yes
checking for rb_wait_for_single_fd()... yes
checking for mysql.h... yes
checking for errmsg.h... yes
checking for mysqld_error.h... yes
creating Makefile

make
compiling result.c
result.c: In function ‘rb_mysql_result_fetch_row’:
result.c:258:31: warning: variable ‘tokens’ set but not used [-Wunused-but-set-variable]
           int hour, min, sec, tokens;
                               ^
result.c:272:58: warning: variable ‘tokens’ set but not used [-Wunused-but-set-variable]
           unsigned int year, month, day, hour, min, sec, tokens;
                                                          ^
result.c:315:33: warning: variable ‘tokens’ set but not used [-Wunused-but-set-variable]
           int year, month, day, tokens;
                                 ^
compiling mysql2_ext.c
compiling client.c
client.c: In function ‘rb_raise_mysql2_error’:
client.c:98:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
   VALUE e = rb_exc_new3(cMysql2Error, rb_error_msg);
   ^
client.c: In function ‘rb_mysql_client_socket’:
client.c:590:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
   int fd_set_fd = wrapper->client->net.fd;
   ^
linking shared-object mysql2/mysql2.so
/usr/bin/ld: cannot find -lmysqlclient
collect2: error: ld returned 1 exit status
make: *** [mysql2.so] Error 1

Gem files will remain installed in /home/user/.rvm/gems/ruby-1.9.3-p392/gems/mysql2-0.3.11 for inspection.
Results logged to /home/user/.rvm/gems/ruby-1.9.3-p392/gems/mysql2-0.3.11/ext/mysql2/gem_make.out

**Comment by boykoc** [comment]
After comparing both servers I found discrepancies between the mysql setup.  I removed all mysql related packages and reinstalled mysql-devel, mysql, mysql-server, mysql-lib.  gem install mysql -v '0.3.11' successfully installed.

**Comment by waynn** [comment]
@boykoc I know you've closed this, but just wanted to say this was super helpful for me. I was banging my head against this exact problem, and found the same sorta similar but not exact stackoverflow threads. I uninstalled and reinstalled through yum and it worked again.
