### ISSUE TITLE
get last query result when enable MULTI_STATEMENTS

### ISSUE THREAD

**Issue by roroco** [brianmario/mysql2#689]
I use following:

    cnn = Mysql2::Client.new(username: 'root', password: 'root', hostname: 'localhost', port: 3306, database: 'ro_cmds_plus_prod', flags: Mysql2::Client::FOUND_ROWS | Mysql2::Client::MULTI_STATEMENTS
    )
    
    r = cnn.query('select "line 1"; select "line 2";').to_a
    puts "r:#{r} ---- #{File.basename __FILE__}:#{__LINE__}"

and get 

    r:[{"line 1"=>"line 1"}] ---- exe.rb:17

I think the right result should be:

    r:[{"line 2"=>"line 2"}] ---- exe.rb:17

**Comment by sodabrew** [comment]
You're getting the first result as expected. To get the second result, call `client.next_result` as shown here: https://github.com/brianmario/mysql2#multiple-result-sets
