### ISSUE TITLE
Mysql2::Error: Lost connection to MySQL server during query

### ISSUE THREAD

**Issue by parasew** [brianmario/mysql2#69]
is there any way to configure the timeout (similar to the ActiveRecord::Base.verification_timeout setting) with rails3?

**Comment by fireflyk** [comment]
Is it solved now?

**Comment by fireflyk** [comment]
I found that it is OK in 0.3.15. But the problem reappears from 0.3.16. 
Is there anyone found that?

**Comment by jamesfebin** [comment]
@fireflyk  I am facing the same issue

**Comment by vmcilwain** [comment]
I am also facing this problem. I am using 0.3.18.

**Comment by vmcilwain** [comment]
My issue was a false alarm. Sorry about that. It turned out to be that I had 2 hosts defined. This didn't jump out at me till I downgraded to 0.3.15 which gave me the ip address it was having problems with.

**Comment by fireflyk** [comment]
@jamesfebin We read the C source code. There is a problem. We start to research how to solve it.
