### ISSUE TITLE
Missing release notes / changelog entries for 0.4.1 and 0.4.2?

### ISSUE THREAD

**Issue by aprescott** [brianmario/mysql2#707]
I can see that that changelog entries are maintained in GitHub's Releases UI. I'm unable to find notes about the 0.4.1 and 0.4.2 releases. https://github.com/brianmario/mysql2/compare/0.4.0...0.4.2 shows a lot of changes, but there's nothing for them in https://github.com/brianmario/mysql2/releases (after expanding out the 2 most recent tags).

I can see from the comparison diff that there were some external changes (like adding `flags:` support). I don't know if these changes were noted somewhere else (since `CHANGELOG` isn't used), then forgotten about, but are there notes somewhere for 0.4.1 and 0.4.2? Can the Releases page be updated if there are any?

**Comment by sodabrew** [comment]
I haven't published it yet, I'll do that today.

**Comment by sodabrew** [comment]
And they're live! Thanks for the reminder:
https://github.com/brianmario/mysql2/releases/tag/0.4.2
https://github.com/brianmario/mysql2/releases/tag/0.4.1
