### ISSUE TITLE
Can't install when older version was working

### ISSUE THREAD

**Issue by bjm88** [brianmario/mysql2#708]
I'm also having problem, installed ruby 2.1.5 with rvm, Mac OS X 10.11.1, mysql 5.6 and 5.7 I tried, both installed via brew.  version 0.3.14 of mysql2 was working fine.  Tried to upgrade and this happen

gem install mysql2 -v '0.4.2' Building native extensions. This could take a while... ERROR: Error installing mysql2: ERROR: Failed to build gem native extension.

/Users/Ben/.rvm/rubies/ruby-2.1.5/bin/ruby -r ./siteconf20151203-80492-qt6gy1.rb extconf.rb
checking for ruby/thread.h... * extconf.rb failed * Could not create Makefile due to some reason, probably lack of necessary libraries and/or headers. Check the mkmf.log file for more details. You may need configuration options.

Provided configuration options: --with-opt-dir --without-opt-dir --with-opt-include --without-opt-include=${opt-dir}/include --with-opt-lib --without-opt-lib=${opt-dir}/lib --with-make-prog --without-make-prog --srcdir=. --curdir --ruby=/Users/Ben/.rvm/rubies/ruby-2.1.5/bin/ruby /Users/Ben/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/mkmf.rb:456:in try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
    from /Users/Ben/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/mkmf.rb:587:intry_cpp' from /Users/Ben/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/mkmf.rb:1067:in block in have_header'
    from /Users/Ben/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/mkmf.rb:918:inblock in checking_for' from /Users/Ben/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/mkmf.rb:351:in block (2 levels) in postpone'
    from /Users/Ben/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/mkmf.rb:321:inopen' from /Users/Ben/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/mkmf.rb:351:in block in postpone'
    from /Users/Ben/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/mkmf.rb:321:inopen' from /Users/Ben/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/mkmf.rb:347:in postpone'
    from /Users/Ben/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/mkmf.rb:917:inchecking_for' from /Users/Ben/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/mkmf.rb:1066:in have_header'
    from extconf.rb:16:in'

extconf failed, exit code 1

Gem files will remain installed in /Users/Ben/.rvm/gems/ruby-2.1.5@caredox/gems/mysql2-0.4.2 for inspection. Results logged to /Users/Ben/.rvm/gems/ruby-2.1.5@caredox/extensions/x86_64-darwin-14/2.1.0-static/mysql2-0.4.2/gem_make.out Benjamins-MacBook-Pro:caredox Ben$ ruby --version ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0] Benjamins-MacBook-Pro:caredox Ben$ mysql --version mysql Ver 14.14 Distrib 5.7.9, for osx10.11 (x86_64) using EditLine wrapper Benjamins-MacBook-Pro:caredox Ben$ uname -a Darwin new-host-3.home 15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64

**Comment by bjm88** [comment]
ok can't even reinstall 0.3.14, so seems after uninstalling something is up.

**Comment by sodabrew** [comment]
You may need to run "xcode-select --install" if you have updated your XCode recently via the App Store and this is the first time you are compiling something using the new toolchain. You'll be prompted to accept a license agreement.

**Comment by bjm88** [comment]
I'm at a loss...have tried lots of different things...
reinstalled mysql 5.6 and 5.7 after updating brew
installed Mac OS X 10.11  xcode 7.1.1 and command line tools
gcc --version
gcc (Homebrew gcc 4.9.2_1) 4.9.2

rvm -v
rvm 1.26.11

ruby -v
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]

gem install mysql2 just wont work.  Keep getting this error
Users/Ben/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.

I tried forcing pointing to my brew cellar, what specifically is it looking for in there.  Can I check mysql installation for a specific file or something?

**Comment by sodabrew** [comment]
Is there anything more specific in the mkmf.log file?

**Comment by bjm88** [comment]
I launched XCode and checked that also, but thanks for response.  In the gem_make.out file its similar info, is there another file somewhere...

/Users/Ben/.rvm/rubies/ruby-2.1.5/bin/ruby -r ./siteconf20151203-1351-hianhk.rb extconf.rb
checking for ruby/thread.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/Users/Ben/.rvm/rubies/ruby-2.1.5/bin/ruby
/Users/Ben/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /Users/Ben/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/mkmf.rb:587:in `try_cpp'
        from /Users/Ben/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/mkmf.rb:1067:in `block in have_header'
        from /Users/Ben/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/mkmf.rb:918:in `block in checking_for'
        from /Users/Ben/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/mkmf.rb:351:in `block (2 levels) in postpone'
        from /Users/Ben/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/mkmf.rb:321:in `open'
        from /Users/Ben/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/mkmf.rb:351:in `block in postpone'
        from /Users/Ben/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/mkmf.rb:321:in `open'
        from /Users/Ben/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/mkmf.rb:347:in `postpone'
        from /Users/Ben/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/mkmf.rb:917:in `checking_for'
        from /Users/Ben/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/mkmf.rb:1066:in `have_header'
        from extconf.rb:16:in `<main>'

**Comment by bjm88** [comment]
Ah found it, there is other info, but not sure what it means...

"gcc -o conftest -I/Users/Ben/.rvm/rubies/ruby-2.1.5/include/ruby-2.1.0/x86_64-darwin14.0 -I/Users/Ben/.rvm/rubies/ruby-2.1.5/include/ruby-2.1.0/ruby/backward -I/Users/Ben/.rvm/rubies/ruby-2.1.5/include/ruby-2.1.0 -I. -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -O3 -I/Users/mpapis/.sm/pkg/active/include -fPIC -mmacosx-version-min=10.7 -pipe conftest.c  -L. -L/Users/Ben/.rvm/rubies/ruby-2.1.5/lib -L. -L/Users/mpapis/.sm/pkg/active/lib -fPIC -Bstatic -fstack-protector   -arch x86_64   -lruby-static -framework CoreFoundation  -lpthread -ldl -lobjc "
dyld: Library not loaded: /usr/local/lib/libisl.10.dylib
  Referenced from: /usr/local/Cellar/gcc/4.9.2_1/libexec/gcc/x86_64-apple-darwin14.0.0/4.9.2/cc1
  Reason: image not found
gcc: internal compiler error: Trace/BPT trap: 5 (program cc1)
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

**Comment by bjm88** [comment]
OK for anyone that runs into this, wanted to post my solution.  Basically if you get into this situation your local Mac OS X env is probably messed up from historical activity.  For me I had to install older versions of gcc for some bar code processing stuff, which required older imagemagick and I ended up having to use Mac Ports and HomeBrew together, this is a bad idea!  Once I totally removed all MacPorts stuff, uninstalled mysql and libtool, and fully updated brew I got things working.  Make sure to clean up everything brew doctor says, do a brew update, repair, clean.  Then reinstall mysql and libtools through brew normally and then gem install mysql2 will work fine.

**Comment by sodabrew** [comment]
Thank you for the solution follow-up!

**Comment by lafeber** [comment]
When running:
`xcode-select --install`

`xcode-select: error: command line tools are already installed, use "Software Update" to install updates`

Then running:
`brew update`

`Error: You have not agreed to the Xcode license. Please resolve this by running:
  sudo xcodebuild -license accept`

This command fixed the above error for me.
