### ISSUE TITLE
Using default_file with .mylogin.cnf

### ISSUE THREAD

**Issue by UnConundrum** [brianmario/mysql2#710]
This is essentially the same issue as raised by issue #494

MySql offers a utility called mysql_config_editor which will accept parameters including a host, user, and password among others.  It creates a file in the user's home directory called .mylogin.cnf.  Within that file the user's password is encrypted.  By using this routine, I can execute mysql on the command line and log right into mysql without a user name or password, even on a remote host.  Unfortunately, every time I try to use the file with Rails and database.yml, I get segmentation fault with:

error: Found option without preceding group in config file: /home/username/.mylogin.cnf at line: 2

The previous ticket was abandoned when the user used chef.  I do not use chef.  Any suggestions in how I can get past this?

**Comment by sodabrew** [comment]
Please check the contents of your .mylogin.cfg file, and make sure there aren't any non-ascii bytes preceding the `[client]` section at the top of the file.

http://dev.mysql.com/doc/refman/5.7/en/mysql-config-editor.html

**Comment by UnConundrum** [comment]
Well, the file itself is encrypted by the mysql_config_editor program (not an option).  The only way you can see its contents that I know of is with the mysql_config_editor print option.  When I use that option, I get:


[client]
user = user_name
password = *****
host = primal.domain_name.com


No extra characters.  By design, there is no way to display the password in plain text.

**Comment by sodabrew** [comment]
The mysql2 gem simply tells libmysqlclient to use this file. It is libmysqlclient that parses the file and in this case, it is libmysqlclient that reports an error.

Unless there is some transformation that libmysqlclient is expecting the mysql2 gem to make on the file before passing it as an argument into the library, I don't know what to do to help.

**Comment by UnConundrum** [comment]
Using libmysqlclient and it’s expectations is somewhat above my pay grade ;)  I wouldn’t know where to start.  I do know that to some point libmysqlclient_dev is/was required and that this is a utility the MySql folks want us using:  http://bugs.mysql.com/bug.php?id=73670   But that was a year ago.

Maybe someone else will have an idea?

**Comment by sodabrew** [comment]
What version of the `libmysqlclient` package do you have installed? (Might
be named libmysqlclient18 or 20).

**Comment by UnConundrum** [comment]
libmysqlclient18 which is reported as the latest version via apt-get

**Comment by sodabrew** [comment]
Ok, what version of the `libmysqlclient18 ` package do you have installed?

**Comment by UnConundrum** [comment]
I’m sorry, I don’t understand.  Do you mean os?  I’m running Ubuntu 15.10.

**Comment by sodabrew** [comment]
I mean the version number of the package, e.g.

```
 apt-cache policy libmysqlclient18
libmysqlclient18:
  Installed: 1:5.5.33-rel31.1-568.precise
```

**Comment by UnConundrum** [comment]
apt-cache policy libmysqlclient18

libmysqlclient18:
  Installed: 5.6.21-1ubuntu14.04
  Candidate: 5.6.21-1ubuntu14.04
  Version table:
 *** 5.6.21-1ubuntu14.04 0
        100 /var/lib/dpkg/status
     5.5.46-0ubuntu0.14.04.2 0
        500 http://de.archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu/ trusty-security/main amd64 Packages
     5.5.35+dfsg-1ubuntu1 0
        500 http://de.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages

**Comment by sodabrew** [comment]
Ok! So that's new enough to have the encrypted file reading code (per your mysql bug link, looks like 5.6.19 was the version it was added?) ...   The source of the original error message is in mysql here: 
https://github.com/mysql/mysql-server/blob/5.6/mysys_ssl/my_default.cc#L1005

**Comment by UnConundrum** [comment]
I posted an issue there to ask if there was something special that they needed.

https://bugs.mysql.com/bug.php?id=73670

I’ll surely share if I get a response.

**Comment by sodabrew** [comment]
@UnConundrum It's good bug etiquette to open a new ticket for a new issue. That bug at MySQL is about packaging the config editor with the user-facing binaries for mysql, rather than with the development libraries, and has nothing to do with the client library crashing when trying to use the encrypted config file.

I think we will need a new bug that specifically reports this crash to get support for fixing the crash.

**Comment by sodabrew** [comment]
The upstream mysql bugs have been closed as resolved, so I'm closing this out too.

> [29 May 6:52] Lars Tangvald
> This bug had a bad category set, so was forgotten. But as of 5.6.36, the mysql_config_editor binary is present in mysql-community-client (not sure exactly when the problem was fixed).
