### ISSUE TITLE
Error when starting rails server

### ISSUE THREAD

**Issue by lalithr95** [brianmario/mysql2#717]
There was a problem when I start the server
'rails s' throws me with following error
```bash
Starting Rails4
/Users/Lalith/.rvm/gems/ruby-2.1.5/gems/bundler-1.11.2/lib/bundler/runtime.rb:80:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'mysql2'. (Bundler::GemRequireError)
	from /Users/Lalith/.rvm/gems/ruby-2.1.5/gems/bundler-1.11.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /Users/Lalith/.rvm/gems/ruby-2.1.5/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
	from /Users/Lalith/.rvm/gems/ruby-2.1.5/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
	from /Users/Lalith/.rvm/gems/ruby-2.1.5/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
	from /Users/Lalith/.rvm/gems/ruby-2.1.5/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
	from /Users/Lalith/.rvm/gems/ruby-2.1.5/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
	from /Users/Lalith/Documents/Intern/hackerrank/config/application.rb:7:in `<top (required)>'
	from /Users/Lalith/.rvm/gems/ruby-2.1.5/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:79:in `require'
	from /Users/Lalith/.rvm/gems/ruby-2.1.5/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:79:in `block in server'
	from /Users/Lalith/.rvm/gems/ruby-2.1.5/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:76:in `tap'
	from /Users/Lalith/.rvm/gems/ruby-2.1.5/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:76:in `server'
	from /Users/Lalith/.rvm/gems/ruby-2.1.5/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /Users/Lalith/.rvm/gems/ruby-2.1.5/gems/railties-4.1.7/lib/rails/commands.rb:17:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'
```
bundle install works
Mysql 5.7.10 installed through brew
Rails 4.1.7
mysql2 gem 0.3.16

**Comment by sodabrew** [comment]
You may need mysql2 0.3.17 or higher for compatibility with MySQL 5.7.

**Comment by lalithr95** [comment]
@sodabrew  Worked with lower version of mysql 5.6, 5.5

**Comment by AparnaDhinakaran** [comment]
@lalithr95, how did you fix the issue?

**Comment by PeterBloom** [comment]
I have the same issue. Error on 'rails s' is

    `rescue in block (2 levels) in require': There was an error while trying to load the gem 'mysql2'. (Bundler::GemRequireError)


MySQL 5.6.23
gem mysql2 0.3.15
rails 3.2.21
bundler 1.11.2

**Comment by sodabrew** [comment]
@PeterBloom Try just loading mysql2 within your gem set to see if there's a more detailed message. Something like `bundle exec ruby -r mysql2`.

**Comment by lalithr95** [comment]
@PeterBloom try this as well
Use mysql2 gem with latest version 0.4.2. 
If you are not allowed to change versions in the Gemfile then uninstall mysql from brew
```bash
brew uninstall mysql
```
Now install mysql5.6 version using brew
```bash
brew tap homebrew/versions
```
Then install mysql56 or something similar formula 
```bash
brew install mysql56
```

**Comment by PeterBloom** [comment]
Thanks @sodabrew and @lalithr95,

My setup is a bit complex. In my local environment, I use a Docker server running MySQL 5.6.27.  (This is to emulate part of a production db architecture.)  My origin/master repo Gemfile.lock (shared by coworkers) calls for mysql2 gem v0.3.15.

When running 'rails s' with this gem version, I received the error "uninitialized constant Mysql2::Client::SECURE_CONNECTION (NameError)".  I am using ruby 2.1.5, rails 3.2.21, bundler 1.10.6 in this environment.

After some research and a few tries, I was able to get a good rails server start with the mysql2 0.3.18 gem.  I had to change my local branch Gemfile.lock to call for this version.  Newer versions of mysql2 gem (such as 0.4.2) failed (I think they may only support MySQL >=5.7).

I'd like to upgrade the versioned Gemfile.lock to v0.3.18, but don't want to create problems for others, or the production environment.

Please let me know if you have any comments on this issue or have experienced something similar.  Thanks!

**Comment by sodabrew** [comment]
In order to use mysql2 0.4.x, you need Rails 4.2.5 or higher. It otherwise works with all versions of MySQL >= 5.0.

If you use the MySQL 5.7 client libraries, then you need mysql2 0.3.17 or higher. You mention that you're using MySQL 5.6.27, but I suspect you may have a different client library or newer headers in your docker image.

**Comment by lalithr95** [comment]
@PeterBloom Have a look at this issue #603 for Mysql2::Client::SECURE_CONNECTION error.

**Comment by Aravind99** [comment]
There was an issue in `mysql2 0.4.0` and later versions.

    Try using these 
    1)gem list mysql2
    1. mysql2-0.3.20
    2. mysql2-0.4.3
    3. All versions
    
    2)gem uninstall mysql2
    
    3)Now change Gemfile 
         gem mysql2,'0.3.14'
    
    4)bundle
