### ISSUE TITLE
{Mysql2::Error} Column count doesn't match value count at row 1 when use mysql2

### ISSUE THREAD

**Issue by roroco** [brianmario/mysql2#718]
here is my [stackoverflow question](http://stackoverflow.com/questions/34604265/mysql2error-column-count-doesnt-match-value-count-at-row-1-when-use-mysql2).

**Comment by sodabrew** [comment]
Check your gist carefully. All of the rows have six columns, but one of them has five values.

```
insert articles (title, url, ctn, ctn_md5, created_at, updated_at) values("Trudy Chelgren (Character)  - Filmography by rating", "http:/www.imdb.com/character/ch0052168/filmorate", "", "2016-01-05 07:12:55", "2016-01-05 07:12:55");

```
