### ISSUE TITLE
Mysql2 insert data from another database

### ISSUE THREAD

**Issue by SpLin12** [brianmario/mysql2#720]
I have several databases (oracle, Sqlite3, Mysql). I need to select some data from a table in the one database and write them in another database. Example i want select some data from sqlite3 insert into table in Mysql.

I've tried doing:

    require 'mysql2'
    require 'sqlite3'

    results =  db.execute "select
    d1
    FROM d" do |row|
    client.query("INSERT INTO pet (d1) VALUES (?)", row)
    end

And i get this error.

    new.rb:48:in `merge!': no implicit conversion of Array into Hash (TypeError)
        from new.rb:48:in `query'
        from new.rb:48:in `block in <main>'
Can anyone help? Thank you.

**Comment by justincase** [comment]
`client.query(sql, options = {})` expects an optional hash of options as its second argument. It doesn't support placeholder as such. You could use a prepared statement:

```ruby
statement = client.prepare("INSERT INTO pet (d1) VALUES (?)")

results =  db.execute "SELECT d1 FROM d" do |row|
  statement.execute(row)
end
```
Do note that `row` needs to contain the actual value (a string, int, etc) not a collection of values such as an array.

**Comment by SpLin12** [comment]
Thanks for the answer
