### ISSUE TITLE
incompatible library version

### ISSUE THREAD

**Issue by daxadax** [brianmario/mysql2#721]
I started up an old project the other, and when I ran tests, I got an error about an incorrect client library version.  I thought that made sense since I hadn't run tests for awhile, so I uninstalled the mysql2 gem and bundled, which upgraded me to v0.4.2.

Now I get the following error: 

```
/home/me/.rvm/gems/ruby-2.2.3/gems/mysql2-0.4.2/lib/mysql2.rb:31:in `require': incompatible library version - /home/me/.rvm/gems/ruby-2.2.3/gems/mysql2-0.4.2/lib/mysql2/mysql2.so (LoadError)
```

I'm running Arch Linux which just saw a large upgrade, so I thought it could be related to mariadb/client - but I haven't found anything to support that.  There are a few references to the same error around the web, including one closed issue here, but nothing that's been resolved:  

https://github.com/brianmario/mysql2/issues/657
[how-do-i-resolve-incompatible-library-version-for-mysql2-gem-with-ruby-2-3](http://stackoverflow.com/questions/34536351/how-do-i-resolve-incompatible-library-version-for-mysql2-gem-with-ruby-2-3-on)

Can anyone point me in the right direction?  I've tried versions of this gem down to 0.3.18, but still got the same error.   Same with reinstalling mariadb/client and running mysql_upgrade

**Comment by jbirdjavi** [comment]
I'm having the same issue on Archlinux.  Mariadb got upgraded to 10.1.10 recently and that's about the only thing that I can think of that would be causing the issue.

**Comment by sodabrew** [comment]
Your client library may be mismatched with your client library headers. Check if there are separate packages for "libmysqlclient" or "mysql-client" and "libmysqlclient-dev" or "mysql-client-devel", etc. and these versions should all be matched.

**Comment by jbirdjavi** [comment]
They're all matched at 10.1.10.  You can see the three maria packages here:
https://www.archlinux.org/packages/?q=maria

**Comment by daxadax** [comment]
yup, I have the same as @jbirdjavi, think this is an issue with arch/mariadb

**Comment by kochka** [comment]
Same issue here (on Arch). I've tried to downgrade mysql libs, and also to link mysql2 with perconaserver lib that is also installed on my computer but without success...

**Comment by johnknott** [comment]
Same here, Arch Linux too. Trying to resolve now, will report back ...

**Comment by johnknott** [comment]
Hmm... I tried downgrading, and reinstalling mysql2 and I still get the same error.

sudo pacman -U /var/cache/pacman/pkg/libmariadbclient-10.0.22-1-x86_64.pkg.tar.xz /var/cache/pacman/pkg/mariadb-10.0.22-1-x86_64.pkg.tar.xz /var/cache/pacman/pkg/mariadb-clients-10.0.22-1-x86_64.pkg.tar.xz

Any ideas ?

**Comment by kochka** [comment]
@johnknott as I said in my previous post, I'm not sure the error linked to mariadb because I've also tried to build mysql2 using libperconaserverclient (as I'm using Percona Server) and I got the same error...

**Comment by jbirdjavi** [comment]
Is there another library that the error message would be referring to?

**Comment by sodabrew** [comment]
Are you possibly compiling with Ruby headers / libraries that don't match the runtimes?

The error message looks like it is coming from `dl` and not from inside mysql2; we used to do our own library version check, but that's now a Windows-only check in 0.4.2 from #678 
```
      rb_raise(rb_eRuntimeError, "Incorrect MySQL client library version! This gem was compiled for %s but the client library is %s.", MYSQL_LINK_VERSION, lib);
```

**Comment by jbirdjavi** [comment]
It must be something else besides maria/percona.  I just reinstalled my `pg` gem (for postgresql) and I'm getting the same error with that gem.  I'll keep digging.
`/home/justin/.rvm/gems/ruby-2.2.3/gems/pg-0.18.2/lib/pg.rb:4:in `require': incompatible library version - /home/justin/.rvm/gems/ruby-2.2.3/gems/pg-0.18.2/lib/pg_ext.so (LoadError)`

**Comment by justincase** [comment]
@jbirdjavi It does appear to come from [libruby](https://github.com/ruby/ruby/blob/ruby_2_3/dln.c#L1330). This `pg` issue might offer a clue. Note the `ruby-devel` package.

> When using RVM and a system Ruby (well, **ruby-devel**) is installed, libruby from
> /usr/lib64 is linked rather than the libruby in the RVM path.

https://bitbucket.org/ged/ruby-pg/issues/229/pg_exit-improperly-linked-when-using-rvm

**Comment by jbirdjavi** [comment]
Success.  I uninstalled the system ruby and now it's working as it should.  Granted, I'm able to do that in my case (and others might not be able to), but the issue is that it was building with the system ruby and not the rvm ruby.

**Comment by daxadax** [comment]
@jbirdjavi worked for me too, nice one!

**Comment by justincase** [comment]
Awesome. Hopefully there will be a proper fix when https://bugs.ruby-lang.org/issues/11111 (linked from #657) is resolved. But for now this will do!

**Comment by sodabrew** [comment]
It doesn't look like I need to make any changes in mysql2, and that https://bugs.ruby-lang.org/issues/11111 was backported to Ruby 2.0, 2.1, 2.2, ... so I think this ticket can be closed out. Please post here if I missed something!
