### ISSUE TITLE
gem install mysql2 fails - /usr/bin/mkdir: Command not found

### ISSUE THREAD

**Issue by fgro** [brianmario/mysql2#724]
Hi,

when trying to install mysql2 gem it fails because make cannot find /usr/bin/mkdir .. this is gentoo, mkdir is located in /bin .. of course I can fix this with symbolic link, still I wanted to report this, also to understand the origin of this problem. Find attached the log.

Thanks

f
[gem-install-mysql2.txt](https://github.com/brianmario/mysql2/files/103282/gem-install-mysql2.txt)

**Comment by justincase** [comment]
What's the output of `RbConfig::MAKEFILE_CONFIG['MAKEDIRS']`?

**Comment by fgro** [comment]
[2] pry(main)> RbConfig::MAKEFILE_CONFIG['MAKEDIRS']
=> "/usr/bin/mkdir -p"

**Comment by justincase** [comment]
That would explain it.
> The makefile configuration using the defaults from when ruby was built.
> https://github.com/ruby/ruby/blob/trunk/lib/mkmf.rb#L60

If you look at e.g. `~/.rbenv/versions/2.2.3/lib/ruby/2.2.0/x86_64-darwin14/rbconfig.rb` it will contain those defaults. I'm not exactly sure how to overwrite those with `bundle` or `gem`. With `make` it should work though.

    cd mysql2/ext/mysql2
    ruby extconf.rb
    make MAKEDIRS='mkdir -p' install

**Comment by sodabrew** [comment]
@fgro Are you still experiencing this issue?

**Comment by mirelon** [comment]
This helped me:

    sudo ln -s /bin/mkdir /usr/bin/mkdir
