### ISSUE TITLE
Is there a way to get reference to underlying IO?

### ISSUE THREAD

**Issue by crazyshot** [brianmario/mysql2#725]
I need to share my mysql connection with external process, because both processes need to work inside single transaction. So the easiest would be act as proxy passing all query requests from this process to mysql and stream results back, but for this I need to have actual IO object.
Using external proxy wouldn't work, as it would open different connections for each process.

Anyone have any ideas?

**Comment by justincase** [comment]
I'm not sure I correctly understand your question. What exactly do you need the socket for? It only understands the MySQL wire protocol after all. If you're *really really* sure that's what you're looking for:

```ruby
require 'mysql2'

client = Mysql2::Client.new(username: 'username', password: 'password')
io = IO.for_fd(client.socket)
```

**Comment by crazyshot** [comment]
Thanks.
Nope. Not sure, I'll have find a way to skip authentication and close connection commands from the other process, which won't be easy, and even after this, i'll have a problem with concurrency. Not sure it's all possible.
And all this to make system tests work with transactions :)
