### ISSUE TITLE
mysql2 IPv6 support

### ISSUE THREAD

**Issue by ton31337** [brianmario/mysql2#726]
Does this gem supports IPv6? Because I can't setup my connection using IPv6. Tried different ways like:
```
[2001:dead::1]
2001:dead::1
[v6.domain]
v6.domain
```
error is the same:
```
    Mysql2::Error
    -------------
    Unknown MySQL server host '[2001:dead::1]' (2)
```

**Comment by justincase** [comment]
Checkout https://github.com/brianmario/mysql2/issues/279#issuecomment-82988020

**Comment by sodabrew** [comment]
@ton31337 The mysql2 gem support IPv6 if the underlying libmysqlclient supports IPv6. If you have an older libmysqlclient, you'll need to update it. You might also have multiple versions of the library on your system - make sure only the newest ones are in use.
