### ISSUE TITLE
Specified 'mysql2' for database adapter, but the gem is not loaded. Add `gem 'mysql2'` to your Gemfile

### ISSUE THREAD

**Issue by sajjadmurtaza** [brianmario/mysql2#727]
Specified 'mysql2' for database adapter, but the gem is not loaded. Add `gem 'mysql2'` to your Gemfile is due to current version but working for gem 'mysql2', '~> 0.3.18'.

Why this is happening.?

**Comment by Znow** [comment]
Have had the same problem for quite some time, all though im using '0.3.19', which is working.

**Comment by sodabrew** [comment]
Until Rails 4.2.5 and higher, only mysql2 version 0.3.x are supported by Rails 4.x. In your Gemfile, `gem 'mysql2', '~> 0.3.18'` will make sure the right version is bundled.

In Rails 4.2.5 and higher, you can use mysql2 0.3.x and 0.4.x as well.
