### ISSUE TITLE
error when executing sql generanted by mysqldump

### ISSUE THREAD

**Issue by gggeek** [brianmario/mysql2#739]
Sorry if this question is asked in the wrong place or explained in a manual - I am a noob in Ruby and Chef.

The problem I have is that I am using the Chef Database cookbook to import a db dump generated by mysqldump.

If I run the mysql command-line tool to execute the exported sql, it works. If I use the Chef action, which depends on the mysql2 gem, it fails with the error:

==> default:     You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SET @OLD
_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
==> default:     /*!40101 SET @OLD_COL' at line 8

**Comment by gggeek** [comment]
ps: might it be a dupe of https://github.com/chef-cookbooks/database/issues/151 ?

**Comment by sodabrew** [comment]
Yes that ticket explains that the issue is in chef and the steps to take to workaround it by setting the necessary multi statements flag.

**Comment by travisLilleberg** [comment]
Hello,

I'm having the same problem and that link is dead. What are necessary flags and how do you set them? Thanks.

**Comment by travisLilleberg** [comment]
Just in case anyone else has the same issue, I solved it by breaking out the statements in the file and running them one by one.

```ruby
sql = File.read('my_export.sql')
statements = sql.split(/;$/)
statements.each { |stmt| ActiveRecord::Base.connection.execute(stmt) }
```

It would still be good to know those flags for the future though.
