### ISSUE TITLE
Please clarify Ruby on Rails compatibility

### ISSUE THREAD

**Issue by paulmenzel** [brianmario/mysql2#743]
The README contains the section below, regarding Ruby on Rails.

> ### Rails / Active Record
>
> * mysql2 0.4.x works with Active Record 4.2.5 and higher.
> * mysql2 0.3.x works with Active Record 3.1 and higher (the AR adapter is now included in AR proper).
> * mysql2 0.2.x includes an Active Record adapter compatible with AR 2.3 and 3.0, and should not be used with AR 3.1 or higher.

Does this mean, that with Ruby on Rails 4.2.0 mysql2 0.3.x should be used?

**Comment by sodabrew** [comment]
Yes, with Rails 4.2.0 you should use mysql2 0.3.x.

**Comment by paulmenzel** [comment]
@sodabrew, thank you for the quick response.

It’d be awesome, if such things could be mentioned in the [release notes](https://github.com/brianmario/mysql2/releases/tag/0.4.0).

Thank’s a lot for your work!

**Comment by paulmenzel** [comment]
Sorry, for being slow. But as the description says *mysql2 0.3.x works with Active Record 3.1 and higher*, does that mean, it also works with Active Record 4.2.5 and higher?

**Comment by sodabrew** [comment]
It does mean that, but I understand your point on the major versions and will update the README to clarify.

**Comment by paulmenzel** [comment]
Awesome. Thanks a lot for your help! I am leaving this issue open, so that it’ll be closed when the README is updated.

**Comment by sodabrew** [comment]
Does 6b42b77e6f0313ed394e862c4512550f3cdf4a49 resolve this concern?

**Comment by tilsammans** [comment]
Gem specs exist for this reason, are there any objections for not specifying `'activerecord', '< 5'` in the `0.3` branch?

**Comment by tilsammans** [comment]
... and a runtime dependency on `activerecord >= 4.2` in `master`?

**Comment by justincase** [comment]
ActiveRecord has `mysql2` as a dependency, not the other way around. I would prefer to stay ORM agnostic — otherwise you might need to add checks for each ORM/lib that decides to use `mysql2`. 

Adding a runtime dependency to ActiveRecord makes more sense imo.

**Comment by tilsammans** [comment]
Of course! I wasn't thinking...

**Comment by sodabrew** [comment]
That would introduce a dependency. Unfortunately there is no syntax for a conflict in the gemspec.
