### ISSUE TITLE
undefined method `pk_and_sequence_for' for #<ActiveRecord::ConnectionAdapters::Mysql2Adapter:0x0000000215abb0>

### ISSUE THREAD

**Issue by Chrisgo-75** [brianmario/mysql2#746]
I am trying to run a migration in a Rails 5.0.0.beta3 API application but am receiving a `undefined method "pk_and_sequence_for" ...` error.

I am using
mysql2 (0.4.3)
migration_comments (0.3.2)

My migration file looks like:

    class CreateApiKeys < ActiveRecord::Migration[5.0]
      # Command used to create this migration file:
      # $ rails g model ApiKey alt_apikey_id:integer access_token:string cunsumer_type:integer consumer_id:integer expires_at:datetime -p
    
      def change
        create_table :api_keys do |t|
          t.integer :alt_apikey_id, :null => false, unique: true
          t.string :access_token, :null => false, unique: true, :comment => "API key given to consumer."
          t.integer :cunsumer_type, :null => false, limit: 7, :default => '1', :comment => "Enum ... [default=>9 | cals_person_id=>1 | cals_apps_appl_id=>2 | ?]"
          t.integer :consumer_id, :null => false, :comment => "Specifies the consumer that the access_token belongs to."
          t.datetime :expires_at, :comment => "Specifies when the token expires."
    
          t.timestamps
        end
      end
    end

Is the error displaying due to MySQL2 gem or due to Rails? Any ideas why the error is displaying?
Thank you,
Chris

**Comment by kamipo** [comment]
`pk_and_sequence_for` was removed at https://github.com/rails/rails/pull/21686.

**Comment by jeremy** [comment]
Unrelated to mysql2 lib.

No exception backtrace to go on here, but it's probably caused by `migration_comments` using the method still: https://github.com/pinnymz/migration_comments/blob/master/lib/migration_comments/active_record/connection_adapters/mysql_adapter.rb#L18-L19

**Comment by Chrisgo-75** [comment]
@jeremy ... right on the money. I learned something new in that the backtrace not only shows errors from my code but also errors from the Gem's libraries that I include. An excerpt from the backtrace is below

    undefined method `pk_and_sequence_for' for #<ActiveRecord::ConnectionAdapters::Mysql2Adapter:0x000000030ee298>
    /usr/local/rvm/gems/ruby-2.2.4-rg251@api_cals/gems/migration_comments-0.3.2/lib/migration_comments/active_record/connection_adapters/mysql_adapter.rb:19:in `set_column_comment'
    /usr/local/rvm/gems/ruby-2.2.4-rg251@api_cals/gems/migration_comments-0.3.2/lib/migration_comments/active_record/connection_adapters/mysql_adapter.rb:76:in `execute_comment'
    /usr/local/rvm/gems/ruby-2.2.4-rg251@api_cals/gems/migration_comments-0.3.2/lib/migration_comments/active_record/connection_adapters/mysql_adapter.rb:50:in `block in create_table_with_migration_comments'
    /usr/local/rvm/gems/ruby-2.2.4-rg251@api_cals/gems/migration_comments-0.3.2/lib/migration_comments/active_record/connection_adapters/mysql_adapter.rb:49:in `each'

So in looking at kamipo's comment, it looks like #21686 has been re-opened?  Besides not using the "migration_comments" gem, how should I proceed? Should I open a ticket/issue with "migration_comments" Github repo or will a person from #21686 open a ticket/issue with "migration_comments" Github repo?

**Comment by jeremy** [comment]
Please do open an issue with migration_comments for Rails 5 support. If you're up for it, you could submit a pull request to add Rails 5 support, too—shouldn't take much, ask whether we `respond_to?` the new method and use it if available.

We won't be restoring the method since removal is the only reliable signal to plugins/libs that override it _expecting_ that their overridden method will be called… which it won't, causing more head-scratching.
