### ISSUE TITLE
`connect': SSL connection error: error:00000001:lib(0):func(0):reason(1) (Mysql2::Error)

### ISSUE THREAD

**Issue by aboutte** [brianmario/mysql2#753]
I have been using mysql2 for a number of years without issue.  Recently we have switched from directly connecting to mysql to using a [Tungsten](https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2111831).  Using mysql2 I am not longer able to connect to the same database that is now behind Tungsten.  

host running ruby script: Mac OS X
mysql version: mysql  Ver 14.14 Distrib 5.7.11, for osx10.10 (x86_64) using  EditLine wrapper
gem version: 0.4.4

My connection string:

```
core = Mysql2::Client.new(:host => "db-core-prd-vip-west.cloudatron.com", :database => "shopatron_db1", :username => "username", :password => "password")
```

The error I get:

```
/Users/andyboutte/.chefdk/gem/ruby/2.1.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:87:in `connect': SSL connection error: error:00000001:lib(0):func(0):reason(1) (Mysql2::Error)
	from /Users/andyboutte/.chefdk/gem/ruby/2.1.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:87:in `initialize'
	from ./proxy.rb:11:in `new'
	from ./proxy.rb:11:in `<main>'
```

I have attached a packet capture of this interaction.  Interesting things I see in the packet capture:

- packet 4 you can see the server greeting is "5.5.47-37.7-log-tungsten"
- packet 6 you can see that no username is sent

Do I need to add some configuration to get this to work? Or does mysql use the server greeting for some internal configuration?

**Comment by aboutte** [comment]
Packet capture 

[mysql2.pcapng.zip](https://github.com/brianmario/mysql2/files/255572/mysql2.pcapng.zip)

**Comment by sodabrew** [comment]
It's failing with an SSL error. Is your Tungsten Replicator configured to require SSL connections?

**Comment by aboutte** [comment]
@sodabrew No we do not use ssl on our connectors.  

But I should have tried mysql before opening this issue.  

```
~ DEVOPS $ mysql -h db-core-prd-vip-west.cloudatron.com -u aboutte -p
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 2026 (HY000): SSL connection error: error:00000001:lib(0):func(0):reason(1)
```

It turns out that mysql binary I am using from homebrew has an issue:

https://github.com/Homebrew/legacy-homebrew/issues/46055

**Comment by sodabrew** [comment]
Thanks for chasing this down and sharing the links, glad you've got it working now!
