### ISSUE TITLE
 An error case of Ubuntu16.04 

### ISSUE THREAD

**Issue by hhoshina** [brianmario/mysql2#756]
When you use the gem mysql2 in ubuntu16.04, an error that there is no libmysqlclient.so.18.
The ubuntu16.04 of the package , libmysqlclient.so.18 is not installed .
In Ubuntu16.04 of environment , or it can run the mysql2 ?

Thanks. 

--- Error Message --------
/usr/local/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mysql2-0.4.4/lib/mysql2.rb:31:in `require': **libmysqlclient.so.18: cannot open shared object file**: No such file or directory - /usr/local/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mysql2-0.4.4/lib/mysql2/mysql2.so (LoadError)
	from /usr/local/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mysql2-0.4.4/lib/mysql2.rb:31:in `<top (required)>'

**Comment by sodabrew** [comment]
Looks like a missing MySQL client library. Have you removed the mysql-client package, or perhaps compiled on box A and deployed onto box B that does not have this package?

**Comment by hhoshina** [comment]
Thanks.

I installed mysql ver5.6 on ubuntu16.04. It was successful in the following manner.
http://makandracards.com/makandra/39899-install-mysql-5-6-in-ubuntu-16-04
