### ISSUE TITLE
Timed-out queries keep running

### ISSUE THREAD

**Issue by kdole** [brianmario/mysql2#762]
My (naive?) assumption was that `read_timeout` would kill the query, but this appears not to be the case:

``` ruby
client = Mysql2::Client.new({read_timeout: 1, write_timeout: 1, connect_timeout: 1, reconnect: true, database: "test", username: "root", host: "localhost"})

connection_id = client.query("SELECT CONNECTION_ID()").first.values.first

begin
  client.query("SELECT sleep(10)")
rescue Mysql2::Error
end

# shows the "SELECT sleep(10)" is still running.
client.query("SHOW FULL PROCESSLIST").each do |row|
  puts row.inspect if row["Id"] == connection_id
end
```

My primary desire for a timeout setting is to protect the database from an accumulation of slow queries, which could affect all clients.

I know I can manually issue `KILL QUERY #{connection_id}`, but it seems like this would be best implemented in the adapter itself.

If not, maybe the documentation should be updated to warn users that these timeout settings don't protect the server?

**Comment by sodabrew** [comment]
This is a limitation in MySQL. There is no reasonable way to implement this in the adapter.

Starting in MySQL 5.7.8 and higher, you can set a server variable for maximum execution time of any query, and can set a maximum time on individual queries in the query string:

http://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_max_execution_time
http://dev.mysql.com/doc/refman/5.7/en/optimizer-hints.html#optimizer-hints-execution-time

**Comment by kdole** [comment]
Thanks for the reply and the tip on execution time in 5.7. When we upgrade to 5.7 I guess it might make more sense not to set a timeout in the adapter, or modify the adapter so that it sets the maximum execution time.

I'm guessing something like the following wouldn't count as "reasonable"? It attempts to mimic what happens when you ctrl-C a query in the console.

```ruby
module Mysql2
  class Client
    def query(sql, options = {})
      @connection_id ||= client.query("SELECT CONNECTION_ID()").first["CONNECTION_ID()"]
      begin
        _query(sql, @query_options.merge(options))
      rescue Mysql2::Error => e
        # check e was a timeout and :reconnect is true
        _query("KILL QUERY #{@connection_id}")
        raise e
      end
    end
  end
end
```

**Comment by carsonreinke** [comment]
@kdole Have you actually tried something like this?  It would be so great to kill queries when terminating connections.

**Comment by sodabrew** [comment]
You could implement that behavior in your application level code, but I would not bake it into the driver.

**Comment by carsonreinke** [comment]
Yeah, I might put in a PR for ActiveRecord, something like `with_query_kill`.

Is there anyway to prevent connection termination after a time out?

**Comment by sodabrew** [comment]
You can make a best-effort to prevent the timeout. You can connect to the server, and ask what the session timeouts are, and then set up timers in your application to call `Client#ping` to keep the connection alive. This will not be 100% foolproof, and the purpose of the timeouts is fundamentally to kill connections that have gone bad or idled inappropriately, to prevent the server from resource starvation.

For example, http://dev.mysql.com/doc/refman/5.5/en/server-system-variables.html#sysvar_net_read_timeout

**Comment by kdole** [comment]
@carsonreinke Not yet. I may try it next week. Thoughts on the above approach appreciated.

**Comment by carsonreinke** [comment]
I did something like this within the context of ActiveRecord:

```ruby
def with_query_kill(&block)
    connection_id = self.select_value('SELECT CONNECTION_ID();')
    begin
      return yield
    rescue ActiveRecord::StatementInvalid => error
      #Timeout?
      raise unless error&.original_exception.is_a?(Mysql2::Error) && error.message =~ /[tT]imeout/

      begin
        self.reconnect!()
        self.execute("KILL QUERY #{connection_id};")
      rescue
        self.logger.warn($!.inspect())
      end
      raise error
    end
  end
```
