### ISSUE TITLE
REQUIRE_CONNECTED should be defined in client.c, not client.h

### ISSUE THREAD

**Issue by jeremyevans** [brianmario/mysql2#763]
The `REQUIRE_CONNECTED` macro is currently defined in `client.h`, but only used in `client.c`.  It calls the `REQUIRE_INITIALIZED` macro, which is defined in `client.c`, so I don't think it is usable outside `client.c`.  Alternatively, `REQUIRE_INITIALIZED` could be moved to `client.h`.

**Comment by sodabrew** [comment]
Nice catch, scheduled to take a look at this for next release.
