### ISSUE TITLE
Malformed packet

### ISSUE THREAD

**Issue by stilney** [brianmario/mysql2#769]
I'm attempting to connect to a MySQL 5.0.22 server, but I'm get the following error:
`Mysql2::Error: Malformed packet`
Is this due to the MySQL server being a really old version? If so, is there an older version of the mysql2 gem that will work with MySQL 5.0.2.2?

I'm currently using the mysql2 0.4.4 gem

**Comment by sodabrew** [comment]
mysql2 simply wraps your libmysqlclient library; check if your client machine has a very different version than your server?

**Comment by stilney** [comment]
Thank you. I would have had to cut through a lot of red tape to upgrade the version on the server. Downgrading the version on my development machine did the trick. Thanks!
