### ISSUE TITLE
Add support for per prepared statement query options

### ISSUE THREAD

**Issue by jeremyevans** [brianmario/mysql2#774]
I just added support for using mysql2 0.4+ native prepared statements to Sequel (https://github.com/jeremyevans/sequel/commit/5066f1625ac0234f51664b2f9be156984301f68c).  Based on my experiences with it, I think improvements to the API would be beneficial.

In the general API to send queries to the server (`Client#query`), you can specify options on a per-query basis.  However, the prepared statements API doesn't appear to support that.  `Client#prepare` only takes the sql, not an options hash, and `Statement#execute` only takes arguments, not an options hash.  `Statement` gets the query options to use by copying the `Client`'s query options inside of `Statement#execute`. `Result` stores the query options in an instance variable, but does not offer a method to access them.

To work around this issue, you need to modify the `Client`'s query options before calling `Statement#execute`, then reset the `Client`'s query options after.  This is what Sequel does in order to make sure that the behavior for prepared statements matches the behavior for non-prepared statements in regards to which options are set.

The other possible way to work around this is to modify the query options in the `Result`, but that has issues:

1. It's ugly (`result.instance_variable_get(:@query_options).merge!(options)`)
2. It causes warnings in `Result#initialize` if the `Client` doesn't have `:cache_rows=>true` (https://github.com/brianmario/mysql2/blob/master/ext/mysql2/result.c#L890)
3. It can't handle streaming, since that happens before the `Result` is created (https://github.com/brianmario/mysql2/blob/master/ext/mysql2/statement.c#L366-L370)

I think the best way to fix this would be to copy the `Client`'s query options to the `Statement` in `Statement#initialize`, and add `Statement#query_options`.  Alternatively, you could add a `Statement#execute_with_options` method that accepted an options hash and merged it into the `Client`'s query options.

**Comment by sodabrew** [comment]
Take a look at #640 and let me know if that looks reasonable to you.

**Comment by jeremyevans** [comment]
@sodabrew That is exactly what I had in mind.  Sorry for not searching first, I should have just commented on that issue.  I'm going to close this now as it is a duplicate, but we can continue this discussion if you want.  Is there a reason you have been hesitant to merge #640?

**Comment by sodabrew** [comment]
I wasn't sure if it was actually needed, or if it even made sense to store different query options into each statement. It's also not obvious to me whether a change to query options on the Client itself should override the options on a Statement that was created previously.

**Comment by jeremyevans** [comment]
I tend to favor the copying approach, so that after the Statement is created, future changes to the Client's options are not picked up, but you could always just merge the Statement's options into the Client's options on every call to `Statement#execute` if you want it to pick up changes in the Client's options.

**Comment by kamipo** [comment]
I'd like to support for per `execute` query options for Active Record because AR caches prepared statements in statement pool.
Ref https://github.com/rails/rails/pull/25507.

**Comment by sodabrew** [comment]
So I finally figured this out! Ruby 1.9.3 added `:` to `rb_scan_args`. Easily implemented in #912.
