### ISSUE TITLE
Gem keeps looking for libmysqlclient18 with mysql 5.7

### ISSUE THREAD

**Issue by stiller-leser** [brianmario/mysql2#781]
We are using the Gem on one of our testing servers with mysql 5.7 and Ubuntu 16.04 installed. For some reasons mysql 0.4.4 keeps looking for libmysqlclient18 instead of *20 as would be appropriate. As 16.04 makes it rather difficult to install mysql 5.6 I would prefer to use the *20-lib which is also installed. I tried to rebuild the gem using `uninstall` and `pristine`, `bundle install --force` as well as specifying the mysql_config of mysql 5.7 using a build configuration.

Any hints as to how I might influence the selection otherwise?

**Comment by heysamhey** [comment]
`wget http://launchpadlibrarian.net/212189159/libmysqlclient18_5.6.25-0ubuntu1_amd64.deb
sudo dpkg -i libmysqlclient18_5.6.25-0ubuntu1_amd64.deb`

This works...

**Comment by sodabrew** [comment]
@stiller-leser You're probably compiling the mysql2 gem binaries on a system with a different libmysqlclient than the system you are deploying to. Compile on systems with equivalent libraries before copying over the binaries.

**Comment by stiller-leser** [comment]
Hey,
@heysamhey thanks for the answer. Yep really just a workaround. It's appreciated though.
@sodabrew Thanks, that hits really close to home. I was actually compiling the gem on the same system (the deployment system). Turns out that reinstalling Gems (or rebuilding for that matter) in Jenkins build scripts does not seem to work as anticipated. The solution was to use a `sudo -u jenkins gem pristine mysql2` on the system. 

I'll close the issue now. Thanks for all the good work!
