### ISSUE TITLE
install the mysql2 adapter

### ISSUE THREAD

**Issue by sspr28** [brianmario/mysql2#786]
I am trying to migrate mysql to mongo using mongify.I am getting the below errors
D:\Public\Ruby23-x64>mongify check database.config
d:/Public/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mysql2-0.3.18-x64-mingw32/lib/mysql2.rb:23: warning: already initialized constant LoadLibrary
d:/Public/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mysql2-0.3.18-x64-mingw32/lib/mysql2.rb:23: warning: previous definition of LoadLibrary was here
d:/public/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `require': Please install the mysql2 adapter:`gem install activerecord-mys
ql2-adapter`(cannot load such file -- mysql2/2.3/mysql2) (LoadError)
        from d:/public/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in`rescue in require'
        from d:/public/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from d:/Public/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in`block in require'
        from d:/Public/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:236:in `load_dependency'
        from d:/Public/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in`require'
        from d:/Public/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mysql2-0.3.18-x64-mingw32/lib/mysql2/mysql2.rb:2:in `<top (required)>'
        from d:/public/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in`require'
        from d:/public/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from d:/Public/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in`block in require'
        from d:/Public/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:236:in `load_dependency'
        from d:/Public/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in`require'
        from d:/Public/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mysql2-0.3.18-x64-mingw32/lib/mysql2.rb:31:in `<top (required)>'
        from d:/public/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in`require'
        from d:/public/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from d:/public/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in`require'
        from d:/Public/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `block in require'
        from d:/Public/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:236:in`load_dependency'
        from d:/Public/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `require'
        from d:/Public/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/mysql2_adapter.rb:4:in`<top (required)>'
        from d:/public/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from d:/public/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in`require'
        from d:/Public/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `block in require'
        from d:/Public/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:236:in`load_dependency'
        from d:/Public/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `require'
        from d:/Public/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/abstract/connection_specification.rb:50:in`r
esolve_hash_connection'
        from d:/Public/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/abstract/connection_specification.rb:29:in `s
pec'
        from d:/Public/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/abstract/connection_specification.rb:130:in`
establish_connection'
        from d:/Public/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongify-1.2.4/lib/mongify/database/sql_connection.rb:40:in `setup_connection_adapter'
        from d:/Public/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongify-1.2.4/lib/mongify/database/sql_connection.rb:56:in`has_connection?'
        from d:/Public/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongify-1.2.4/lib/mongify/cli/command/worker.rb:95:in `check_sql_connection'
        from d:/Public/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongify-1.2.4/lib/mongify/cli/command/worker.rb:64:in`execute'
        from d:/Public/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongify-1.2.4/lib/mongify/cli/application.rb:28:in `execute!'
        from d:/Public/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongify-1.2.4/bin/mongify:15:in`<top (required)>'
        from d:/Public/Ruby23-x64/bin/mongify:22:in `load'
        from d:/Public/Ruby23-x64/bin/mongify:22:in`<main>'

But i have mysql adapter and mysql2 . 

D:\Public\Ruby23-x64>gem list

**\* LOCAL GEMS ***

actioncable (5.0.0.1)
actionmailer (5.0.0.1)
actionpack (5.0.0.1)
actionview (5.0.0.1)
activejob (5.0.0.1)
activemodel (5.0.0.1, 3.2.22.5)
activerecord (5.0.0.1, 3.2.22.5)
activerecord-mysql2-adapter (0.0.3)
activesupport (5.0.0.1, 3.2.22.5)
arel (7.1.2, 3.0.3)
bigdecimal (1.2.8)
bson (1.12.5, 1.10.2)
bson_ext (1.10.2)
builder (3.2.2, 3.0.4)
bundler (1.13.1)
columnize (0.9.0)
concurrent-ruby (1.0.2)
debugger-linecache (1.2.0)
debugger-ruby_core_source (1.3.8)
did_you_mean (1.0.0)
erubis (2.7.0)
globalid (0.3.7)
highline (1.7.8)
i18n (0.7.0)
io-console (0.4.5)
json (2.0.2, 1.8.3)
loofah (2.0.3)
mail (2.6.4)
method_source (0.8.2)
mime-types (3.1)
mime-types-data (3.2016.0521)
mini_portile2 (2.1.0)
minitest (5.8.3)
mongify (1.2.4)
mongo (1.10.2)
multi_json (1.12.1)
mysql2 (0.4.4 x64-mingw32, 0.3.18 x64-mingw32)
net-telnet (0.1.1)
nio4r (1.2.1)
nokogiri (1.6.8 x64-mingw32)
pkg-config (1.1.7)
power_assert (0.2.6)
psych (2.0.17)
rack (2.0.1)
rack-test (0.6.3)
rails (5.0.0.1)
rails-dom-testing (2.0.1)
rails-html-sanitizer (1.0.3)
railties (5.0.0.1)
rake (10.4.2)
rdoc (4.2.1)
rubygems-update (2.6.6)
sprockets (3.7.0)
sprockets-rails (3.2.0)
test-unit (3.1.5)
thor (0.19.1)
thread_safe (0.3.5)
tzinfo (1.2.2, 0.3.51)
websocket-driver (0.6.4)
websocket-extensions (0.1.2)

could anyone of you help me to fix the issue. since i am not familiar in ruby/rails/mongify..

Thanks,
Prabhu

**Comment by sodabrew** [comment]
You don't need the activerecord-mysql2-adapter gem separately, it's been included with activerecord since AR 3.1.

**Comment by sspr28** [comment]
Thanks for your reply...but am getting the above errors for mongify check daatabase.config..

I tried to re-install the ruby and dev kit and am getting the below error as part development kit steps.

D:\Public\Ruby>cd D:\Public\Devkit

D:\Public\Devkit>ruby dk.rb install
[INFO] Skipping existing gem override for 'D:/Public/Ruby'
[WARN] Skipping existing DevKit helper library for 'D:/Public/Ruby'

**Comment by sodabrew** [comment]
Ah, sorry, here's the issue:
```
cannot load such file -- mysql2/2.3/mysql2 (LoadError) from d:/public/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:inrescue in require'
```

You have available:
```
mysql2 (0.4.4 x64-mingw32, 0.3.18 x64-mingw32)
```

Of these, the 0.3.18 version is getting selected:
```
d:/Public/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mysql2-0.3.18-x64-mingw32/lib/mysql2.rb:23: warning: already initialized constant LoadLibrary
```

The published Windows package for mysql2 0.3.18 does not include binaries for Ruby 2.3.

**Comment by sspr28** [comment]
when i am tryin to do install ruby dk.rb install , am getting the below warning.

[INFO] Updating convenience notice gem override for 'D:/Public/ruby'
[INFO] Installing 'D:/Public/ruby/lib/ruby/site_ruby/devkit.rb'

Is it ignorable or how to fix this..I tried multiple time to de-install and install ruby but am getting the same warning message...

**Comment by sodabrew** [comment]
Those are not warnings, they are INFO messages. Why are you trying to uninstall ruby? Do this:

```
gem uninstall mysql2 -v 0.3.18
```

**Comment by sspr28** [comment]
Thanks ..Let me check and will update you if any issues..

**Comment by sspr28** [comment]
After unistall also am getting the same errors...Is it something related to configuration.

**Comment by sodabrew** [comment]
Do you still need help? Were you able to get the gem working on your system?
