### ISSUE TITLE
Support per-session max_statement_time

### ISSUE THREAD

**Issue by mattyb** [brianmario/mysql2#787]
Introduced in 5.7.4, provides server-side timeout of select statements

http://mysqlserverteam.com/server-side-select-statement-timeouts/
http://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_max_statement_time

Related to #762

**Comment by jeremy** [comment]
No need for special support, huh? Issue the SET after you connect or embed it into specific queries you'd like to time out.

**Comment by sodabrew** [comment]
No special support is required, you just need to set the variable:

```
client = Mysql2::Client.new(login credentials)

# Set the max execution time for all queries in this session:
client.query("SET SESSION MAX_EXECUTION_TIME=2000")

# Set the max execution time for the immediate query only:
client.query("SELECT /*+ MAX_EXECUTION_TIME(1000) */ * FROM table")

# Set the max execution time for the session even if a reconnect occurs:
client = Mysql2::Client.new(login credentials...,
    init_command: "SET @@SESSION.MAX_EXECUTION_TIME = 2000",
    reconnect: true)
```

**Comment by mattyb** [comment]
I see now. Thank you!

**Comment by sodabrew** [comment]
No sweat, it's a good question and a common problem (has been for many years with MySQL queries continuing amok even after the client is forcibly disconnected) that it's probably worth a README note. (That said the readme is getting awfully long...)
