### ISSUE TITLE
Auto-detect OpenSSL installed with Homebrew?

### ISSUE THREAD

**Issue by indirect** [brianmario/mysql2#788]
I've been having trouble installing both 0.3.21 and 0.4.4 on macOS Sierra 10.12.0. It seems like (for reasons that I don't really understand), `ld` was unable to find the homebrew-installed openssl (located in `/usr/local/opt/openssl`). The characteristic error message was `ld: library not found for -lssl`. Any given install attempt looked something like this:

```
$ brew install openssl
$ brew install mysql
$ gem install mysql2
Building native extensions.  This could take a while...
[... less relevant stuff ...]
linking shared-object mysql2/mysql2.bundle
ld: library not found for -lssl
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [mysql2.bundle] Error 1

make failed, exit code 2
```

My first assumption was that I could fix this by exporting `LDFLAGS` including , including `-L/usr/local/opt/openssl/lib`, as suggested by Homebrew. Unfortunately, it seems like neither the mysql2 extconf.rb or the resulting Makefile respect an exported `$LDFLAGS`, and so that didn't fix anything at all.

Then, I discovered that manually editing the `Makefile` to add the `-L` argument worked, changing this line:

```
LIBS =  -L/usr/local/Cellar/mysql/5.7.15/lib -lmysqlclient -lssl -lcrypto  -lpthread -lgmp -ldl -lobjc 
```
into this line instead:

```
LIBS =  -L/usr/local/Cellar/mysql/5.7.15/lib -L/usr/local/opt/openssl/lib -lmysqlclient -lssl -lcrypto  -lpthread -lgmp -ldl -lobjc 
````

and suddenly everything worked. But there's no option to allow me to pass in libs while building the gem, so I was stuck for a while. Eventually I figured out that this particular extconf accepts an additional lib argument in the form `gem install mysql2 -- --with-opt-lib=/usr/local/opt/openssl/lib`. Suddenly, installing the gem was successful!

It would be super cool if extconf could either provide a generic option for LDFLAGS, or an option for the SSL lib, or even just automatically checked the default homebrew OpenSSL location of `/usr/local/opt/openssl/lib` and linked it from there if it's present.

Thanks!

**Comment by zubin** [comment]
For those with a custom homebrew path:

    gem install mysql2 -- --with-opt-lib=$HOMEBREW_ROOT/opt/openssl/lib

**Comment by sodabrew** [comment]
Adding `$HOMEBREW_ROOT` as a prefix to the default search paths sounds reasonable to me at https://github.com/brianmario/mysql2/blob/master/ext/mysql2/extconf.rb#L38 but that's only going to help if MySQL tells us where it linked to its SSL libraries.

Can you try `gem install mysql2 -- --with-mysql-config=$HOMEBREW_ROOT/opt/bin/mysql_config` and see if that side-steps the SSL issue?

**Comment by zubin** [comment]
@sodabrew No cigar:

```
$ gem install mysql2 -v0.3.21 -- --with-mysql-config=$HOMEBREW_ROOT/opt/bin/mysql_config
Fetching: mysql2-0.3.21.gem (100%)
Building native extensions with: '--with-mysql-config=/opt/boxen/homebrew/opt/bin/mysql_config'
This could take a while...
ERROR:  Error installing mysql2:
        ERROR: Failed to build gem native extension.

    current directory: /opt/rubies/2.2.5/lib/ruby/gems/2.2.0/gems/mysql2-0.3.21/ext/mysql2
/opt/boxen/rbenv/versions/2.2.5/bin/ruby -r ./siteconf20161018-14288-ari04r.rb extconf.rb --with-mysql-config=/opt/boxen/homebrew/opt/bin/mysql_config
checking for ruby/thread.h... yes
checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
checking for rb_thread_blocking_region()... no
checking for rb_wait_for_single_fd()... yes
checking for rb_hash_dup()... yes
checking for rb_intern3()... yes
-----
Cannot find mysql_config at /opt/boxen/homebrew/opt/bin/mysql_config
-----
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/opt/boxen/rbenv/versions/2.2.5/bin/$(RUBY_BASE_NAME)
        --with-mysql-dir
        --without-mysql-dir
        --with-mysql-include
        --without-mysql-include=${mysql-dir}/include
        --with-mysql-lib
        --without-mysql-lib=${mysql-dir}/lib
        --with-mysql-config

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /opt/boxen/rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/mysql2-0.3.21/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /opt/boxen/rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/mysql2-0.3.21 for inspection.
Results logged to /opt/boxen/rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/mysql2-0.3.21/gem_make.out
```

**Comment by sodabrew** [comment]
Probably just a wrong path for mysql_config, I made it up off the top of my head (I use MacPorts, just saying) :)

`find $HOMEBREW_ROOT -name mysql_config` and use that?

**Comment by zubin** [comment]
@sodabrew Ah that's better (without `/opt`):

```
$ gem install mysql2 -v0.3.21 -- --with-mysql-config=$HOMEBREW_ROOT/bin/mysql_config
Fetching: mysql2-0.3.21.gem (100%)
Building native extensions with: '--with-mysql-config=/opt/boxen/homebrew/bin/mysql_config'
This could take a while...
Successfully installed mysql2-0.3.21
1 gem installed
```

**Comment by sodabrew** [comment]
Please let me know if mysql2 0.4.5 works out of the box with your non-default `$HOMEBREW_PATH`.

**Comment by zubin** [comment]
Looks good, thanks!

```
$ echo $HOMEBREW_ROOT
/opt/boxen/homebrew
$ gem install mysql2 -v0.4.5
Fetching: mysql2-0.4.5.gem (100%)
Building native extensions.  This could take a while...
Successfully installed mysql2-0.4.5
1 gem installed
```

**Comment by sodabrew** [comment]
Awesome! Thank you!

**Comment by sj26** [comment]
Unfortunately @zubin's issue here wasn't really the originally reported problem.

I'm having the originally reported problem: macOS Sierra+ doesn't ship with accessible ssl or crypto so installing usually requires separately compiled openssl using homebrew openssl which isn't in the default library paths, and is "cellar-only" in homebrew so also isn't in `$HOMEBREW_PREFIX/lib`, it must be manually referenced, as mentioned:

```
gem install mysql2 -- --with-opt-lib=/usr/local/opt/openssl/lib
```

It's be great if extconf could detect this and compensate. Even asking ruby where it's libssl is would be great:

```
$ irb -r openssl
irb> $LOADED_FEATURES.grep(/openssl.bundle/).first
=> "/usr/local/rbenv/versions/2.4.2/lib/ruby/2.4.0/x86_64-darwin16/openssl.bundle"
irb> IO.popen(["otool", "-L", _], &:read).split.grep(/libssl/).first
=> "/usr/local/opt/openssl/lib/libssl.1.0.0.dylib"
```

**Comment by zahhar** [comment]
As of today Homebrew defaults to MySQL 8.0, OpenSSL 1.1 and mysql2 0.5 that work great all together out of the box. However to upgrade of my legacy applications from Rails 3.2 to more recent versions I had to setup local environment on my MacOS BigSur 11.1. 

My goal was to install mysql2 gem version 0.3.x (this is only one allowing smooth migration from Rails 3.2 to Rails 4.2 through versions 4.0 and 4.1) together with mySQL 5.x. Both of them in turn depend on OpenSSL 1.0

Here is what worked for me:

```
// Clean-up all your faulty attempts you did before
// Homebrew does not store openssl 1.0 anymore, so I had to find alternative — openssl1.0.2t 
wget https://github.com/tebelorg/Tump/releases/download/v1.0.0/openssl.rb
brew install openssl.rb

brew install mysql@5.7
brew link mysql@5.7 --force
brew install mysql-client@5.7
// NB! Pay close attention to path where you have mysql_config and openssl 1.0 installed
gem install mysql2 -v 0.3.21 -- --with-mysql-config=/usr/local/bin/mysql_config --with-ldflags=-L/usr/local/Cellar/openssl/1.0.2t/lib --with-cppflags=-I/usr/local/Cellar/openssl/1.0.2t/include

```

Voilá:

`Building native extensions with: '--with-mysql-config=/usr/local/bin/mysql_config --with-ldflags=-L/usr/local/Cellar/openssl/1.0.2t/lib --with-cppflags=-I/usr/local/Cellar/openssl/1.0.2t/include'
This could take a while...
Successfully installed mysql2-0.3.21
Parsing documentation for mysql2-0.3.21
Installing ri documentation for mysql2-0.3.21
Done installing documentation for mysql2 after 0 seconds
1 gem installed`
