### ISSUE TITLE
Not connecting to my database

### ISSUE THREAD

**Issue by hugofsousa** [brianmario/mysql2#790]
I was trying to use heroku to connect to my database, with the gem "mysql2" of ruby. Setting by DATABASE_URL. Unfortunately, I`m getting the error message:

Can't connect to MySQL server on 'mysql20.redehost.com.br' 

And I tried to make the connection again, via heroku`s rails console:

client = Mysql2::Client.new(host: "mysql20.redehost.com.br",username: "myusername",password: "mypassword" ,port: "41890",database: "mydatabase")

But I got the same error. Any suggestion?

**Comment by sodabrew** [comment]
Can you connect with a command-line mysql client? It sounds like you should run through typical MySQL troubleshooting steps first.
