### ISSUE TITLE
Connecting to MYSQL via config file options in database.yml

### ISSUE THREAD

**Issue by sgoyal1012** [brianmario/mysql2#801]
Hi Team

I am trying to connect to MYSQL using database.yml in the config section; ala https://github.com/brianmario/mysql2#reading-a-mysql-config-file

I tried what the above link suggests on the IRB, it does work via the following command:

```
Mysql2::Client.new(:default_file => '/etc/test.cnf', :default_group => 'client')
```

/etc/test.cnf is a standard mysql cnf file--> https://gist.github.com/sgoyal1012/192f34f7ff8e549c9889ea96e7213e1c#file-cnf-file

However trying it like this (please look at the environment 'development'): https://gist.github.com/sgoyal1012/192f34f7ff8e549c9889ea96e7213e1c does not seem to work. It does not appear to be reading the params 'default_file' and 'default_group'.

![screen shot 2016-10-20 at 3 28 40 pm](https://cloud.githubusercontent.com/assets/7093391/19580293/2df8a224-96da-11e6-9d9a-05ca4ef7b2cf.png)

Am I doing this right , i.e. are the 'default_file' and 'default_group' options supported in database.yml? 
The conf file is a standard mysql config file; I have tested it to work via

```
sudo mysql --defaults-file='/etc/test.cnf'
```

Thanks a lot!

Sahil

**Comment by sodabrew** [comment]
Your YAML appears to be valid. Settings in the config file are overridden by settings in the YAML hash, so the username will come from your DEFAULTS hash and not from the config file.

**Comment by sgoyal1012** [comment]
Thanks a lot, I should have raised an issue earlier.
That seems to be exactly the problem over here. Closing the issue.

**Comment by sgoyal1012** [comment]
Hi @sodabrew I tried your approach and seems there is a problem still. Here is the config file after moving the 'username' and 'host' out of the defaults section, so that the enviroment (test) picks it up from the cnf file. https://gist.github.com/sgoyal1012/192f34f7ff8e549c9889ea96e7213e1c

It however, still seems to try to connect as root and to localhost. Could you verify if the database.yml looks fine to you?
I am using mysql2 gem version 0.3.18.

**Comment by sgoyal1012** [comment]
Followup: The problem is here: https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb#L14

The adapter just 'assumes' the user to be root, if not specified in the YML file for an environment. Not sure why that would be done, but that's how it is.

**Comment by sodabrew** [comment]
Oh wow, I didn't realize the AR adapter had a default username of `root`. That's a real bummer! I support you could supply the username in your yaml, and the password in the client config file as a workaround? The upside is that the client config file can be encrypted, so at least the password has an extra layer of over-the-shoulder protection.

**Comment by sodabrew** [comment]
I went back and looked at the history of the mysql2_adapter in Rails, and found that setting the default username to`root` has been there for 6+ years: https://github.com/rails/rails/commit/70b9db173e958944fcf61ac8514408fba9ef0c9a

**Comment by sodabrew** [comment]
Rails accepted the patch in just a few hours! Not having the root user as the database default should appear in Rails 5.1.0 when it lands. I'll close this ticket now, and we can keep tabs on the Rails development process to see if there's any future changes that affect this.

**Comment by sgoyal1012** [comment]
Great, thanks! Almost had lost track of this :). Thanks for working on this, could you post a link to the patch here?
