### ISSUE TITLE
Mysql2::Client::SECURE_CONNECTION

### ISSUE THREAD

**Issue by lrpasquetto** [brianmario/mysql2#803]
Hello!

I'm an old project that is in the air. Cloned it locally and not funcionamais the **"rails s"**

Accuses failure mysql2. Can anyone help?

`gem 'rails', '3.2.3'`
`gem 'mysql2', '~> 0.3.1'`

Error:
`Gem Load Error is: uninitialized constant Mysql2::Client::SECURE_CONNECTION`

Unfortunately I can not update the rails, I have to work in this version.

**Comment by sodabrew** [comment]
You've upgraded MySQL, please update the mysql2 gem to a newer version in the 0.3.x series (`bundle update mysql2` should do the trick).

**Comment by deepakmahakale** [comment]
Changing the version to `~> 0.3.21` fixed it for me

```ruby
gem 'mysql2', '~> 0.3.21'
```

**Comment by Huzefa-anchanto** [comment]
@sodabrew: `bundle update mysql2` worked for me !!!
