### ISSUE TITLE
How to start rails  while mysql is not started?

### ISSUE THREAD

**Issue by melotusme** [brianmario/mysql2#808]
It would crash  when execute `bundle exec rails s`  while mysqld is not started?
How to avoid that?

**Comment by sodabrew** [comment]
It shouldn't crash, but it throw errors due to failure to connect. You can post the error.

**Comment by melotusme** [comment]
This is the error `mysql2-0.3.21/lib/mysql2/client.rb:70:in `connect': Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2) (Mysql2::Error)`

**Comment by sodabrew** [comment]
If the Rails server and the MySQL server are on different machines, then you will never be able to connect using a local socket, which is what the error message means: `Can't connect to local MySQL server through socket '/tmp/mysql.sock'`. You need to configure your Rails app to connect to MySQL using the hostname or IP address of the other server.

**Comment by melotusme** [comment]
Yes, the error is in my local machine, so I use the word `like this error`,sorry, I did not find the corresponding error informations

**Comment by sodabrew** [comment]
Good luck! Please close this issue when you've resolved the problem.
