### ISSUE TITLE
Special Caracteres Not Working

### ISSUE THREAD

**Issue by hugofsousa** [brianmario/mysql2#809]
My database server just alow passwords with at least one special caracter. But I can`t connect with anyone, I had already tried: #, !, ?, *, &, %, @

**Comment by sodabrew** [comment]
Special characters work fine. Let's figure out what's going wrong. Please explain how you are providing the password into the `Mysql2::Client.new()` constructor. Are you using Rails? Are you using a one-off script? Are you using a YAML config file or a DATABASE_URL? Are you using a mysql config file?

**Comment by sodabrew** [comment]
Closing due to lack of information.
