### ISSUE TITLE
[Redhat linux] mysql2 0.4.5 throwing undefined symbol: __gxx_personality_v0 while building rake

### ISSUE THREAD

**Issue by venki09** [brianmario/mysql2#810]
I am uplifting my mysql2 from 0.3.18 to 0.4.5 and while building the rake task ```bundle exec rake db:migrate``` I am getting the following error

```
/vendor/bundle/ruby/2.2.0/extensions/x86_64-linux/2.2.0-static/mysql2-0.4.5/mysql2/mysql2.so: undefined symbol: __gxx_personality_v0
```

I am using Rake version 11.2.2 and bundler gem version 1.13.6 . Has anyone seen this issue before? let me know if more information is needed. Thanks

What did I try?
I was initially on ruby-2.1.0 and I upgraded it to 2.2.x thinking there might be some ruby version mismatch when the gem was built and it didn't fix the issue as well. The version of redhat is RHEL 6.6

**Comment by sodabrew** [comment]
This error is coming from GCC. For some reason you compiled mysql2 with a C++ compiler but not a C++ linker. Note that mysql2 is C code only, so I'm not sure why it was compiled as C++ for you. Is it possible that you used a case-insensitive filesystem and accidentally uppercased the filenames? (i.e. `gcc MYSQL2.C` would be assumed to be a C++ file, whereas `gcc mysql2.c` is assumed to be C).

**Comment by venki09** [comment]
The mkmf.rb generates the Makefile as specified by the [extconf.rb](https://github.com/brianmario/mysql2/blob/0.4.5/ext/mysql2/extconf.rb#L257) and when I look at the Makefile, it says that .c files are compiled in C. Entries in Makefile

```
.SUFFIXES: .c .m .cc .mm .cxx .cpp .o .S

.cc.o:
        $(ECHO) compiling $(<)
        $(Q) $(CXX) $(INCFLAGS) $(CPPFLAGS) $(CXXFLAGS) $(COUTFLAG)$@ -c $<

.cc.S:
        $(ECHO) translating $(<)
        $(Q) $(CXX) $(INCFLAGS) $(CPPFLAGS) $(CXXFLAGS) $(COUTFLAG)$@ -S $<

.mm.o:
        $(ECHO) compiling $(<)
        $(Q) $(CXX) $(INCFLAGS) $(CPPFLAGS) $(CXXFLAGS) $(COUTFLAG)$@ -c $<

.mm.S:
        $(ECHO) translating $(<)
        $(Q) $(CXX) $(INCFLAGS) $(CPPFLAGS) $(CXXFLAGS) $(COUTFLAG)$@ -S $<

.cxx.o:
        $(ECHO) compiling $(<)
        $(Q) $(CXX) $(INCFLAGS) $(CPPFLAGS) $(CXXFLAGS) $(COUTFLAG)$@ -c $<

.cxx.S:
        $(ECHO) translating $(<)
        $(Q) $(CXX) $(INCFLAGS) $(CPPFLAGS) $(CXXFLAGS) $(COUTFLAG)$@ -S $<

.cpp.o:
        $(ECHO) compiling $(<)
        $(Q) $(CXX) $(INCFLAGS) $(CPPFLAGS) $(CXXFLAGS) $(COUTFLAG)$@ -c $<

.cpp.S:
        $(ECHO) translating $(<)
        $(Q) $(CXX) $(INCFLAGS) $(CPPFLAGS) $(CXXFLAGS) $(COUTFLAG)$@ -S $<

.c.o:
        $(ECHO) compiling $(<)
        $(Q) $(CC) $(INCFLAGS) $(CPPFLAGS) $(CFLAGS) $(COUTFLAG)$@ -c $<

.c.S:
        $(ECHO) translating $(<)
        $(Q) $(CC) $(INCFLAGS) $(CPPFLAGS) $(CFLAGS) $(COUTFLAG)$@ -S $<
```
Here is the mkmf line of code that says what those entries mean - https://github.com/ruby/ruby/blob/v2_2_0/lib/mkmf.rb#L2596-L2599

**Comment by sodabrew** [comment]
Checking back on this ticket - were you able to solve the problem? If so, what fixed it? If not, what can I still help with?

**Comment by mpick92** [comment]
Upgrading to Ruby 2.3.x seemed to work for me - I had the same error for 2.2.x

**Comment by venki09** [comment]
Sorry for the late reply. We had this issue while upgrading node from RHEL-6.6 to RHEL-6.8. I installed mysql2 on a fresh vm with 6.8 installed already and that worked.

**Comment by sodabrew** [comment]
Glad to hear! Closing the issue now.
