### ISSUE TITLE
no implicit conversion of Hash into String

### ISSUE THREAD

**Issue by Punknoodles** [brianmario/mysql2#815]
ERROR TypeError: no implicit conversion of Hash into String
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/handler/webrick.rb:113:in `block in service'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/body_proxy.rb:31:in `each'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/body_proxy.rb:31:in `each'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/handler/webrick.rb:112:in `service'
        C:/Ruby23/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
        C:/Ruby23/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
        C:/Ruby23/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'

**Comment by sodabrew** [comment]
This does not appear to be a mysql2 issue. Can you describe the problem and what help you are seeking?

**Comment by Punknoodles** [comment]
never mind, i have found the fix.
