### ISSUE TITLE
gem install mysql2 (ruby 1.9.3) failed with ./install not found

### ISSUE THREAD

**Issue by cailiang9** [brianmario/mysql2#824]
make
compiling client.c
compiling result.c
compiling infile.c
compiling statement.c
compiling mysql2_ext.c
linking shared-object mysql2/mysql2.so

make  install
./install -m 0755 mysql2.so .gem.20170203-65-134792y/mysql2
make: ./install: Command not found
make: *** [.gem.20170203-65-134792y/mysql2/mysql2.so] Error 127

**Comment by sodabrew** [comment]
Are you executing `make` and `make install` yourself or is that debug output?

**Comment by sodabrew** [comment]
Please post your output from `ruby -r pp -e 'pp RbConfig::CONFIG.select { |k,v| k =~ /^I/ }'`

Mine is:
```
$ ruby -r pp -e 'pp RbConfig::CONFIG.select { |k,v| k =~ /^INSTALL/ }'
{"INSTALL"=>"/usr/bin/install -c",
 "INSTALLDOC"=>"all",
 "INSTALL_DATA"=>"/usr/bin/install -c -m 644",
 "INSTALL_SCRIPT"=>"/usr/bin/install -c",
 "INSTALL_PROGRAM"=>"/usr/bin/install -c"}
```

**Comment by sodabrew** [comment]
Ping - is this problem still occurring for you?
