### ISSUE TITLE
Unstable test: Mysql2::Statement close should free server resources

### ISSUE THREAD

**Issue by ltangvald** [brianmario/mysql2#826]
While building 0.4.5 for Ubuntu 17.04 i386, the test run failed twice with the following message (on the third try it passed)
  1) Mysql2::Statement close should free server resources
     Failure/Error: expect { stmt.close }.to change(&method(:stmt_count)).by(-1)
       expected result to have changed by -1, but was changed by -3
      ./spec/mysql2/statement_spec.rb:750:in `block (3 levels) in <top (required)>'

Build logs: http://autopkgtest.ubuntu.com/packages/r/ruby-mysql2/zesty/i386
The stmt_count function checks the global prepared statement counter in MySQL, making it very vulnerable to interactions with other tests.

**Comment by sodabrew** [comment]
Yes, this is a known issue. Is it gumming up the works for you as a packager? I can add some auto-retry logic if it would help.

**Comment by sodabrew** [comment]
The unit tests were recently improved, but still aren't perfect. Is this causing an outsized problem for you as a packager?

**Comment by ltangvald** [comment]
Hi, sorry, I didn't see the first comment.
In packaging we simply disabled this test, so it's not a big problem.

**Comment by sodabrew** [comment]
Ok! Closing for now. Thank you for your work on packaging!
