### ISSUE TITLE
Making wrapper->connected accessible in Ruby

### ISSUE THREAD

**Issue by pschambacher** [brianmario/mysql2#827]
Hi!

I see that the ping method is relying on `wrapper->connected` to know if there is an actual connection before doing the ping: https://github.com/brianmario/mysql2/blob/0.4.4/ext/mysql2/client.c#L1019

Would it be possible to make this information accessible via a getter for Ruby so we could rely on it?

**Comment by sodabrew** [comment]
Resolved by #796
