### ISSUE TITLE
async prepared statements

### ISSUE THREAD

**Issue by fw42** [brianmario/mysql2#829]
Is it currently possible to run prepared statements asynchronously?

It seems like neither the `prepare` nor the `execute` methods take a `async` parameter (like `query` does) and setting `query_options[:async] = true` also doesn't seem to have an effect.

Is this a known (intended?) limitation?

**Comment by fw42** [comment]
Possibly relevant: https://bugs.mysql.com/bug.php?id=60470

**Comment by sodabrew** [comment]
This should be resolved in mysql2 0.5 with PR #912 and improved by PR #958.

**Comment by sodabrew** [comment]
So async is not supported, but `:stream` is now supported for prepared statement results.
