### ISSUE TITLE
MySQL2 Gem Acces Denied but Login via Terminal Works

### ISSUE THREAD

**Issue by willisjtc** [brianmario/mysql2#830]
I'm running a rake task and attempting to create a database connection to mysql via the mysql2 gem but for some reason I am getting this error:

    *** Mysql2::Error Exception: Access denied for user 'user'@'localhost' (using password: YES)

This is the connection code:

    Mysql2::Client.new(host: server, database: db, username: user, password: pwd)

There are two reasons this is strange:

- I am able to use the same credentials to login via the terminal

- I created a VM (centos 7) and added a mysql database and uploaded the dump.sql file and was able to login just fine via the terminal and by using the MySQL2 gem. So I know that code works, I'm just not sure why it doesn't work for the mysql instance it is running on.

I've checked the user privileges and my user has all the necessary privileges, the database is running on localhost, I've tried setting the host parameter to 127.0.0.1 and got the same error.

Calling this: `mysql> select USER(), CURRENT_USER();` returns the following:

    +--------------------+----------------+
    | USER()             | CURRENT_USER() |
    +--------------------+----------------+
    | user@localhost     | user@%         |
    +--------------------+----------------+
    1 row in set (0.00 sec)

Calling this:

    mysql> Select SUBSTRING_INDEX(host,':',1) as 'ip'   From information_schema.processlist   WHERE ID=connection_id();

returns:

    +-----------+
    | ip        |
    +-----------+
    | localhost |
    +-----------+

My MySQL version is 5.7.17 for linux, running on CentOS 7. I'm running rails 4.0.4 and ruby 1.9.3 and my gem version is 0.4.5.

Any ideas why this wouldn't work for one Centos/MySql version and it would for another and why I can login though the terminal and can't in my code?

**Comment by sodabrew** [comment]
Does your server require SSL connections?
What version of mysql libraries are on your client side? Older versions of MySQL's libmysqlclient library do not enable SSL by default. Newer versions since MySQL 5.7.x do enable SSL by default.

**Comment by willisjtc** [comment]
How do I determine the client mysql libraries? I'm getting this:

    $ sudo yum install mysql-devel
        Loaded plugins: fastestmirror, langpacks
         Loading mirror speeds from cached hostfile
          * base: centos.mirror.constant.com
          * extras: centos.chi.host-engine.com
           * updates: centos.mirror.constant.com
          Package mysql-community-devel-5.7.17-1.el7.x86_64 already installed and latest version
          Nothing to do
    $ yum info mysql-devel
          Loaded plugins: fastestmirror, langpacks
          Loading mirror speeds from cached hostfile
           * base: centos.mirror.constant.com
           * extras: centos.chi.host-engine.com
           * updates: centos.mirror.constant.com
          Error: No matching Packages to list

**Comment by willisjtc** [comment]
Ok, this is what i've got:

    mysql-community-client.x86_64          5.7.17-1.el7                    @mysql57-community
    mysql-community-common.x86_64          5.7.17-1.el7                    @mysql57-community
    mysql-community-devel.x86_64           5.7.17-1.el7                    @mysql57-community
    mysql-community-libs.x86_64            5.7.17-1.el7                    @mysql57-community
    mysql-community-libs-compat.x86_64     5.7.17-1.el7                    @mysql57-community
    mysql-community-server.x86_64          5.7.17-1.el7                    @mysql57-community
    mysql57-community-release.noarch       el7-9                           installed

**Comment by sodabrew** [comment]
Try adding an SSL option, that will enable an SSL connection, and will help clarify if lack of SSL is the problem: https://github.com/brianmario/mysql2#ssl-options

The error message would be access denied because you were able to connect to MySQL, but not allowed to authenticate without an SSL-encrypted connected.

**Comment by willisjtc** [comment]
How would I go about adding my client public key to the authorized mysql list? The problem is that this isn't my machine nor my database. I've been given a sandbox and told to get this working.

**Comment by willisjtc** [comment]
Finally got it working. It was an SSL issue; once i got all the right ssl certs and keys in everything worked. Thanks @sodabrew!
