### ISSUE TITLE
Proxy QuotaGuard and socket

### ISSUE THREAD

**Issue by StephaneJuban** [brianmario/mysql2#837]
Hi,

I need to use QuotaGuard to have a proxy (with username & password) with static IP to be whitelisted. The proxy works fine but I'm unable to use it with mysql2.

Any example on how to face this issue or how to use the socket option of Mysql2::Client ? It doesn't seems to work, whatever if I put a valid file or an non-existing file, the result is the same. I don't even know if this is what I need to use a proxy.

Thanks

**Comment by sodabrew** [comment]
I found the documentation for QuotaGuard here: http://blog.quotaguard.com/accessing-mysql-static-ip/

It says that you will be accessing MySQL through SOCKS5, which means you will not be using a local socket, you will be using an IP address for the MySQL server. You will need to run your entire Rails application inside of a wrapper like `socksify`. There is no direct support for SOCKS5 in mysql2 gem or in the libmysqlclient library.

**Comment by StephaneJuban** [comment]
Thanks for the support, I will take a look at socksify !
