### ISSUE TITLE
Gem Load Error is: uninitialized constant Timeout::Error

### ISSUE THREAD

**Issue by phspies** [brianmario/mysql2#839]
Gem Load Error is: uninitialized constant Timeout::Error
Backtrace for gem load error is:
/.rvm/gems/ruby-2.3.1/gems/mysql2-0.4.5/lib/mysql2.rb:80:in `<module:Util>'
/.rvm/gems/ruby-2.3.1/gems/mysql2-0.4.5/lib/mysql2.rb:57:in `<module:Mysql2>'
/.rvm/gems/ruby-2.3.1/gems/mysql2-0.4.5/lib/mysql2.rb:56:in `<top (required)>'
/.rvm/gems/ruby-2.3.1/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `require'
/.rvm/gems/ruby-2.3.1/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
/.rvm/gems/ruby-2.3.1/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `each'
/.rvm/gems/ruby-2.3.1/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `block in require'
/.rvm/gems/ruby-2.3.1/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `each'
/.rvm/gems/ruby-2.3.1/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `require'
/.rvm/gems/ruby-2.3.1/gems/bundler-1.14.6/lib/bundler.rb:107:in `require'
/RubymineProjects/app/config/application.rb:7:in `<top (required)>'
/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7/lib/rails/commands/commands_tasks.rb:78:in `require'
/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7/lib/rails/commands/commands_tasks.rb:78:in `block in server'
/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7/lib/rails/commands/commands_tasks.rb:75:in `tap'
/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7/lib/rails/commands/commands_tasks.rb:75:in `server'
/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7/lib/rails/commands.rb:17:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'

**Comment by sodabrew** [comment]
That's an odd error, I have not seen that before. The failure occurs in this method below. It "works for me" and I cannot reproduce your error case.

Do you have this gem in your Gemfile? https://rubygems.org/gems/timeout if so please remove it and try again.

```
 66     #
 67     # In Mysql2::Client#query and Mysql2::Statement#execute,
 68     # Thread#handle_interrupt is used to prevent Timeout#timeout
 69     # from interrupting query execution.
 70     #
 71     # Timeout::ExitException was removed in Ruby 2.3.0, 2.2.3, and 2.1.8,
 72     # but is present in earlier 2.1.x and 2.2.x, so we provide a shim.
 73     #
 74     if Thread.respond_to?(:handle_interrupt)
 75       require 'timeout'
 76       # rubocop:disable Style/ConstantName
 77       TimeoutError = if defined?(::Timeout::ExitException)
 78         ::Timeout::ExitException
 79       else
 80         ::Timeout::Error
 81       end
 82     end
```
