### ISSUE TITLE
SocketError causes dead thread to own connection.

### ISSUE THREAD

**Issue by AlexRiedler** [brianmario/mysql2#841]
I am using Sequel gem v4.43; with mysql2 v0.4.2 -- but also tried v0.4.5; ruby version 2.3.1p112); and occasionally I get into a scenario where by:

The mysql2 Client is owned by a dead thread due to a SocketError that was raised during a call to `_query`

Details:

1. `SocketError: Socket was remotely closed` 
https://github.com/brianmario/mysql2/blob/3854d19ccac834b0e07e0c18d6f26465630daf8c/lib/mysql2/client.rb#L107

2. Sequel gem ThreadedConnectionPool will put connection back into pool (ensure)

3. After being fetched out the pool:

```
Mysql2::Error: This connection is in use by: #<Thread:0x007f7528121390@/home/<>/apps/<>/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/util.rb:24 dead>
```

Any suggestions on how to resolve this? I am feeling like we are missing an ensure somewhere by which it should be relieving the owner of the thread when a socket error occurs; or maybe its upstream in Sequel and it should be disconnecting when it gets a SocketError ? (although I would have thought it would have wrapped in Mysql2 Error class)

Any help would be much appreciated!

**Comment by sodabrew** [comment]
This may be resolved by #811

**Comment by sodabrew** [comment]
Please try out new version 0.4.6 and report back if it resolves this problem or not!

**Comment by AlexRiedler** [comment]
@sodabrew tested it out; no cigar. same issue.

**Comment by sodabrew** [comment]
Another relevant fix was merged recently. Please try out new version 0.4.7 and report back if it resolves this problem or not!

**Comment by AlexRiedler** [comment]
I believe this may be resolved; woot! Closing!
