### ISSUE TITLE
Prepared statement results to json

### ISSUE THREAD

**Issue by randohinn** [brianmario/mysql2#852]
A `client.prepare().execute()` returns `Mysql2::Result` which appears to be Enumerable? How could I turn this to a Hash, to pass to `JSON.generate` ? 

Neither prepare or execute seem to accept the `:as => array` anywhere..

**Comment by sodabrew** [comment]
Did you resolve the issue? Please post so that other who might have the same question in the future can find this!

**Comment by randohinn** [comment]
Running `to_a`on the results and passing the output of that to JSON worked wonderfully.
