### ISSUE TITLE
Please update the documentation for the usage of docker on localhost.

### ISSUE THREAD

**Issue by ThomasKoppensteiner** [brianmario/mysql2#858]
I'm running the MySQL-Server (5.7) in official Docker image (https://hub.docker.com/_/mysql/) on localhost (for development and testing).
The container port `3306` is mapped to the host port `4306`.

I found out, that there is a difference in the connection behaviour if I use `127.0.0.1` instead of `localhost`.

**localhost**
This configuration isn't working for Docker because it tries to communicate over a socket, which a) may not be available or b) points to the MySQL-Server on the host, which is the wrong one.
```ruby
{
  host: "localhost",
  port: 4306,
  database: "my_db",
  username: "my_user",
  password: "my_pwd",
  sslverify: false,
  ssl_mode: :disabled,
  reconnect: true
}
```

**127.0.0.1**
This configuration works for Docker on the localhost, because no socket is used.
```ruby
{
  host: "127.0.0.1",
  port: 4306,
  database: "my_db",
  username: "my_user",
  password: "my_pwd",
  sslverify: false,
  ssl_mode: :disabled,
  reconnect: true
}
```

**Comment by sodabrew** [comment]
Yes, I agree it would be useful to mention that "localhost" means "try local socket first, and then localhost dns second"
