### ISSUE TITLE
Build fails with Mariadb 10.2.6

### ISSUE THREAD

**Issue by bigcurl** [brianmario/mysql2#863]
Hi,
this is a follow up issue from #851. Currently building the gem still fails for me on Debian Strech with Mariadb 10.2.6 installed from the Mariadb Repository.

Here is the the output from the build process:

`$ gem install --local mysql2-0.4.6.gem 
Building native extensions.  This could take a while...
ERROR:  Error installing mysql2-0.4.6.gem:
ERROR: Failed to build gem native extension.

checking for rb_absint_size()... yes
checking for rb_absint_singlebit_p()... yes
checking for ruby/thread.h... yes
checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
checking for rb_thread_blocking_region()... no
checking for rb_wait_for_single_fd()... yes
checking for rb_hash_dup()... yes
checking for rb_intern3()... yes
checking for rb_big_cmp()... yes
-----
Using mysql_config at /usr/bin/mysql_config
-----
checking for mysql.h... yes
checking for SSL_MODE_DISABLED in mysql.h... no
checking for MYSQL_OPT_SSL_ENFORCE in mysql.h... yes
checking for errmsg.h... yes
checking for mysqld_error.h... yes
-----
Setting libpath to /usr/lib/x86_64-linux-gnu
-----
creating Makefile

current directory: **
make "DESTDIR=" clean

current directory: /**
make "DESTDIR="
compiling mysql2_ext.c
compiling client.c
client.c: In function ‘decr_mysql2_client’:
client.c:33:49: error: ‘NET {aka struct st_net}’ has no member named ‘vio’; did you mean ‘pvio’?
 #define CONNECTED(wrapper) (wrapper->client->net.vio != NULL && wrapper->client->net.fd != -1)
                                                 ^
client.c:291:9: note: in expansion of macro ‘CONNECTED’
     if (CONNECTED(wrapper) && !wrapper->automatic_close) {
         ^~~~~~~~~
client.c: In function ‘rb_mysql_client_closed’:
client.c:33:49: error: ‘NET {aka struct st_net}’ has no member named ‘vio’; did you mean ‘pvio’?
 #define CONNECTED(wrapper) (wrapper->client->net.vio != NULL && wrapper->client->net.fd != -1)
                                                 ^
client.c:484:10: note: in expansion of macro ‘CONNECTED’
   return CONNECTED(wrapper) ? Qfalse : Qtrue;
          ^~~~~~~~~
client.c: In function ‘rb_mysql_client_async_result’:
client.c:33:49: error: ‘NET {aka struct st_net}’ has no member named ‘vio’; did you mean ‘pvio’?
 #define CONNECTED(wrapper) (wrapper->client->net.vio != NULL && wrapper->client->net.fd != -1)
                                                 ^
client.c:37:8: note: in expansion of macro ‘CONNECTED’
   if (!CONNECTED(wrapper) && !wrapper->reconnect_enabled) { \
        ^~~~~~~~~
client.c:565:3: note: in expansion of macro ‘REQUIRE_CONNECTED’
   REQUIRE_CONNECTED(wrapper);
   ^~~~~~~~~~~~~~~~~
client.c: In function ‘disconnect_and_raise’:
client.c:33:49: error: ‘NET {aka struct st_net}’ has no member named ‘vio’; did you mean ‘pvio’?
 #define CONNECTED(wrapper) (wrapper->client->net.vio != NULL && wrapper->client->net.fd != -1)
                                                 ^
client.c:610:7: note: in expansion of macro ‘CONNECTED’
   if (CONNECTED(wrapper)) {
       ^~~~~~~~~
client.c: In function ‘disconnect_and_mark_inactive’:
client.c:33:49: error: ‘NET {aka struct st_net}’ has no member named ‘vio’; did you mean ‘pvio’?
 #define CONNECTED(wrapper) (wrapper->client->net.vio != NULL && wrapper->client->net.fd != -1)
                                                 ^
client.c:671:9: note: in expansion of macro ‘CONNECTED’
     if (CONNECTED(wrapper)) {
         ^~~~~~~~~
client.c: In function ‘rb_query’:
client.c:33:49: error: ‘NET {aka struct st_net}’ has no member named ‘vio’; did you mean ‘pvio’?
 #define CONNECTED(wrapper) (wrapper->client->net.vio != NULL && wrapper->client->net.fd != -1)
                                                 ^
client.c:37:8: note: in expansion of macro ‘CONNECTED’
   if (!CONNECTED(wrapper) && !wrapper->reconnect_enabled) { \
        ^~~~~~~~~
client.c:752:3: note: in expansion of macro ‘REQUIRE_CONNECTED’
   REQUIRE_CONNECTED(wrapper);
   ^~~~~~~~~~~~~~~~~
client.c: In function ‘rb_mysql_client_real_escape’:
client.c:33:49: error: ‘NET {aka struct st_net}’ has no member named ‘vio’; did you mean ‘pvio’?
 #define CONNECTED(wrapper) (wrapper->client->net.vio != NULL && wrapper->client->net.fd != -1)
                                                 ^
client.c:37:8: note: in expansion of macro ‘CONNECTED’
   if (!CONNECTED(wrapper) && !wrapper->reconnect_enabled) { \
        ^~~~~~~~~
client.c:808:3: note: in expansion of macro ‘REQUIRE_CONNECTED’
   REQUIRE_CONNECTED(wrapper);
   ^~~~~~~~~~~~~~~~~
client.c: In function ‘_mysql_client_options’:
client.c:33:49: error: ‘NET {aka struct st_net}’ has no member named ‘vio’; did you mean ‘pvio’?
 #define CONNECTED(wrapper) (wrapper->client->net.vio != NULL && wrapper->client->net.fd != -1)
                                                 ^
client.c:43:7: note: in expansion of macro ‘CONNECTED’
   if (CONNECTED(wrapper)) { \
       ^~~~~~~~~
client.c:852:3: note: in expansion of macro ‘REQUIRE_NOT_CONNECTED’
   REQUIRE_NOT_CONNECTED(wrapper);
   ^~~~~~~~~~~~~~~~~~~~~
client.c: In function ‘rb_mysql_client_server_info’:
client.c:33:49: error: ‘NET {aka struct st_net}’ has no member named ‘vio’; did you mean ‘pvio’?
 #define CONNECTED(wrapper) (wrapper->client->net.vio != NULL && wrapper->client->net.fd != -1)
                                                 ^
client.c:37:8: note: in expansion of macro ‘CONNECTED’
   if (!CONNECTED(wrapper) && !wrapper->reconnect_enabled) { \
        ^~~~~~~~~
client.c:969:3: note: in expansion of macro ‘REQUIRE_CONNECTED’
   REQUIRE_CONNECTED(wrapper);
   ^~~~~~~~~~~~~~~~~
client.c: In function ‘rb_mysql_client_socket’:
client.c:33:49: error: ‘NET {aka struct st_net}’ has no member named ‘vio’; did you mean ‘pvio’?
 #define CONNECTED(wrapper) (wrapper->client->net.vio != NULL && wrapper->client->net.fd != -1)
                                                 ^
client.c:37:8: note: in expansion of macro ‘CONNECTED’
   if (!CONNECTED(wrapper) && !wrapper->reconnect_enabled) { \
        ^~~~~~~~~
client.c:996:3: note: in expansion of macro ‘REQUIRE_CONNECTED’
   REQUIRE_CONNECTED(wrapper);
   ^~~~~~~~~~~~~~~~~
client.c: In function ‘rb_mysql_client_last_id’:
client.c:33:49: error: ‘NET {aka struct st_net}’ has no member named ‘vio’; did you mean ‘pvio’?
 #define CONNECTED(wrapper) (wrapper->client->net.vio != NULL && wrapper->client->net.fd != -1)
                                                 ^
client.c:37:8: note: in expansion of macro ‘CONNECTED’
   if (!CONNECTED(wrapper) && !wrapper->reconnect_enabled) { \
        ^~~~~~~~~
client.c:1013:3: note: in expansion of macro ‘REQUIRE_CONNECTED’
   REQUIRE_CONNECTED(wrapper);
   ^~~~~~~~~~~~~~~~~
client.c: In function ‘rb_mysql_client_affected_rows’:
client.c:33:49: error: ‘NET {aka struct st_net}’ has no member named ‘vio’; did you mean ‘pvio’?
 #define CONNECTED(wrapper) (wrapper->client->net.vio != NULL && wrapper->client->net.fd != -1)
                                                 ^
client.c:37:8: note: in expansion of macro ‘CONNECTED’
   if (!CONNECTED(wrapper) && !wrapper->reconnect_enabled) { \
        ^~~~~~~~~
client.c:1027:3: note: in expansion of macro ‘REQUIRE_CONNECTED’
   REQUIRE_CONNECTED(wrapper);
   ^~~~~~~~~~~~~~~~~
client.c: In function ‘rb_mysql_client_thread_id’:
client.c:33:49: error: ‘NET {aka struct st_net}’ has no member named ‘vio’; did you mean ‘pvio’?
 #define CONNECTED(wrapper) (wrapper->client->net.vio != NULL && wrapper->client->net.fd != -1)
                                                 ^
client.c:37:8: note: in expansion of macro ‘CONNECTED’
   if (!CONNECTED(wrapper) && !wrapper->reconnect_enabled) { \
        ^~~~~~~~~
client.c:1044:3: note: in expansion of macro ‘REQUIRE_CONNECTED’
   REQUIRE_CONNECTED(wrapper);
   ^~~~~~~~~~~~~~~~~
client.c: In function ‘rb_mysql_client_select_db’:
client.c:33:49: error: ‘NET {aka struct st_net}’ has no member named ‘vio’; did you mean ‘pvio’?
 #define CONNECTED(wrapper) (wrapper->client->net.vio != NULL && wrapper->client->net.fd != -1)
                                                 ^
client.c:37:8: note: in expansion of macro ‘CONNECTED’
   if (!CONNECTED(wrapper) && !wrapper->reconnect_enabled) { \
        ^~~~~~~~~
client.c:1069:3: note: in expansion of macro ‘REQUIRE_CONNECTED’
   REQUIRE_CONNECTED(wrapper);
   ^~~~~~~~~~~~~~~~~
client.c: In function ‘rb_mysql_client_ping’:
client.c:33:49: error: ‘NET {aka struct st_net}’ has no member named ‘vio’; did you mean ‘pvio’?
 #define CONNECTED(wrapper) (wrapper->client->net.vio != NULL && wrapper->client->net.fd != -1)
                                                 ^
client.c:1097:8: note: in expansion of macro ‘CONNECTED’
   if (!CONNECTED(wrapper)) {
        ^~~~~~~~~
client.c: In function ‘rb_mysql_client_prepare_statement’:
client.c:33:49: error: ‘NET {aka struct st_net}’ has no member named ‘vio’; did you mean ‘pvio’?
 #define CONNECTED(wrapper) (wrapper->client->net.vio != NULL && wrapper->client->net.fd != -1)
                                                 ^
client.c:37:8: note: in expansion of macro ‘CONNECTED’
   if (!CONNECTED(wrapper) && !wrapper->reconnect_enabled) { \
        ^~~~~~~~~
client.c:1347:3: note: in expansion of macro ‘REQUIRE_CONNECTED’
   REQUIRE_CONNECTED(wrapper);
   ^~~~~~~~~~~~~~~~~
client.c: In function ‘rb_set_ssl_mode_option’:
client.c:140:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
client.c: In function ‘rb_mysql_client_ping’:
client.c:1102:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
client.c: In function ‘rb_mysql_client_closed’:
client.c:485:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
client.c: At top level:
cc1: warning: unrecognized command line option ‘-Wno-used-but-marked-unused’
cc1: warning: unrecognized command line option ‘-Wno-static-in-inline’
cc1: warning: unrecognized command line option ‘-Wno-reserved-id-macro’
cc1: warning: unrecognized command line option ‘-Wno-missing-variable-declarations’
cc1: warning: unrecognized command line option ‘-Wno-documentation-unknown-command’
cc1: warning: unrecognized command line option ‘-Wno-disabled-macro-expansion’
cc1: warning: unrecognized command line option ‘-Wno-covered-switch-default’
cc1: warning: unrecognized command line option ‘-Wno-conditional-uninitialized’
Makefile:238: recipe for target 'client.o' failed
make: *** [client.o] Error 1

make failed, exit code 2

Gem files will remain installed in /** for inspection.
Results logged to /**/gem_make.out`

**Comment by bigcurl** [comment]
#864 fixes the error and works with 10.2.6 (version conditional missing for now) but results in `NameError: uninitialized constant Mysql2::Client::LONG_PASSWORD`

**Comment by sodabrew** [comment]
Fixed in master branch.
