### ISSUE TITLE
OSX Ruby 2.4 Gem install error

### ISSUE THREAD

**Issue by zagros** [brianmario/mysql2#868]
## Description of issue:
I have installed Ruby 2.4 from source on OSX Sierra (not using Homebrew, rbenv etc) and can install every other gem except Mysql2 gem.

I tried installing the gem using these 3 variations, the results being identical in all 3 times:

`sudo gem install mysql2`

`sudo gem install mysql2 -- --with-mysql-config=/usr/local/mysql-5.7.11-osx10.9-x86_64/bin/mysql_config `

`sudo gem install mysql2 -v '0.4.7' -- --with-mysql-dir=/usr/local/mysql-5.7.11-osx10.9-x86_64`

## The results are the following:
Note the two errors below, one being about "_rb_thread_call_without_gvl_" redeclaration (original declaration being in ruby's header file itself), and the second being lack of define statement for the trap.

__how should I proceed?__

```
Building native extensions with: '--with-mysql-config=/usr/local/mysql-5.7.11-osx10.9-x86_64/bin/mysql_config'
This could take a while...
ERROR:  Error installing mysql2:
	ERROR: Failed to build gem native extension.

    current directory: /usr/local/lib/ruby/gems/2.4.0/gems/mysql2-0.4.7/ext/mysql2
/usr/local/bin/ruby -r ./siteconf20170707-40154-rcsjqh.rb extconf.rb --with-mysql-config=/usr/local/mysql-5.7.11-osx10.9-x86_64/bin/mysql_config
checking for rb_absint_size()... no
checking for rb_absint_singlebit_p()... no
checking for ruby/thread.h... yes
checking for rb_thread_call_without_gvl() in ruby/thread.h... no
checking for rb_thread_blocking_region()... no
checking for rb_wait_for_single_fd()... no
checking for rb_hash_dup()... no
checking for rb_intern3()... no
checking for rb_big_cmp()... no
-----
Using mysql_config at /usr/local/mysql-5.7.11-osx10.9-x86_64/bin/mysql_config
-----
checking for mysql.h... yes
checking for errmsg.h... yes
checking for mysqld_error.h... yes
checking for SSL_MODE_DISABLED in mysql.h... yes
checking for SSL_MODE_PREFERRED in mysql.h... yes
checking for SSL_MODE_REQUIRED in mysql.h... yes
checking for SSL_MODE_VERIFY_CA in mysql.h... yes
checking for SSL_MODE_VERIFY_IDENTITY in mysql.h... yes
checking for MYSQL.net.vio in mysql.h... yes
checking for MYSQL.net.pvio in mysql.h... no
-----
Setting rpath to /usr/local/mysql-5.7.11-osx10.9-x86_64/lib
-----
creating Makefile

current directory: /usr/local/lib/ruby/gems/2.4.0/gems/mysql2-0.4.7/ext/mysql2
make "DESTDIR=" clean

current directory: /usr/local/lib/ruby/gems/2.4.0/gems/mysql2-0.4.7/ext/mysql2
make "DESTDIR="
compiling client.c
In file included from client.c:1:
In file included from ./mysql2_ext.h:41:
In file included from ./client.h:18:
/usr/local/include/ruby-2.4.0/ruby/backward/rubysig.h:14:2: warning: rubysig.h is obsolete [-W#warnings]
#warning rubysig.h is obsolete
 ^
In file included from client.c:1:
In file included from ./mysql2_ext.h:41:
./client.h:22:1: error: static declaration of 'rb_thread_call_without_gvl' follows non-static declaration
rb_thread_call_without_gvl(
^
/usr/local/include/ruby-2.4.0/ruby/thread.h:28:7: note: previous declaration is here
void *rb_thread_call_without_gvl(void *(*func)(void *), void *data1,
      ^
In file included from client.c:1:
In file included from ./mysql2_ext.h:41:
./client.h:29:3: error: use of undeclared identifier 'TRAP_BEG'
  TRAP_BEG;
  ^
./client.h:31:3: error: use of undeclared identifier 'TRAP_END'
  TRAP_END;
  ^
In file included from client.c:13:
./wait_for_single_fd.h:31:10: warning: implicit declaration of function 'rb_thread_select' is invalid in C99 [-Wimplicit-function-declaration]
  return rb_thread_select(fd + 1, rfds, wfds, efds, tvp);
         ^
2 warnings and 3 errors generated.
make: *** [client.o] Error 1

make failed, exit code 2

Gem files will remain installed in /usr/local/lib/ruby/gems/2.4.0/gems/mysql2-0.4.7 for inspection.
Results logged to /usr/local/lib/ruby/gems/2.4.0/extensions/x86_64-darwin-16/2.4.0-static/mysql2-0.4.7/gem_make.out
```

**Comment by sodabrew** [comment]
```
checking for rb_absint_size()... no
checking for rb_absint_singlebit_p()... no
checking for ruby/thread.h... yes
checking for rb_thread_call_without_gvl() in ruby/thread.h... no
checking for rb_thread_blocking_region()... no
checking for rb_wait_for_single_fd()... no
checking for rb_hash_dup()... no
checking for rb_intern3()... no
checking for rb_big_cmp()... no
```

You're missing the Ruby headers for your version of Ruby.

**Comment by sodabrew** [comment]
> I have installed Ruby 2.4 from source on OSX Sierra (not using Homebrew, rbenv etc) and can install every other gem except Mysql2 gem.

Is there anything I can help you with here, with respect to where you've installed both your Ruby binary and your Ruby C headers? The expected sequence of config tests for Ruby 2.4 is:

```
checking for rb_absint_size()... yes
checking for rb_absint_singlebit_p()... yes
checking for ruby/thread.h... yes
checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
checking for rb_thread_blocking_region()... no
checking for rb_wait_for_single_fd()... yes
checking for rb_hash_dup()... yes
checking for rb_intern3()... yes
checking for rb_big_cmp()... yes
```

**Comment by zagros** [comment]
good catch @sodabrew 

I did the following to fix the issue (again I would like to emphasize for anyone else stumbling across this post) that I had downloaded the Ruby source code myself, compiled my own OpenSSL, Apr-1-Config, Apu-1-Config, and anything else you can think of as I don't like Homebrew and/or other package managers:

As per @sodabrew, my ruby installation was missing headers, so since I still had my terminal window open a few days back when I had made this ticket, in the same ruby source code working folder I was installing ruby from, I ran the ./configure again but this time with --enable-shared so that headers get added


```
./configure --with-opt-dir=/usr/local/ssl/ --enable-shared 
make && sudo make install
```

this reinstalled Ruby 2.4 for me but with headers, then I could run this to install mysql2

`sudo gem install mysql2 --platform=ruby -- --with-mysql-config=/usr/local/mysql-5.7.11-osx10.9-x86_64/bin/mysql_config --with-include-dir=/usr/local/include/ruby-2.4.0/ruby/`

thanks for your help, you can close this thread!

**Comment by sodabrew** [comment]
Thanks very much for posting your resolution notes! Always great for future Google-search stumblers!

**Comment by hakanai** [comment]
I'm getting this exact issue myself, but ruby-build installed all my rubies for me, and when I go looking for the headers, they _seem_ like they're present, but is it possible it's looking for a specific header file and only that one header file is missing?

```
% ls -a ~/DevEnv/rbenv/versions/2.3.1/include/ruby-2.3.0/ruby 
.		debug.h		encoding.h	missing.h	regex.h		subst.h		util.h
..		defines.h	intern.h	oniguruma.h	ruby.h		thread.h	version.h
backward	digest.h	io.h		re.h		st.h		thread_native.h	vm.h
```
