### ISSUE TITLE
'localhost' host leads to Mysql2::Error

### ISSUE THREAD

**Issue by ch1c0t** [brianmario/mysql2#869]
The client initialization suggested in the readme [here](https://github.com/brianmario/mysql2#usage) leads to `Mysql2::Error`:
```ruby
[1] pry(main)> require 'mysql2'
true
[2] pry(main)> client = Mysql2::Client.new(:host => "localhost", :username => "root")
Mysql2::Error: Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock' (2 "No such file or directory")
from /home/ch1c0t/.gem/ruby/2.4.0/gems/mysql2-0.4.8/lib/mysql2/client.rb:89:in `connect'
```

It works only if we pass an IP like `"127.0.0.1"`, which is inconvenient inside containers communicating by means of docker-compose [networking](https://docs.docker.com/compose/networking).

**Comment by sodabrew** [comment]
This is documented behavior.

https://github.com/brianmario/mysql2/blob/master/README.md#connecting-to-localhost

**Comment by ch1c0t** [comment]
@sodabrew Thanks, I missed that.

It looks like the documented behavior is different from actual one. According to the second clause, when the socket is not available, it should have looked up "localhost" to find an IP address, but instead `Mysql2::Error` were thrown.

I am on Arch Linux:
```
➜  ~ cat /etc/hosts 
#
# /etc/hosts: static lookup table for host names
#

#<ip-address>   <hostname.domain.org>   <hostname>
127.0.0.1       localhost.localdomain   localhost
::1             localhost.localdomain   localhost

# End of file
```

**Comment by sodabrew** [comment]
You're right, I was mistaken to claim the fallback, and will update the documentation. Thank you!

**Comment by sodabrew** [comment]
Documentation updated a700aea7dc69

**Comment by ch1c0t** [comment]
Thank you. Looks very clear.

The last line

>Any other value will be looked up as a hostname for a TCP connection.

helped me to find out an issue in my code.
