### ISSUE TITLE
Failure to launch rails console - improper mysql2 gem installation

### ISSUE THREAD

**Issue by lkananowicz** [brianmario/mysql2#873]
Hi. I have an issue very similar to the on described on:
https://github.com/brianmario/mysql2/issues/810

OS: CentOS 6.9

Tried in the following configurations:
ruby 2.2.2 + rails 4.0.6 + mysql2 0.3.21
ruby 2.3.6 + rails 4.0.6 + mysql2 0.3.21
ruby 2.3.6 + rails 4.2.5 + mysql2 0.4.8

Gem installation actually succeeds but then trying to acccess rails console via
bundle exec rails c production
produces:
`/path_to_app/shared/bundle/ruby/2.3.0/gems/mysql2-0.4.8/lib/mysql2.rb:31:in `require': /path_to_app/shared/bundle/ruby/2.3.0/gems/mysql2-0.4.8/lib/mysql2/mysql2.so: undefined symbol: __gxx_personality_v0 - /path_to_app/shared/bundle/ruby/2.3.0/gems/mysql2-0.4.8/lib/mysql2/mysql2.so (LoadError)

	from /path_to_app/shared/bundle/ruby/2.3.0/gems/mysql2-0.4.8/lib/mysql2.rb:31:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.3.4/gems/bundler-1.15.1/lib/bundler/runtime.rb:82:in `require'
	from /usr/local/rvm/gems/ruby-2.3.4/gems/bundler-1.15.1/lib/bundler/runtime.rb:82:in `block (2 levels) in require'
	from /usr/local/rvm/gems/ruby-2.3.4/gems/bundler-1.15.1/lib/bundler/runtime.rb:77:in `each'
	from /usr/local/rvm/gems/ruby-2.3.4/gems/bundler-1.15.1/lib/bundler/runtime.rb:77:in `block in require'
	from /usr/local/rvm/gems/ruby-2.3.4/gems/bundler-1.15.1/lib/bundler/runtime.rb:66:in `each'
	from /usr/local/rvm/gems/ruby-2.3.4/gems/bundler-1.15.1/lib/bundler/runtime.rb:66:in `require'
	from /usr/local/rvm/gems/ruby-2.3.4/gems/bundler-1.15.1/lib/bundler.rb:108:in `require'
	from /path_to_app/releases/20170714101534/config/application.rb:14:in `<top (required)>'
	from /path_to_app/shared/bundle/ruby/2.3.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:141:in `require'
	from /path_to_app/shared/bundle/ruby/2.3.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:141:in `require_application_and_environment!'
	from /path_to_app/shared/bundle/ruby/2.3.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:67:in `console'
	from /path_to_app/shared/bundle/ruby/2.3.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /path_to_app/shared/bundle/ruby/2.3.0/gems/railties-4.2.5/lib/rails/commands.rb:17:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'

`

Any suggestions on solving the problem?

**Comment by sodabrew** [comment]
Could you post the output of the following:
```
$ ruby -r pp -e 'pp RbConfig::CONFIG.select { |k,v| k =~ /^C/ }'
```

I want to see what compiler is being used. I suspect that for some reason a C++ compiler is building the module, when a C compiler should be used.

**Comment by lkananowicz** [comment]
Sure, here it is:
`lkananowicz@kxblade1007:~$ ruby -r pp -e 'pp RbConfig::CONFIG.select { |k,v| k =~ /^C/ }'
{"CONFIGURE"=>"configure",
 "COMMON_HEADERS"=>"",
 "COMMON_MACROS"=>"",
 "COMMON_LIBS"=>"",
 "CROSS_COMPILING"=>"no",
 "CCDLFLAGS"=>"-fPIC",
 "CHDIR"=>"cd -P",
 "CP"=>"cp",
 "CC_VERSION"=>"gcc -v",
 "COUTFLAG"=>"-o ",
 "CPPOUTFILE"=>"-o conftest.i",
 "CPP"=>"gcc -E",
 "CXXFLAGS"=>
  " -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat",
 "CPPFLAGS"=>"  ",
 "CFLAGS"=>
  " -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat  -fPIC",
 "CXX"=>"g++",
 "CC"=>"gcc"}`

**Comment by lkananowicz** [comment]
@sodabrew I guess I should consider CXX env variable value. Does value "g++" means that module was built by C++ compiler?

**Comment by sodabrew** [comment]
Your CC variable is "gcc" which is good. Hmm. Is it possible that you've upgraded your GCC version between "major" 4.x revisions in between building Ruby and building this gem?

**Comment by kontomierz** [comment]
@sodabrew The server which we used was managed by the tool called puppet. Unfortunately I do not have a root access to it. Can you explain how can I check whether GCC was upgraded (if it is possible without root access)?

**Comment by sodabrew** [comment]
Sorry I missed your reply months ago! This comment from #810 strikes me as most likely related: https://github.com/brianmario/mysql2/issues/810#issuecomment-309129639  The user there had built the gem on RHEL 6.6 and then upgraded the environment to RHEL 6.8. Recompiling resolved the issue.

**Comment by lkananowicz** [comment]
@sodabrew Thanks. By recompiling you mean a full re-installation of mysql2 gem?

**Comment by sodabrew** [comment]
Yes, reinstalling the gem (within the Bundle or Gemset, for example) will recompile it.

If you are using a separate build environment, I would recommend checking if it matches your production environment.

**Comment by sodabrew** [comment]
Were you able to resolve the issue?

**Comment by lkananowicz** [comment]
@sodabrew Yes, thanks for your help!
