### ISSUE TITLE
Failed to load libmysql.dll

### ISSUE THREAD

**Issue by rwega** [brianmario/mysql2#881]
Failed to load libmysql.dll from C:\Ruby24-x64\lib\ruby\gems\2.4.0\gems\mysql2-0.4.9-x64-mingw32\vendor\libmysql.dll

Please help.

**Comment by sodabrew** [comment]
Use Ruby 2.3 or lower, I have not provided binaries for Ruby 2.4 on Windows yet.

**Comment by rwega** [comment]
Thanks, it worked. i used ruby 2.3.3.

**Comment by enkessler** [comment]
@sodabrew  I get the same error, even when using Ruby 2.3

`Failed to load libmysql.dll from C:\Ruby\Ruby23\lib\ruby\gems\2.3.0\gems\mysql2-0.4.10-x86-mingw32\vendor\libmysql.dll`

**Comment by sodabrew** [comment]
Does the file exist?

**Comment by enkessler** [comment]
It does, yes. It existed in the 2.4 installation as well but both of them fail to load in the same manner.

**Comment by enkessler** [comment]
I rolled back to `mysql2 v0.3.21` and Ruby 2.3 and things are working fine.
