### ISSUE TITLE
Invalid DATETIME is converted to a local time in a way that loses information

### ISSUE THREAD

**Issue by pdg137** [brianmario/mysql2#882]
This gem converts DATETIME values to local time, which presents a challenge when the value is not convertable: for example, under a timezone such as America/Los_Angeles following US daylight saving rules, this

```ruby
result = client.query('select convert("2017-03-12 02:30", datetime) as x')
p result.first['x']
```
yields `2017-03-12 03:30:00 -0700`, which seems wrong, since the hour has changed from a "2" to a "3". This also causes information loss, since the result is indistinguishable from a database value of `2017-03-12 03:30`.  A mathematically equivalent answer of `2017-03-12 02:30:00 -0800` would be better, even though that date does not ever occur in the timezone, since the raw data would be recoverable by dropping the timezone component.

**Comment by sodabrew** [comment]
The gem itself isn't doing a conversion here, but it is returning a Ruby `Time` object that does have implicit conversions:

```
irb > result = client.query('select convert("2017-03-12 02:30", datetime) as x')
irb > p result.first['x'].class
Time
```

**Comment by pdg137** [comment]
I see, the `Time` class does exhibit this behavior, so I guess it's not this gem's fault:

```
irb> Time.new(2017, 3, 12, 2, 30)
=> 2017-03-12 03:30:00 -0700
```

**Comment by pdg137** [comment]
For reference, if you want to read a DATETIME column that might contain invalid values, for example one that happens to be stored in UTC when the rest of the table is in localtime, you can bypass the `Time` class entirely and read it out as a string with something like this:

```ruby
    result = client.query("select concat(datetime_utc) from table")
    value = DateTime.parse(result.to_a[0][0]+' +0000')
```

**Comment by sodabrew** [comment]
@pdg137 This suggestion will cause multiple conversions to take place. If you want to fetch the string-value of a column, this will do the trick:

```
client.query("SELECT datetime_column FROM table", cast: false)
```

You can also specify the timezone of your application with these config options: https://github.com/sodabrew/mysql2#timezones
