### ISSUE TITLE
cast_booleans does not work with prepared statements

### ISSUE THREAD

**Issue by jonathann92** [brianmario/mysql2#883]
Hi, I initialized the mysql2 client with 'cast_booleans' = true
Then I use a prepared statement to query a table. The boolean returns as '\x01'. When I query with client.query('select boolValue from myTable') then the values will be true or false

**Comment by sodabrew** [comment]
What version of mysql2 gem are you using?

Just to check, make sure you use `:cast_booleans => true` in the connection hash (important that the key is a symbol, not a string).

**Comment by jonathann92** [comment]
Hi thanks for replying quickly! I'm using mysql2 (0.4.9 x86-mingw32, 0.4.6 x86-mingw32). I tried using :cast_booleans instead of 'cast_booleans' = true and it still doesnt work for prepared statements

**Comment by sodabrew** [comment]
Specifically, `:cast_booleans` does not work with `BIT(1)` per tests in #903. Please let me know if you have other data types / column types that also don't work. Apologies for the long delay before I got the specs updated to verify this issue.
