### ISSUE TITLE
.query.stream and promise api

### ISSUE THREAD

**Issue by jomel** [brianmario/mysql2#897]
I am trying to use mysql2 to import data from a large mariaDB table, process and push to mongoDB via mongoose. The data is huge, so I started looking at streaming.

If i use the default mysql2 api, streaming works as expected.

If I use Promise API
```
var mysql = require('mysql2/promise');
const connection = mysql.createConnection({...})
var s1 = connection.query('Select * from table').stream()
```
I get the error: **TypeError: connection.query(...).stream is not a function**

My connection setup (currently using the Promises API) is shared across the app and I don't want to switch to the basic version as it means I'd have to re-write too much. 

Is there a way to use streaming with the Promise API? The closest I got was processing the data in "chunks" using Promise.all, .map etc, but it's not elegant & is slow.

**Comment by sodabrew** [comment]
This is the Ruby mysql2 gem. I think you're looking for the NodeJS mysql2 npm: https://github.com/sidorares/node-mysql2
