### ISSUE TITLE
Malformed packet (Mysql2::Error) with MariaDB server

### ISSUE THREAD

**Issue by raphaelyancey** [brianmario/mysql2#915]
I was running into the same issue from the CLI `mysql` client on Debian. I installed `mariadb-client` and could then connect. 

Now I'm running into the same problem (I guess) with the `mysql2` gem, although I built it with `gem install mysql2 -- --with-mysql-config=/usr/bin/mariadb_config`.

I don't usually work with Ruby so maybe I missed an installation step? Something like a cache removal or a rebuild?

**Comment by sodabrew** [comment]
I don't think this has any problem with the Ruby or gem side of things, but rather that the client library and the server are not compatible in some unexpected way. MySQL protocol has been stable for a long time.

What versions of MariaDB client and server and connector/c do you have installed?

**Comment by sodabrew** [comment]
If you were able to resolve the issue, could you post what works for you, in case someone in the future finds this issue?

**Comment by raphaelyancey** [comment]
@sodabrew It wasn't a MariaDB server after all. I could connect with MariaDB client because of it handling older MySQL versions better than the MySQL client.
