### ISSUE TITLE
Using unsupported buffer type: 245  Error

### ISSUE THREAD

**Issue by Flip120** [brianmario/mysql2#920]
We are getting this error when trying to use the prepared statements in a table that has a JSON field.

```
Mysql2::Error:
  Using unsupported buffer type: 245  (parameter: 1)
```
Here the code that we have:
```
statement = client.prepare("SELECT * FROM table WHERE JSON_EXTRACT(body, '$.id') = ?")
data = statement.execute('an_id')
```
body is a JSON field

**Comment by sodabrew** [comment]
What version of mysql2 gem are you using?

**Comment by kamipo** [comment]
This should be fixed in 0.4.2 (#693).

**Comment by singulardroid** [comment]
Hello, I faced same issue with mysql 0.5.2 within rails2.5 lambda environment on AWS. Do you have any ideas how to solve it?

**Comment by metaskills** [comment]
Sharing this Mysql2 Lambda gem project if anyone is interested. https://github.com/customink/mysql2-lambda
