### ISSUE TITLE
Windows installation has no binary for Ruby 2.4

### ISSUE THREAD

**Issue by nyxnyx** [brianmario/mysql2#923]
Hi,
I have Ruby2.4 on windows 10. When I install mysql2 with gem it doesn't contain binary for 2.4. Even if I select to build one - there is no binary for 2.4
This results to following error while starting rails:
``
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mysql2-0.4.5-x64-mingw32/lib/mysql2/mysql2.rb:2:in `require': cannot load such file -- mysql2/2.4/mysql2 (LoadError)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mysql2-0.4.5-x64-mingw32/lib/mysql2/mysql2.rb:2:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mysql2-0.4.5-x64-mingw32/lib/mysql2.rb:31:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mysql2-0.4.5-x64-mingw32/lib/mysql2.rb:31:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:81:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:76:in `each'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:76:in `block in require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:65:in `each'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:65:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler.rb:114:in `require'
        from D:/Projects/sverige/config/application.rb:7:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:133:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:133:in `block in perform'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:130:in `tap'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:130:in `perform'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/command/base.rb:63:in `perform'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/command.rb:44:in `invoke'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
        from bin/rails:9:in `require'
        from bin/rails:9:in `<main>'
``

Contents of gem installation directory:
``
C:\Ruby24-x64\lib\ruby\gems\2.4.0\gems\mysql2-0.4.5-x64-mingw32\lib\mysql2>dir
 Volume in drive C has no label.
 Volume Serial Number is 1848-D1E1

 Directory of C:\Ruby24-x64\lib\ruby\gems\2.4.0\gems\mysql2-0.4.5-x64-mingw32\lib\mysql2

2017-12-07  16:52    <DIR>          .
2017-12-07  16:52    <DIR>          ..
2017-12-07  16:34    <DIR>          2.0
2017-12-07  16:34    <DIR>          2.1
2017-12-07  16:34    <DIR>          2.2
2017-12-07  16:34    <DIR>          2.3
2017-12-07  16:34             5 862 client.rb
2017-12-07  16:34               121 console.rb
2017-12-07  16:34             1 132 em.rb
2017-12-07  16:34             2 346 error.rb
2017-12-07  16:34                53 field.rb
2017-12-07  16:34                58 mysql2.rb
2017-12-07  16:34                62 result.rb
2017-12-07  16:34               335 statement.rb
2017-12-07  16:34                38 version.rb
               9 File(s)         10 007 bytes
               6 Dir(s)  50 598 948 864 bytes free

C:\Ruby24-x64\lib\ruby\gems\2.4.0\gems\mysql2-0.4.5-x64-mingw32\lib\mysql2>
``

There is now 2.4 directory

**Comment by jwalkerbg** [comment]
Me, too. I installed binary version of mysql2 on windows, and the directory 2.4 is missing.
My questions is: is mysql2 compatible with Ruby 2.4.x or we have to downgrade ruby to 2.3.x ?

**Comment by sodabrew** [comment]
As stated, it is compatible with Ruby 2.4 on Windows but does not currently include binaries for this version of Ruby. You can compile mysql2 yourself or downgrade to Ruby 2.3 for the latest available binary distributions.

The next version of mysql2 gem will include binaries for Ruby 2.4 and 2.5 soon after.

**Comment by akeshmiri** [comment]
Greeting,
Do you have any estimate when the next release is planned?

**Comment by SleeplessByte** [comment]
In the meanwhile you can build it yourself, without extra tools, as long as you did install the MSYS2 toolchain (e.g. using ruby installer), and it's actually quite easy (and similar for other gems like bcrypt):

You will need:
- MSYS2 (if you don't have it check: [RubyInstaller Instructions](https://github.com/oneclick/rubyinstaller2)
- The location of your ruby installation (likely `C:\Ruby24-x64\`)
- The location of your MySQL connector installation (likely `C:\Program Files\MySQL\MySQL Connector.C 6.1`)
- A "failed" installation of mysql2 (simply run bundle or gem install)

The steps are as follows, but substitute the paths so they work for you. I am assuming `mysql2 0.4.10`, and ruby `2.4.x`, with default installation paths:

1. Open MSYS2 (in my case the 64bit version, via Start Menu or `C:\msys64\msys2_shell.cmd -mingw64`)
1. Browse to ruby installation, find the gem folder, then go into `ext`, `mysql2`: 
    ```Bash
    cd  "C:\Ruby24-x64\lib\ruby\gems\2.4.0\gems\mysql2-0.4.10-x64-mingw32\ext\mysql2"
    ```
    - For other ruby versions, get the `major.minor.0` folder, and naturally grab the correct gem version you're trying to install.
1. Create the necessary make file using the Ruby installation and Connector paths:
     ```Bash
    cd  "C:\Ruby24-x64\bin\ruby" extconf.rb --with-mysql-dir="C:\Program Files\MySQL\MySQL Connector.C 6.1"
    ```
    - You have to prepend with the ruby installation path because your windows environment is not available in this terminal, unless you run with `-use-full-path` or edit `msys2_shell.cmd`
    - If you forget to add the `--with-mysql-dir` option, the error message thrown is `mysql client is missing. Check your installation of MySQL or Connector/C, and try again`. The make file will try to use the `lib` and `include` from your Connector installation.
1. Run `make` in the current directory to "make" (read: compile / make / build the software)
     ```Bash
    make
    ```
1. Install the software using `make install`
     ```Bash
    make install
    ```
1. Copy the new `mysql2.so` from the `ext` folder to the `lib/2.4.0` folder
    - If you forget this you will (still) see 
1. Rejoice

**Comment by sodabrew** [comment]
Just posted mysql2 0.5.0 with Ruby 2.0 - 2.5 for Windows.

**Comment by chanchancel** [comment]
sodabrew it works in mine.
I have ruby v2.5.1p57
and Rails version 5.2.1.
bundled mysql2 0.5.0

and my 'rails about' cmd isnt giving me crap


Great Job man
