### ISSUE TITLE
Missing changelog for 0.4.10?

### ISSUE THREAD

**Issue by valscion** [brianmario/mysql2#924]
Hi! Thank you for maintaining this gem 🙇 

We've got an automated pending dependency upgrade from v0.4.9 to v0.4.10 and I noticed that v0.4.10 changelog seems to be missing?

Here's the information I've got:

#### ✳️ mysql2 (0.4.9 → 0.4.10) · [Repo](http://github.com/brianmario/mysql2) · [Changelog](https://github.com/brianmario/mysql2/blob/master/CHANGELOG.md)

<strong>Commits</strong>

<p><a href="https://github.com/brianmario/mysql2/compare/9c2d277cf07b7f481e5c665e745985115bc6f434...59e446d99df3b7f7f13f08cc3c82952afb6737fc">See the full diff on Github</a>. The new version differs by 27 commits:</p>

<ul>
<li><a href="https://github.com/brianmario/mysql2/commit/59e446d99df3b7f7f13f08cc3c82952afb6737fc"><code>Bump version to 0.4.10</code></a></li>
<li><a href="https://github.com/brianmario/mysql2/commit/080ea37901b021138c84c0290fd08ba55e428bd0"><code>Merge pull request #904 from sodabrew/better_specs</code></a></li>
<li><a href="https://github.com/brianmario/mysql2/commit/f8ee23acebad84fbbabe062d4bfc25f25e8d02c3"><code>Stash the mysql-build@oss.oracle.com key locally instead of calling pgp.mit.edu</code></a></li>
<li><a href="https://github.com/brianmario/mysql2/commit/ad4cd99983533c39fb5ab32d42a4cc270b7613a5"><code>Test five significant figures of microseconds to reduce off-by-one-microsecond errors</code></a></li>
<li><a href="https://github.com/brianmario/mysql2/commit/f971f369366f25b8029baf233b92b1613d847de7"><code>Backport the cast_booleans test structure to results spec</code></a></li>
<li><a href="https://github.com/brianmario/mysql2/commit/b6cbf1758b85d262b917ef70410d009ddbecbad7"><code>Merge pull request #903 from sodabrew/statement_specs_prepare</code></a></li>
<li><a href="https://github.com/brianmario/mysql2/commit/e52fc0ae593f7e33bcbd94bd8866ba388b10252d"><code>Fix server_info</code></a></li>
<li><a href="https://github.com/brianmario/mysql2/commit/975c30e524bb9104f1aa0705dae869dfa20c6213"><code>Fix rubocop</code></a></li>
<li><a href="https://github.com/brianmario/mysql2/commit/934a4a8fa587fbad910bdd09915df032df9a3df2"><code>Cast the BIT(1) type when :cast_booleans is true for prepared statements</code></a></li>
<li><a href="https://github.com/brianmario/mysql2/commit/35a4f6bf5f3604bc888475535ff6716bead945f3"><code>Test prepared statements in the prepared statements tests: boolean</code></a></li>
<li><a href="https://github.com/brianmario/mysql2/commit/255c759a86de02970eec1cb335a0ce3e3386dd62"><code>Test prepared statements in the prepared statements tests: date & time</code></a></li>
<li><a href="https://github.com/brianmario/mysql2/commit/cffb76dd0eb7a54bea7282aa209ce88b5f0b1cd0"><code>Make sure ssl is enabled if only :sslverify is set (#889)</code></a></li>
<li><a href="https://github.com/brianmario/mysql2/commit/763235ec8311a28c8959628fee1fec4f07edfafa"><code>Merge pull request #902 from sodabrew/remove_mysqld_error_h</code></a></li>
<li><a href="https://github.com/brianmario/mysql2/commit/8a8246670339fadbf05012fbf8ceefd7016d0cd2"><code>Use keyserver.ubuntu.com for the Percona key</code></a></li>
<li><a href="https://github.com/brianmario/mysql2/commit/92dbef3a50da812666ac7543213452d6e0776d5e"><code>Include mysqld_error.h has been here for ages but was superfluous</code></a></li>
<li><a href="https://github.com/brianmario/mysql2/commit/beac69ac0ccd0f614bb4035d9679214bbcbe1e45"><code>Merge pull request #901 from sodabrew/remove_mysql_com_h</code></a></li>
<li><a href="https://github.com/brianmario/mysql2/commit/830dd7377baeb3d64457a74d670dfb026905be31"><code>Check the server version instead of the client version of MySQL on OS X specs</code></a></li>
<li><a href="https://github.com/brianmario/mysql2/commit/8d8fbf94c3fc783a1becafb9efa6db8f4d0985f1"><code>Include mysql_com.h has been here for ages but was superfluous</code></a></li>
<li><a href="https://github.com/brianmario/mysql2/commit/151d5f0a12122be147ea2f19f670dd9a2307745e"><code>Merge pull request #900 from sodabrew/mariadb_version_again</code></a></li>
<li><a href="https://github.com/brianmario/mysql2/commit/a2e62e096bd07ffe7c21cba227855b46c0761088"><code>Install MariaDB client headers after Travis CI fix for MariaDB 10.2 broke earlier 10.x</code></a></li>
<li><a href="https://github.com/brianmario/mysql2/commit/80f743502d5d96cad98cbe44582822cf672d8592"><code>ifdef consistency</code></a></li>
<li><a href="https://github.com/brianmario/mysql2/commit/f987eec1cbfe77bb6b30f17d4454cd2a5db114d4"><code>More work towards MariaDB version string compatibility</code></a></li>
<li><a href="https://github.com/brianmario/mysql2/commit/b2cbe3e3d8fff33b8c6a1e1a64ce4e45666ff766"><code>extended keyword for the explain statement has been removed (#894)</code></a></li>
<li><a href="https://github.com/brianmario/mysql2/commit/f5709fd4265e4efb013b6d9f250f94af87f93ad1"><code>Return false on deprecated set secure auth</code></a></li>
<li><a href="https://github.com/brianmario/mysql2/commit/ac34e68fe041edae722bcebaa09dcbf0f621c742"><code>MYSQL_SECURE_AUTH has been removed in MySQL 8.0.3 RC (#892)</code></a></li>
<li><a href="https://github.com/brianmario/mysql2/commit/58d0a0d4cf595ac164a1207d7e44b301455f118d"><code>Switch from pending to skip because of rspec 3 changes</code></a></li>
<li><a href="https://github.com/brianmario/mysql2/commit/5ebb89955a59f397368036d3fad8c7d857e32f98"><code>Update MySQL Connector/C version for Windows</code></a></li>
</ul>

**Comment by sodabrew** [comment]
Added changelog https://github.com/brianmario/mysql2/releases/tag/0.4.10
