### ISSUE TITLE
Mysql2 segfault..?

### ISSUE THREAD

**Issue by Insood** [brianmario/mysql2#934]
Hello,

I've been rolling my forehead across the keyboard for the last couple of days trying to figure this out.

**What's going on:**
My RoR application does not want to connect to a mysql database. In fact, I get a segfault.

[Here's what the error log looks like](https://gist.github.com/Insood/4438c2bc36f07b25182937fa308c0023)

**My setup**
* centos-release-7-1.1503.el7.centos.2.8.x86_64
* Ruby 2.4.0
* mysql2 0.4.10
* rvm 1.29.3
* mariadb-devel 10.1.30
* rails 5.1.2 [Gemfile & Gemfile.lock](https://gist.github.com/Insood/962426de93ccd7552c63a6eddc2edc7f)
* Using capistrano to deploy

**What's strange:**
I don't get a segfault if I include mysql2 from irb.

```
[gpopov@fbdlp-web03 current]$ irb
2.4.0 :001 > require 'mysql2'
 => true
2.4.0 :002 > Mysql2::Client.new()
Mysql2::Error: Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2 "No such file or directory")
        from /usr/local/rvm/gems/ruby-2.4.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:89:in `connect'
        from /usr/local/rvm/gems/ruby-2.4.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:89:in `initialize'
        from (irb):2:in `new'
        from (irb):2
        from /usr/local/rvm/rubies/ruby-2.4.0/bin/irb:11:in `<main>'
2.4.0 :003 > exit
```

Capistrano does install the gems in a different directory (/usr/local/rvm/bin/rvm 2.4.0 do bundle install --path /var/www/audit-staging/shared/bundle --jobs 4 --without development test --deployment
)

[So there is a difference between the gem environments.](https://gist.github.com/Insood/513776026d3bc71b08fe3987bf141797)

[However, the two mysql2.so files appear to be using the same shared libraries](https://gist.github.com/Insood/10eae5b72aae8226c1a173208376187d)

I can't figure out what to do - I can't tell if it's an issue with my setup (likely) or mysql2/rails/rvm/ruby (less likely). It does work on my development machine (which has a similar setup), but obviously not in production -- so unfortunately I cannot reproduce it.

**Comment by Insood** [comment]
I ended up reinstalling everything (yum update, reinstall ruby, reinstall passenger, reinstall nginx, compile gems) to fix this. I'm still not sure what or how my system installation broke ¯\_(ツ)_/¯

**Comment by sodabrew** [comment]
Sorry to hear that it was such a weird error! I hadn't ever seen that location of segfault, in `mysql_close_slow`, so I didn't have much to go on yet. Glad it's working now!
