### ISSUE TITLE
Test of MySQL server garbage collection randomly fails

### ISSUE THREAD

**Issue by ltangvald** [brianmario/mysql2#937]
The test at
https://github.com/brianmario/mysql2/blob/b2cfca1fabe8ef698c9d0ea3db31cb2ca8485ddc/spec/mysql2/statement_spec.rb#L695 (statement close should free server resources) is testing internal server behavior that isn't fully deterministic from the outside, as the server won't always immediately free up the resources, causing the test to fail randomly in Ubuntu (MySQL 5.7)

**Comment by ltangvald** [comment]
The suggested Ubuntu patch will disable the test with xit, but it should probably either be dropped or rewritten somehow.

**Comment by sodabrew** [comment]
Interesting, this must have been a change in MySQL 5.7 that makes the statement unloading garbage collection less immediate.

I don't see a suggested patch?

**Comment by ltangvald** [comment]
Whops, sorry :)
The patch is below, but it just works around the issue by disabling the test.

[patch.txt](https://github.com/brianmario/mysql2/files/1688346/patch.txt)

And yes, this is because of a change in 5.7. I seem to remember this exact same issue showing up in another package back when Ubuntu was first updated to 5.7, but can't recall which package it was.

**Comment by sodabrew** [comment]
I don't want to just skip this test, since it's important to check that the `Statement#close` method works... I am looking into whether I can use the Performance Schema for MySQL 5.7 to measure this value without depending on MySQL's garbage collector.
