### ISSUE TITLE
Could not dump table "discount_profile_rules" because of following StandardError Unknown type 'json' for column 'value_json'

### ISSUE THREAD

**Issue by zedtux** [brianmario/mysql2#940]
I have a Rails 4 application, using MySQL, with one table having a `json` type column. 

While I was doing a `rake db:setup`, I found out that a table was missing in the Rails `schema.rb` file with the following comment:

```ruby
...
# Could not dump table "discount_profile_rules" because of following StandardError
#   Unknown type 'json' for column 'value_json'
...
```

Could it be a bug in the way Rails is loading the `db:setup` task or in the gem?

**Comment by sodabrew** [comment]
I suspect you're running rather out-of-date versions. What version of Rails 4.x and the mysql2 gem are you using?

**Comment by zedtux** [comment]
Thank you @sodabrew for your comment!

I'm running a Rails 4.2.2 application and Mysql2 version 0.3.18.

**Comment by sodabrew** [comment]
Sorry for the long delay to reply, but yes, the `json` field type is not supported until mysql2 0.4.x. And in order to use mysql2 0.4.x you will need at least Rails 4.2.5 or a higher Rails 4.x version.

**Comment by zedtux** [comment]
Okay, thank you @sodabrew for your comment, we planned to upgrade to Rails 5, so our problem will be fixed then. 👍

**Comment by zedtux** [comment]
@sodabrew I'm coming back on this as I'm now working on the migration to Rails 5.

Before migrating I'm working on cleaning up the accumulated migration scripts and wanted to use the `db/schema.rb` as a single migration script and remove the old one, but as I have this issue I can't.

Reading again your comment I checked our Gemfile and we are actually using Rails 4.2.5 and mysql2 4.1.0 but we still have this issue.

Is there anything I should do to get to the point where the `json` column type is understood by the Rake db dump schema task?

**Comment by zedtux** [comment]
I got this issue solved by using the [json_on_rails](https://github.com/saveriomiroddi/json_on_rails) gem as suggested by [this SO answer](https://stackoverflow.com/a/50504014/1996540).
