### ISSUE TITLE
port connection defaults to 3306

### ISSUE THREAD

**Issue by AurimasLazdauskas** [brianmario/mysql2#942]
Port connection option defaults to 3306 when I use alias for host IP. I have a docker container for mysql listening to port 3357. When I try to connect like this:
```client = Mysql2::Client.new(database: 'development_db', host: 'localhost', port: 3357, username: 'root')```
I connect to mysql running locally. I verified this by inspecting table structure as I abandoned local db some time ago and it doesn't have all the migrations.
However, when I connect like so:
```client = Mysql2::Client.new(database: 'development_db', host: '127.0.0.1', port: 3357, username: 'root')```

it connects to docker container. I don't know if it was supposed to work this way, but I to give you guys a head up if you run into problems.

I am using rails 5.1 and mysql2 0.4.10.

**Comment by sodabrew** [comment]
Yes, this is documented behavior. The MySQL client library has special handling for `localhost`, it will use the local socket. https://github.com/brianmario/mysql2#connecting-to-mysql-on-localhost-and-elsewhere
