### ISSUE TITLE
ActiveRecord::StatementInvalid: Mysql2::Error: FUNCTION databse_name.regexp_substr does not exist

### ISSUE THREAD

**Issue by chandrasekarvcs** [brianmario/mysql2#946]
I'm using
gem 'mysql2', '~> 0.3.14'
ruby '2.0.0'
gem 'rails', '3.2.18'

Error details :

ActiveRecord::StatementInvalid: Mysql2::Error: FUNCTION database.regexp_substr does not exist: SELECT distinct substring(regexp_substr(column_name, 'sub_code":"[A-Z]+'), 16) FROM database_name.table_name where some_id = 12;

**Comment by sodabrew** [comment]
There is no function named `regexp_substr` in MySQL. That's an Oracle function. See this documentation for the list of available MySQL String Functions: https://dev.mysql.com/doc/refman/5.7/en/string-functions.html
