### ISSUE TITLE
"Specified 'mysql2' for database adapter, but the gem is not loaded" when upgrading to 0.5.0

### ISSUE THREAD

**Issue by roberts1000** [brianmario/mysql2#950]
I just tried upgrading from 0.4.10 to 0.5.0 in a Rails app and got the following error when starting the server in development:

```bash
=> Booting Puma
=> Rails 5.1.5 application starting in development 
=> Run `rails server -h` for more startup options
Exiting
Traceback (most recent call last):
   ....
   5: from /home/dev/.rvm/gems/ruby-2.5.0/gems/activesupport-5.1.5/lib/active_support/lazy_load_hooks.rb:69:in `instance_eval'
   4: from /home/dev/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.5/lib/active_record/railtie.rb:124:in `block (2 levels) in <class:Railtie>'
   3: from /home/dev/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.5/lib/active_record/connection_handling.rb:58:in `establish_connection'
   2: from /home/dev/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:880:in `establish_connection'
   1: from /home/dev/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/connection_specification.rb:185:in `spec'
/home/dev/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/connection_specification.rb:188:in `rescue in spec': Specified 'mysql2' for database adapter, but the gem is not loaded. Add `gem 'mysql2'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord). (Gem::LoadError)
```

I simply changed the version in the Gemfile to 0.5.0 and rebundled.  If I downgrade to 0.4.10, everything works fine.

I'm using:

**Ruby:** 2.5.0
**Rails:** 5.15
**Ubuntu:** 16.04
**mysql:** mysql  Ver 14.14 Distrib 5.7.21, for Linux (x86_64) using  EditLine wrapper

**Comment by sodabrew** [comment]
This is expected until the next minor revisions of Rails that enable mysql2 0.5.0 to load.

**Comment by bverem** [comment]
Is mysql2 0.5.0 expected to work with Ruby 2.5.0?

**Comment by sodabrew** [comment]
Yes, Ruby 2.5 is fully supported.

**Comment by EmTee70** [comment]
Can you please add an info to your readme.md. 
After fresh installation of rails (5.1.5 with ruby 2.5.0) I ran into this ....

**Comment by obfuscoder** [comment]
I am also experiencing this issue with Rails 4.2.10. Will this be addressed in Rails 4.2.11 as well? I can't find an issue in the rails project mentioning this problem.

**Comment by sodabrew** [comment]
For Rails 4.x please pin the gem to `mysql2 '~> 0.4.0'` to avoid the 0.5.x upgrade.

For Rails 5.x the next point releases will enable both mysql2 0.4.x and 0.5.x.

**Comment by bmulholland** [comment]
Could the release notes be updated to include this?

**Comment by sodabrew** [comment]
Done! https://github.com/brianmario/mysql2/releases/tag/0.5.0

**Comment by sodabrew** [comment]
Correct, Rails 4.x cannot use mysql2 0.5.x. The actual code would work fine, but Rails 4 has a version restriction in place to prevent use of mysql2 0.5.x. This is intentional, as it allows future changes to the API without silently risking their use in older code not prepared to use the new APIs.

**Comment by EmTee70** [comment]
I just ran into this with rails 5.1.5 and my question is, for whom dose 0.5.0 work?
With 0.4.10 everything is fine. But your sentence 
> you may wish to pin the mysql2 version in your Gemfile

is not 100% clear.  You should write it exactly:
Please use ... in your Gemfile.

**Comment by thienanh96** [comment]
I'm using Ruby 2.4, Rails: 5.15. What version of mysql2 can I use ? Thank you!

**Comment by qichunren** [comment]
I also got same problem. Ruby 2.4 Rails 5.1.5, when I update  mysql2 from 0.4.0 to 0.5.0

    

> /home/qichunren/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/connection_specification.rb:188:in `rescue in spec': Specified 'mysql2' for database adapter, but the gem is not loaded. Add `gem 'mysql2'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord). (Gem::LoadError)

**Comment by sodabrew** [comment]
For Rails 4.x please pin the gem to mysql2 '~> 0.4.0' to avoid the 0.5.x upgrade.

For Rails 5.x the next point releases will enable both mysql2 0.4.x and 0.5.x.

Until the next 5.x point release, you should pin the mysql2 gem to 0.4.x as well. It will probably be a few weeks until the next point releases.

**Comment by sodabrew** [comment]
Rails 5.0.7 and 5.1.6 have been released with support for mysql2 0.5.x.

**Comment by kevinhq** [comment]
Experienced this problem too.
Rails 4.2.10
mysql2 0.5.1

Reverting to 0.4.10 did solve the problem. This means, Rails 4.2.10 can't use latest 0.5.x ?

**Comment by sodabrew** [comment]
Rails 4.x will not be updated to allow mysql2 0.5.x, simply because it is outside of its feature update maintenance window. As a matter of functionality, it would work fine together, but as a matter of being community supported it is not.

**Comment by adilw3nomad** [comment]
Just FYI, in case you are running MySql and Rails in docker containers; **make sure you remember to rebuild the Rails image after updating Rails version to 5.1.6**

just posting incase someone else has a brain fart like I did and couldn't figure out why it still wouldn't work after upgrading rails to 5.1.6 and mysql to 0.5.2 😅

**Comment by n00dle** [comment]
It looks like [mysql2 0.5.x is now supported](https://github.com/rails/rails/compare/v4.2.10...v4.2.11) with the [4.2.11 release](https://weblog.rubyonrails.org/2018/11/27/Rails-4-2-5-0-5-1-5-2-have-been-released/).
