### ISSUE TITLE
On Heroku: "Your mysql client library does not support setting ssl_mode; full support comes with 5.7.11."

### ISSUE THREAD

**Issue by dpaola2** [brianmario/mysql2#951]
The error: `/app/vendor/bundle/ruby/2.2.0/gems/mysql2-0.5.0/lib/mysql2/client.rb:51: warning: Your mysql client library does not support setting ssl_mode; full support comes with 5.7.11.`

Is there a specific way I must build the gem on Heroku? I have set `ssl_mode: :preferred` in my call to `Mysql2::Client.new(...)`

**Comment by sodabrew** [comment]
You will need a newer client library. I’m not familiar enough with Heroku to advise how to get that.

**Comment by dpaola2** [comment]
OK, thanks.
