### ISSUE TITLE
NameError: uninitialized constant Mysql2::Client::FOUND_ROWS

### ISSUE THREAD

**Issue by Articdive** [brianmario/mysql2#959]
Rails version: Rails 5.1.6
Ruby version: ruby 2.5.1p57 (2018-03-29 revision 63029) [x64-mingw32]
Windows 10
IDE: RubyMine
mysql2 version: 0.5.0
 - // - // - // -
So I'm trying to db:migrate and then I get this error, full trace if it helps you at all:
D:\Ruby25-x64\bin\ruby.exe -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) C:/Users/<User>/Desktop/IntelliJ-Workspace/Ruby/RailsProject/bin/rails --trace db:migrate
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:migrate
rails aborted!
NameError: uninitialized constant Mysql2::Client::FOUND_ROWS
D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `mysql2_connection'
D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:759:in `new_connection'
D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:803:in `checkout_new_connection'
D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:782:in `try_to_checkout_new_connection'
D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:743:in `acquire_connection'
D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:500:in `checkout'
D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:374:in `connection'
D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `retrieve_connection'
D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_handling.rb:116:in `retrieve_connection'
D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/activerecord-5.1.6/lib/active_record/connection_handling.rb:88:in `connection'
D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/activerecord-5.1.6/lib/active_record/schema_migration.rb:20:in `table_exists?'
D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/activerecord-5.1.6/lib/active_record/schema_migration.rb:24:in `create_table'
D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/activerecord-5.1.6/lib/active_record/migration.rb:1125:in `initialize'
D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/activerecord-5.1.6/lib/active_record/migration.rb:1007:in `new'
D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/activerecord-5.1.6/lib/active_record/migration.rb:1007:in `up'
D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/activerecord-5.1.6/lib/active_record/migration.rb:985:in `migrate'
D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/activerecord-5.1.6/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/activerecord-5.1.6/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `block in execute'
D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `each'
D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `execute'
D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
D:/Ruby25-x64/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:182:in `invoke'
D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:160:in `invoke_task'
D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `each'
D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block in top_level'
D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:125:in `run_with_threads'
D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:110:in `top_level'
D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/commands/rake/rake_command.rb:18:in `perform'
D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/command.rb:46:in `invoke'
D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/commands.rb:16:in `<top (required)>'
C:/Users/<User>/Desktop/IntelliJ-Workspace/Ruby/RailsProject/bin/rails:4:in `require'
C:/Users/<User>/Desktop/IntelliJ-Workspace/Ruby/RailsProject/bin/rails:4:in `<top (required)>'
-e:1:in `load'
-e:1:in `<main>'
Tasks: TOP => db:migrate

Process finished with exit code 1

database.yml : 
development:
   adapter: mysql2
   encoding: utf8
   database: ror_development
   username: root
   password: <password>
   host: <somelocaladdress>
   port: 3306

If i need to add anything let me know, im some 16 year old and i'm just getting started with development, I just couldn't find any documentation of this error on the internet.

**Comment by reklawevarg** [comment]
Try this:
gem uninstall mysql2
gem install mysql2 -v 0.4.9

**Comment by Articdive** [comment]
Downgrading to 0.4.9 did not solve the issue, same error

**Comment by sodabrew** [comment]
If you're using Ruby 2.5, you must use mysql2 0.5.0 to get the precompiled binaries. Rails 5.1.6 includes the small change to use mysql2 0.5.0.

So what I'm left with is thinking that maybe the header package in the build of mysql2 0.5.0 for Windows was missing a set of constants. I will take a look at this before building the next 0.5.1 packages.

**Comment by Articdive** [comment]
I have not found a workaround

**Comment by zaxanllc** [comment]
Working on this issue also.  So far have not found a work around.

**Comment by LudwigKrause** [comment]
@sodabrew 
Is this issue connected to #954 and will be solved within milestone 5.1?

**Comment by sodabrew** [comment]
Yes, it's the same problem. Yes, will be resolved in the next version's binary build for Windows.

**Comment by 2cutekids** [comment]
In the meantime How do I get around this, I am having this issue also.
Ruby 2.3.0
Rails 5.1.6

**Comment by reklawevarg** [comment]
Certainly you can downgrade to an older version?  I am using 0.4.9 on Ruby 2.3.3.

**Comment by grainmiller** [comment]
@sodabrew when do you expect the next versions binary build for Windows?

**Comment by sodabrew** [comment]
Please try mysql2 0.5.1 binaries now.

**Comment by grainmiller** [comment]
Works like a charm. Thank you very much. Will send you nudes :P

**Comment by danepenttila** [comment]
0.5.1 worked for me. Thanks!

**Comment by kagayakuYume** [comment]
I have same problem.
Could you help me.
"NameError in WelcomeController#index
uninitialized constant Mysql2::Client::FOUND_ROWS"
