### ISSUE TITLE
 MySQL2 5.0.1, CPU usage is almost 100%.

### ISSUE THREAD

**Issue by oxygen-xx** [brianmario/mysql2#961]
CentOS release 6.9 (Final).
Linux 2.6.32-696.10.2.el6.x86_64
Mysql Ver 14.14 Distrib 5.7.14, for Linux (x86_64) .

MySQL Ruby2.5.1, Rails5.2.0 or Rails 5.1.6, MySQL2 5.0.1, CPU usage is almost 100%.

**Comment by sodabrew** [comment]
Have you been able to resolve this issue?
