### ISSUE TITLE
[BUG] db:migrate with utf8mb4 on Centos failed

### ISSUE THREAD

**Issue by cuijiemmx** [brianmario/mysql2#967]
production server env:
ruby 2.4.2
rails 5.1.4
Centos 6.3
MySQL 5.7 Community Server

I use capistrano to deploy an app on production server，the step db:migrate reported an error:
mysql: Character set 'utf8mb4' is not a compiled character set and is not specified in the '/usr/share/mysql/charsets/Index.xml', the database.xml defined as below
...
encoding: utf8mb4
charset: utf8mb4
collation: utf8mb4_unicode_ci
variables:
    sql_mode: TRADITIONAL
...

I found a workaround, by modifying Index.xml and replace utf8 with utf8mb4
However, I also deploy other apps on the same server with utf8 defined in database.xml, deploy those apps will encounter a similar error: Character set 'utf8' is not a ...

Besides, I'm not using the MySQL server on the production server, I use a remote MySQL server with my.cnf properly set to utf8mb4

**Comment by sodabrew** [comment]
There seems to be an open bug about this:
https://bugs.mysql.com/bug.php?id=82349

**Comment by cuijiemmx** [comment]
@sodabrew  Thanks for your ref, this bugs was reported in 2016 but not resolved yet ...
does mysql2 also support MariaDB? Has MariaDB resolved this issue?

**Comment by sodabrew** [comment]
Yes MariaDB is supported. I don't know if the same problem exists.

**Comment by cuijiemmx** [comment]
@sodabrew it is strange that in my local dev environment, rake db:migrate with utf8mb4 set in database.xml works as expected, no work around required
env: 
MacOS High Sierra
MySQL 5.7 (installed by homebrew)

**Comment by cuijiemmx** [comment]
After days of research, I found the root cause!

utf8mb4 got supported in MySQL Server 5.5

My production server comes with MySQL-devel version 5.1, it provides client libs required by mysql2 native extension compilation

So when I deploy my app to production server for first time, I got the error 'Character set 'utf8mb4' is not a compiled character set and is not specified in the '/usr/share/mysql/charsets/Index.xml', at this point the mysql2 gem is already installed with its native extension compiled using mysql 5.1 client libs, and this gem is cached!

So even I upgraded MySQL-devel to 5.7, this issue still exists because the mysql2 gem is cached and not updated

The solution is quite simple, just remove shared/bundle (created by capistrano) directory and rerun bundle, so the mysql2 gem got recompiled with mysql 5.7 client libs

Absolutely this MySQL bug has ready been resolved

@sodabrew thanks for your commet
