### ISSUE TITLE
Threads killed do not release database connection

### ISSUE THREAD

**Issue by tcdowney** [brianmario/mysql2#968]
This may be similar to #638 and #841. We've found that when a thread is killed while it is executing a query, it continues to own the connection even after it is dead. We use the `mysql2` adapter via `sequel`, but we were able to reproduce this directly.

## Minimal Reproduction Steps:
```ruby
mysql = Mysql2::Client.new(...)
thread = Thread.new { mysql.query("select sleep(3)")}
sleep 1
Thread.kill(thread)
```

Then executing `mysql.query("select sleep(3)")` results in an error like:

```ruby
Mysql2::Error: This connection is in use by: #<Thread:0x00005589f0841b40@(pry):29 dead>
from /var/vcap/data/packages/cloud_controller_ng/74d3e2700be88474643958f946de61df0e4a7b5b/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `_query'
```

## Versions
* `mysql2` - `0.4.10`
* `ruby` - `ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]`
* `mariadb` - `10.1.32-MariaDB`
* `mariadb_connector_c` - `2.3.5`

Any ideas regarding why this is happening?

Thanks,
Tim && @selzoc

**Comment by sodabrew** [comment]
I consider this correct behavior. If you've killed the thread in the middle of execution, it's not reasonable to bring the connection back into a known-good state. When the `query` method returns, the active thread id will be cleared and you can use the connection again.

There is an API function for resetting a connection, but it's not exposed in the mysql2 gem as it was just added in MySQL 5.7 (I actually had no idea about this function until 2 minutes ago): https://dev.mysql.com/doc/refman/5.7/en/mysql-reset-connection.html

**Comment by tcdowney** [comment]
@sodabrew are you saying that once the query returns (even though the thread is killed) the subsequent call to `mysql.query("select sleep(3)")` should succeed? When I do something like this I still get errors:

```ruby
thread = Thread.new { mysql.query("select sleep(3)")}
sleep 1
Thread.kill(thread)
sleep 30
mysql.query("select sleep(3)")


Mysql2::Error: This connection is in use by: #<Thread:0x00005645a497e948@(pry):24 dead>
from /var/vcap/data/packages/cloud_controller_ng/74d3e2700be88474643958f946de61df0e4a7b5b/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `_query'
```

It seems like the connection just gets into a permanently bad state. Is that the behavior you expect?

**Comment by sodabrew** [comment]
Yes, the thread that was executing on that connection was killed, so the full lifecycle of the query was not completed, from the thread taking possession of the connection, going through several API calls to fetch the results, and then releasing the connection (setting `active_thread = nil`).
