### ISSUE TITLE
Mysql2::Error: Access denied for user 'root'@'localhost' on Ubuntu 18.04

### ISSUE THREAD

**Issue by arturoblanco** [brianmario/mysql2#969]
# Description
Hi, I'm getting error: **`Mysql2::Error: Access denied for user 'root'@'localhost'`** after installing MySQL version `5.7.22`.

When I was using MySQL version `5.7.20` and GEM version `0.3.21` this did not happened. And also I could login to shell by using `mysql -u root -p` with current version I have to use `sudo` at the beginning.

# ENV Info
```
- Rails version: 4.2.10
- Ruby: 2.2.2
- Gem mysql2: 0.4.10
- MySQL:  5.7.22
```
Is anyone having the same issue?

**Comment by sodabrew** [comment]
MySQL 5.7 changed the way root passwords are set by default, so you may need to take some manual steps to reset the root password: https://www.percona.com/blog/2016/05/18/where-is-the-mysql-5-7-root-password/

**Comment by thuythuy1212** [comment]
/mnt/c/myweb$  mysql -u root -p
Enter password:
ERROR 1698 (28000): Access denied for user 'root'@'localhost'
ngocthuy@DESKTOP-PIKNVLI:/mnt/c/myweb$
how can fix this?

**Comment by junaruga** [comment]
> how can fix this?

@thuythuy1212 I think 2 options to fix it.
You can read the following part of the shell script used in this repo's CI, then execute the way 1 to use `ALTER USER ..` or the way 2 to use `DROP USER ..` and `CREATE USER ..` and `GRANT ...`.

https://github.com/brianmario/mysql2/blob/346b4a43a146aa2239b82a6bb1020c66f6e456a0/ci/setup.sh#L107-L134
