### ISSUE TITLE
NameError uninitialized constant ActiveRecord::ConnectionAdapters::AbstractMysqlAdapter::MysqlDateTime

### ISSUE THREAD

**Issue by khadijakarkhanawala** [brianmario/mysql2#970]
Ruby version: 2.4.3
Rails version: 5.1.4
mysql2 version: 0.4.10 (Also happened in 0.5.1)

I upgraded mysql2 gem from 0.3.21 and I started getting this error on all pages. I am not able to figure out the issue here. I have been researching about this but have not found any relevant reference.

The error occurs at
`current_user = Rails.cache.read(key)`

I do not understand how it could be related to caching. But when I comment out cache code and query directly it starts working. I am using redis for caching.

I also checked **abstract_mysql_adapter.rb** file and there is no mention of MysqlDateTime.

**Comment by sodabrew** [comment]
I was just looking at what might have caused this - could you post the resolution you found so it may help the next person who googles-by?

**Comment by swapnilfuturism** [comment]
Even I am migrating from 
Old: Ruby-2.4.9 to Rails-4.2.1
New: Ruby-2.4.0 to Rails-5.0.7

and facing exactly same issue. Will post here if above resolution works for me.
