### ISSUE TITLE
A question about dependencies

### ISSUE THREAD

**Issue by guiferpa** [brianmario/mysql2#972]
Hi, I have a question of beginner. I started work with MySQL and Ruby together and when installing the gem`mysql2` I saw that `mysql-devel` dependency is required.

However I was curious, why do you need this libraries of OS? Do not use **HTTP protocol** to integration with MySQL instance. Cannot you create this integration in this gem? Why use dependencies?

Below, the partial output when installing the gem:

```bash
mysql client is missing. You may need to 'apt-get install libmysqlclient-dev' or 'yum install mysql-devel', and
try again.
```

**Comment by sodabrew** [comment]
MySQL speaks its own protocol, not HTTP. The key dependency is the MySQL-provided C library that speaks this protocol to the server, and provides a C API that this gem uses.

There is a native Ruby implementation of the MySQL protocol available in a different gem, so this is possible to do, but it's not the path this gem chose to pursue.

**Comment by guiferpa** [comment]
@sodabrew Tks so much about your answer. I have some more of questions to you :smile: :

1. Do you know what is name of protocol used?
2. Why choose use a dependency instead of to implements in **gem** the integration with the MySQL database?

One more time, thanks about your attention.

**Comment by sodabrew** [comment]
MySQL protocol documentation: https://dev.mysql.com/doc/internals/en/client-server-protocol.html

The MySQL C API is stable and the C client library works well and is actively maintained.

Here is a gem that implements the protocol in Ruby. It's an excellent effort, but has not been actively maintained recently. https://github.com/tmtm/ruby-mysql

Here is an implementation of the protocol in Go. It is very recent, as most things written in Go are pretty recent, and it looks well maintained. https://github.com/go-sql-driver/mysql

**Comment by guiferpa** [comment]
Thanks very much.
