### ISSUE TITLE
`Mysql2::Error: Unknown table` for views

### ISSUE THREAD

**Issue by marksiemers** [brianmario/mysql2#977]
When using a `table_name_prefix` for a view, an error is thrown because mysql cannot find a table when the prefix is used in the select clause.

For example, this error will happen with a view:
```
Mysql2::Error: Unknown table 'some_db_name.some_view':
SELECT `some_db_name`.`some_view`.* FROM `some_db_name`.`some_view`
```

In the same scenario with a table, there is no error:
```
SELECT `some_db_name`.`some_table`.* FROM `some_db_name`.`some_table`
```

Based on testing directly in MySql, if the prefix is not included in the SELECT statement (and still included in the FROM clause), it should work:
```
SELECT `some_view`.* FROM `some_db_name`.`some_view`
```

If you can point me to the place that the SELECT clause in generated, I may be able to do a PR. Also, if this should be addressed in ActiveRecord, LMK. I think it is MySql specific but I have not confirmed that.

**Comment by marksiemers** [comment]
Found a workaround, in the model:
```ruby
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  self.table_name_prefix = 'some_prefix.'
end

class SomeModelBackedByView < ApplicationRecord
  self.table_name = "#{table_name_prefix}some_database_view"
  default_scope { select("`some_database_view`.*") }
end
```

**Comment by sodabrew** [comment]
Thank you, however this gem does not generate any SELECT statements; in the case of Rails it is ActiveRecord that generates them for you. If there's a change you want to see in ActiveRecord to better support this use case please file the issue on their tracker.

**Comment by marksiemers** [comment]
Thanks @sodabrew 
Given that this is probably an uncommon issue and I have a reasonable (IMO) workaround using `default_scope` - I may leave it as is. This likely doesn't apply to postgresql as they don't allow you to access more than one db per connection. I think it is a MySql specific issue.

Does the ActiveRecord team allow anything in that isn't db-agnostic?

Just to document this, there was an additional issue (associations) that required a work around:
```ruby
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  self.table_name_prefix = 'some_prefix.'
end

class SomeModelBackedByView < ApplicationRecord
  self.table_name = "#{table_name_prefix}some_database_view"
  default_scope { select("`some_database_view`.*") }
end

class SomeOtherModel < ApplicationRecord
  # The class_name option isn't necessary, just the second argument for scoping the association
  has_many :some_models, -> { select("`some_database_view`.*") }, class_name: :SomeModeBackedByView
end
```

**Comment by sodabrew** [comment]
So this is exclusively an active record issue. They have adapters for specific configuration and issues for each database type, so yes there is a place for this type of adjustment.
