### ISSUE TITLE
Warning cause an Mysql2::Error

### ISSUE THREAD

**Issue by neo4u** [brianmario/mysql2#979]
Is it expected behavior in the mysql2 gem for a warning such as data truncated for column? Isn't this only supposed to be a warning and not cause an error?

**Comment by sodabrew** [comment]
Correct, this should not raise an exception. Can you share a reproducible case?

**Comment by neo4u** [comment]
```
require 'mysql2'

client = Mysql2::Client.new(
  host: "localhost",
  username: 'username',
  password: 'password',
  database: 'db_name',
  local_infile: true,
  reconnect: true
)

rs = client.query("SELECT STR_TO_DATE('2018-06-25 07:36:23', '%Y-%m-%d')")
```
I believe this is a false positive.
