### ISSUE TITLE
bundle install fails on MYSQL2 0.4.4 

### ISSUE THREAD

**Issue by CapellaBlue** [brianmario/mysql2#981]
Hello, I've fought with this block for 24 hours and would love some help. 
I ensure that I am in the directory of the app I'm working on. 
then:
`brew install mysql@5.6` (ive also tried with the current mysql 8+)
=> installs fine.
`bundle install` (version of bundle is 1.16.2)
=>
```
Fetching mysql2 0.4.4
Installing mysql2 0.4.4 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/Users/amandacapella/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/mysql2-0.4.4/ext/mysql2
/Users/amandacapella/.rbenv/versions/2.4.3/bin/ruby -r
./siteconf20180620-48087-1cu44mh.rb extconf.rb
checking for ruby/thread.h... yes
checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
checking for rb_thread_blocking_region()... no
checking for rb_wait_for_single_fd()... yes
checking for rb_hash_dup()... yes
checking for rb_intern3()... yes
-----
Using mysql_config at /usr/local/mysql/bin/mysql_config
-----
checking for mysql.h... yes
checking for errmsg.h... yes
checking for mysqld_error.h... yes
-----
Setting rpath to /usr/local/mysql/lib
-----
creating Makefile

current directory:
/Users/amandacapella/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/mysql2-0.4.4/ext/mysql2
make "DESTDIR=" clean

current directory:
/Users/amandacapella/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/mysql2-0.4.4/ext/mysql2
make "DESTDIR="
compiling client.c
In file included from client.c:1:
In file included from ./mysql2_ext.h:41:
./result.h:24:3: error: unknown type name 'my_bool'
  my_bool *is_null;
  ^
./result.h:25:3: error: unknown type name 'my_bool'
  my_bool *error;
  ^
client.c:454:3: error: use of undeclared identifier 'my_bool'
  my_bool res = mysql_read_query_result(client);
  ^
client.c:456:19: error: use of undeclared identifier 'res'
  return (void *)(res == 0 ? Qtrue : Qfalse);
                  ^
client.c:775:3: error: use of undeclared identifier 'my_bool'
  my_bool boolval;
  ^
client.c:806:7: error: use of undeclared identifier 'boolval'
      boolval = (value == Qfalse ? 0 : 1);
      ^
client.c:807:17: error: use of undeclared identifier 'boolval'
      retval = &boolval;
                ^
client.c:810:10: error: use of undeclared identifier 'MYSQL_SECURE_AUTH'; did
you mean 'MYSQL_DEFAULT_AUTH'?
    case MYSQL_SECURE_AUTH:
         ^~~~~~~~~~~~~~~~~
         MYSQL_DEFAULT_AUTH
/usr/local/mysql/include/mysql.h:188:3: note: 'MYSQL_DEFAULT_AUTH' declared here
  MYSQL_DEFAULT_AUTH,
  ^
client.c:811:7: error: use of undeclared identifier 'boolval'
      boolval = (value == Qfalse ? 0 : 1);
      ^
client.c:812:17: error: use of undeclared identifier 'boolval'
      retval = &boolval;
                ^
client.c:843:38: error: use of undeclared identifier 'boolval'
        wrapper->reconnect_enabled = boolval;
                                     ^
client.c:1231:38: error: use of undeclared identifier 'MYSQL_SECURE_AUTH'; did
you mean 'MYSQL_DEFAULT_AUTH'?
  return _mysql_client_options(self, MYSQL_SECURE_AUTH, value);
                                     ^~~~~~~~~~~~~~~~~
                                     MYSQL_DEFAULT_AUTH
/usr/local/mysql/include/mysql.h:188:3: note: 'MYSQL_DEFAULT_AUTH' declared here
  MYSQL_DEFAULT_AUTH,
  ^
12 errors generated.
make: *** [client.o] Error 1

make failed, exit code 2

Gem files will remain installed in
/Users/amandacapella/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/mysql2-0.4.4
for inspection.
Results logged to
/Users/amandacapella/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/extensions/x86_64-darwin-17/2.4.0-static/mysql2-0.4.4/gem_make.out

An error occurred while installing mysql2 (0.4.4), and Bundler cannot
continue.
Make sure that `gem install mysql2 -v '0.4.4' --source 'http://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  mysql2
```
okay, so maybe `sudo gem install mysql2 -v '0.4.4' --source 'http://rubygems.org/'`
=> outputs the same error. I notice the `checking for rb_thread_blocking_region()... no` and have googled this for help, but no results have helped. 

I recently wiped and reinstalled everything for my env. I use Docker to start mysql?
macOS High Sierra 10.13.5
mysql 5.6 and 8 have same issue.
ruby 2.4.3
rails 4
xcode is up to date and dev tools/cl tools installed

what am I missing? What else can I provide to get help on this issue? It seems every issue on SO is a variant of this issue, but doesnt match perfectly (or the answers do not remedy the

**Comment by sodabrew** [comment]
Update to a newer version of mysql2 gem to handle your newer version of MySQL.

**Comment by CapellaBlue** [comment]
I will try this, but I work on a team of developers-- updating my gemfile may have consequences. For this reason, I have contacted my lead developer. His mysql version is 5.6 (hence my intentional install of mysql 5.6, and his mysql2 gem installs fine with `bundle install`

**Comment by CapellaBlue** [comment]
FWIW, this advice helped: however, not in my case. My Ruby version is 2.4.3, and as this ticket previously explained (https://github.com/brianmario/mysql2/issues/950) I'm unable to use 0.5.1

I've 'gem install mysql -v '0.4.10' -- but I'm not (perhaps from fatigue? yay:) able to figure out how to make sure our applicate uses the version I've installed (I've added it to the gemfile, but now bundler wants to keep using 0.5.1).

**Comment by sodabrew** [comment]
Edit your gemfile thusly, and then run `bundle update`:

```
gem 'mysql2', '~> 0.4.10'
```

The squiggly-greater-than allows the last component of the version to float up but not any other components up the version, so you'd get a future 0.4.11 but not 0.5.x.

**Comment by CapellaBlue** [comment]
Because of my 'fresh slate' environment purge, my editor was not configured to autosave.... so...I kept changing my gemfile....and `bundle update mysql2` wasn't registering the update. 

autosave enabled. 
mysql2 installed.
deserved break earned...or maybe just needed. 

thank you for the continued interaction regardless. In a sea of silent SO issues, this actually helped me the most. All the best~

**Comment by bradseefeld** [comment]
After installing the older version of mysql via brew, you have to force link it:
```
brew install mysql@5.6
brew link mysql@5.6 --force
```

After running this, the gem was still having difficulty finding openssl libs, so I had to give it some help:
```
export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/opt/openssl/lib/
```

This allowed bundler to install mysql2 -v 0.4.4

**Comment by kazennka** [comment]
Building native extensions. This could take a while...
ERROR:  Error installing mysql2:
	ERROR: Failed to build gem native extension.

    current directory: /Users/urijkunicyn/.rvm/gems/ruby-2.3.1/gems/mysql2-0.4.4/ext/mysql2
/Users/urijkunicyn/.rvm/rubies/ruby-2.3.1/bin/ruby -I /Users/urijkunicyn/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0 -r ./siteconf20190606-87406-ksva3k.rb extconf.rb
checking for ruby/thread.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/urijkunicyn/.rvm/rubies/ruby-2.3.1/bin/$(RUBY_BASE_NAME)
/Users/urijkunicyn/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /Users/urijkunicyn/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/mkmf.rb:587:in `try_cpp'
	from /Users/urijkunicyn/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/mkmf.rb:1091:in `block in have_header'
	from /Users/urijkunicyn/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/mkmf.rb:942:in `block in checking_for'
	from /Users/urijkunicyn/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/mkmf.rb:350:in `block (2 levels) in postpone'
	from /Users/urijkunicyn/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /Users/urijkunicyn/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/mkmf.rb:350:in `block in postpone'
	from /Users/urijkunicyn/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /Users/urijkunicyn/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/mkmf.rb:346:in `postpone'
	from /Users/urijkunicyn/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/mkmf.rb:941:in `checking_for'
	from /Users/urijkunicyn/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/mkmf.rb:1090:in `have_header'
	from extconf.rb:16:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/urijkunicyn/.rvm/gems/ruby-2.3.1/extensions/x86_64-darwin-16/2.3.0/mysql2-0.4.4/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/urijkunicyn/.rvm/gems/ruby-2.3.1/gems/mysql2-0.4.4 for inspection.
Results logged to /Users/urijkunicyn/.rvm/gems/ruby-2.3.1/extensions/x86_64-darwin-16/2.3.0/mysql2-0.4.4/gem_make.out

**Comment by futer90** [comment]
Building native extensions. This could take a while...
ERROR:  Error installing mysql2:
	ERROR: Failed to build gem native extension.

    current directory: /Users/urijkunicyn/.rvm/gems/ruby-2.3.1/gems/mysql2-0.4.4/ext/mysql2
/Users/urijkunicyn/.rvm/rubies/ruby-2.3.1/bin/ruby -I /Users/urijkunicyn/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0 -r ./siteconf20190606-87406-ksva3k.rb extconf.rb
checking for ruby/thread.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/urijkunicyn/.rvm/rubies/ruby-2.3.1/bin/$(RUBY_BASE_NAME)
/Users/urijkunicyn/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /Users/urijkunicyn/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/mkmf.rb:587:in `try_cpp'
	from /Users/urijkunicyn/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/mkmf.rb:1091:in `block in have_header'
	from /Users/urijkunicyn/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/mkmf.rb:942:in `block in checking_for'
	from /Users/urijkunicyn/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/mkmf.rb:350:in `block (2 levels) in postpone'
	from /Users/urijkunicyn/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /Users/urijkunicyn/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/mkmf.rb:350:in `block in postpone'
	from /Users/urijkunicyn/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /Users/urijkunicyn/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/mkmf.rb:346:in `postpone'
	from /Users/urijkunicyn/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/mkmf.rb:941:in `checking_for'
	from /Users/urijkunicyn/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/mkmf.rb:1090:in `have_header'
	from extconf.rb:16:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/urijkunicyn/.rvm/gems/ruby-2.3.1/extensions/x86_64-darwin-16/2.3.0/mysql2-0.4.4/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/urijkunicyn/.rvm/gems/ruby-2.3.1/gems/mysql2-0.4.4 for inspection.
Results logged to /Users/urijkunicyn/.rvm/gems/ruby-2.3.1/extensions/x86_64-darwin-16/2.3.0/mysql2-0.4.4/gem_make.out

**Comment by 1v** [comment]
```
client.c:810:10: error: use of undeclared identifier 'MYSQL_SECURE_AUTH'; did
you mean 'MYSQL_DEFAULT_AUTH'?
```
I had same error with `mysql  Ver 8.0.19-0ubuntu0.19.10.3 for Linux on x86_64 ((Ubuntu))`. Solved by updating exclusively `mysql2` gem:
```
bundle update --conservative mysql2
```
```
-    mysql2 (0.4.5)
+    mysql2 (0.5.3)
```

**Comment by emads3** [comment]
Seems that you miss the main files needed to build `mysql2` gem
```
sudo apt-get install libsqlite3-dev libmysqlclient-dev -y
```
`libsqlite3-dev` is not mandatory but install it since it's the default rails DB.
