### ISSUE TITLE
Rails 4.0 compatibility

### ISSUE THREAD

**Issue by florrain** [brianmario/mysql2#984]
Hello,

I'm working with a Rails 4.0 application where I'm seeing [this error](https://github.com/brianmario/mysql2/issues/772). I'd like to upgrade the mysql2 client version to the latest as possible (0.4.6 and greater). The application is using a 0.3.x version currently.

I'm seeing two inconsistent versioning recommendations, one in the README and one in the 0.5.0 release notes.

```mysql2 0.4.x works with Rails / Active Record 4.2.5 - 5.0 and higher.```

```For Rails 4.x please pin the gem to mysql2 '~> 0.4.0' to avoid the 0.5.x upgrade.```

Could you tell which is the source of truth?

Thanks

**Comment by sodabrew** [comment]
Both statements are true.

If you need mysql2 0.4.x you'll need at least Rails 4.2.5.

**Comment by florrain** [comment]
The second infers that 4.0 and 4.2 can be used with `~> 0.4.0` which goes in conflict with the first that is stricter. I guess I'll go the safe way and try to do the Rails upgrade before mysql2.

**Comment by jcowhigjr** [comment]
https://stackoverflow.com/questions/22932282/gemloaderror-for-mysql2-gem-but-its-already-in-gemfile just in case someone is confused that the mysql2 gem can be added to the Gemfile with Rails 4.0 .. You will see a confusing failure when you boot the application.  

So I think it is actually.. true for rails 4.1, 4.2 etc.. but

For Rails 4.0 please pin the gem to mysql2 '~> 0.3.0' to avoid the 0.4.x upgrade.  But yea no one should stay on rails 4.0 at this point.
