### ISSUE TITLE
SSL connection error: error:00000001:lib (0):func(0):reason(1)

### ISSUE THREAD

**Issue by arnoldmarunda** [brianmario/mysql2#986]
Failing to connect remotely to a WP Engine database using SSL with mysql2 as per instruction on 
[Setting Remote Database Access](https://wpengine.com/support/setting-remote-database-access)
I know the connection is possible as I have been able to connect using Sequel Pro

```
ActiveRecord::Base.establish_connection(
adapter: 'mysql2',
host: ENV['MYSQL_HOST'],
username: ENV['MYSQL_USER'],
password: ENV['MYSQL_PASS'],
database: ENV['MYSQL_DB'],
sslverify: true,
sslca: './wpengine_root_ca.pem',
port: 13306
)
```

The follow error is occurring
`SSL connection error: error:00000001:lib (0):func(0):reason(1) `

**Comment by sodabrew** [comment]
@arnoldmarunda Have you had success sorting out the SSL connection settings?

**Comment by arnoldmarunda** [comment]
@sodabrew I ended up connecting via SSH. Thank you for following up
