### ISSUE TITLE
Adding CentOS to Travics CI

### ISSUE THREAD

**Issue by junaruga** [brianmario/mysql2#988]
I would propose adding CentOS (+ Fedora Linux) environment to Travis CI.

As you know, Travis CI is run on Ubuntu.
However using Docker, it is possible to run tests on CentOS and Fedora.

The reason why I want to add it is because we sometimes receive questions about installation on CentOS. It is also useful for people to see CentOS test case is passed casually, and to save maintainer's time.

Personally I am maintaining the RPM package of `mysql2`. So, it's good for me to see the passed test. :)

I want to show the example by sending PR.

How do you think?

**Comment by sodabrew** [comment]
Resolved by #989
