### ISSUE TITLE
MySql 8.0.11 - Rails 5.2 crash

### ISSUE THREAD

**Issue by UnConundrum** [brianmario/mysql2#990]
My app had no issues under 5.7.  I upgraded MySql today to 8.0.  Launching rails c, I get:

[1] pry(main)> User.find(17)
   (0.7ms)  SET NAMES utf8mb4,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/activerecord-5.2.0/lib/active_record/connection_adapters/mysql/database_statements.rb:19: [BUG] Segmentation fault at 0x0000000000000c1a
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0043 p:---- s:0235 e:000234 CFUNC  :each
c:0042 p:---- s:0232 E:000df0 CFUNC  :to_a

....etc for thousands of lines.

**Comment by sodabrew** [comment]
Can you capture the C-level backtrace with debugging symbols installed?

**Comment by UnConundrum** [comment]
Sorry, that's beyond my skillset, but I can follow instructions.

**Comment by nikhilm492** [comment]
I am also working on the same app.

The mysql2 gem version is 0.5.1

Below is the C level backtrace and Ruby level backtrace:
 
-- C level backtrace information -------------------------------------------
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(rb_vm_bugreport+0x769) [0x7f57d2070959]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0xa9df4) [0x7f57d1ee2df4]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x1a7f22) [0x7f57d1fe0f22]
/lib/x86_64-linux-gnu/libc.so.6(0x7f57d1a86f20) [0x7f57d1a86f20]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x7f57d1fe9ca0) [0x7f57d1fe9ca0]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(st_lookup+0x25) [0x7f57d1feac05]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(rb_enc_find_index+0x3b) [0x7f57d1ecdfeb]
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/mysql2-0.5.1/lib/mysql2/mysql2.so(rb_mysql_result_fetch_row+0x131) [0x7f57c9acb041]
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/mysql2-0.5.1/lib/mysql2/mysql2.so(0x9f1f) [0x7f57c9ac9f1f]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x22da56) [0x7f57d2066a56]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x22e181) [0x7f57d2067181]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x22ed81) [0x7f57d2067d81]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x21b512) [0x7f57d2054512]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(rb_block_call+0x3c) [0x7f57d20546cc]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x986c8) [0x7f57d1ed16c8]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x218ee6) [0x7f57d2051ee6]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x22ab83) [0x7f57d2063b83]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x22460e) [0x7f57d205d60e]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x228f8d) [0x7f57d2061f8d]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x22ca5a) [0x7f57d2065a5a]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x22cfbe) [0x7f57d2065fbe]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x148eea) [0x7f57d1f81eea]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x218ee6) [0x7f57d2051ee6]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x22ab83) [0x7f57d2063b83]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x22460e) [0x7f57d205d60e]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x228f8d) [0x7f57d2061f8d]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x229e2c) [0x7f57d2062e2c]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x22be77) [0x7f57d2064e77]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x21b84e) [0x7f57d205484e]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(rb_catch_obj+0x1c) [0x7f57d205497c]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x218ee6) [0x7f57d2051ee6]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x22ab83) [0x7f57d2063b83]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x223a1b) [0x7f57d205ca1b]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x228f8d) [0x7f57d2061f8d]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x229e2c) [0x7f57d2062e2c]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x22be77) [0x7f57d2064e77]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x21b84e) [0x7f57d205484e]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(rb_catch_obj+0x1c) [0x7f57d205497c]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x218ee6) [0x7f57d2051ee6]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x22ab83) [0x7f57d2063b83]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x223a1b) [0x7f57d205ca1b]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x228f8d) [0x7f57d2061f8d]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x22fb59) [0x7f57d2068b59]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(rb_rescue2+0xd2) [0x7f57d1eec382]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x218ee6) [0x7f57d2051ee6]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x22ab83) [0x7f57d2063b83]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x223a1b) [0x7f57d205ca1b]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x228f8d) [0x7f57d2061f8d]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x229e2c) [0x7f57d2062e2c]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x22a104) [0x7f57d2063104]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x22a1f0) [0x7f57d20631f0]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x22a372) [0x7f57d2063372]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x22ab83) [0x7f57d2063b83]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x22460e) [0x7f57d205d60e]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x228f8d) [0x7f57d2061f8d]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0xf9a71) [0x7f57d1f32a71]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0xfc2f1) [0x7f57d1f352f1]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(rb_require_safe+0x9) [0x7f57d1f353d9]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x218ee6) [0x7f57d2051ee6]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x22ab83) [0x7f57d2063b83]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x22460e) [0x7f57d205d60e]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0x228f8d) [0x7f57d2061f8d]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(0xb02a4) [0x7f57d1ee92a4]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(ruby_exec_node+0x1d) [0x7f57d1eeb30d]
/usr/local/rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5(ruby_run_node+0x1e) [0x7f57d1eee5de]
/usr/local/rvm/rubies/ruby-2.5.0/bin/ruby(main+0x4b) [0x55c2f0e648eb] ./main.c:42

-- Ruby level backtrace information ----------------------------------------
bin/rails:4:in `<main>'
bin/rails:4:in `require'
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/railties-5.2.0/lib/rails/commands.rb:18:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/railties-5.2.0/lib/rails/command.rb:46:in `invoke'
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/railties-5.2.0/lib/rails/command/base.rb:65:in `perform'
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/railties-5.2.0/lib/rails/commands/console/console_command.rb:96:in `perform'
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/railties-5.2.0/lib/rails/commands/console/console_command.rb:19:in `start'
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/railties-5.2.0/lib/rails/commands/console/console_command.rb:64:in `start'
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/pry-byebug-3.6.0/lib/pry-byebug/pry_ext.rb:11:in `start_with_pry_byebug'
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/pry-0.11.3/lib/pry/pry_class.rb:192:in `start'
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/pry-0.11.3/lib/pry/repl.rb:13:in `start'
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/pry-0.11.3/lib/pry/repl.rb:38:in `start'
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/pry-0.11.3/lib/pry/input_lock.rb:79:in `with_ownership'
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/pry-0.11.3/lib/pry/input_lock.rb:61:in `__with_ownership'
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/pry-0.11.3/lib/pry/repl.rb:38:in `block in start'
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/pry-0.11.3/lib/pry/repl.rb:67:in `repl'
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/pry-0.11.3/lib/pry/repl.rb:67:in `loop'
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/pry-0.11.3/lib/pry/repl.rb:77:in `block in repl'
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/pry-0.11.3/lib/pry/pry_instance.rb:241:in `eval'
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/pry-0.11.3/lib/pry/pry_instance.rb:241:in `catch'
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/pry-0.11.3/lib/pry/pry_instance.rb:242:in `block in eval'
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/pry-0.11.3/lib/pry/pry_instance.rb:242:in `catch'
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/pry-0.11.3/lib/pry/pry_instance.rb:243:in `block (2 levels) in eval'
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/pry-0.11.3/lib/pry/pry_instance.rb:323:in `handle_line'
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/pry-0.11.3/lib/pry/pry_instance.rb:355:in `evaluate_ruby'
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/pry-0.11.3/lib/pry/pry_instance.rb:355:in `eval'
(pry):1:in `<main>'
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/activerecord-5.2.0/lib/active_record/querying.rb:5:in `last'
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/activerecord-5.2.0/lib/active_record/relation/finder_methods.rb:153:in `last'
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/activerecord-5.2.0/lib/active_record/relation/finder_methods.rb:556:in `ordered_relation'
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/activerecord-5.2.0/lib/active_record/relation/delegation.rb:46:in `primary_key'
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/activerecord-5.2.0/lib/active_record/attribute_methods/primary_key.rb:75:in `primary_key'
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/activerecord-5.2.0/lib/active_record/attribute_methods/primary_key.rb:87:in `reset_primary_key'
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/activerecord-5.2.0/lib/active_record/attribute_methods/primary_key.rb:99:in `get_primary_key'
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/activerecord-5.2.0/lib/active_record/model_schema.rb:324:in `table_exists?'
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/activerecord-5.2.0/lib/active_record/connection_adapters/schema_cache.rb:48:in `data_source_exists?'
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/activerecord-5.2.0/lib/active_record/connection_adapters/schema_cache.rb:114:in `prepare_data_sources'
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/schema_statements.rb:36:in `data_sources'
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:89:in `query_values'
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/activerecord-5.2.0/lib/active_record/connection_adapters/mysql/database_statements.rb:19:in `query'
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/activerecord-5.2.0/lib/active_record/connection_adapters/mysql/database_statements.rb:19:in `to_a'
/usr/local/rvm/gems/ruby-2.5.0@v5/gems/activerecord-5.2.0/lib/active_record/connection_adapters/mysql/database_statements.rb:19:in `each'

**Comment by UnConundrum** [comment]
Original problem was rails running on Ubuntu 18.04 with database on OS X High Sierra.  I executed the same code on the Mac with the same results, but it generated a Crash Report:

<script src="https://gist.github.com/UnConundrum/7058fbe245812086c0fd69560158ae7d.js"></script>

**Comment by sodabrew** [comment]
This is #976. I'll get a release out as soon as I can.

**Comment by UnConundrum** [comment]
Thanks.  Much appreciated.

**Comment by mauricionr** [comment]
I've updated to mysql 8.0.11 and got errors on bundle install

```
Fetching mysql2 0.3.20
Installing mysql2 0.3.20 with native extensions
Building native extensions.  This could take a while...
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /Users/mauricionr/.asdf/installs/ruby/2.2.8/bin/ruby -r ./siteconf20180704-15835-1t3shx3.rb extconf.rb
checking for ruby/thread.h... yes
checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
checking for rb_thread_blocking_region()... no
checking for rb_wait_for_single_fd()... yes
checking for rb_hash_dup()... yes
checking for rb_intern3()... yes
-----
Using mysql_config at /usr/local/bin/mysql_config
-----
checking for mysql.h... yes
checking for errmsg.h... yes
checking for mysqld_error.h... yes
-----
Setting rpath to /usr/local/Cellar/mysql/8.0.11/lib
-----
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling infile.c
compiling client.c
client.c:367:33: warning: implicit conversion loses integer precision: 'long' to 'unsigned int' [-Wshorten-64-to-32]
        elapsed_time = end_time - start_time;
                     ~ ~~~~~~~~~^~~~~~~~~~~~
client.c:439:3: error: use of undeclared identifier 'my_bool'
  my_bool res = mysql_read_query_result(client);
  ^
client.c:441:19: error: use of undeclared identifier 'res'
  return (void *)(res == 0 ? Qtrue : Qfalse);
                  ^
client.c:775:3: error: use of undeclared identifier 'my_bool'
  my_bool boolval;
  ^
client.c:806:7: error: use of undeclared identifier 'boolval'
      boolval = (value == Qfalse ? 0 : 1);
      ^
client.c:807:17: error: use of undeclared identifier 'boolval'
      retval = &boolval;
                ^
client.c:810:10: error: use of undeclared identifier 'MYSQL_SECURE_AUTH'; did you mean 'MYSQL_DEFAULT_AUTH'?
    case MYSQL_SECURE_AUTH:
         ^~~~~~~~~~~~~~~~~
         MYSQL_DEFAULT_AUTH
/usr/local/Cellar/mysql/8.0.11/include/mysql/mysql.h:188:3: note: 'MYSQL_DEFAULT_AUTH' declared here
  MYSQL_DEFAULT_AUTH,
  ^
client.c:811:7: error: use of undeclared identifier 'boolval'
      boolval = (value == Qfalse ? 0 : 1);
      ^
client.c:812:17: error: use of undeclared identifier 'boolval'
      retval = &boolval;
                ^
client.c:843:38: error: use of undeclared identifier 'boolval'
        wrapper->reconnect_enabled = boolval;
                                     ^
client.c:1165:56: warning: implicit conversion loses integer precision: 'size_t' (aka 'unsigned long') to 'unsigned int' [-Wshorten-64-to-32]
  mysql2rb = mysql2_mysql_enc_name_to_rb(charset_name, charset_name_len);
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~               ^~~~~~~~~~~~~~~~
client.c:1198:38: error: use of undeclared identifier 'MYSQL_SECURE_AUTH'; did you mean 'MYSQL_DEFAULT_AUTH'?
  return _mysql_client_options(self, MYSQL_SECURE_AUTH, value);
                                     ^~~~~~~~~~~~~~~~~
                                     MYSQL_DEFAULT_AUTH
/usr/local/Cellar/mysql/8.0.11/include/mysql/mysql.h:188:3: note: 'MYSQL_DEFAULT_AUTH' declared here
  MYSQL_DEFAULT_AUTH,
  ^
2 warnings and 10 errors generated.
make: *** [client.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/gems/2.2.0/gems/mysql2-0.3.20 for inspection.
Results logged to /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-17/2.2.0/mysql2-0.3.20/gem_make.out

  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/2.2.0/rubygems/ext/builder.rb:89:in `run'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/2.2.0/rubygems/ext/builder.rb:51:in `block in make'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/2.2.0/rubygems/ext/builder.rb:43:in `each'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/2.2.0/rubygems/ext/builder.rb:43:in `make'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/2.2.0/rubygems/ext/ext_conf_builder.rb:44:in `block in build'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/2.2.0/tempfile.rb:319:in `open'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/2.2.0/rubygems/ext/ext_conf_builder.rb:19:in `build'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/2.2.0/rubygems/ext/builder.rb:161:in `block (2 levels) in build_extension'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/2.2.0/rubygems/ext/builder.rb:160:in `chdir'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/2.2.0/rubygems/ext/builder.rb:160:in `block in build_extension'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/2.2.0/rubygems/ext/builder.rb:159:in `build_extension'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/2.2.0/rubygems/ext/builder.rb:198:in `block in build_extensions'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/2.2.0/rubygems/ext/builder.rb:195:in `each'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/2.2.0/rubygems/ext/builder.rb:195:in `build_extensions'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/2.2.0/rubygems/installer.rb:707:in `build_extensions'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/rubygems_gem_installer.rb:23:in `build_extensions'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/2.2.0/rubygems/installer.rb:250:in `install'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/source/rubygems.rb:153:in `block in install'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/rubygems_integration.rb:217:in `preserve_paths'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/source/rubygems.rb:142:in `install'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/installer/gem_installer.rb:56:in `install'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/installer/parallel_installer.rb:162:in `do_install'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/installer/parallel_installer.rb:147:in `install_serially'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/installer/parallel_installer.rb:102:in `call'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/installer/parallel_installer.rb:78:in `call'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/installer.rb:258:in `install_in_parallel'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/installer.rb:194:in `install'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/installer.rb:91:in `block in run'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/process_lock.rb:12:in `block in lock'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/process_lock.rb:9:in `open'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/process_lock.rb:9:in `lock'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/installer.rb:72:in `run'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/installer.rb:25:in `install'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/cli/install.rb:65:in `run'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/cli.rb:224:in `block in install'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/settings.rb:136:in `temporary'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/cli.rb:223:in `install'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/bin/bundle:23:in `load'
  /Users/mauricionr/.asdf/installs/ruby/2.2.8/bin/bundle:23:in `<main>'

An error occurred while installing mysql2 (0.3.20), and Bundler cannot continue.
Make sure that `gem install mysql2 -v '0.3.20'` succeeds before bundling.

In Gemfile:
  mysql2
```

i guess is related

**Comment by sodabrew** [comment]
Not related. Please don’t hijack bugs.

Mysql2 0.3.x is not compatible with MySQL 8. Update you gem or downgrade your MySQL.

**Comment by mauricionr** [comment]
sorry!

**Comment by sodabrew** [comment]
Please try mysql2 0.5.2 and let me know if this resolves the runtime crash with MySQL 8!

**Comment by UnConundrum** [comment]
It’s working well.  Thank you for taking care of this so quickly.  It’s greatly appreciated.
