### ISSUE TITLE
When was mysql 5.7 support introduced?

### ISSUE THREAD

**Issue by virtser** [brianmario/mysql2#993]
Hello,

We are upgrading now from mysql 5.5 to 5.7 and wondering if we need to upgrade our old version of gem to support 5.7?

We are currently using:
```
ruby '2.2.6'
gem 'rails', '3.2.22.5'
gem 'mysql2', '~> 0.3.11'
```

I couldn't find it in release notes.

Thank you.

**Comment by sodabrew** [comment]
Later releases of 0.3.x support MySQL 5.7. Support is improved in 0.4.x and 0.5.x, but you'd need to update Rails as well.
