### ISSUE TITLE
Using unsupported buffer type - prepared queries for a table with a JSON field

### ISSUE THREAD

**Issue by chrisbarber86** [brianmario/mysql2#996]
We're seeing an issue using the mysql2 gem with prepared statements against a table that contains a JSON column.

Below is an example running against MySQL 5.7 running in a Docker Container.

### Environment

MySQL: `mysql/mysql-server:5.7` docker image
Ruby: `v2.5.0`, `v2.5.1`
OS: `OSX High Sierra 10.13.6`
Docker: `Docker version 18.03.1-ce, build 9ee9f40`
MySQL2 Gem Versions tested: `v0.5.1, v0.5.2`

### Example Table:

```sql
CREATE TABLE `test` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `data` json DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```

### Client setup:

```ruby
client = Mysql2::Client.new(host: '127.0.0.1', port: '3306', database: 'test', username: 'root', password: 'admin', reconnect: true)
```

### Insert a row: ✅ 

```ruby
query = ("INSERT INTO `test` (`test`.`data`, `test`.`created_at`, `test`.`updated_at` ) VALUES (?,?,?)")
values = ['{"foo": "bar"}', Time.now, Time.now]

statement = client.prepare(query)
statement.execute(*values)
```

![image](https://user-images.githubusercontent.com/145826/42956479-f7b15406-8b77-11e8-85f2-6fd8a1afe13c.png)

### Simple query: ✅ 

```ruby
query = "SELECT * FROM `test` WHERE `test`.`id` = '1'"

client.query(query).to_a
```

#### Output:
```
[{:id=>1, :data=>"{\"foo\": \"bar\"}", :created_at=>2018-07-19 17:02:18 +0100, :updated_at=>2018-07-19 17:02:18 +0100}]
```

### Prepared query: (Does select the JSON field) :x:

```ruby
query = "SELECT * FROM `test` WHERE `test`.`id` = ?"
values = [1]

statement = client.prepare(query)
statement.execute(*values)
```

#### Output:
```
Traceback (most recent call last):
        6: from /Users/my.name/.rbenv/versions/2.5.0/bin/irb:11:in `<main>'
        5: from (irb):10
        4: from /Users/my.name/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/mysql2-0.5.2/lib/mysql2/statement.rb:6:in `execute'
        3: from /Users/my.name/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/mysql2-0.5.2/lib/mysql2/statement.rb:6:in `handle_interrupt'
        2: from /Users/my.name/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/mysql2-0.5.2/lib/mysql2/statement.rb:7:in `block in execute'
        1: from /Users/my.name/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/mysql2-0.5.2/lib/mysql2/statement.rb:7:in `_execute'
Mysql2::Error (Using unsupported buffer type: 245  (parameter: 2))
```

### Prepared query: (Does not select the JSON field) ✅ 

```ruby
query = "SELECT `test`.`id`, `test`.`created_at`, `test`.`updated_at` FROM `test` WHERE `test`.`id` = ?"
values = [1]

statement = client.prepare(query)
statement.execute(*values)
```

#### Output:
```
[{"id"=>1, "created_at"=>2018-07-19 17:02:18 +0100, "updated_at"=>2018-07-19 17:02:18 +0100}]
```

**Comment by baljeet03** [comment]
I think you have similar issue like this one `https://github.com/brianmario/mysql2/issues/920`. It has been fixed in new version, I tested in my local too.

**Comment by chrisbarber86** [comment]
@baljeet03 Yeah it looks similar, but that was supposed to be fixed in v0.4.2, but i'm using v0.5.2 which should have those changes in it and it's still not working.

**Comment by baljeet03** [comment]
Can you try the prepare statement inside mysql?
`prepare stmt from 'select * from test where id = ?';`
`set @value=1;`
`execute stmt using @value;`

**Comment by chrisbarber86** [comment]
@baljeet03 that looks to work:

```
irb(main):001:0> require 'mysql2'
=> true
irb(main):002:0> client = Mysql2::Client.new(host: '127.0.0.1', port: '3306', database: 'test', username: 'root', password: 'admin', reconnect: true)
=> #<Mysql2::Client:0x00007f9ae0836a08 @read_timeout=nil, @query_options={:as=>:hash, :async=>false, :cast_booleans=>false, :symbolize_keys=>false, :database_timezone=>:local, :application_timezone=>nil, :cache_rows=>true, :connect_flags=>2148573701, :cast=>true, :default_file=>nil, :default_group=>nil, :host=>"127.0.0.1", :port=>"3306", :database=>"test", :username=>"root", :password=>"admin", :reconnect=>true}>
irb(main):003:0> statement = "prepare stmt from 'select * from test where id = ?'"
=> "prepare stmt from 'select * from test where id = ?'"
irb(main):004:0> client.query(statement)
=> nil
irb(main):005:0> set = "set @value=1"
=> "set @value=1"
irb(main):006:0> client.query(set)
=> nil
irb(main):007:0> client.query("execute stmt using @value").to_a
=> [{"id"=>1, "data"=>"{}", "created_at"=>2018-07-25 07:57:09 +0100, "updated_at"=>2018-07-25 07:57:09 +0100}]
```

**Comment by baljeet03** [comment]
This error is thrown by Mysql, I am not able to replicate this in my local. One more thing you can try is by looking into the `query log`.
First enable the `general_log` and give the location of `general_log_file`. I think, both of these by default should be enable. Then try to execute the above statement.

**Comment by chrisbarber86** [comment]
Ok, i think I've got to the bottom of this now. The mysql gem I was using was compiled against my local mysql, which was still 5.6, but the MySQL i was querying was against was 5.7 running in docker.

I'll close this now. Thanks for your help @baljeet03

**Comment by sodabrew** [comment]
Glad to hear that this is resolved! Thank you very much for posting your solution! This helps the next person searching for this error very much.
