### ISSUE TITLE
Prepare does not support "SHOW ..."

### ISSUE THREAD

**Issue by olingern** [brianmario/mysql2#997]
## Description

I searched for outstanding issues and only found [an irrelevant issue](https://github.com/brianmario/mysql2/issues/927) opened for "SHOW ...", and I also didn't see this listed in the [MySQL limitations](https://dev.mysql.com/doc/refman/5.6/en/c-api-prepared-statement-problems.html) linked in the docs.

The following code triggers a mysql error when using the `prepare` method; however it is valid code and the `query` method allows / supports it ( _if given interpolated values_ ).

### Code

```ruby
statement1 = @client.prepare("SHOW TABLES FROM ?")
statement1.execute("my_database")

statement2 = @client.prepare("SHOW COLUMNS FROM ?")
statement2.execute("my_table")
```

### Error

```
`prepare': You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?' at line 1 (Mysql2::Error)
```

## Expected behavior

`prepare` and `query` support the same query types. I'm guessing prepare is getting caught [here ](https://github.com/brianmario/mysql2/blob/4410099f45f8e263adfbc259f8bb95f103057fbf/ext/mysql2/statement.c#L134)for some reason.

## Why

Brakeman is currently catching a SQL injection issue with the usage of query due to my database name being dynamically genrated, i.e.:

```ruby
  # just an example. not sure if brakeman would throw an error with this.
  @client.query("SHOW TABLES FROM #{get_db_name()} )";
```

## Additional notes

The database I'm attempting to connect to has an environment appended to. For example: `my_db-development`

**Comment by sodabrew** [comment]
SHOW just doesn't support prepared query parameters I'm afraid. This is a core MySQL limitation.

**Comment by olingern** [comment]
@sodabrew I see. 

For anyone else who comes here, this is the alternative I ended up going with:

`SELECT table_name FROM information_schema.tables where table_schema='my_database_name';`
