### ISSUE TITLE
DateTime not sent to DB correctly - Rails 5.2

### ISSUE THREAD

**Issue by naerymdan** [brianmario/mysql2#998]
On Rails 5.2

Schema:
`t.datetime "updated_at", precision: 6, null: false`

Code within rails c
```
object.updated_at.iso8601(12) 
=> "2018-08-01T16:26:57.690512000000Z"
object.save
UPDATE `object` SET `updated_at` = '2018-08-01 16:26:57.690512.690512' WHERE `object`.`id` = 1
```

and moreso:
```
object.updated_at = DateTime.now.end_of_day
object.updated_at.iso8601(12) 
=> "2018-08-01T23:59:59.999999999000-04:00"
object.save
UPDATE `object` SET `updated_at` = '2018-08-01 16:26:57.999999.999999' WHERE `object`.`id` = 1
object.reload
object.updated_at.iso8601(12) 
=> "2018-08-02T00:00:00.000000000000-04:00"
```

Basically it seems to repeat the milliseconds and microseconds into the nano and pico precision blindly, as well as completely ignore the defined precision, which ends up rounding the time in mysql 5.7 and completely failing in 5.6

**Comment by naerymdan** [comment]
Please disregard this monstrosity of a bug caused by a 4 years old monkey patch in our stack.

**Comment by sodabrew** [comment]
Happens to the best of us! Thank you for posting back the reason for the error, in case someone else comes along from a Google search with the same issue. Surely you're not the first person to add this monkey patch in the days before the microsecond support was built-in.
